### ISSUE TITLE
Document instantiation of "cognitoUser"

### ISSUE THREAD

**Issue by tomislacker** [aws/amazon-cognito-identity-js#1]
> **Use case 4.** Authenticating a user and establishing a user session with the Amazon Cognito Identity service.

There's no documentation on where/how the `cognitoUser` variable gets instantiated.

**Comment by itrestian** [comment]
Hi Tom,

Thanks for noticing! I have updated the documentation to show how a CognitoUser is instantiated based on a CognitoUserPool object.

Ionut.

**Comment by tomislacker** [comment]
Seems legit, thank you for the quick turnaround.  I was able to eventually find that by digging through the code but then I also ran into the problem in #2
