### ISSUE TITLE
provide source files for aws-cognito-sdk for better builds and prettier ES6/browserify/webpack/etc

### ISSUE THREAD

**Issue by konsumer** [aws/amazon-cognito-identity-js#100]
When I try to import `dist/aws-cognito-sdk.js` directly in webpack, I get this warning:

```
./~/amazon-cognito-identity-js/dist/aws-cognito-sdk.js
Critical dependencies:
4:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/amazon-cognito-identity-js/dist/aws-cognito-sdk.js 4:113-120
```

I'd prefer to be able to get my own sourcemaps, in my own build-chain. Are the source-files for aws-cognito-sdk available?

In order to get the basic library, I am currently doing this (which is a bit gross):

``` js
import 'amazon-cognito-identity-js/dist/aws-cognito-sdk'
import 'amazon-cognito-identity-js/src/CognitoUser'
import 'amazon-cognito-identity-js/src/CognitoUserPool'
import 'amazon-cognito-identity-js/src/CognitoRefreshToken'
import 'amazon-cognito-identity-js/src/CognitoIdToken'
import 'amazon-cognito-identity-js/src/CognitoAccessToken'
import 'amazon-cognito-identity-js/src/AuthenticationDetails'
import 'amazon-cognito-identity-js/src/CognitoUserSession'
import 'amazon-cognito-identity-js/src/CognitoUserAttribute'
import 'amazon-cognito-identity-js/src/AuthenticationHelper'
import 'amazon-cognito-identity-js/src/DateHelper'
```

With an ES6 or CommonJS entry-point (rather than monkey-patching a global), I could be doing this:

``` js
import {AWSCognito, CognitoUser, CognitoUserPool, CognitoRefreshToken, CognitoIdToken, CognitoAccessToken, AuthenticationDetails, CognitoUserSession, CognitoUserAttribute, AuthenticationHelper, DateHelper} from 'amazon-cognito-identity'
```

A more realistic import might look like this (register example, in much clearer ES6):

``` js
import {AWSCognito, CognitoUserPool, CognitoUserAttribute} from 'amazon-cognito-identity'

// This is required to derive the endpoint
AWSCognito.config.region = 'us-east-1'

const userPool = new CognitoUserPool({
  UserPoolId: '...', // Your user pool id here
  ClientId: '...' // Your client id here
})

const attributeList = [
  new CognitoUserAttribute({ Name: 'email', Value: 'email@mydomain.com' }),
  new CognitoUserAttribute({ Name: 'phone_number', Value: '+15555555555' })
]

userPool.signUp('username', 'password', attributeList, null, (err, result) => {
  if (err) return console.error(err)
  const cognitoUser = result.user
  console.log('user name is ' + cognitoUser.getUsername())
})
```

WIth the source for aws-cognito-sdk (it appears you used browserify), I'd be willing to submit a PR that puts everything in this nice structure, and builds the same functionality in output files.

**Comment by konsumer** [comment]
I guess this is really 2 issues:
- The source (before browserify) would be helpful
- providing an ES2015-friendly interface would make things better

Here is my first stab at the second thing:

``` js
// TODO: build this from separate source-files
import 'aws-sdk/dist/aws-sdk'

import 'amazon-cognito-identity-js/dist/aws-cognito-sdk'
import 'amazon-cognito-identity-js/src/CognitoUser'
import 'amazon-cognito-identity-js/src/CognitoUserPool'
import 'amazon-cognito-identity-js/src/CognitoRefreshToken'
import 'amazon-cognito-identity-js/src/CognitoIdToken'
import 'amazon-cognito-identity-js/src/CognitoAccessToken'
import 'amazon-cognito-identity-js/src/AuthenticationDetails'
import 'amazon-cognito-identity-js/src/CognitoUserSession'
import 'amazon-cognito-identity-js/src/CognitoUserAttribute'
import 'amazon-cognito-identity-js/src/AuthenticationHelper'
import 'amazon-cognito-identity-js/src/DateHelper'

const { AWS, AWSCognito } = window
const { CognitoUser, CognitoUserPool, CognitoRefreshToken, CognitoIdToken, CognitoAccessToken, AuthenticationDetails, CognitoUserSession, CognitoUserAttribute, AuthenticationHelper, DateHelper } = AWSCognito.CognitoIdentityServiceProvider
const { util, VERSION, Signers, Protocol, XML, JSON, Model, apiLoader, Service, Credentials, CredentialProviderChain, TemporaryCredentials, WebIdentityCredentials, CognitoIdentityCredentials, SAMLCredentials, Config, config, Endpoint, HttpRequest, HttpResponse, HttpClient, SequentialExecutor, EventListeners, Request, Response, ResourceWaiter, ParamValidator, events, XHRClient, ACM, APIGateway, ApplicationAutoScaling, AutoScaling, CloudFormation, CloudFront, CloudHSM, CloudTrail, CloudWatch, CloudWatchEvents, CloudWatchLogs, CodeCommit, CodeDeploy, CodePipeline, CognitoIdentity, CognitoIdentityServiceProvider, CognitoSync, ConfigService, DeviceFarm, DirectConnect, DynamoDB, DynamoDBStreams, EC2, ECR, ECS, ElastiCache, ElasticBeanstalk, ElasticTranscoder, ELB, EMR, Firehose, GameLift, Inspector, IotData, Kinesis, KMS, Lambda, MachineLearning, MarketplaceCommerceAnalytics, MobileAnalytics, OpsWorks, RDS, Redshift, Route53, Route53Domains, S3, SES, SNS, SQS, SSM, StorageGateway, STS, WAF } = AWS
export { AWS, AWSCognito, CognitoUser, CognitoUserPool, CognitoRefreshToken, CognitoIdToken, CognitoAccessToken, AuthenticationDetails, CognitoUserSession, CognitoUserAttribute, AuthenticationHelper, DateHelper, util, VERSION, Signers, Protocol, XML, JSON, Model, apiLoader, Service, Credentials, CredentialProviderChain, TemporaryCredentials, WebIdentityCredentials, CognitoIdentityCredentials, SAMLCredentials, Config, config, Endpoint, HttpRequest, HttpResponse, HttpClient, SequentialExecutor, EventListeners, Request, Response, ResourceWaiter, ParamValidator, events, XHRClient, ACM, APIGateway, ApplicationAutoScaling, AutoScaling, CloudFormation, CloudFront, CloudHSM, CloudTrail, CloudWatch, CloudWatchEvents, CloudWatchLogs, CodeCommit, CodeDeploy, CodePipeline, CognitoIdentity, CognitoIdentityServiceProvider, CognitoSync, ConfigService, DeviceFarm, DirectConnect, DynamoDB, DynamoDBStreams, EC2, ECR, ECS, ElastiCache, ElasticBeanstalk, ElasticTranscoder, ELB, EMR, Firehose, GameLift, Inspector, IotData, Kinesis, KMS, Lambda, MachineLearning, MarketplaceCommerceAnalytics, MobileAnalytics, OpsWorks, RDS, Redshift, Route53, Route53Domains, S3, SES, SNS, SQS, SSM, StorageGateway, STS, WAF }
```

This gives me importable pieces from the entire AWS-SDK and this project.

Now, if I put this in a file called `aws.js`, I can do this:

``` js
import {AWSCognito, CognitoUserPool, CognitoUserAttribute} from './aws'

// This is required to derive the endpoint
AWSCognito.config.region = 'us-east-1'

const userPool = new CognitoUserPool({
  UserPoolId: '...', // Your user pool id here
  ClientId: '...' // Your client id here
})

const attributeList = [
  new CognitoUserAttribute({ Name: 'email', Value: 'email@mydomain.com' }),
  new CognitoUserAttribute({ Name: 'phone_number', Value: '+15555555555' })
]

userPool.signUp('username', 'password', attributeList, null, (err, result) => {
  if (err) return console.error(err)
  const cognitoUser = result.user
  console.log('user name is ' + cognitoUser.getUsername())
})
```

In my webpack file I had to also do the hacks mentioned in aws/aws-sdk-js#603 , namely:

``` js
{
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules)/,
        loader: 'babel'
      },
      // gross hack: https://github.com/aws/aws-sdk-js/issues/603
      { test: /aws-sdk/, loaders: ['transform?brfs'] },
      { test: /\.json$/, loaders: ['json'] }
    ]
  }
}
```

and install transform-loader & brfs, which is not ideal (it is requiring me to use browserify, when I don't otherwise need to.)

I still get the warning about it being pre-built (at least until the `TODO` is resolved) but the interface in ES6 is pretty nice.

**Comment by itrestian** [comment]
A pull request for this would definitely be welcome. 

The source for aws-cognito-sdk is the following 

https://github.com/aws/amazon-cognito-identity-js/blob/master/dist/aws-cognito-sdk.js

Although that is generated from the main aws sdk by namespacing it to AWSCognito. The main aws sdk now has all the methods that are required and I am looking into eliminating completely aws-cognito-sdk but preserving the AWSCognito namespace in order to preserve backwards compatibility.

**Comment by konsumer** [comment]
That is what I am getting at above: [this file](https://github.com/aws/amazon-cognito-identity-js/blob/master/dist/aws-cognito-sdk.js) throws a warning in webpack that it's been built, can't be tree-shaked, and leaves a whacked sourcemap. In the above ES6 code-snippet I am importing it. It's not UMD, so it will cause problems for others who use browserify & requirejs, too. It's not really source, it's the generated output from browserify, but if it comes from aws-sdk, then that gives me a hint of where to look to fix it. 

I can't help but feel that ES6 tree-shaking might be able to solve all of these problems mostly automatically, but it'd be a super big pain to track all the internal/external deps and rewrite all in ES6 by hand. Because of ES6's static dep-trees, you can get what's needed at runtime, in the user's own project. For example, if I was only using S3 and Cognito, it would pull all the Cognito, auth, and S3 stuff when my project builds, but trim the rest. Both [rollup](http://rollupjs.org/guide/) and [webpack 2](https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233#.beqwvrgtf) can do this.

I will submit a PR for a simple ES6 interface for this project (that pulls out the right pieces directly from aws-sdk) for now (just the code above with no aws-cognito-sdk,) and do a little research about conversion of the whole aws-sdk to code that is friendlier to ES6 and easier to tree-shake. There might be a way to automate it. Another key thing would be getting rid of dynamic requires, and possibly brfs.

Should I submit an issue (that maybe I fix myself) to move to ES6-focused build-chain for aws-sdk, too?

In situations where the user needs lots of other stuff from aws-sdk, it'd be good to reuse as much as possible, but I do see the importance of maintaining backwards compatibility with `AWSCognito`, but that can really just be an object that points to the underlying aws-sdk stuff. Are other parts of aws-sdk being pulled out like this for other sub-projects like this one? What are the benefits of keeping just the parts in this project separate (like why not merge it all with aws-sdk?)

**Comment by itrestian** [comment]
Yes, it comes from the aws-sdk basically we expose AWSCognito instead of AWS. A PR for that sounds good like you said just an object that points to the underlying aws-sdk stuff. I'm not aware of any other projects like this one. When we first started this project, not all APIs needed were exposed through the main aws sdk.

You can submit an issue for the aws sdk as well I think.

**Comment by konsumer** [comment]
Ok, thanks. It seems that the problem is bigger, as I dive in. For some reason it's unable to find aws-sdk/dist/aws-sdk when it's included in this project, even though I've added aws-sdk as a dependency & `npm install`'d it. I tried to load it in a demo project with both browserify & webpack. I think that is probably related to aws/aws-sdk-js#603.

I'd like to keep working on this, but time-constraints in my own project are prohibitive, and will probably force me to do what everyone else seems to be doing, and just include aws-sdk the old fashioned way (with `<script>` tags,) and not integrate AWS into my build-chain, directly. It will mean lots more for the user to download, but will probably get me where I need to be in a reasonable amount of time.

Hopefully the above code examples are helpful to future-people who are in the same boat. I believe that for aws-sdk-js and amazon-cognito-identity-js to be really useful to people, it should expose its interface in a reasonable way (actually use commonjs or es6 module syntax) to make it able to be integrated into developer's tooling, but I just don't think I have the time right now to do it myself.

**Comment by konsumer** [comment]
For others working on this, I started working on a [simple example](https://github.com/konsumer/aws-cognito-example) that uses webpack, ES6, react, redux. I just gave up on using it in my build system and pulled all the AWS stuff into the index.html with script tags, and it seems to work well.

**Comment by simonbuchan** [comment]
@konsumer, if it helps, I've been using webpack as in this comment: https://github.com/aws/amazon-cognito-identity-js/issues/48#issuecomment-235423796

I've done some changes since then to remove the `moment` import and to ensure only `aws-sdk` is used (and not duplicate stuff from `aws-cognito-sdk`), but the tree-shaking type stuff is something I'd like to get done, our JS bundle is over half unused stuff from `aws-sdk` :)

**Comment by itrestian** [comment]
Pull request solves this
https://github.com/aws/amazon-cognito-identity-js/pull/108
