### ISSUE TITLE
Safari Browser Error: "Refused to connect to 'https://cognito-identity.us-east-1.amazonaws.com/' because it violates the following Content Security Policy directive..."

### ISSUE THREAD

**Issue by heavenfreshca** [aws/amazon-cognito-identity-js#102]
Hello,

I am currently facing an issue which happens when I call the cognito user function “authenticateUser” in my web page and then I am getting an error in my Safari browser error console as seen in the image below.

<img width="1280" alt="safaribrowsererror_signinpage" src="https://cloud.githubusercontent.com/assets/8204819/17561423/d99b1f72-5ef3-11e6-93a4-dddbb3f9486d.png">

The page is deployed under https. Also, I observed that this only occurs when I run the page in a Safari browser. Based on my research, this is related to “Content Security Policy” when it comes to modern browsers.

Please let me know your thoughts about this issue and how can I resolve it.
Thank you in advance for your help.

**Comment by itrestian** [comment]
Can you successfully call signUp and confirmRegistration? Those calls go to the same endpoint.

**Comment by heavenfreshca** [comment]
I've just tried calling signUp function, however it produces the same error as above.

**Comment by itrestian** [comment]
Are you actually setting connect-src in your Content-Security-Policy? You might want to include the endpoint in that.

**Comment by heavenfreshca** [comment]
Yes, I've tried several configurations with the Content-Security-Policy like adding the following on my source code:

`<meta http-equiv="Content-Security-Policy" content="connect-src 'self' https://cognito-identity.us-east-1.amazonaws.com;">`

or

`<meta http-equiv="Content-Security-Policy" content="connect-src 'self' *.amazonaws.com;">`

But still no luck with it..

**Comment by itrestian** [comment]
All I can think is that you have some kind of Safari extension that messes with Javascript execution. This doesn't seem to be related to Cognito as you can see that it is not reading your connect-src tag and uses the default which doesn't whitelist the endpoint.
