### ISSUE TITLE
Authentication fails when remembered devices are enabled

### ISSUE THREAD

**Issue by artema** [aws/amazon-cognito-identity-js#103]
User pools with user devices enabled fail to authenticate for web browsers with long user agent names.

> 1 validation error detected: Value 'Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_4 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G35 (4939056448)' at 'deviceName' failed to satisfy constraint: Member must have length less than or equals to 150.

**Comment by itrestian** [comment]
Thank you for bringing this up. I will bring up this issue with the team so that we prioritize and fix it.

**Comment by itrestian** [comment]
Hi, if this is a solution can you disable device tracking for now and we will have a fix for this in the next release?

**Comment by jbailey2010** [comment]
Hi,

Very sorry for the trouble. We've deployed a fix to loosen up this limitation, you should be unblocked. Try logging in again, let us know if you run into any more issues.
