### ISSUE TITLE
Suddenly getting error "this isn't base64!" during auth.

### ISSUE THREAD

**Issue by RickDT** [aws/amazon-cognito-identity-js#114]
It looks like this is originating in sjcl.js, but I have not changed that file recently. I'm kind of at a loss because I haven't changed anything...

I got this when trying to load a session and trying to login as a user. Both Safari and Chrome.

**Comment by RickDT** [comment]
Additional information: 

Surprisingly, this appears to only affect one user. (though, we only have 2 users in the User Pool at this time). I was able to log in as another test user fine. Additionally, I tried logging in with the broken user on a coworker's machine (who is remote), and they got the same error. Hence, it does appear to be that user and not some sort of improperly cached data (we also used Incognito to test).

The user sub in question is `47ee90a7-dd74-4104-a37f-f5d1556607fe`. Any insight would be great. Thanks!

**Comment by itrestian** [comment]
By looking at sjcl it seems that 

https://github.com/bitwiseshiftleft/sjcl/blob/master/core/codecBase64.js#L40

this is thrown when calling base64.toBits which we call only for converting the secret block to bits that comes base64 encoded from our service. Using Firebug, is the secret block base64 encoded?

**Comment by RickDT** [comment]
Thanks @itrestian. Is this helpful? I've copied the req/resp with the associated error (see line 221) into a gist. The response body is a buffer. Should it have been a Base64 string?

https://gist.github.com/RickDT/12952c16385de5874608ad025bf8f093

**Comment by itrestian** [comment]
It seems you are actually getting the tokens in the response. is device tracking enabled for the user pool?

**Comment by RickDT** [comment]
No, device tracking is not turned on and MFA is Off.

**Comment by itrestian** [comment]
I think I have figured out the problem and pushed the fix for it. The problem was that the JWT tokens were base64url encoded and not base64 encoded. There isn't such a big difference but I guess it kicked in cause of some data that was being escaped and was returned in your id token in which case the parsing of the token failed.

Can you check if the latest code works for you?

**Comment by RickDT** [comment]
Yes, I can log in with this user now! Thanks so much :)

**Comment by fdm20** [comment]
I'm getting the same error. How do you fix this?
