### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by paulsson** [aws/amazon-cognito-identity-js#115]
Typescript is being adopted heavily now and almost all Angular2 projects are using Typescript.
I have an Angular2 project using Typescript and the aws-sdk-js.  Th aws-sdk-js team is providing Typescript typings which are working out great although they aren't in master yet:
https://github.com/aws/aws-sdk-js/tree/support/typescript/typings

When will this add on library for working with cognito user pools add Typescript typings?  I believe the above branch for aws-sdk-js automatically has the typings files created when changes are made.

Is this library going to be rolled into the aws-sdk-js eventually?

Thanks!

**Comment by simonbuchan** [comment]
Main issue would be getting the team to keep it up to date, if they don't want to do that, probably best to leave it to DefinitelyTyped.

**Comment by paulsson** [comment]
The main problem with DefinitelyTyped is the definitions even for typings of aws-sdk-js is that they aren't useable because they are so outdated.  See:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7458

For aws-sdk-js I'm using typings from:
https://github.com/ingenieux/aws-sdk-typescript

**Comment by ryutamaki** [comment]
This is my temporary typings definitions just for reference

``` typescript
declare module "amazon-cognito-identity-js" {

  import { ClientConfig } from "aws-sdk";

  export interface AuthenticationDetailsData {
    Username: string;
    Password: string;
  }

  export class AuthenticationDetails {
    constructor(data: AuthenticationDetailsData);

    public getUsername(): string;
    public getPassword(): string;
    public getValidationData(): any[];
  }

  export interface CognitoUserData {
    Username: string;
    Pool: CognitoUserPool;
  }

  export class CognitoUser {
    constructor(data: CognitoUserData);

    public getSignInUserSession(): CognitoUserSession;
    public getUsername(): string;

    public getAuthenticationFlowType(): string;
    public setAuthenticationFlowType(authenticationFlowType: string): string;

    public getSession(callback: Function): void;
    public authenticateUser(params: any, callbacks: any): void;
    public confirmRegistration(code: string, somethingWhichIsTrue: boolean, callback: (err: any, result: any) => void): void;
    public resendConfirmationCode(callback: Function): void;
  }

  export interface CognitoUserAttributeData {
    Name: string;
    Value: string;
  }

  export class CognitoUserAttribute {
    constructor(data: CognitoUserAttributeData);

    public getValue(): string;
    public setValue(value: string): CognitoUserAttribute;
    public getName(): string;
    public setName(name: string): CognitoUserAttribute;
    public toString(): string;
    public toJSON(): Object;
  }

  export interface CognitoUserPoolData {
    UserPoolId: string;
    ClientId: string;
    Paranoia?: number;
  }

  export class CognitoUserPool {
    constructor(data: CognitoUserPoolData);

    public getUserPoolId(): string;
    public getClientId(): string;
    public getParanoia(): number

    public setParanoia(paranoia: number): void;

    public signUp(username: string, password: string, userAttributes: any[], validationData: any[], callback: (err: any, result: any) => void): void;

    public getCurrentUser(): CognitoUser;
  }

  export interface CognitoUserSessionData {
    IdToken: string;
    AccessToken: string;
    RefreshToken?: string;
  }

  export class CognitoUserSession {
    constructor(data: CognitoUserSessionData);

    public getIdToken(): CognitoIdToken;
    public getRefreshToken(): CognitoRefreshToken;
    public getAccessToken(): CognitoAccessToken;
    public isValid(): boolean;
  }

  export class CognitoIdentityServiceProvider {
    public config: ClientConfig;
  }

  export class CognitoAccessToken {
    constructor(accessToken: string);

    getJwtToken(): string;
    getExpiration(): number;
  }

  export class CognitoIdToken {
    constructor(idToken: string);

    getJwtToken(): string;
    getExpiration(): number;
  }

  export class CognitoRefreshToken {
    constructor(refreshToken: string);

    getJwtToken(): string;
    getExpiration(): number;
  }
}
```

**Comment by itrestian** [comment]
Thanks! Closing the issue since we merged the above. Thanks everyone!

**Comment by cvrabie** [comment]
There doesn't seem to be a ClientConfig exported by the aws-sdk anymore. I think that for the Cognito identity service provider this has been replaced by [`CognitoIdentityServiceProvider.Types.ClientConfiguration`](https://github.com/aws/aws-sdk-js/blob/master/clients/cognitoidentityserviceprovider.d.ts#L12) which is just [`ServiceConfigurationOptions & ClientApiVersions`](https://github.com/aws/aws-sdk-js/blob/master/clients/cognitoidentityserviceprovider.d.ts#L2594)

**Comment by cvrabie** [comment]
Pull request to fix this: https://github.com/aws/amazon-cognito-identity-js/pull/254

**Comment by quantuminformation** [comment]
Thanks for doing this, 

its actually easier if you dev in TypeScript first as you get the types export for free. You can then auto publish it to defTyped.
