### ISSUE TITLE
Error: CognitoUserPool is not a constructor

### ISSUE THREAD

**Issue by cmoel** [aws/amazon-cognito-identity-js#116]
Hi folks

I'm running into an issue when following Use Case 1 from the Usage section of the README:
https://github.com/aws/amazon-cognito-identity-js#usage. I installed the library into my project with a specific SHA because I'm trying to use it with Webpack:

```
npm install --save github:aws/amazon-cognito-identity-js#c82b936991d4e8aedf02302817f4f21428d246cc
```

I was successfully able to get `AWSCognito` as a global variable in my project after updating my Webpack config with the instructions I found here: https://github.com/aws/amazon-cognito-identity-js/issues/48#issuecomment-235423796.

The problem I'm experiencing is with this code (using a real `UserPoolId` and real `ClientId`):

``` javascript
AWSCognito.config.region = 'us-east-1'
var poolData = {
  UserPoolId: '<my-pool-id>',
  ClientId: '<my-client-id>',
}
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData)
```

I get this error in the console:

```
Uncaught TypeError: AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool is not a constructor
```

What am I doing wrong?

Thanks!

**Comment by simonbuchan** [comment]
Sorry, this is me changing the build to output a UMD package in #108, so when in use by a package-aware system like webpack you don't need to do nearly any of that any more. I'm writing a PR to update the docs now, but that PR has an updated webpack.config.

**Comment by cmoel** [comment]
Ok, great! Thanks for the heads up. Anything I can do to help?

**Comment by simonbuchan** [comment]
@cmoel I'll ping this issue when I put up the PR so you can take a look and see if I missed anything?

**Comment by simonbuchan** [comment]
@cmoel Up at #117

**Comment by cmoel** [comment]
@simonbuchan Thanks for the updated docs, they definitely helped with getting set up! I created a small PR to help with importing for people not used to the `exports-loader`: https://github.com/aws/amazon-cognito-identity-js/pull/122.

I'm still getting the same `CognitoUserPool is not a constructor` error but don't have much more time to try to troubleshoot at this point. I'll be traveling for the next few weeks and should be able to take another look when I'm back.

**Comment by joneal** [comment]
I am getting the same exception with the latest pulled from GitHub.  When will this issue be resolved?

**Comment by simonbuchan** [comment]
You get this message when incorrectly importing the library, that is, the
constructor in undefined. This issue was closed with updated usage docs, so
I suggest checking against that first

**Comment by joneal** [comment]
Thanks.

I found that I was loading the libraries out of order i.e. was loading
'amazon-cognito-identity.min.js' before 'aws-cognito-sdk.js'.  Once I
switched order everything started working.

Bad:
    <script src="aws/jsbn.js"></script>
    <script src="aws/jsbn2.js"></script>
    <script src="aws/sjcl.min.js"></script>
    <script src="aws/amazon-cognito-identity.min.js"></script>
    <script src="aws/aws-cognito-sdk.js"></script>

Good:
    <script src="aws/jsbn.js"></script>
    <script src="aws/jsbn2.js"></script>
    <script src="aws/sjcl.min.js"></script>
    <script src="aws/aws-cognito-sdk.js"></script>
    <script src="aws/amazon-cognito-identity.min.js"></script>
