### ISSUE TITLE
Uncaught TypeError: Cannot read property 'BigInteger' of undefined

### ISSUE THREAD

**Issue by hengbenkeji** [aws/amazon-cognito-identity-js#124]
I use the library in a typical nodejs development environment.
The following code (Use Case 4) generates an error.

```
cognitoUser.authenticateUser(authenticationDetails, {
    onSuccess: function (result) {
      console.log('access token + ' + result.getAccessToken().getJwtToken());
      AWS.config.credentials = new AWS.CognitoIdentityCredentials({
          IdentityPoolId : 'us-east-1:bf6edaa6-69fb-4e81-bdd5-cd7868xxxxxx',
          Logins : {
              'us-east-1_qWYxxxxxx' : result.getIdToken().getJwtToken()
          }
        });
    },

    onFailure: function(err) {
        alert(err);
    },

});
```

I traced the error down to the function as shown below. Any workaround for this problem?
By the way, when I use your updated contents on webpack, I still have this problem.

![default](https://cloud.githubusercontent.com/assets/15041387/17916132/ffe784b4-69e2-11e6-970c-3f3cbf5e593c.JPG)

**Comment by itrestian** [comment]
Are you using the dist files for our library from github or from npm? Can you try the github dist files for our library?

**Comment by hengbenkeji** [comment]
Thank you Sir, I will try github this time.

**Comment by hengbenkeji** [comment]
Problem solved. Yet, I still get other problems, which I will post in a new post.
I tried the js libraries available on this Repo, and it worked.
The BigInteger problem is solved.

**Comment by itrestian** [comment]
I have just updated npm as well.
