### ISSUE TITLE
How to make a ClientId for browsers' use?

### ISSUE THREAD

**Issue by hengbenkeji** [aws/amazon-cognito-identity-js#125]
I just create a ClientId by the following command for my browser.

```
aws cognito-idp create-user-pool-client --user-pool-id  us-east-1_qWYpdEk4A --client-name clientname1
```

Then I got the following ClientId, then I used the ClientId for Use Case 4.

```
{
    "UserPoolClient": {
        "UserPoolId": "us-east-1_qWYpdEk4A",
        "LastModifiedDate": 1471871472.647,
        "ClientId": "5gvf9g9ee0dtvb9rm3acoqis6r",
        "RefreshTokenValidity": 30,
        "CreationDate": 1471871472.647,
        "ClientName": "clientname1"
    }
}
```

Yet, I got errors reporting "POST https://cognito-idp.us-east-1.amazonaws.com/ 400 (Bad Request)" in the console of my browser, as follows

![image](https://cloud.githubusercontent.com/assets/15041387/17918045/3d8efb10-69f4-11e6-89aa-4e7df0ec1674.png)

I searched the reported issues here, failing to find a solution.

The following is my code according to Use Case 4. Is there something wrong?

```
AWSCognito.config.region = 'us-east-1'
var authenticationData = {
    Username : 'username',
    Password : 'password',
}

var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData)
var poolData = { 
    UserPoolId : 'us-east-1_qWYpdEk4A', // Your user pool id here
    ClientId : '5gvf9g9ee0dtvb9rm3acoqis6r' // Your client id here
}

var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
var userData = {
    Username:   'username',
    Pool:       userPool
};

var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

cognitoUser.authenticateUser(authenticationDetails, {
  onSuccess: function (result) {
    console.log('access token + ' + result.getAccessToken().getJwtToken());
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId : 'bf6edaa6-69fb-4e81-bdd5-cd7868b86539',
      Logins : {
        'cognito-idp.us-east-1.amazonaws.com/qWYpdEk4A' : result.getIdToken().getJwtToken()
      }
    });
  },

  onFailure: function(err) {
      alert(err);
  },

});
```

The errors in my browser:
![image](https://cloud.githubusercontent.com/assets/15041387/17917904/e3060946-69f2-11e6-9ead-a50fabc6aa1d.png)

**Comment by itrestian** [comment]
The error says that your user does not exist. You should create and confirm a user before signing in.

**Comment by hengbenkeji** [comment]
Thank you Sir. Problem solved.

I must do User Case 1 to create a user first, then I do User Case 4 to authenticate the user.

A new user can ask silly questions.
