### ISSUE TITLE
latest npm/webpack not working

### ISSUE THREAD

**Issue by crediblenotand** [aws/amazon-cognito-identity-js#127]
related to https://github.com/aws/amazon-cognito-identity-js/pull/108

with Node.js 5.x, or 6.x, Webpack 1.13 and following the latest instructions in the README.md, and version 1.0.0 from https://www.npmjs.com/package/amazon-cognito-identity-js (published this morning)

``` javascript
new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails({
  Username: 'myUsername',
  Password: 'myPassword'
});
```

the following error is retured:

```
AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails is not a constructor
```

**Comment by itrestian** [comment]
Hi, not sure what your setup is but have you seen Simon's comment below:

@itrestian probably should also update the examples to show the difference with using the SDK as a module - that is, you don't need to get the exports off of AWSCognito.CognitoIdentityServiceProvider? That should probably wait until this is published on npm though.

-var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
+var cognito = require('amazon-cognito-identity-js');
+var userPool = new cognito.CognitoUserPool(poolData);

**Comment by sarah-pixvana** [comment]
@crediblenotand I have seen that error before when i am not properly importing 'amazon-cognito-identity-js/dist/amazon-cognito-identity.min'

**Comment by crediblenotand** [comment]
thank you @itrestian and @sarah-pixvana 

the old `require` syntax appears to work, but I can't figure out how to get the es6 `import` syntax to work.

**Comment by crediblenotand** [comment]
ignore my previous comment, the following works:

``` javascript
import AWSCognito from 'aws-sdk'
import { AuthenticationDetails, CognitoUserPool, CognitoUser } from 'amazon-cognito-identity-js';
```

**Comment by itrestian** [comment]
glad to hear it. so we can close this?
