### ISSUE TITLE
Error: undefined is not an object (evaluating 'a.codec.utf8String')

### ISSUE THREAD

**Issue by npalethorpe** [aws/amazon-cognito-identity-js#129]
Getting the above error after updating my scripts to the latest versions of 'amazon-cognito-identity.min.js' when making a call to cognitoUser.getSession.

**Comment by itrestian** [comment]
This seems to be an issue with sjcl. Perhaps you are missing some functions in sjcl (it is customizable). Can you check if your sjcl has the utf8String codec or pull it from the sjcl github.

**Comment by npalethorpe** [comment]
Hi, I can confirm I have the full the sjcl version with utf8String codec. I am running the latest version from the root directory on the sjcl github. The issue has only started occurring since updating the amazon-cogito-identity.min.js files.
Appreciate the help.

**Comment by itrestian** [comment]
Can you check if you have the base64url codec as well?

**Comment by npalethorpe** [comment]
Within the sjcl.js file? Yes, I can see the sjcl.codec.base64url within the file.

**Comment by npalethorpe** [comment]
Sorry, found out what the issue was; I had temporarily commented out the include line for the sjcl.js file...and then forgotten I had commented it out. I apologise for wasting your time on my stupidity!

**Comment by itrestian** [comment]
No worries. Glad you managed to solve it.
