### ISSUE TITLE
Session tokens clarification.

### ISSUE THREAD

**Issue by newtriks** [aws/amazon-cognito-identity-js#131]
I am securing my AWS gateway api using Cognito user pool authorizers. This requires me to send a header with key `Authorization` and value of a user `token`. Currently I can follow the steps to sign in to the Cognito User Pool as an identity provider and then on success use the token to make a successful API request e.g. `result.getIdToken().getJwtToken()`. 

When I add the provider name and token to the `Logins` map and using `AWS.config.credentials.get` I can retrieve a `sessionToken`.

It then gets confusing as when I retrieve the user from the local store I get an error that the session has expired but `AWS.config.credentials.sessionToken` returns a value.

Could someone help clarify what these sessions and tokens with their differences and real world application in authorisation please?

**Comment by jbailey2010** [comment]
Apologies for the confusion.

The session token is just a piece of the AWS credentials that you get back in the credentials.get call, it's only associated with those credentials and refers to the session of the credentials. The tokens in the user pools context refers to the user's login session, not the credentials session. It's used to identify the user during that authenticated session.

Does that make sense?

**Comment by newtriks** [comment]
No need for apologies  :) So to clarify, there are two sessions to be aware of, each with their own unique tokens:
1. A credentials session and its token is retrieved using `AWS.config.credentials.get`.
2. A user login and its token is retrieved using `result.getIdToken().getJwtToken()`.

Makes sense @jbailey2010 thanks. 

Would I be correct suggesting that `AWS.config.credentials.get` would be used for _unauthenticated_ sessions only e.g. because a JWT token is not required but a valid credentials session is?

**Comment by jbailey2010** [comment]
One slight change to that - the result.getIdToken().getJwtToken() only gets the id token, not the rest of it. I believe the access and refresh token for that login session are inside result, and retrieved in a similar manner.

So, it should be used for either. If a provider login token (for example the id token from the user pools session) is given, it will use that to generate credentials for an authenticated cognito federated identity. If none is given, it will generate credentials for an unauthenticated one. It distinguishes between the two based on if a login token has been given. 

This call is where the SDK consumes the identity token that you got from signing in with user pools and uses that to give you credentials.
