### ISSUE TITLE
Cannot read property 'hex' of undefined

### ISSUE THREAD

**Issue by yasuhiro-iida** [aws/amazon-cognito-identity-js#134]
aws-cognito-sdk.min.js:20 Cannot read property 'hex' of undefined

I could sign up my Cognito User Pools, but could not login(Use case 4).
I include every APIs(jsbn.js, jsbn2.js, sjcl.js, aws-sdk.js, aws-cognito-sdk.min.js, amazon-cognito-identity.min.js).

Does some library miss or some implementation is needed for Use case 4?

Thanks in advance!

**Comment by itrestian** [comment]
That should be part of sjcl so it means your import of sjcl is not working.
The dependencies are required only to do the SRP math for authentication so that is why the login is not working. How are you importing sjcl?

**Comment by simonbuchan** [comment]
It will be failing on `AuthenticationHelper.js:223`:

```
const hashHex = sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash(sjcl.codec.hex.toBits(hexStr)));
                           ^
```

Essentially, `sjcl` is defined, but not the actual `sjcl` module as `sjcl.codec` is undefined.

Our build (specifically, the babel translation of `import`) defaults undefined or null so `sjcl` is probably not defined at all in the browser: try evaluating `sjcl` using the browser F12 javascript console.

Perhaps check you are used Save As... on the [raw `sjcl.js` from the root of the github repository](https://raw.githubusercontent.com/bitwiseshiftleft/sjcl/master/sjcl.js), not the github page for it.

The SDK could add early-checks for the libraries being defined correctly?

``` js
import AWS from 'aws-sdk';
import sjcl from 'sjcl';
import jsbn from 'jsbn';

if (typeof AWS === 'undefined' || !AWS || typeof AWS.CognitoIdentityServiceProvider !== 'function') {
  // Or throw?
  console.error('Amazon Cognito Identity SDK: Missing or invalid aws-sdk dependency');
}
if (typeof sjcl === 'undefined' || !sjcl || !sjcl.codecs || typeof sjcl.codec.hex !== 'function') {
  console.error('Amazon Cognito Identity SDK: Missing or invalid sjcl dependency');
}
if (typeof jsbn === 'undefined' || !jsbn || typeof jsbn.BigInteger !== 'function') {
  console.error('Amazon Cognito Identity SDK: Missing or invalid jsbn dependency');
}
```

**Comment by itrestian** [comment]
Yes, it would make sense to add checks for the basic ones that might be missing depending on sjcl library users import.

**Comment by hsachdevah** [comment]
I was facing the same issue but then replaced the sjcl.js with the link provided by @simonbuchan and it worked like a charm :)

**Comment by itrestian** [comment]
Did that work @yasuhiro-iida?

**Comment by yasuhiro-iida** [comment]
Thank you!
It works if I replaced the sjcl.js.
