### ISSUE TITLE
What Authentication Flow is used for `cognitoUser.authenticateUser`?

### ISSUE THREAD

**Issue by emmanuelmillionaer** [aws/amazon-cognito-identity-js#137]
In order to get a valid user session I am doing the same like in Use Case 4 described in the Readme:

```
   cognitoUser.authenticateUser
```

Seeing the code, https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js I am not sure which authentication-flow from the Cognito-Docs is used:

http://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html

Could you please give me a hint? Thanks

**Comment by jbailey2010** [comment]
It's actually neither. The flows you were looking at were the authentication flows for Cognito federated identities, not for Cognito user pools. They're different services. Authenticate signs the user in, which will give the login tokens back for the user's session. If you want to use federated identities, you can treat the id token you got back as the login token of a provider, but other than that overlap, they're different services.

Does that make sense?

**Comment by emmanuelmillionaer** [comment]
@jbailey2010 Thanks!

**Comment by emmanuelmillionaer** [comment]
@jbailey2010 Thanks for this answer 👍 Is there additional documentation regarding Cognito user pool authentication?

**Comment by jbailey2010** [comment]
Lots of it in our [developer guide](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html)

**Comment by emmanuelmillionaer** [comment]
@jbailey2010 Great! Thanks a lot! 💯

**Comment by sdruipeng** [comment]
too early to say thanks
