### ISSUE TITLE
Cannot use Safari in private mode

### ISSUE THREAD

**Issue by yasuhiro-iida** [aws/amazon-cognito-identity-js#138]
I got error 'QuotaExceededError: QuotaExceededError: DOM Exception 22' in Safari private mode.

I could not signin for Cognito User Pools. It does not happen in normal mode. Is this the same [issue](https://github.com/aws/aws-sdk-mobile-analytics-js/issues/10) ?

How to avoid this error?

Thanks in advance!

**Comment by itrestian** [comment]
Seems like it. We do use localStorage for storing tokens. Although some users don't want to use localStorage and we will most probably make it optional as outlined below:

https://github.com/aws/amazon-cognito-identity-js/issues/87

**Comment by yasuhiro-iida** [comment]
Thank you!
So now we can not avoid this situation. I'm waiting for not using localStorage by default.
