### ISSUE TITLE
Missing credentials in config

### ISSUE THREAD

**Issue by yasuhiro-iida** [aws/amazon-cognito-identity-js#139]
I got an error "NotAuthorizedException: Missing credentials in config".
Basically I can user signup, login , etc... but cannot use admin method(adminDisableUser, adminDeleteUser...)

Here is my code.

``` :js
AWS.config.region = 'ap-northeast-1';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'MyIdentityPoolId'
});
var provider = new AWS.CognitoIdentityServiceProvider();

var params = {
    UserPoolId: 'MyUserPoolId',
    Username: 'Username'
};

provider.adminDisableUser(params, function(err, data) {
    if (err) {
        console.log(err);
    } else {
        console.log(data);
    }
}
```

What I missed or do i need more settings in Cognito console?

Thanks in advance!

**Comment by itrestian** [comment]
You are missing a call to refresh after you specify the identity pool id. Check use case 17 in README.

**Comment by yasuhiro-iida** [comment]
Is this step correct?
1. Initialize credentials
2. Login cognito user pools
3. refresh credentials
4. can use admin method

**Comment by itrestian** [comment]
If you're using the id token that you get from user pools in the logins map, you should do 2 first. That's basically what use case 17 does. Calling admin methods only require aws credentials, no user pools access token.

**Comment by yasuhiro-iida** [comment]
Thank you so much!
Finally, it works if I add the refresh credentials step!

**Comment by tbiinfotech** [comment]
How can I get `MyIdentityPoolId` programmatically?
