### ISSUE TITLE
Login with cognito federated identitiy

### ISSUE THREAD

**Issue by GuerkanDemirci** [aws/amazon-cognito-identity-js#14]
I got all examples working by hard coding my AWS credentials into the web page code.

Now I want to remove my AWS credentials and change to federated identity login.
I've created an federated identity pool and selected Cognito as the authentication provider.
I've used my user pool id and app client id to configure the authentication provider settings.

When omitting the
    AWSCognito.config.update({accessKeyId: '....', secretAccessKey: '...'});
and using
    AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({ IdentityPoolId: '....'});
instead, then I am getting a failure stating
   "NotAuthorizedException: Missing credentials in config"

How do I need to configure the CognitoIdentityCredentials to be able to login with my Cognito provider?

**Comment by GuerkanDemirci** [comment]
I am getting success when enabling "Enable access to unauthenticated identities" on the federated identity pool. The user is already registered in my Cognito authentication provider and I can see the login is successfully failing when giving wrong username or password. Isn't that an authenticated identity?

**Comment by theJasonHall** [comment]
I'm running into this same issue while running the sign up code (Use case 1) from the readme.  After enabling "Enable access to unauthenticated identities", it worked.

I looked at the Network tab and there are five calls to us-east-1.amazonaws.com.  These are the requests in order:

Request URL:https://cognito-identity.us-east-1.amazonaws.com/
1. OPTIONS
2. POST -  X-Amz-Target:AWSCognitoIdentityService.GetId 
3. POST - X-Amz-Target:AWSCognitoIdentityService.GetCredentialsForIdentity

Request URL:https://cognito-idp.us-east-1.amazonaws.com/
4. OPTIONS
5. POST - X-Amz-Target:AWSCognitoIdentityProviderService.SignUp

When "Enable access to unauthenticated identities" is disabled, it fails at 2.

Hope this helps!

**Comment by itrestian** [comment]
At this point you shouldn't require passing AWS credentials (even dummy ones) as we have switched to unauthenticated calls when making User Pools calls.
