### ISSUE TITLE
Test failing when running CognitoUserPool

### ISSUE THREAD

**Issue by jamieallen59** [aws/amazon-cognito-identity-js#141]
The getCurrentUser function in CognitoUserPool relies on local storage which breaks when running my tests.

Would it be good to add some sanitisation so it doesn't fail if localStorage or getItem do not exist? e.g. change this part:

``` javascript
  getCurrentUser() {
    const lastUserKey = `CognitoIdentityServiceProvider.${this.clientId}.LastAuthUser`;
    const storage = window.localStorage;

    const lastAuthUser = storage.getItem(lastUserKey);
    if (lastAuthUser) {
      const cognitoUser = {
        Username: lastAuthUser,
        Pool: this,
      };

      return new CognitoUser(cognitoUser);
    }

    return null;
  }
```

To this:

``` javascript
  getCurrentUser() {
    const lastUserKey = `CognitoIdentityServiceProvider.${this.clientId}.LastAuthUser`;
    const { localStorage = {} } = window;

    const lastAuthUser = localStorage.getItem ? localStorage.getItem(lastUserKey) : null;
    if (lastAuthUser) {
      const cognitoUser = {
        Username: lastAuthUser,
        Pool: this,
      };

      return new CognitoUser(cognitoUser);
    }

    return null;
  }
```

What do you think? Would have opened a pull request if I could have!

**Comment by itrestian** [comment]
This is definitely a direction we are considering as you can see in the issue about making localStorage use optional:

https://github.com/aws/amazon-cognito-identity-js/issues/87

**Comment by simonbuchan** [comment]
You could also fake out either the SDK, as in #136 or local storage, as I am currently doing in [my SDK test suite branch](https://github.com/skilitics/amazon-cognito-identity-js/blob/tests/src/CognitoUserPool.test.js#L100)

**Comment by jamieallen59** [comment]
Yea I ended up faking localStorage to get it passing. I just assumed that you wouldn't want to assume localStorage existence. But then... "Assumption is the mother of all...". Thanks for the quick answers!
