### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Unicoranium** [aws/amazon-cognito-identity-js#142]
I am trying to call "cognitoUser.authenticateUser()" but it says "Uncaught TypeError: n.update is not a function" in console.

This [Plunker](http://plnkr.co/edit/QjdXvmtEYdvH2db9cvcr?p=preview) produces the error in console.
Test username and password are both "TestUser1".

**Comment by itrestian** [comment]
Most probably you are missing part of the SJCL library, similar to https://github.com/aws/amazon-cognito-identity-js/issues/134

**Comment by Unicoranium** [comment]
I had that same error but I fixed it because my script tags were in the wrong order

**Comment by Unicoranium** [comment]
Wait... Never mind... I used @simonbuchan 's sjcl.js link and it works now. Thank you for leading me there though

**Comment by simonbuchan** [comment]
Sounds like we should just direct link the files in the docs?

**Comment by Unicoranium** [comment]
I think that would make less problems with them. I've had 2 errors that wouldn't have happened if it was just copy paste the script tags

**Comment by itrestian** [comment]
Thanks! Just updated:
https://github.com/aws/amazon-cognito-identity-js/commit/8e09695773f9aea6ce4f7133b7989a4a0a46aa67
