### ISSUE TITLE
Authenticating over multiple devices

### ISSUE THREAD

**Issue by npalethorpe** [aws/amazon-cognito-identity-js#144]
I've been developing an application up until now I've been switching between an iPhone and an Android phone; authentication has been fine up until now. Today I have tried to use a different iPhone and each time I attempt a login it comes back with a 'NotAuthorizedException' - I am using the exact same details for all phones (I've triple checked this!).

The only thing I can think it may be is that we have device remembering turned on... - In the documentation it states that "_you can track devices that users have logged in to, as well as set a maximum number of devices per user_" only I can't see anywhere to set the maximum number of devices so I don't know if I'm running into that - and even if I were, why would I be getting a 'NotAuthorizedException' response back?

Any help would be much appreciated.

**Comment by jbailey2010** [comment]
I can tell you with absolute confidence it doesn't have to do with number of devices. A few follow up questions:
- How long before this issue popped up did you enable device remembering?
- Are you trying to share refresh tokens across devices?
- Did you tinker with or alter the local storage in any way before this popped up?
- Can you give us a request id and timestamp of a failed authentication?

**Comment by npalethorpe** [comment]
We've had device remembering enabled for the past 3 weeks (at a guess) but I feel this is likely the first 'new' device I've attempted to log in using since turning on device remembering. It is worth mentioning that I turned device remembering off and then attempted to login and I got the same error.

As far as I am aware I'm not attempting to share the refresh token - I take it direct from the session object (Called from getCurrentUser().getSession).

Around the login procedure I don't touch the local storage - thats not to say there isn't any values in the local storage at the point of logging in.

I've just ran the procedure again and got the same error - see below the response (Along with request Id) as requested:
`2016-09-16 20:01:56.887675 myapp[371:60270] {"credentials":null,"credentialProvider":null,"region":"us-east-1","logger":null,"apiVersions":{},"apiVersion":null,"httpOptions":{"timeout":120000},"maxRedirects":10,"paramValidation":true,"sslEnabled":true,"s3ForcePathStyle":false,"s3BucketEndpoint":false,"s3DisableBodySigning":true,"computeChecksums":true,"convertResponseTypes":true,"correctClockSkew":false,"customUserAgent":null,"dynamoDbCrc32":true,"systemClockOffset":0,"signatureVersion":null,"signatureCache":true,"retryDelayOptions":{"base":100},"useAccelerateEndpoint":false}
2016-09-16 20:02:33.527164 myapp[371:60270] Authentication Error: {"line":20,"column":5758,"sourceURL":"file:///var/containers/Bundle/Application/C0...E6C40/myapp.app/www/js/lib/aws-cognito-sdk.min.js","message":"Incorrect username or password.","code":"NotAuthorizedException","time":"2016-09-16T19:02:33.501Z","requestId":"1fb14095-7c40-11e6-aba4-59def130cdc9","statusCode":400,"retryable":false,"retryDelay":27.100237027324603}`

Thanks for the help

**Comment by jbailey2010** [comment]
We'll dive deeper once we're back in office, but I can tell you that failure isn't related to device tracking. It failed during the PASSWORD_VERIFIER stage of the RespondToAuthChallenge API, which is the part of the authentication where the user's username and password are validated. It hadn't yet tried to authenticate the device.

**Comment by jbailey2010** [comment]
Apologies for the slow follow up. Are you still running into this issue? If so, could you provide a few snippets of how you're authenticating with the SDK?
