### ISSUE TITLE
authenticateUser skipping GetId call

### ISSUE THREAD

**Issue by birnbaum** [aws/amazon-cognito-identity-js#15]
I experienced the problem that the first `authenticateUser` call after a page refresh fails with an "missing credentials error" (that often masks the real error returned by the API).

Under the hood `authenticateUser` seems to call `GetCredentialsForIdentity` with some IdentityId that gets rejected by the API with an _NotAuthorizedException_. If I fire `authenticateUser` a second time - without changing anything in between - it is first doing a call to `GetId` and then calling `GetCredentialsForIdentity` with this new ID that then gets accepted.

As a workaround I now call `AWSCognito.config.credentials.clearCachedId();` before calling `authenticateUser` and everything works fine.

---

At the beginning of the script I do:

```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: 'eu-west-1:e71ecd05-fbec-430b-8520-60d375fad889'
});
AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: 'eu-west-1:e71ecd05-fbec-430b-8520-60d375fad889'
});
```

Am I missing something or is this a bug?

**Comment by gpcrawford** [comment]
I am seeing the same thing - the first call to authenticateUser succeeds, the next one fails, the next one succeeds... and so on.  However, calling the clearCachedId method before authenticateUser makes things work as expected.

**Comment by nosh** [comment]
I'm seeing this behavior as well. Calling AWSCognito.config.credentials.clearCachedId() before authenticate prevents this from happening. 
However, (in addition) every time I refresh the page and re-login (with a call to 'authenticateUser'), a new unauthenticated user is created (even though I successfully log in with a username/password. So I'm ending up with 100s of unauthenticated users in my pool, even though I've only logged in with authentication. Is this expected?

**Comment by itrestian** [comment]
Hi guys,

For authenticateUser don't think credentials are needed in the first place since these calls are marked as such. You might have to set some values for the credentials but that is just an artifact of the AWS SDK that does a check and throws an error if no credentials are present.

For example:  AWSCognito.config.update({accessKeyId: 'ionutkey', secretAccessKey: 'ionutsecret'});

Let me know if it works. 

Ionut.
