### ISSUE TITLE
This versus AWS-SDK Webpack modules

### ISSUE THREAD

**Issue by pruett** [aws/amazon-cognito-identity-js#151]
I'm curious how this approach compares against using the aws-sdk now with built-in module / webpack support? https://github.com/aws/aws-sdk-js/pull/1123

Does this tutorial translate well with using the indivdual sdk "clients"? https://github.com/aws/aws-sdk-js/tree/master/clients

If so, can you point out the pieces of this tutorial that map with their respective "clients"?

Thanks.

**Comment by itrestian** [comment]
Basically this library is just a wrapper over the cognitoidentityserviceprovider client available in the aws-sdk. This library just provides the features that are listed in the README, for example (among others) it does the SRP math required for authentication and it provides functions for device remembering if this is a feature you have enabled in your user pool. 

Of course you could just skip completely in using this SDK and implement all the features mentioned directly in your project and call the respective APIs.

**Comment by pruett** [comment]
I see. Thank you.
