### ISSUE TITLE
Token is not from a supported provider of this identity pool

### ISSUE THREAD

**Issue by vinodhum** [aws/amazon-cognito-identity-js#153]
Hi,
I am getting "Token is not from a supported provider of this identity pool"
fallowing steps from example I was able to create user and authenticate user
but after authentication when I try to configure Aws with below code I Keep getting
that error

```
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId :  IdentityId_Pool_ID,
                Logins : {
                    'cognito-idp.us-east-1.amazonaws.com/'+User_Pool_ID : result.getIdToken().getJwtToken()
                }); 
```

I am using exact same Identity Pool ID, User Pool ID and Client ID for all api call's.
any idea what I am I doing wrong ?

**Comment by simonbuchan** [comment]
I hit this when the region after `cognito-idp.` in the logins didn't match the pool region, though for me it was in the code creating the identity pool.

**Comment by rachitdhall** [comment]
Is your identity pool configured with the correct user pool? You can associate Cognito user pool with Cognito Identity Pool in the Cognito Federated Identities console under the section Cognito in 'Authentication providers' tab.

**Comment by vinodhum** [comment]
I deleted and created new userPool and forgot to update Authentication providers so  I had wrong userPool Id in Authentication providers once updated with new userpoolid it worked.
thanx
