### ISSUE TITLE
custom html message not sent

### ISSUE THREAD

**Issue by solshark** [aws/amazon-cognito-identity-js#155]
Hi,

I'm trying to send custom html message on user sign up (with lambda function). If I stick to short plain text message - it works fine. But if I use html (with inline styles which make message quite big) I'm getting default message from web ui customization.

Any way to send nice-looking html messages?

Little update - very basic html works, but not if it's getting complex. And I can't find any error logs or similar which might give me a hints.

**Comment by RickDT** [comment]
I had the same issue lately and had to reduce the size of the HTML string by a lot. I removed superfluous white space and redundant styles and eventually got it to go through, but it was a pain to test and trouble-shoot.

Some official documentation on the limits placed on that Trigger response would be great!

**Comment by solshark** [comment]
@RickDT Thx for hint. Will start to do the same (minify html).

**Comment by itrestian** [comment]
Hi, we recently increased the size of the messages that can be sent so this should be solved now.

**Comment by joost** [comment]
The [aws cognito message costomization docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-settings-message-customizations.html) say: "The maximum length for the message is 2048 UTF-8 characters, including the verification code."

@itrestian is this still the case? BTW there is an error in the docs saying the 'Customizing SMS Verification Messages' can be 2048 chars.

**Comment by itrestian** [comment]
It should work now with more than 2048 chars (Custom message length). We are in the process of updating the documentation.
