### ISSUE TITLE
Latest version breaks webpack build

### ISSUE THREAD

**Issue by sarah-pixvana** [aws/amazon-cognito-identity-js#156]
The latest update (1.5.0) breaks my webpack build. I am getting an error "require not defined" coming from aws-sdk/clients/cognitoidentityserviceprovider.js 
<img width="942" alt="screen shot 2016-09-23 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/17787540/18796302/7f6e44c8-817d-11e6-85bd-fbf99e58c970.png">

**Comment by sarah-pixvana** [comment]
@itrestian  just want to make sure you see this.

**Comment by itrestian** [comment]
Are you using a webpack setup similar to the one in the examples?

**Comment by sarah-pixvana** [comment]
Yes followed almost exactly. Below is my webpack config file. (Note that everything works fine when I roll back to 1.2.0)

```
'use strict';
let webpack = require('webpack');
const AWS_SDK_MAIN = 'aws-sdk/dist/aws-sdk.min';
let DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = {
    devtool: 'eval-source-map',
    entry: ['./app/index.js'] ,
    output: {
        path: __dirname,
        publicPath: '/',
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['', '.js', '.jsx'],
        alias: {
            'aws-sdk$': AWS_SDK_MAIN
        }
    },
    module: {
        loaders: [
            { exclude: /node_modules/, loader: 'babel',query: {presets: ['react', 'es2015', 'stage-1']} },
            { test: /\.css$/,loader: 'style-loader' },
            { test: /\.css$/, loader: 'css-loader', query: {modules: true, localIdentName: '[local]___[hash:base64:5]'} },
            { test: /\.css$/,loader: 'postcss-loader' },  
            { test: require.resolve(AWS_SDK_MAIN), loader: 'exports?AWS' }
        ],
        noParse:  [
            /aws\-sdk/,
            /aws-cognito-sdk/
        ],
        preLoaders: [
            {
                test: /\.min\.js$/,
                loader: 'source-map'
            }
        ],
    },
    postcss: function (webpack){
        return [
            require('postcss-import')({ addDependencyTo: webpack }),
            require('postcss-cssnext')
        ];
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': '"debug"' //production, dev, trace, debug, info, warn, error 
            }
        }),
        new DashboardPlugin({ port: 8080 })
    ],

    devServer: {
        historyApiFallback: true,
        contentBase: './',
        colors: true,
        inline: true
    }
};
```

**Comment by hassankhan** [comment]
Any update on this? Getting the same error 😢 In my case, rolling down to 1.2.0 now causes errors about the AWS-SDK not being found. Should I be using the full AWS SDK? 

Also, I have two Webpack configurations, one for dev and one for production. I only get the `require is not defined` error on the production build.

**Comment by hassankhan** [comment]
I'm working around the issue by copying the `src/` folder to my project and installing the AWS-SDK.

**Comment by hassankhan** [comment]
Ok, figured out what I was doing wrong, should have been obvious with hindsight 🙄 

@sarah-pixvana, all you should need to do is remove `aws-cognito-sdk` from `module.noParse`, and all the `AWS_SDK_MAIN` stuff too. Worked for me, at least.

**Comment by hassankhan** [comment]
I've just updated to Webpack 2 with no problems and everything seems to work fine. I do think that there should be a single file in `dist/` with all dependencies rolled in (i.e. no `require()` statements, ES5/UMD I think?).

A possibly even simpler fix might be to simply not minify the source, and output it to `lib/` or something and point `main` in `package.json` to the `index.js` in there.

I think the reason people are tripping up on this is most Webpack configurations have `noParse: /\.min\.js$/`, at least for production. I think it does make sense, removing it from the configuration DOES feel like a workaround, and it shouldn't be too difficult to implement (happy to do a PR).

**Comment by hassankhan** [comment]
Scratch that, I was looking at the wrong tab, it is not working for me after upgrading to Webpack 2.

Sorry for the noise 😞

**Comment by sarah-pixvana** [comment]
I have created a new web application that is using a new cognito user pool, and am now running into the same issue even locked into version 1.2.0. @itrestian I saw you marked this as a bug, please let me know when your team comes up with a solution. Thanks!

**Comment by itrestian** [comment]
Yes, looking into it.

**Comment by Strainy** [comment]
Same issue, any work-arounds exist for this at present?

**Comment by cloudinertia-system** [comment]
I will step through a high level overview of the primary webpack configuration options that I managed to get working. My implementation utilizes the npm package, webpack v1.14.0. I tested various similar configurations by trial and error to include the aws-sdk node_module dist client files, script generated from the SDK builder added to my local file system, and script from the CDN. I managed to only get the implementation of the script from the CDN working with the webpack configuration.
In addition, I am utilizing AngularJS 1.6, I hope this webpack configuration assists with other use cases.
I included the aws-sdk for javascript in the browser, script tag, in the head of my index.html.
In the webpack.config.js file, on the configuration object property "plugins", awsPlugin of the prep object, I used the "ProvidePlugin" to make the global "AWS" object available by correlating a named reference as the value 'aws', that value is further exposed as the key on the "externals" property, this named reference is utilized as the file name in require and import statements to point the the script tag; explained in more detail below.
In the webpack.config.js file, on the configuration object property "externals", I referenced the global 'AWS' object as the value to the externals property's key as 'aws', to import AWS from 'aws'; explained in more detail below.
The "externals" property is used to make global variables available as a module in this case 'AWS', the "plugins" property, awsPlugin of the prep object, new "ProvidePlugin" is used to make modules available as variables inside modules.
!Note: the contra-mapping of the prep object "awsPlugin" property's key value pair compared to the config object "externals" property's key value pair.

#### Index.html
````
<!DOCTYPE html>
<html ng-app="root" ng-strict-di>
	<head>
		<meta charset="utf-8">
		<title>Console</title>
		<base href="/">
		<link rel="icon" type="image/x-icon" href="images/favicon.ico">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500" rel="stylesheet">
		<link rel="stylesheet" href="css/styles.css">

		<script src="https://sdk.amazonaws.com/js/aws-sdk-2.9.0.min.js"></script>
	</head>
	<body>
		<root>
			<span class="loader">Loading...</span>
		</root>
		<script src="js/app.bundle.js"></script>
	</body>
</html>
````

#### Webpack.config.js
````
'use strict';
let webpack = require('webpack');
let cleanPlugin = require('clean-webpack-plugin');
let copyPlugin = require('copy-webpack-plugin');
let extractPlugin = require('extract-text-webpack-plugin');

const root = `${__dirname}/framework`;
const dist = `${__dirname}/dist`;
const paths = {
	app: `${root}/app/root.module.js`,
	styles: `${root}/styles`,
	static: {
		index: `${root}/index.html`,
		images: `${root}/images/**/*`,
	},
};

/* Plugins */
const prep = {
	clean: new cleanPlugin([
		dist,
	]),
	copy: new copyPlugin([{
		from: paths.static.index,
	}, {
		from: paths.static.images,
		to: 'images/',
		flatten: true,
	}]),
	jquery: new webpack.ProvidePlugin({
		$: "jquery",
		jQuery: "jquery",
		"window.jQuery": "jquery"
	}),
	aws: new webpack.ProvidePlugin({
		AWS: 'aws',
	}),
};

const extract = {
	styles: new extractPlugin('css/styles.css'),
};

/* Loaders */
const scriptsloaders = {
	test: /\.js$/,
	exclude: [
		/node_modules/,
	],
	loaders: [
	'ng-annotate-loader',
	'babel-loader',
	],
};

const stylesloaders = {
	test: /\.scss$/,
	exclude: /node_modules/,
	loader: extractPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?sourceMap'),
};

const markuploaders = {
	test: /\.html$/,
	exclude: /node_modules/,
	loader: 'ngtemplate-loader!html-loader',
};

const fontsloaders = {
	test: /\.(eot|svg|ttf|woff|woff2)$/,
	exclude: /node_modules/,
	loader: 'file-loader?name=fonts/[path][name].[ext]',
};

const jsonloaders = {
	test: /\.json$/,
	loader: 'json',
};

/* Config object */
const config = {
	entry: {
		bundle: paths.app,
	},
	devtool: 'source-map',
	module: {
		loaders: [
			scriptsloaders,
			stylesloaders,
			markuploaders,
			fontsloaders,
			jsonloaders,
		],
	},
	plugins: [
		prep.clean,
		prep.copy,
		prep.jquery,
		prep.aws,
		extract.styles,
	],
	sassLoader: {
		includePaths: [paths.styles],
	},
	output: {
		path: `${dist}/`,
		publicPath: '/',
		filename: 'js/app.[name].js',
	},
	externals: {
		aws: 'AWS',
	},
	devServer: {
		port: 8080,
		historyApiFallback:true,
	},
	resolve: {
		extensions: ['', '.js', '.es6', '.json'],
	},
};

module.exports = config;
```

#### Root.module.js, example of import statement
```
import jquery from 'jquery';
import angular from 'angular';
import ngAria from 'angular-aria';
import ngAnimate from 'angular-animate';
import ngMessages from 'angular-messages';
import ngSanitize from 'angular-sanitize';
import ngMaterial from 'angular-material';
import uiRouter from 'angular-ui-router';
import AWS from 'aws';

import { rootComponent } from './root.component';
import { common } from './common/common.module';
import { components } from './components/components.module';
import './root.scss';

export const root = angular
	.module('root', [
		ngAria,
		ngAnimate,
		ngMessages,
		ngMaterial,
		uiRouter,
		common,
		components,
	])
	.component('root', rootComponent)
	.config(($locationProvider, $urlRouterProvider) => {
		'ngInject';

		$locationProvider.html5Mode(true).hashPrefix('!');
	})
	.name;

```

**Comment by itrestian** [comment]
This was probably related to Webpack support in the main aws sdk at that point.

https://github.com/aws/aws-sdk-js/issues/1341
