### ISSUE TITLE
how to ListUsers from User Pool ?

### ISSUE THREAD

**Issue by vinodhum** [aws/amazon-cognito-identity-js#157]
How to list all the users from specific user pool ?

**Comment by itrestian** [comment]
You won't be able to do that using this SDK. You can however use the AWS SDK that exposes the listUsers operation in the cognitoidentityserviceprovider client. That is an authenticated operation and you will need AWS credentials to call it.

**Comment by vinodhum** [comment]
and how do I do that from AWS SDK ? this is what I tried 

```
let users = AWS.cognitoidentityserviceprovider.ListUsers({
            "AttributesToGet": [],
            "Filter": "",
            "Limit": 10,
            "UserPoolId": CognitoUtil._USER_POOL_ID
        });
        console.log(users);
```

but its not working

**Comment by vinodhum** [comment]
got it. this helped [http://stackoverflow.com/questions/39609500/aws-javascript-api-example-to-list-all-user-pools-associated-with-an-account/39649866#39649866]
thanx
