### ISSUE TITLE
Problem with angular-cli webpack

### ISSUE THREAD

**Issue by objecteer** [aws/amazon-cognito-identity-js#158]
I'm currently working on an angular 2 project, and would like to migrate my project to angular-cli webpack. I loaded all amazon-cognito-identity-js script files via apps.scripts in angular-cli.json as follows:
    "scripts": [
      "../node_modules/jsbn/index.js",
      "../node_modules/sjcl/sjcl.js",
      "../node_modules/amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js",
      "../node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js",
      "../node_modules/aws-sdk/dist/aws-sdk.min.js"
    ],
and declares AWS and AmazonCognitoIdentity in the cognito service module as follows:
    declare let AWS:any;
    declare let AmazonCognitoIdentity:any;

This approach seem to be working, for example I can get current cognitoUser and get user name from calling cognitoUser.getUsername. However, when I made a call that is required to communicate with AWS cloud (such as, cognitoUser.getSession), I always got an this error:
    TypeError: Cannot read property 'utf8String' of undefined

**Comment by itrestian** [comment]
This is most probably a missing sjcl method. Can you try using the build on github for sjcl as that one has all the required functions?

**Comment by objecteer** [comment]
I have downloaded the lastest sjcl.js from github, and got the same error as issue #160.

**Comment by objecteer** [comment]
I tried the approach from issue #160 and the problem was solved.
