### ISSUE TITLE
cognitoUser.authenticate causing the form to be submitted twice

### ISSUE THREAD

**Issue by Alphatiger** [aws/amazon-cognito-identity-js#16]
cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('access token + ' + result.getAccessToken().getJwtToken());
        },

```
    onFailure: function(err) {
        alert(err);
    },

});
```

The above is causing the form to be submitted twice, Environment IONIC
any guess?

**Comment by itrestian** [comment]
Not sure why that would happen. The authenticateUser call does make 2 service calls, can it be related to that?

Ionut.

**Comment by Alphatiger** [comment]
No ideas but the ionic controller is executing it twice, surprisingly if i am keeping it in the app.js it is running only once,  got stuck :(

**Comment by itrestian** [comment]
Seems to be an environment problem and not an SDK problem, if you think there's something wrong with the SDK implementation, let us know!

Ionut.
