### ISSUE TITLE
cognitoUser.authenticateUser error Cannot read property 'hex' of undefined

### ISSUE THREAD

**Issue by neojack647** [aws/amazon-cognito-identity-js#160]
I am unable to get authenticateUser to work ever since I have upgraded angular-cli  to webpack  and angular2 final. 
Currently using aws-sdk 2.6.4 and sjcl 1.06 
angular-cli
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../public/jsbn.js",
        "../public/jsbn2.js",
        "../node_modules/sjcl/sjcl.js",  
        "../public/aws-cognito-sdk.min.js",
        "../public/amazon-cognito-identity.min.js",
        "../node_modules/aws-sdk/dist/aws-sdk.js",  
        "../node_modules/bootstrap/dist/js/bootstrap.js" 
      ],
any ideas?

**Comment by itrestian** [comment]
Most probably you are missing some sjcl functions. Can you pull sjcl from github, that should have all the necessary codecs.

**Comment by neojack647** [comment]
I tried the master from https://github.com/bitwiseshiftleft/sjcl and I received the same error. 
I also ensured codec,bytes is included.

**Comment by neojack647** [comment]
This is an issue with angular-cli and how it is loading scripts for webpack in the angular-cl.json file. SJCL is null in the amazon-cognito-identity.min.js file. 
I pulled down the amazon-cognito-identity-js project. Rebuilding amazon-cognito-identity.min.js so that SJCL is set to false for excluding 3rd party in the webpack.config.js file fixes this. Obviously forcing a 3rd party to included in the build is less than desirable but it does fix it for now.

**Comment by Zingoer** [comment]
Got the same error

**Comment by Zingoer** [comment]
I'm new to the webpack and still can't figure our the way to import the cognito sdk into my project. So I use the old script way to import the following files
```html
<script src="https://cdn.rawgit.com/aws/amazon-cognito-identity-js/master/dist/aws-cognito-sdk.min.js"></script>
    <script src="https://cdn.rawgit.com/aws/amazon-cognito-identity-js/master/dist/amazon-cognito-identity.min.js"></script>
    <script src="http://www-cs-students.stanford.edu/~tjw/jsbn/jsbn.js"></script>
    <script src="http://www-cs-students.stanford.edu/~tjw/jsbn/jsbn2.js"></script>
    <script src="https://cdn.rawgit.com/bitwiseshiftleft/sjcl/master/sjcl.js"></script>
```
Then when I try the authenticate:
```javascript
var poolData = {
			UserPoolId: '...',
			ClientId:'...'
		};

		var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);


		var authenticationData = {
			Username: 'username',
			Password: 'password'
		};

		var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);

		var userData = {
			Username: 'username',
			Pool: userPool
		};

		var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
		cognitoUser.authenticateUser(authenticationDetails, {
			onSuccess: function(result){
				console.log('access token + ' + result.getAccessToken().getJwtToken());
			},
			onFailure: function(err){
				alert(err);
			},
		});
	}
```

I got the same error 

> Cannot read property 'hex' of undefined
    at e.value (https://cdn.rawgit.com/aws/amazon-cognito-identity-js/master/dist/amazon-cognito-identity.min.js:19:5167)
    at new e (https://cdn.rawgit.com/aws/amazon-cognito-identity-js/master/dist/amazon-cognito-identity.min.js:19:2794)
    at e.value (https://cdn.rawgit.com/aws/amazon-cognito-identity-js/master/dist/amazon-cognito-identity.min.js:19:10569)
    at AppServices.login (eval at 121 (http://localhost:3001/app.bundle.js:142:2), <anonymous>:52:16)
    at new LandingController (eval at 124 (http://localhost:3001/app.bundle.js:163:2), <anonymous>:23:15)

**Comment by bedorlan** [comment]
Hello @neojack647 
Please elaborate a little more in your solution. Its not clear to me how to fix this.
Thank you

**Comment by neojack647** [comment]
In the webpack.config.js  of the amazon-cognito-identity-js project I set SJCL = false 
Then rebuilt the project
setting it to false forces the thirdparty file to be included in the build. 
Not sure if that answers your question.

**Comment by fabian-dev** [comment]
Hey @neojack647, great hack! That works for me as well. Can you file an issue at angular-cli for that? Unfortunately I'm still not getting in depth what is getting wrong, but I would highly appreciate to not rely on my homebrew amazon-cognito-identity-js.js forever. Thanks in advance.

**Comment by magnattic** [comment]
This got closed, but what's the solution for angular-cli? Using a homebrew js is a workaround at best.

**Comment by ZhiliangGong** [comment]
I moved these javascript files to the index.html file, and things worked:

<script src="assets/js/jsbn.js"></script>
<script src="assets/js/jsbn2.js"></script>
<script src="assets/js/sjcl.js"></script>
<script src="assets/js/aws-cognito-sdk.min.js"></script>
<script src="assets/js/amazon-cognito-identity.min.js"></script>
<script src="assets/js/aws-sdk-2.7.13.min.js"></script>
<script src="assets/js/aws-sdk-mobile-analytics.min.js"></script>

**Comment by ZhiliangGong** [comment]
I moved the javascript library files to index.html, and things worked:

`<script src="assets/js/jsbn.js"></script>
<script src="assets/js/jsbn2.js"></script>
<script src="assets/js/sjcl.js"></script>
<script src="assets/js/aws-cognito-sdk.min.js"></script>
<script src="assets/js/amazon-cognito-identity.min.js"></script>
<script src="assets/js/aws-sdk-2.7.13.min.js"></script>
<script src="assets/js/aws-sdk-mobile-analytics.min.js"></script>`

**Comment by Leon-Africa** [comment]
Adding these does not resolve the issue on my side, really strange as I have a working project that using the same code yet does not encounter this issue.

The only difference is that the one is using verification on signup. But once a user is verified and sign in call made I don't see how this can be an issue.

It fails at:

cognitoUser.authenticateUser(authenticationDetails, {

**Comment by Leon-Africa** [comment]
I went ahead an cloned the entire repo - reference js files, now I get something completely different, see image:
![screen shot 2017-08-15 at 11 52 14 am](https://user-images.githubusercontent.com/16097992/29310978-38ce0dda-81b0-11e7-819c-59d808e9b974.png)

This is strange because I only want MFA on signup, not sign in... MFA on signup works.

But this error is being thrown for sign in

UPDATE: This is solved by disabling MFA - which only works for SMS
