### ISSUE TITLE
Pre-sign up lambda autoConfirmUser

### ISSUE THREAD

**Issue by sarah-pixvana** [aws/amazon-cognito-identity-js#161]
I am using the pre-sign up lambda trigger feature. Cognito is triggering my lambda fine, but I noticed something that seemed strange.

When editing what the response that is returned to cognito, I noticed that cognito is automatically confirming the user whether I set response.autoConfirmUser to "true" or "false". However, when i take my line of code that references the response out completely, it is not confirming the user. 

doesn't work properly. It is still auto-confirming the user even though I am setting that value to false: 

```
public void authorize(final Json request) {
        final Json userName = request.get("userName");
        log.debug("email captured:", "userName", userName);

        final Json response = request.get("response");

        if (userName.toString().contains("approved email address") {
            log.debug("email approved");
            response.set("autoConfirmUser",false");
            return;
        } else {
            throw new ForbiddenException("Email address not approved");
        }

    }
```

works fine:

```
public void authorize(final Json request) {
        final Json userName = request.get("userName");
        log.debug("email captured:", "userName", userName);

        if (userName.toString().contains("approved email address") {
            log.debug("email approved");
            return;
        } else {
            throw new ForbiddenException("Email address not approved");
        }

    }
```

**Comment by chetanme** [comment]
This is unexpected. Users should only be confirmed if the autoConfirmed flag is set to true. Can you paste the full code for your pre sign up lambda trigger?

Best way to debug what event is being sent to and from a lambda trigger is to log the event and then looking at the CloudWatch logs for your trigger. It will give you the exact JSON coming in and going out of your lambda trigger. If autoConfirmed flag is set to true in the outgoing event, service will confirm the users by default. Can you verify this in CloudWatch as well?

**Comment by sarah-pixvana** [comment]
@chetanme yes I've been watching the cloudwatch logs for the lambda and can verify. I noticed, that even if the response was logging "autoConfirmUser": "false" in cloudwatch, the confirmation email would not go out and the user would be set to Confirmed in user pools, which was unexpected. But then when I completely removed the line of code in my lambda to do with the response, the confirmation email would send and the user would be listed as Unconfirmed. 

below is my lambda code that caused the unexpected result:

```

public abstract class EventApplication {

    public abstract void wire(final Stack stack, final Context context);

    public abstract Json run(final Json request, final Context context);
}

public class AccountMasterApplication extends EventApplication {

    private static final PixLogger log = new PixLogger();

    @Override
    public void wire(final Stack stack, final Context context) {
        log.debug("write called", "stack", stack);

    }

    public void authorize(final Json request) {
        final Json userName = request.get("userName");
        log.debug("email captured:", "userName", userName);

        if (userName.toString().contains("@<approved email address>")) {
            log.debug("email captured approved");
            return;
        } else {
            throw new PixForbiddenException("Email address not approved");
        }

    }

    @Override
    public Json run(final Json request, final Context context) {
        log.debug("run()", "request", request);
        authorize(request);
        return request;
    }
}
```

**Comment by kushwahavinay** [comment]
Seems like this thread lost attention. 
I tried reproducing it but did not see the unexpected result. Are you still facing this problem?

**Comment by sarah-pixvana** [comment]
Thanks for checking in. No longer experiencing this problem. I believe that our build process was deploying the custom lambda new each time without cognito getting access- however an update that you made awhile back must have fixed the problem. If we see it again in the future will be sure to let you know.

**Comment by robertbrower-technologies** [comment]
I am experiencing the same problem. I set event.response.autoConfirmUser = false. The response.autoConfirmUser  in the logged event is false. My user still get registered. I tried what sarah-pixvana suggested, ie, just not set event.response.autoConfirmUser in case of preconfirmation failure, but that doesn't work. If you set response.failAuthentication to true, you can prevent the user registration process from continueing, but the user gets a no so user friendly error in the Register UI, ie, Unexpected Lambda Output or something along those lines. I need a real solution. Thank you.
