### ISSUE TITLE
Getting errors with use case 17 

### ISSUE THREAD

**Issue by nueverest** [aws/amazon-cognito-identity-js#162]
I get this console output when I run the code below:

![image](https://cloud.githubusercontent.com/assets/2917370/18894314/11cb3c1c-84c7-11e6-851b-9b438de2a1a5.png)

POST https://cognito-identity... 400 (Bad Request)
Error: Invalid login token. Issuer doesn't match providerName(...)

How do I make these errors go away?

How do I `console.log()` the refresh token string?

``` javascript
AWS.config.region = 'XX-XXXX-X';
AWSCognito.config.region = 'XX-XXXX-X';
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
var cognitoUser = userPool.getCurrentUser();
var loginKey = 'cognito-idp.' + region + '.amazonaws.com/' + poolData.UserPoolId

// Integrate User Pools with Cognito Identity and handle token refresh.
if (cognitoUser != null) {
    cognitoUser.getSession(function (err, result) {
        if (err) {
            console.error(err);
        }
        if (result) {
            console.log('You are now logged in.');

            // Add the User's Id Token to the Cognito credentials login map.
            AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                IdentityPoolId: identityPoolId,
                Logins: {
                    loginKey: result.getIdToken().getJwtToken()
                }
            });
        }
    });
}

// Not sure why this doesn't work it is copy/pasted from AWS use case 17
//call refresh method in order to authenticate user and get new temp credentials
AWS.config.credentials.refresh(function (error) {
    if (error) {
        console.error(error);
    } else {
        console.log('Successfully logged!');
    }
});
```

As a side note, use case 17 seems to mix in ES6 function formatting and includes an extra tab on the last line.  The full word `error` is used as opposed to `err`. 

What does `console.log('Successfully logged!');` mean?  Does that mean successfully logged in, or is some sort of aws server logging operation taking place?

**Comment by chetanme** [comment]
`Issuer doesn't match providerName` indicates that the loginKey being constructed does not match the value that token has. Can you print and confirm that loginKey you are sending in the Logins map is of format `cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>`?

<region> value should be one of us-east-1, eu-west-1, us-west-2 or ap-northeast-1.

As for printing the refresh token, like ID token, we have a get method. [getRefreshToken](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUserSession.js#L46) which also returns a JWT token.

**Comment by nueverest** [comment]
When I run the following:

``` javascript
idToken.textContent = result.getIdToken().getJwtToken();
accessToken.textContent = result.getAccessToken().getJwtToken();
refreshToken.textContent = result.getRefreshToken().getJwtToken();
```

The id and access token requests succeed, but the getRefreshToken() fails.

`Uncaught TypeError: result.getRefreshToken(...).getJwtToken is not a function`

**Comment by nueverest** [comment]
I just solved the refresh token issue with this: `refreshToken.textContent = result.getRefreshToken().token;`

**Comment by nueverest** [comment]
My `loginKey` looks like this: `cognito-idp.us-west-2.amazonaws.com/us-west-2_XXXXXXX`

Also, it is this part of the code that throws an error.

``` javascript
AWS.config.credentials.refresh(function (error) {
    if (error) {
        console.error(error);
    } else {
        console.log('Successfully logged!');
    }
});
```

**Comment by chetanme** [comment]
Can you post a service request id for one of these failed requests with the time stamp?

**Comment by nueverest** [comment]
Date:Wed, 28 Sep 2016 13:26:43 GMT
x-amzn-ErrorMessage: Invalid login token. Issuer doesn't match providerName
x-amzn-ErrorType: NotAuthorizedException:
x-amzn-RequestId: 32b963a7-857f-11e6-94cf-7372c5356b7d

**Comment by nickGermi** [comment]
You can't use:

```
                Logins: {
                    loginKey: result.getIdToken().getJwtToken()
                }
```

Above 'loginKey' will be interpreted literally and not by it's value. Instead create an empty object, assign the value of loginKey as it's key with its value being result.getIdToken().getJwtToken()

For example:

```
var loginProvider = {};
loginProvider[loginKey] = result.getIdToken().getJwtToken();
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: identityPoolId,
    Logins: loginProvider
});
```

**Comment by bradennapier** [comment]
You could also potentially use ES6 if you are setup for it:

```js
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
   ...identity,
   Logins: {
     [`cognito-idp.${AWS_REGION}.amazonaws.com/${POOL_ID}`]: session.getIdToken().getJwtToken()
   }
})
```

**Comment by tbiinfotech** [comment]
How can I get identityPoolId ?

**Comment by dotchev** [comment]
@tbiinfotech, you should create an Identity Pool, see http://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html
