### ISSUE TITLE
Clearer instructions on how to use with API Gateway

### ISSUE THREAD

**Issue by hassankhan** [aws/amazon-cognito-identity-js#165]
Hi all,

Thanks for all your amazing work on the repo, makes working with Cognito painless 😄. I've been trying (and failing) to get a Cognito User Pool Authorizer working with API Gateway for the past few days. 

I'm trying to integrate User Pools and APIG in a React/Redux app (hopefully will be able to open-source an example soon!), and I'm trying to keep minimal on the AWS dependencies. I'm using this library for auth, and `fetch` to make HTTP requests.

I've run through the oft-linked [blog post](https://mobile.awsblog.com/post/Tx3JK25U7Z9EUIU/Integrating-Amazon-Cognito-User-Pools-with-API-Gateway), but that makes no mention of how you should be setting up your User Pool App Client (don't use a client secret!) or on how a request should be made to APIG once the authorizer is enabled.

From what I see, it says that passing an unexpired ID token in the headers like `Authorization: Bearer <token>` should work, but I keep getting 401 Unauthorized responses. I also tried making requests using Postman, with the same results. I've tested my ID token in the APIG console, and I get no problems there.

I'm sorry if I've rambled a bit, just not quite sure what I'm doing wrong. Thanks in advance for any help 👍

**Comment by hassankhan** [comment]
Just to update, I've spoken to AWS Support and it now seems to be working. For future reference, all you need to do is pass the header like: `Authorization: <token>` and it should work perfectly.

**Comment by dmongit** [comment]
@hassankhan Can you be more specific on which token? I run AWS.config.credentials.refresh and then I do a fetch on (where userToken is AWS.config.credentials.sessionToken:
`new Request(`${global.API_URL}/myGetAPI?since=${since}`, {
        headers: new Headers({
          'Authorization': userToken
        })
      })`

I get Error: Unauthorized

Update: Never mind... I see now that it's the JWT token from AWS.

**Comment by infinitetrooper** [comment]
@dmongit How did you manage to get the JWT token, I'm using the following code `credentialsProvider.getIdentityId().continueWith` with `task.result` but, it's still showing Unauthorized.

I'm using the user pool authorisation, it needs the Identity token as the Authorisation header.

ThankYou
