### ISSUE TITLE
checking if an identity already exists

### ISSUE THREAD

**Issue by rares-lupascu** [aws/amazon-cognito-identity-js#166]
Hey

I see that the description for GetId says: Generates (or retrieves) a Cognito ID

My use case needs to not allow people to login if they are not already setup so i do not need to identities to be created on the fly

So my question is ... upon login/signin ... how do i check if an identity already exists for the provided credentials?

thanks

**Comment by jbailey2010** [comment]
Can you clarify a bit on what information you'll have on login/what you mean by 'for the provided credentials'? 

If it's the login token from a provider, Cognito doesn't handle that use case for you. If a token is already linked to an identity, it will give you that identity, giving you a new one if not. No API exists to lookup based on a token. If that's what you're looking for, you may have to keep an additional mapping of your own to know what does or doesn't exist.

**Comment by hassankhan** [comment]
I think @wowzaaa is referring to the 'unauth' feature from Cognito Identity Pools, this library only deals with User Pools if I'm not mistaken?

**Comment by rares-lupascu** [comment]
well there is a difference between signup and signin
from what i understand GetId creates the identity if it does not exist ... what i need is to not create a new identity if it does not already exists

**Comment by jbailey2010** [comment]
To be clear, hassankhan is correct. GetId is a Cognito federated identities API (identity pools), which is what my answer was directed towards. Are you asking about that, or user pools?

**Comment by rares-lupascu** [comment]
my mistake sry :(

yes i am asking about Cognito federated identities API
user pools are still in beta and i would not risk using it in production :)

**Comment by jbailey2010** [comment]
Ah, so then my original answer would apply. Federated identities doesn't have an API to check if an identity id exists or not, you would need to track a mapping of ids to be able to do this. 

For the record, though, user pools is no longer in beta as a service, it went GA in mid July. This use case would be much easier managed in using that.

**Comment by jbailey2010** [comment]
I made an assumption that may not be true - if you're using developer authenticated identities, you could use the LookupDeveloperIdentity API to do this.

**Comment by rares-lupascu** [comment]
yeah with developer authenticated identities you would have a mapping of ids :)
but i plan to support social logins so ... if someone tried to login with FB without being already signed up before ... i would need it to not create a new id for that ... rather give me an error message that the user does not exist or something :) ..

and yes ... user pools would be the better option :D .. thanks .. did not knew it was no longer in beta

**Comment by jbailey2010** [comment]
To support social logins, you would need to use both. User pools doesn't natively support social logins at this time.  To do that, you would still have to have the mapping yourself. 

I'm not sure I understand your use case, though. What do you mean by 'if they are not already set up'? If you aren't using user pools and are aiming for social identities, there isn't really a user profile to set up on the Cognito side.
