### ISSUE TITLE
Consider using the Web Cryptography API and selectively polyfilling

### ISSUE THREAD

**Issue by binoculars** [aws/amazon-cognito-identity-js#168]
Most browsers have all of the cryptography functions built-in with the [Web Cryptography API](http://caniuse.com/#feat=cryptography). No need to load a separate library, unless required for a polyfill.

**Comment by itrestian** [comment]
Thank you for the suggestion. I will mention it within the team such that we add it to our roadmap.

**Comment by itrestian** [comment]
Closing. We removed the SJCL and started using similar functions from the main AWS SDK.

**Comment by binoculars** [comment]
👍  I have working implementation here: https://github.com/binoculars/aws-sigv4/tree/feature/node-4/src

I plan on cleaning it up into a release as time permits.
