### ISSUE TITLE
A new user is confused

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#17]
I'm new to AWS and specifically cognito. I eventually discovered the JS SDK, though it is rather hidden in your copious docs. It's not really well signposted form other places like mobile.

I stumbled across [pools pages](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) in the copious docs and they are just what I need. But then got stuck on [the page ](http://docs.aws.amazon.com/cognito/latest/developerguide/setting-up-the-javascript-sdk.html) that says download the SDK but provides no details. None of the functions are in the JS SDK. 
- Is this where we should download from? It seems to be. IS this kept more up to date than the docs?
- 'Create an app for your user pool' - how? what? where?
- I'm more than a little concerned about the size of all this for my mobile app. I removed moment from my code as it was > 200K for a [couple of lines of code](https://github.com/OpenDirective/brian/blob/master/src/js/drivers/activityLog.js#L18-L24). With all the other stuff this is getting pretty big. 
- The docs say it is beta and here it is a 'preview'

**Comment by SteveALee** [comment]
A better link for the sjcl appears to be the minimized link here. Other wise you have to download and build it.

https://bitwiseshiftleft.github.io/sjcl/

**Comment by itrestian** [comment]
Hi Steve,
- We are in the process of updating the documentation but you can find more information here or on the Cognito forums at the moment. 
- This happens in the Cognito console. Please find more info on the blog post below: http://mobile.awsblog.com/post/TxGNH1AUKDRZDH/Announcing-Your-User-Pools-in-Amazon-Cognito
- That's a good update, thanks! Also, the SDK is in developer preview, certain things might change between now and GA, however we will try to keep the experience the same.

Also for the sjcl you linked, I don't think that contains the bytes codec, mentioned in the README.md

https://github.com/aws/amazon-cognito-identity-js/blob/master/README.md

Ionut.

**Comment by SteveALee** [comment]
Thanks for quick response :)

> This happens in the Cognito console. Please find more info on the blog post below: 

I figured what you meant as I created the pool :)

Right now I'm trying to get the scripts to load and run properly in webpak environment - this modenrr tooling is too complex :( For some reason jsbn2 never sees the BigInteger even though I see the code being run. Probably closure related, sigh. Once I get past that I'll see how sjcl works

Thanks again

**Comment by SteveALee** [comment]
So the readme says 'Optionally, download and include the AWS JavaScript SDK in order to use other AWS services. The SDK is necessary in order to use AWS.CognitoIdentityCredentials:'

But 'Use case 1' uses `AWS.config.credentials = new AWS.CognitoIdentityCredentials`

So how _optional_ is it?

**Comment by SteveALee** [comment]
Another problem is having copied the Use case 1 and fighting some very strange problems I now get a 400 from the `POST  https://cognito-identity.us-east-1.amazonaws.com`.

Checking the code again I see I need an `IdentityPoolID` whatever that might be. All I can find is on SE it looks somehting like `us-east-1:bb42af4a-9ec4-41fe-8211-65c60d2dcef6` but I am unable to find that anywhere in the pools UI. How do I get one?

**Comment by SteveALee** [comment]
Well I finally fiquire I need to use the Fedorated option AS WELL as the user pool. They appeared to be mutually exclusive. Having set that all up I tried the PoolID in the sample code

```
us-east-1:9127624e-b818-45ed-99da-b1a2016dd8a3
```

But I'm still getting the 400 and missing credentials. Here is my complete code

```
function addUser () {
  AWS.config.region = 'us-east-1' // Region
  AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:9127624e-b818-45ed-99da-b1a2016dd8a3' // your identity pool id here
  })

  AWSCognito.config.region = 'us-east-1'
  AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:9127624e-b818-45ed-99da-b1a2016dd8a3' // your identity pool id here
  })
/* eslint-enable immutable/no-mutation */

  const poolData = {
    UserPoolId: 'us-east-1_4suI6ClSV',
    ClientId: '3mn5hcp6edn2li2hgksl44nst2'
  }
  const userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData)

  const dataName = {
    Name: 'given_name',
    Value: 'Fred'
  }
  const attributeName = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataName)

  const attributeList = [attributeName]

  userPool.signUp('username', 'password', attributeList, null, (err, result) => {
    if (err) {
      alert(err)
      return
    }
    const cognitoUser = result.user
    console.log('user name is ' + cognitoUser.getUsername())
  })
}

export default addUser
```

**Comment by SteveALee** [comment]
![awscognitoerror](https://cloud.githubusercontent.com/assets/618922/14999211/b1f2f204-117f-11e6-8fe5-404f69e34a68.png)

**Comment by mattgleeson** [comment]
I had the "Missing credentials" problem. It went away when I allowed "unauthenticated access" in my identity pool.

**Comment by itrestian** [comment]
Hi guys,

For authenticateUser don't think credentials are needed in the first place since these calls are marked as such. You might have to set some values for the credentials but that is just an artifact of the AWS SDK that does a check and throws an error if no credentials are present.

For example: AWSCognito.config.update({accessKeyId: 'ionutkey', secretAccessKey: 'ionutsecret'});

Let me know if it works.

After this, you can do something similar to this to get AWS credentials to work with other services.

https://github.com/aws/amazon-cognito-identity-js/issues/12

Ionut.

**Comment by SteveALee** [comment]
It would help if the error message could indicate if the problem is client or server side.

**Comment by SteveALee** [comment]
@mattgleeson when I finally figured i needed to set up 'federated access' for an unfederated user pool (huh?) the final step was to to create access for unauthed users, though I think i did not select them in an earlier step.

Now I can;t figure how to edit the pool :(

**Comment by SteveALee** [comment]
oh there's 'edit', way over on the right, well away form the main navigation :(

@mattgleeson yes that works! thanks. I spent hours on this too. :)

It's a mute point if non existing users are unauthorised though! I don't actually want anauthorised access, but it's a nice feature an I might later take advantage of it.

**Comment by SteveALee** [comment]
@itrestian I added your example line verbatim and it works if placed AFTER the call to `AWSCognito.config.credentials`. At least I get user already exists as I created them when unauthed accesss was enabled. 

Interestngly, I deleted the identiy but not the user in the Conginto control panel so am a little confused why it works.

**Comment by SteveALee** [comment]
So in summary both solutions work. For now I use the dummy client credentials option untill I want unauthed access.

**Comment by SteveALee** [comment]
@itrestian 

> certain things might change between now and GA, however we will try to keep the experience the same.

When is GA? We plan to use this in some user trials (300 odd users) for a EU project so it would be great if there were few breaking changes :)

I don;t fancy the alterntive option of managing the user authentication myself. Am very pleased this option exists. I plan to add the federated access later.
