### ISSUE TITLE
Use AWS-SDK as peerDependency

### ISSUE THREAD

**Issue by hassankhan** [aws/amazon-cognito-identity-js#171]
Apparently since v2.6.1, you can now use the actual AWS-SDK with Webpack properly. Should this library then require it to be a peer dependency?

**Comment by itrestian** [comment]
Thank you for the suggestion. I will mention this within so that we prioritize the change accordingly.

**Comment by tdsfugal** [comment]
Confused.  Does AWS-SDK need to be a dependency or not?

**Comment by itrestian** [comment]
Not necessarily. We also provide the option of including a slimmed down version of the AWS SDK in the dist folder. See aws-cognito-sdk.js and aws-cognito-sdk.min.js.

**Comment by fsenart** [comment]
@itrestian how to you generate `aws-cognito-sdk.[min].js`? I can't figure out which repo or script is used to integrate these files, update them, etc.

**Comment by itrestian** [comment]
We generate it from a minimal version of the main aws sdk https://github.com/aws/aws-sdk-js/blob/master/dist/aws-sdk.js by changing 

if (typeof window !== 'undefined') window.AWS = AWS;
if (typeof module !== 'undefined') module.exports = AWS;
if (typeof self !== 'undefined') self.AWS = AWS;

to

if (typeof window !== 'undefined') window.AWSCognito = AWS;
if (typeof module !== 'undefined') module.exports = AWS;
if (typeof self !== 'undefined') self.AWSCognito = AWS;

That version only contains the CognitoIdentityServiceProvider client.

**Comment by thopras** [comment]
I tried to use "**amazon-cognito-identity-js**": "**^1.16.0**"with "**aws-sdk**": "**2.42.0**",
but this doesn't seem to work. I found out that amazon-cognito-identity-js uses internally **aws-sdk v. 2.6.0** which confuses me because the current version of **aws-sdk is 2.45.0**. 

I need to use the following services: 
Cognito, API functions (lambda) and push notifications.<br>

Which version of what module should I use to get this running?

**Comment by itrestian** [comment]
The AWS SDK as a dependency has been removed.

Also, You can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo.

https://github.com/aws/aws-amplify
