### ISSUE TITLE
ERROR in Entry module not found:

### ISSUE THREAD

**Issue by yunusde** [aws/amazon-cognito-identity-js#178]
Hi,

I do exactly what says in 'Using NPM and Webpack' but when i try to build, i keep getting same error message no matter what.

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./src/entry in

could you please help me.

**Comment by itrestian** [comment]
That points to the entry module that requires or imports the rest of your project (just a placeholder) so it should be modified accordingly.
