### ISSUE TITLE
CognitoUser.authenticateUser don't work properly.

### ISSUE THREAD

**Issue by exabugs** [aws/amazon-cognito-identity-js#179]
I use iPhone5.

During CognitoUser.authenticateUser is calling, display has been completely locked.
(BigInteger calculating ?)

After waiting 60 seconds, an authentication error occurs.

In the same code and same account, there is no problem in the case of MacBookAir Chrome.

**Comment by exabugs** [comment]
In the case of the above, CognitoUserPool.signUp and CognitoUser.confirmRegistration is no problem.

**Comment by jbailey2010** [comment]
Can you provide a code snippet of how you're signing in? 60 seconds sounds pretty high.

**Comment by exabugs** [comment]
Snippet below.

```
var data = {
    UserPoolId: 'ap-northeast-1_xxxxxxxxx',
    ClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
};
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(data);

// Use case 4. Authenticating a user and establishing a user session with the Amazon Cognito Identity service.
$('#user_login_btn').click(function() {
    var username = $("#inputUsername").val();
    var password = $("#inputPassword").val();

    console.log(username + " : " + password);

    var authenticationData = {
        Username: username,
        Password: password
    };
    var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);

    var userData = {
        Username: username,
        Pool: userPool
    };
    var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

    cognitoUser.authenticateUser(authenticationDetails, {

        onSuccess: function(result) {

            console.log("Login success : " + username);

        },

        onFailure: function(err) {
            alert(err);
            message($('#message3'), err, "alert-danger");
        }

    });
});
```

**Comment by itrestian** [comment]
Is our iOS SDK an option for you? The performance of BigInteger Javascript libraries on older mobile devices is not that great. We require a BigInteger library for our SRP computations. See issue below:

https://github.com/aws/amazon-cognito-identity-js/issues/69

**Comment by exabugs** [comment]
I got a good idea!
How about this?
![2016-10-21 10 55 40](https://cloud.githubusercontent.com/assets/1234874/19584184/92a6c36a-977d-11e6-9cf3-e4168f66a470.png)

**Comment by itrestian** [comment]
Note that the username and password never travel between the device and Cognito User Pools. Clients only send password claims as part of the Secure Remote Password protocol. If your use case allows for the sending of the username and password over the wire, you can use the ADMIN_NO_SRP_AUTH flow as explained in the documentation: 

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html
