### ISSUE TITLE
ES6 or CommonJS modules as well please

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#18]
I realise a script tag is the simplest and thus lowest common denominator but I'm using a modern web set up using babel and ES6 modules so want to `import`

thanks

**Comment by itrestian** [comment]
Hi Steve,

Thanks for mentioning this. This is definitely something we will consider for GA. The reason is like you said, a script tag will work on more browsers.

Ionut.

**Comment by SteveALee** [comment]
I tried using the [webpack script-loader](https://github.com/webpack/script-loader) which lets you load with a require in the including page. But it just did not work, even after much experimentation. So I added Into my html and told ESLint about the global vars.

**Comment by itrestian** [comment]
We will take this as a feature request and try to include it in our roadmap.

Ionut.

**Comment by SteveALee** [comment]
I appreciate that and I'm sure others will to. For larger apps it's better to not have everything global, though you do create a namespace. I realise module formats are a bit of a mess right now, hopefully ES6 will win out though.
