### ISSUE TITLE
Sign in error for admin created accounts

### ISSUE THREAD

**Issue by artema** [aws/amazon-cognito-identity-js#180]
Sign in fails for users created using the adminCreateUser SDK method with the following error:
`Cannot read property 'NewDeviceMetadata' of undefined`

**Comment by chetanme** [comment]
Can you add some steps to reproduce this? Some code which you have written to use this SDK would also help us narrow down the issue.

**Comment by artema** [comment]
It fails on the authenticateUser for users that need to provide a new password for their account, the error is in the authenticateUserInternal method.

```
const authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails({
  Username: username,
  Password: password
});

const user = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser({
  Username: username,
  Pool: pool
});

user.authenticateUser(authenticationDetails, {
  onSuccess: resolve,
  onFailure: reject,
  newPasswordRequired: (userAttributes, requiredAttributes) => {
    user.completeNewPasswordChallenge(password, {}, this);
  }
});
```

Here's what I receive from the Cognito service when that happens:

```
{"ChallengeName":"NEW_PASSWORD_REQUIRED","ChallengeParameters":{"requiredAttributes":"[\"userAttributes.preferred_username\"]","userAttributes":"{\"email_verified\":\"true\",\"preferred_username\":\"\",\"email\":\"mail@example.com\"}"},"Session":"TqP-ufqXl1e2yTFnDC4KOsRCjxv8CGYCKTnCMXBZFt0pNVLufoGtk9WP3iidPpWWB9n-vg_T1qeiClFjdqsI4d1GjH7qigsjc8iotRHKUuKfkS2ZHlckZS8MJqbZWBrusRbHYjDRzr7hEolgE2WNnkVxlvwjuZOv2RbLXfXrLcX1f3Lojs9dGbsm49AhPVscZ_aHKyHcYSQsDmiFWXcQRnBlbpaPQ5E0ZEDrw4faD37gznQk2VewVo0Clpbt7F0bzx1YPCaorHXCOzrQXWyD6gqwg_nH9Is8B9gTu1sHCy20FwPJAzOTx7uzz9FZSj3U4g8aifHKrHV_y-YKIshjx_ksGpmqtrHbKM9utKrX2W20EASLLHRpm-i8Ujtfauc7E2yPayFZVfAVrNtGARakdIc9UbP7cixqNGRy1OaIN-GDwUsR64Np9u57dw_AVYD9-yo4nrSDtBCgA3a3xNVLSha4MJYl-DV9RHRfaWKww4h-5cQz1fb4J5lYMrh6B_iq1o7T2sS9JZ59B-SGd9GlSharbQ5JqCK8nHpi3aQZ7tBLL8dFlitQEcWOBvzs0cdUrvOICDnzhL94JvQHFaUoTTB6_mCZudSfCxxTIZ5-vjk_mqTq8B9pYo4RFWH0kqHhPxlTdTVZpSvlEDa21Ur3_G7ECbAnhmkSyA--Q4M8CTR2bxb-Kvxt1dpxugFZMzT46bI2j7Ze9wu4NYUBIOjSsRKcNjw"}
```

**Comment by l3wi** [comment]
I am also experiencing this issue. Same code as above

**Comment by chetanme** [comment]
Apologies for the delay. I just tried to reproduce this with different user pool configurations but I was not able to.

Can you give some more details about your user pool configuration? Device configuration, MFA configuration, alias configuration and anything else that can help us reproduce.

**Comment by artema** [comment]
Remember devices: user opt-in
MFA: optional (suppressed by a remembered device)
Required attributes: preferred username
Alias attributes: e-mail, phone (require verification)
Sign up: admin only

**Comment by l3wi** [comment]
Remember devices: Always
MFA: Off
Required attributes: email, phone
Alias attributes: email
Sign up: admin only

Hope this helps

**Comment by l3wi** [comment]
@itrestian Same as #132. Fixed for me now.

**Comment by itrestian** [comment]
@l3wi . Not sure I understand, you mean this is fixed as well, after I fixed https://github.com/aws/amazon-cognito-identity-js/issues/132? Closing then, feel free to open if needed.
