### ISSUE TITLE
Error including sdk with Aurelia webpack

### ISSUE THREAD

**Issue by frakevich** [aws/amazon-cognito-identity-js#181]
Hi, I have an Aurelia site with webpack and typescript. I have included the sdk like this:
import { CognitoUserPool, CognitoUserAttribute, CognitoUser } from 'amazon-cognito-identity-js';
(the editor highlights 'amazon-cognito-identity-js' as not resolved, but I see all of its files in node_modules).

I am getting an npm build error for each object above:
/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min"' has no exported member 'CognitoUserPool'.

Any recommendations?
Thank you!

**Comment by itrestian** [comment]
We haven't experimented using the SDK in that configuration but some users seem to have got it to work

http://stackoverflow.com/questions/39714424/how-can-i-get-the-amazon-cognito-identity-sdk-working-in-aurelia

**Comment by frakevich** [comment]
Thanks!  This helped, I was not finding this page in my own searches.
