### ISSUE TITLE
TypeError with use case 4

### ISSUE THREAD

**Issue by zlnvch** [aws/amazon-cognito-identity-js#184]
When trying to call the cognitoUser.authenticateUser() method I get the following error:

Chrome: Cognito Error:{"message":"Cannot read property 'input' of undefined","code":"TypeError"}
Firefox: Cognito Error:{"message":"a.service.api.operations[a.operation] is undefined","code":"TypeError"}

I am using the correct version of sjcl.js linked [here](https://raw.githubusercontent.com/bitwiseshiftleft/sjcl/master/sjcl.js).

My script order seems to match the readme (with a few additions at the end):

```
<script src="jsbn.js"></script>
<script src="jsbn2.js"></script>
<script src="sjcl.js"></script>
<script src="moment.min.js"></script>
<script src="aws-cognito-sdk.min.js"></script>
<script src="amazon-cognito-identity.min.js"></script>
<script src="aws-sdk.min.js"></script>
<script src="amazon-cognito.min.js"></script>
<script src="aws-sdk-mobile-analytics.min.js"></script>
```

Any ideas on what I might be doing wrong?

**Comment by itrestian** [comment]
I think this might be a main aws sdk issue. One of the operations the call uses, is not in the operations map (initiateAuth or respondToAuthChallenge). What version of the aws sdk are you using? Does it work with the latest?

**Comment by zlnvch** [comment]
I am using the latest version of all scripts, including aws sdk 2.6.10. I actually think that it's the amazon-cognito-identity.min.js script. The login worked with an older version of amazon-cognito-identity.min.js, but not in the latest. But, I had another issue with the older version, so I had to upgrade.

**Comment by zlnvch** [comment]
Hi itrestian,

Upon further inspection, it looks like while my aws-sdk.min.js was the latest version, my aws-cognito-sdk.min.js was still an older version. Updating it fixed the problem.

Thanks for your help.

**Comment by itrestian** [comment]
The aws-cognito-sdk is just a trimmed down version of the main aws sdk. It basically contains only the Cognito Identity service calls. I guess an older version wouldn't contain the initiateAuth and respondToAuthChallenge service calls.

**Comment by znebby** [comment]
Hmm - but it seems I need both? I mean, if I include the aws-sdk and try to remove the aws-cognit-sdk, I have errors.
