### ISSUE TITLE
calling api gateway with user pool

### ISSUE THREAD

**Issue by zivnini** [aws/amazon-cognito-identity-js#185]
Can you please provide an example of how to do that after authenticated?

**Comment by itrestian** [comment]
The documentation explains it pretty well:
    http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html

Also, the following blog post is pretty helpful:
    https://aws.amazon.com/blogs/mobile/integrating-amazon-cognito-user-pools-with-api-gateway/

**Comment by itrestian** [comment]
Hi, is there still an issue with this?
