### ISSUE TITLE
Automatically verify Email/Phone of Admin created user

### ISSUE THREAD

**Issue by l3wi** [aws/amazon-cognito-identity-js#187]
Is there a way to automatically verify the email/phone of an Admin created user? 

It stands to reason that their email/phone is verified if they login with their one time password.

**Comment by chetanme** [comment]
As mentioned in the API reference for [AdminCreateUser](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html), you can pass `email_verified=true` and/or `phone_number_verified=true` in [UserAttributes](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminCreateUser.html#CognitoUserPools-AdminCreateUser-request-UserAttributes).

**Comment by l3wi** [comment]
My Bad. 
Thanks for pointing this out.
