### ISSUE TITLE
NPM error: no versions found in https://github.com/aws/amazon-cognito-identity-js.git

### ISSUE THREAD

**Issue by EdGonzalez-** [aws/amazon-cognito-identity-js#188]
When specifying latest version of 1.7 in bower.json, returns no version found error.  Specifying "latest" returns 1.6

**Comment by itrestian** [comment]
Weird. Running
npm show amazon-cognito-identity-js version
returns
1.7.0

**Comment by itrestian** [comment]
Does this work now?
