### ISSUE TITLE
Confirm Code Expiration

### ISSUE THREAD

**Issue by sarah-pixvana** [aws/amazon-cognito-identity-js#189]
How many days are the confirmation codes good for? Could not find in docs anywhere

**Comment by itrestian** [comment]
Confirmation and verification codes are valid for 24 hours. Forgot password codes are valid for 1 hour only.

**Comment by itrestian** [comment]
I guess this is mentioned here but it doesn't explicitly say confirmation codes :).

http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

**Comment by sarah-pixvana** [comment]
Thank you!
