### ISSUE TITLE
Unable to build Stanford JavaScript Crypto Library on WIndows

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#19]
Well you probably could with cygwin but I use MinSys/MinGW these days and specifically the version that comes with Git for WIndows. For some reason they do not supply make and I gave up trying to get a single exe
So set up a VM with Ubuntu on

You might like to add a note

**Comment by itrestian** [comment]
Noted, should I change the README.md file or you want to send a pull request?

Ionut.

**Comment by SteveALee** [comment]
I'll do a PR. 
Do you know if it works with the --without-all option to keep it small?

**Comment by itrestian** [comment]
Yes, I am sure it can be configured using only the required components since some of the components are not required.

Ionut.
