### ISSUE TITLE
rollup support

### ISSUE THREAD

**Issue by paulsson** [aws/amazon-cognito-identity-js#190]
I'd really like to be able to use rollup for bundling my javascript files.  I'm trying to import class CognitoUserPool but I get the below error:

```
[23:15:52]  bundle dev failed:  Module <blahblahblah>/node_modules/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js does not export CognitoUserPool (imported by...)
```

I should mention I'm writing an app using Ionic2 which has switched to using rollup for its javascript bundling.

@simonbuchan I see you mentioned in your PR for adding webpack support that you were interested in rollup support as well:

> I'd like to figure out if there's a decent way to deal with aws-sdk and possibly mention other bundler options like rollup

https://github.com/aws/amazon-cognito-identity-js/pull/108#issuecomment-240859778

Any chance this is on your radar still?

I'm using the below dependency versions as defined in my package.json:

```
    "amazon-cognito-identity-js": "^1.7.0",
    "aws-sdk": "^2.6.10",
```

**Comment by simonbuchan** [comment]
I just kept `main` pointing at the dist file, which is a webpack generated UMD bundle, so Rollup probably doesn't support extracting the exports and tree-shaking that, which is what I believe webpack is doing when it is using it.

The entrypoint it generates it from is `amazon-cognito-identity-js/enhance.js`, as it (to keep compat with pre-webpack builds) also adds all the exports to `AWS/AWSCognito.CognitoIdentityServiceProvider`, so you could try importing from that or direct from `amazon-cognito-identity-js/src/CognitoUserPool` etc.., but that's not ideal as that could change in later builds.

From some googling, it looks like we just need to add a `jsnext:main` to the `package.json`, though we should probably not use the `AWS` stomping code in `enhance.js`: could you give this branch a try?

```
npm i skilitics/amazon-cognito-identity-js#jsnext-main
```

**Comment by simonbuchan** [comment]
Well I did some playing around and it looks like `aws-sdk-js` needs to support rollup directly, though I'm not discounting some rollup plugin trickery. Perhaps put together a small use-case and open an issue over there? There is [this similar one for JSPM](https://github.com/aws/aws-sdk-js/issues/1029) which is somewhat outdated with the webpack support merged.

**Comment by paulsson** [comment]
I've really got to do some reading and research on all these javascript bundlers and module terminology.  I don't feel I'm versed enough yet in ECMA6/Typescript and all the crazy new package/module management and bundlers to explain or detail what the problem is trying to used any of the AWS javascript SKDs with Typescript projects and bundlers like rollup.
I've also got to read up on the different module formats (ES6, AMD, CommonJS, globals) to understand them.
I was hoping that someone might have gotten it working using some rollup trick and could point me through the process so that I could get back to developing my app.
I haven't done much with Typescript before I started this Ionic2/Angular2 project.  The last javascript management and bundler tools I used and dug pretty deep into were bower and grunt... yikes.   That was a while ago.
I wouldn't know how to articulate the real cause of the issue in a ticket opened on the aws-sdk-js project.
I'll take any help or pointers.  Even references to get myself up to speed on understanding ES6, AMD, CommonJS, globals, SystemJS, Webpack, Babel, Rollup... and how they are relate to each other.

**Comment by itrestian** [comment]
You can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo.

https://github.com/aws/aws-amplify
