### ISSUE TITLE
Getting "AccessDeniedException" when I try to get all users from current user pool.

### ISSUE THREAD

**Issue by starodekar1** [aws/amazon-cognito-identity-js#191]
I have implemented all the use cases and it is working perfectly.
Getting the access-token after login .
Now i want to get all the users of current user pool, i found the method in the userPool.client object.

var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);

var params = {
    UserPoolId : MY-POOL-ID
}

userPool.client.listUsers(params,function(err, result){
    if (err)
        return fn(err);
    else
        return fn(result);
});

for which i'm getting AccessDeniedException.

**Comment by itrestian** [comment]
That is an authenticated operation so you would need AWS credentials to run it. You would need to populate AWSCognito.config.credentials with valid AWS credentials.

The user pools operations exposed in the SDK are unauthenticated operations (you don't need AWS credentials to run them).

You can get AWS credentials in a number of ways. By using Cognito Identity such as in use case 17 for example.
