### ISSUE TITLE
UserNotFoundException, UserNotConfirmedException, PasswordResetRequiredException

### ISSUE THREAD

**Issue by jonsmirl** [aws/amazon-cognito-identity-js#192]
Two new exceptions added for the authentication APIs: These exceptions have been added to accurately represent the user state when the username is invalid and when the user is not confirmed. You will have to update your application to handle these exceptions.
UserNotFoundException: Returned when the username user does not exist.
UserNotConfirmedException: Returned when the user has not been confirmed.
PasswordResetRequiredException: When administator has requested for a password reset for the user.

These exceptions don't generate callbacks in the SDK, how are we supposed to handle them in Javascript? I don't really like pattern matching on the error string text to detect them.

**Comment by itrestian** [comment]
The errors are just valid JSON. They contain status codes and the exact exception as below

error is {"message":"User does not exist.","code":"UserNotFoundException","time":"2016-10-26T17:25:32.212Z","requestId":"328585ca-9ba1-11e6-995f-9d4c30d9d8b5","statusCode":400,"retryable":false,"retryDelay":61.30185149939563}

**Comment by jonsmirl** [comment]
So test for?
error.code = "UserNotFoundException"

I don't want to test for something that might get translated to another language.

**Comment by jonsmirl** [comment]
this works, probably should be added to documentation.

```
            onFailure: function(err) {
                if (err.code = "UserNotConfirmedException") {
                    alert("JDS user not confirmed");
                }
                if (err.code = "UserNotFoundException") {
                    alert("JDS user not found");
                }
```

**Comment by itrestian** [comment]
You mean a section to explain how to identify different exceptions? That can be added, you can send a pull request to update the documentation.

**Comment by itrestian** [comment]
Updated docs.

https://github.com/aws/amazon-cognito-identity-js/commit/c63ea8ab90fb5a82f7df4799ccf3a34db26b8be2
