### ISSUE TITLE
AdminCreateUser operation not available through CognitoUser.client

### ISSUE THREAD

**Issue by carlgustavjung** [aws/amazon-cognito-identity-js#193]
Hello and thank you for this excellent library,

I am using the JS API in the browser.
I am using the instance of `CognitoIdentityServiceProvider` located in `CognitoUser.client` in order to call the Admin\* API operations. I invoke the operations using `cognitoUser.client.makeRequest(...)`
I am able to call 'adminSetUserSettings', 'adminEnableUser', 'adminResetUserPassword' but there is an issue when calling 'AdminCreateUser'.
I get this error in the browser console : 
`TypeError: a.service.api.operations[a.operation] is undefined`

When searching inside https://github.com/aws/amazon-cognito-identity-js/blob/master/dist/aws-cognito-sdk.js I noticed that 'AdminCreateUser' was missing between 'AdminConfirmSignUp' and 'AdminDeleteUser'.

PS: I can invoke the method using the standard AWS sdk `AWS.CognitoIdentityServiceProvider()`.

Best,

**Comment by itrestian** [comment]
Thanks for bringing this up. Just wondering if there's a need for it. It is not exposed because it is not necessary in the      amazon-cognito-identity SDK, we are not calling it. We can definitely expose it if there's a need, however as you said, it can be accessed through the main aws sdk.
