### ISSUE TITLE
Google Signin How to

### ISSUE THREAD

**Issue by Patrax** [aws/amazon-cognito-identity-js#194]
I don't think there's enough documentation out there about Google sign in. I need to access user attributes from my user pool as with the normal flow. So far I've compiled what I found.

```
window.onSignIn = function(googleUser) {
    // Useful data for your client-side scripts:
    var profile = googleUser.getBasicProfile();
    var email = profile.getEmail()

    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    signinCallback( id_token, email )
  };

  function signinCallback(id_token, email) {
     // Add the Google access token to the Cognito credentials login map.
     AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: config.IdentityPoolId,
        Logins: {
           'accounts.google.com': id_token
        }
     });

     // Obtain AWS credentials
     AWS.config.credentials.get(function(){
        // Access AWS resources here.
        console.log('Google sign in callback')
     });
  }
```

However, when I try to mix the normal flow with this I don't get an authenticated user so I can't access the attributes I need from my user pool user.

```
var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider
    .CognitoUser({
      Username : googleEmail,
      Pool : helpers.getUserPool()
    });
```

How can I authenticate with Google but get the user object from my user pool to get/update attributes?

**Comment by Patrax** [comment]
I'm closing this issue because I'm attempting the Cognito Sync route to sync the attributes that I need with the different logins.

**Comment by MattyK14** [comment]
@Patrax is there a snippet you could provide to help me out with this?

**Comment by Patrax** [comment]
Sorry @MattyK14 I don't have access to this code base anymore.
