### ISSUE TITLE
getting jwt for newly created user

### ISSUE THREAD

**Issue by charlieschwabacher** [aws/amazon-cognito-identity-js#198]
When creating users through `CognitoUserPool::signUp`, is there a way to get a JWT authorizing the newly created user without using `authenticateUser` and a second round trip to cognito?

**Comment by itrestian** [comment]
Getting tokens directly after sign up is not possible at this point. However, we have heard about this requirement from multiple users. This is a use case that we target to support. However, I cannot comment on the timeline.

**Comment by charlieschwabacher** [comment]
Thanks for the quick reply
