### ISSUE TITLE
Cannot authenticate user when device has been forgotten but keys are still in local storage

### ISSUE THREAD

**Issue by jogold** [aws/amazon-cognito-identity-js#200]
When trying to authenticate user with device keys in local storage, if the device has been forgotten a 400 ResourceNotFoundException (Device does not exist) is returned. 

This could happen if the user has the ability to forget previously remembered devices using ForgetDevice but also when deleting "not remembered" devices using AdminForgetDevice.

How do you recommend to handle this case ? Call cognitoUser.clearCachedDeviceKeyAndPassword() and retry ?

**Comment by itrestian** [comment]
Thank you for mentioning this. If the device was switched to not remembered, we should clearCachedDeviceKeyAndPassword, 

Optionally, as you mention, you can call that upon catching that exception.

**Comment by jogold** [comment]
Do you think this should be handled in the SDK ? (retrying after ResourceNotFoundException)

Let's imagine the following scenario : on computer A the user is given a list of remembered devices and chooses to forget computer B from that list (because he forgot to log out from computer B, ForgetDevice is the only way to invalidate the refresh token of a another device). After a while the user wants to log in again on computer B. He will get the ResourceNotFoundException.

**Comment by itrestian** [comment]
I think it would make sense to handle it in the SDK.

**Comment by jogold** [comment]
See https://github.com/aws/amazon-cognito-identity-js/pull/206
