### ISSUE TITLE
Request for clarification on documentation for CustomMessage Cognito Event Trigger

### ISSUE THREAD

**Issue by ljovanovic** [aws/amazon-cognito-identity-js#201]
In the documentation (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) there is a disclaimer on the CustomMessage event that indicates that it is intended to only be used for new user signups, yet I see several event triggerSource values such as CustomMessage_UpdateUserAttribute that are not relevant to that scenario (new user sign up).

Can you confirm whether this disclaimer is still accurate and what, if any, considerations exist for using the trigger outside of that scenario?  Specifically we plan to customize the email content to differentiate between conditions.

Essentially just trying to understand the motivations for the statement contained within the docs to ensure we're not heading down the wrong path.

Thank you.

**Comment by itrestian** [comment]
Hi, Thank you for pointing this out. The note in the documentation is indeed confusing and we will remove it. The custom message lambda trigger is invoked whenever a verification code is employed so it can have all the trigger sources that are mentioned in the documentation (not particularly sign ups only so forgot password and updating certain attributes also invoke it). So you should be fine customizing the message based on the trigger source.

**Comment by itrestian** [comment]
Documentation has been updated. Thanks for pointing that out!
