### ISSUE TITLE
AWS Authentication very slow on iOS Phonegap app

### ISSUE THREAD

**Issue by skicson** [aws/amazon-cognito-identity-js#209]
Similar to [this issue](https://github.com/aws/amazon-cognito-identity-js/issues/69).    When authenticating on an actual iPhone device, the authentication can take up to 60 seconds between the `cognitoUser.authenticateUser` call and the `onSuccess` method. 

On all other devices (desktop, android phones), it works fine.  Connecting to the web-based version from the iPhone's browser also works as expected.

It's only the Phonegap/Javascript version on the iPhone where I'm seeing this delay.

Any suggestions for figuring this out?

**Comment by skicson** [comment]
With some more investigation, like the issue cited above, the slowdown seems to be in the `bnModPow` function in the jsbn2.js library..

Not sure why this is just a problem with the iOS phonegap app, and not a problem with the web-based version running in the mobile safari browser....

**Comment by skicson** [comment]
After more investigation, the issue seems to be the performance of the jsbn2 library using the stock UIWebView.  I upgraded to use the WKWebView and it performs the same ops ~100x faster.  Unfortunately WKWebView causes other critical issues with Angular2 but that's obviously not within the scope of the AWS identity project.  Closing....

**Comment by munavvarfairoos** [comment]
Hi skicsonm,
Now i am facing the same issue, in my android device it working perfectly but in my ios devices it take too much time can you please guid me how you fixed this issue it would be a great help
Thanks
Munavvar

**Comment by skicson** [comment]
Unfortunately I don't have a solution yet.  For now I just put up a busy screen until it is done processing.

If you aren't using Angular 2, but you are using Phonegap, you can try to install the WKWebView plugin which is much faster but may cause other issues.

**Comment by munavvarfairoos** [comment]
Hi
Thanks a lot for your reply.
now i am doing android on cordova and ios in objectives
Thanks
Munavvar Fairoos

**Comment by FLATT-Dev** [comment]
Here is a Cordova plugin that handles AWS authentication on iOS and Android. This is a fork of the original 
 iOS only plugin. I started the Android port and implemented basic login and sign up without confirmation. Feel free to contribute. On my lowly Galaxy 3 authentication takes 2 seconds now  vs 15 seconds when using jdk. Please contribute to the android-dev branch. The sample app has some bugs and needs to be fixed. I'll continue adding features as needed for my project
https://github.com/FLATT-Dev/cordova-plugin-aws-user-pool/tree/android-dev
Andy
