### ISSUE TITLE
Admin Users

### ISSUE THREAD

**Issue by hassankhan** [aws/amazon-cognito-identity-js#210]
Unfortunately, we require something similar to the Cognito User Pool console's user view to administrate new/existing users, and it seems that this SDK doesn't support anything to do with admin users currently.

I know this has been brought up before, and @itrestian has mentioned that support could be added if there was enough interest. I'm happy to create a PR if that is still the case?

**Comment by jbailey2010** [comment]
Yeah, absolutely. Feel free to create a PR if you need it.
