### ISSUE TITLE
Preferred username as alias and disabled verifications.

### ISSUE THREAD

**Issue by Arekusei** [aws/amazon-cognito-identity-js#211]
There is a problem with the preferred_username change.
1.  Settings validation is disabled (checkboxes Email and SMS are unchecked at Verifications tab)
2. Calling adminUpdateUserAttributes to change preferred_username.
3. Trying to log in (adminInitiateAuth) with a new preferred_username and i'm get the error "UserNotFoundException: User does not exist".

**Comment by jbailey2010** [comment]
A few questions 
- Are you seeing this issue with at least one verification set up?
- Is this issue consistent, or intermittent? 
- Did you set up preferred_username as an alias?
- You specifically mention having used the admin APIs, does that mean you're only seeing it when using those? Or that you have only used those?
