### ISSUE TITLE
cognitoUser.deleteUser() should clearCachedTokens() internally

### ISSUE THREAD

**Issue by martintasker** [aws/amazon-cognito-identity-js#213]
I found that when I deregister myself using deleteUser() (using use case 13 code), then refresh the page which has use case 16 code for getting back the last session from local storage, then I apparently have a valid session after the page refresh.  Of course the moment I try to actually do anything it is revealed as invalid.  I had to work around this by calling clearCachedTokens() after deleteUser().  Wouldn't it make sense to have included clearCacheTokens in the deleteUser() implementation itself?

(You can see my code [here](https://github.com/martintasker/cognito-auth/blob/master/demo/app/scripts/cognito-auth/cognito-user.service.js): just search for `clearCachedTokens()`.)

**Comment by itrestian** [comment]
Thank you for bringing this up. You are right, I think it makes sense to clear the tokens after deleting the user in the SDK.

**Comment by itrestian** [comment]
This has been merged.

https://github.com/aws/amazon-cognito-identity-js/pull/214
