### ISSUE TITLE
How do I do authentication of a user with external identity providers

### ISSUE THREAD

**Issue by mhafren** [aws/amazon-cognito-identity-js#217]
I have done the authentication part with facebook already ie. I have received an access_token from facebook. I can't seem to find how to authenticate/register the user using an access_token? 

Does this library not support this feature yet or am I missing something?

**Comment by bmdako** [comment]
I'm not sure I on the right track. But maybe this is what you should do:

```javascript
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'IdentityPoolId',
      Logins: {
        'graph.facebook.com': accessToken
      }
    });
    AWS.config.credentials.get(credentialsGetCallback);
```

**Comment by itrestian** [comment]
that's pretty much the example although you don't need to use this library. The cognito identity broker access functionality is in the main AWS JavaScript SDK.
