### ISSUE TITLE
Does amazon-cognito-identity-js has valid git tag ?

### ISSUE THREAD

**Issue by extend1994** [aws/amazon-cognito-identity-js#225]
Hi,
according to library request cdnjs/cdnjs#9725, I would like to check whether there is a [valid tag](https://github.com/aws/amazon-cognito-identity-js/tags) that allows me to add the library with auto-update config.
With auto-update config, cdnjs will be able to automatically update libraries that are known to git repo.
For more details about auto-update config on cdnjs, you can check https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md .
For more details about tag, you can check https://git-scm.com/book/en/v2/Git-Basics-Tagging .

Thank you!

**Comment by itrestian** [comment]
At this point no but we can add this in the future. Thanks for mentioning!

**Comment by itrestian** [comment]
Just created v1.11.0. Thanks!

**Comment by extend1994** [comment]
Hi @itrestian , thank you for your response and great work! 
Could you please tell me that whether amazon software license is a kind of open source license or give me some suggestion about it?

Thank you again :)
