### ISSUE TITLE
aws-cognito-sdk.min.js:21 Uncaught Error: AWS.CognitoSyncManager is not a constructor(…)

### ISSUE THREAD

**Issue by amank12** [aws/amazon-cognito-identity-js#226]
Here is the code :

<!DOCTYPE html>
<html>
<head>
	<script src="jsbn.js"></script>
	<script src="jsbn2.js"></script>
	<script src="sjcl.js"></script>
	
	
	<script src="https://sdk.amazonaws.com/js/aws-sdk-2.6.10.min.js"></script>
	<script src="aws-cognito-sdk.min.js"></script>
	<script src="amazon-cognito-identity.min.js"></script>
	
	<script src="aws-sdk.js"></script>
	<script src="amazon-cognito.min.js"></script>
	
	
	
</head>

<body>
	  
    <script>

	AWS.config.region = 'ap-northeast-2'; //This is required to derive the endpoint
        
    var poolData = { UserPoolId : 'ap-northeast-2_go0rGKVb5',
        ClientId : '6a0n8dqpi9i7be9mtve36u6klm'
    };
	
	var authenticationData = {
        Username : 'username',
        Password : 'Password1#',
    };
    var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
	
	if ( authenticationDetails != null)
		console.log('Got Authentication');
	
	var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
	
	if ( userPool != null)
		console.log('Got userPool');
		
	
	
	 var userData = {
        Username : 'username',
        Pool : userPool
    };
    var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
	
	if ( cognitoUser != null)
		console.log('Got cognitoUser');
		
	cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('access token : ' + result.getAccessToken().getJwtToken());
            console.log('idToken : ' + result.getIdToken().getJwtToken());
			
			AWS.config.credentials = new AWS.CognitoIdentityCredentials({
				IdentityPoolId: 'ap-northeast-2:8ea060bb-dbb5-484d-b2cf-bd786c48a396',
					Logins: {
						'cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_go0rGKVb5':   result.getIdToken().getJwtToken()
					}
				});
				
				AWS.config.credentials.refresh(function (error) {
					if (error) {
						console.error(error);
					} else {
						console.log('Successfully logged!');
					}
				});
				
				// Obtain AWS credentials
				AWS.config.credentials.get(function(){					
					var accessKeyId = AWS.config.credentials.accessKeyId;
					var secretAccessKey = AWS.config.credentials.secretAccessKey;
					var sessionToken = AWS.config.credentials.sessionToken;
					
					console.log("Access Key:", AWS.config.credentials.accessKeyId);
					console.log("Secret Access Key:", AWS.config.credentials.secretAccessKey);
					console.log("Session Token:", AWS.config.credentials.sessionToken);
				});
				client = new AWS.CognitoSyncManager();
        },

        onFailure: function(err) {
            alert(err);
        },

    });
	
	</script>
	
	</body>
</html>

I have a federated identity that user Congnito to authenticate a user.  After authentication I want to add a dataset and attributes to the user.  In above code I am able to authenticate user but getting an error when I add AWS.CognitoSyncManager constructor.  Error message is : aws-cognito-sdk.min.js:21 Uncaught Error: AWS.CognitoSyncManager is not a constructor(…)

**Comment by akashbiz** [comment]
@amank12 what was the solution for this issue? I am facing the same issue, can you share the solution for this please?
