### ISSUE TITLE
Global Namespace Pollution

### ISSUE THREAD

**Issue by bflora2** [aws/amazon-cognito-identity-js#230]
I notice that jsbn.js, jsbn2.js, and sjcl.js introduce a vast amount of pollution into the global space. This is both very bad practice and dangerous. As an example, you can't safely use Cognito for authentication in the implementation of a white label web service meant to be embedded in client websites because sooner or later that service would end up causing errors on client websites due to global namespace collisions.

Are there any plans to clean this up?

**Comment by itrestian** [comment]
Thank you for bringing this up. We haven't looked into it much besides trying out other libraries that do similar things. Note that there are different versions of the libraries you mentioned that solve some of the issues. We linked to the original ones for obvious reasons.

**Comment by bflora2** [comment]
I think for now I will simply bundle the five files that implement Cognito's JavaScript SDK into a single file with that file's contents wrapped in an IIFE. For now, that should provide me with a quick, safe solution that avoids changing the actual code. 

**Update:** Bundling the files works fine, but as soon as I enclosed the bundled code in an IIFE the code from amazon-cognito-identity.min.js threw an "u.BigInteger is not a constructor" error. Apparently that code expects some of its dependencies to actually be in the global space, not simply within function scope. Sigh.

**Comment by itrestian** [comment]
We removed these dependencies (pulled in BigInteger and using AWS utils instead of SJCL). See pull requests 

https://github.com/aws/amazon-cognito-identity-js/pull/282
https://github.com/aws/amazon-cognito-identity-js/pull/281
