### ISSUE TITLE
Strange naming of this project

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#235]
It's really odd that this is named the webpack/babel example when it's actually a reactjs application.

I really wish I had known up front that there was a reactjs example application, it would have saved me days of futzing around.

**Comment by itrestian** [comment]
Sorry about that, we can update the Relevant Examples section of the main README file to explain that.

**Comment by itrestian** [comment]
Just updated. Feel free to send a pull request if it requires more clarification.

https://github.com/aws/amazon-cognito-identity-js/commit/3a4aceb5dafbfa2ee2844b4d827302da696de3f1
