### ISSUE TITLE
mfaRequired callback does not provide masked phone number information

### ISSUE THREAD

**Issue by codynguyen** [aws/amazon-cognito-identity-js#236]
Hi,

During authentication process for MFA-enabled users, the aws cognito server does return the masked phone number information in the response:

```
{
  "ChallengeName": "SMS_MFA",
  "ChallengeParameters": {
    "CODE_DELIVERY_DELIVERY_MEDIUM": "SMS",
    "CODE_DELIVERY_DESTINATION": "+*******0008"
  },
  "Session": "[session string]"
}
```

However, the lib only exposes `ChallengeName` in the `mfaRequired` callback: https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L269

It'd be great if the callback provides the `ChallengeParameters` as well, so that client app can show the masked phone number as instruction for the authentication process. For example: '_A verification code has been sent to your phone +*******0008, please enter the code to login._'

**Comment by itrestian** [comment]
Pulled in! Thanks!
