### ISSUE TITLE
CognitoUser.authenticateUser expects callback argument to be an options object not a function

### ISSUE THREAD

**Issue by sbussard** [aws/amazon-cognito-identity-js#238]
The `CognitoUser.authenticateUser` method expects an argument called `callback` that is expected to have the following properties:

`callback.newPasswordRequired`
`callback.mfaRequired`
`callback.customChallenge`
`callback.authSuccess`

Conventionally, the term `callback` refers specifically to a function to be called. 
This argument resembles an `options` object rather than a callback.

**Comment by sbussard** [comment]
It looks like I'm not the first one to notice this. Sorry for the duplicate issue.

https://github.com/aws/amazon-cognito-identity-js/issues/135

**Comment by itrestian** [comment]
Thanks for bringing this up! It might make sense to rename callback to object since we are just calling methods on the object.

**Comment by itrestian** [comment]
You can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo.

https://github.com/aws/aws-amplify

**Comment by sbussard** [comment]
Thanks for the heads up @itrestian!
