### ISSUE TITLE
Possible to create a v1.10.0 tag?

### ISSUE THREAD

**Issue by upgradingdave** [aws/amazon-cognito-identity-js#239]
I'm interested in using `amazon-cognito-identity-js` inside a clojurescript project. In order to use it easily from clojurescript, I've created a [cljsjs](http://cljsjs.github.io/) package [here](https://github.com/upgradingdave/packages/tree/aws-cognito-sdk/aws-cognito-identity-js).  

In order to keep the cljsjs package in sync with this repository, it would be helpful if you wouldn't mind creating a v1.10.0 tag? That way, the cljsjs package could always reliably find the version 1.10.0 js at a url like: 

https://github.com/aws/amazon-cognito-identity-js/archive/v1.10.0.zip

Also, feel free to name the tag whatever is best for you. I suggested `v1.10.0` as the tag name because that's the convention used by https://github.com/aws/aws-sdk-js, but if there's another naming convention, that'd be fine as well!

**Comment by itrestian** [comment]
Just created v1.11.0
