### ISSUE TITLE
Is Config settings redundant in react+webpack example?

### ISSUE THREAD

**Issue by howardya** [aws/amazon-cognito-identity-js#243]
In the example, 
https://github.com/aws/amazon-cognito-identity-js/blob/master/examples/babel-webpack/src/main.jsx#L10-L13

Are the sentences highlighted above necessary? I removed them and they still work.

Thank you :)

**Comment by itrestian** [comment]
In that specific example, yes it is. However, if you would want to integrate User Pools with Cognito Identity such as in Use case 17, you would have to set them.
