### ISSUE TITLE
Get specific attributes with name?

### ISSUE THREAD

**Issue by howardya** [aws/amazon-cognito-identity-js#244]
In the example shown,

Use case 5. Retrieve user attributes for an authenticated user.

``` jsx
    cognitoUser.getUserAttributes(function(err, result) {
        if (err) {
            alert(err);
            return;
        }
        for (i = 0; i < result.length; i++) {
            console.log('attribute ' + result[i].getName() + ' has value ' + result[i].getValue());
        }
    });
```

is there away to get a specific attributes instead of getting all?

**Comment by itrestian** [comment]
This is not possible at this point as the service call we make is to retrieve all the user details. You can filter the specific attributes yourself.

**Comment by howardya** [comment]
I see, alright. Thank you for the reply. It would be nice if we can selectively choose the attributes we want?

By the way, in the attributes, I notice user has a attribute named 'sub', may I know what is this?

Cheers

**Comment by itrestian** [comment]
Pretty much the UUID of the authenticated user.
