### ISSUE TITLE
Login tokens after successful user signup confirmation

### ISSUE THREAD

**Issue by hfougere** [aws/amazon-cognito-identity-js#246]
After the user successfully provides the correct validation code after they sign up, would it be possible to return the access tokens you get after a successful login? This way we could use the tokens to recreate the user session and automatically log in the user. Right now the confirm signup function returns a blank payload on success.

**Comment by itrestian** [comment]
Thanks, we have heard this requirement in the past. See issue https://github.com/aws/amazon-cognito-identity-js/issues/186 

I will add this as a +1 for the feature.
