### ISSUE TITLE
Cognito SDK: this.client.makeUnauthenticatedRequest timing out on Lambda

### ISSUE THREAD

**Issue by stevilyu** [aws/amazon-cognito-identity-js#247]
I'm trying to authenticate against cognito in  my lambda function, and I've narrowed down the problem to this part of the amazon-cognito-identity-js package:

src/CognitoUser.js

this.client.makeUnauthenticatedRequest('initiateAuth', {
      AuthFlow: this.authenticationFlowType,
      ClientId: this.pool.getClientId(),
      AuthParameters: authParameters,
      ClientMetadata: authDetails.getValidationData(),
    }, (err, data) => {....

This call seems to time out.  Is there something special I need to setup to allow my Lambda functions to access Cognito?  The code works just fine running locally but once it is running in Lambda it fails.

Thanks!

**Comment by stevilyu** [comment]
Nevermind, I had my Lambda function setup to use a VPC and needed to add a NAT gateway for it.

**Comment by itrestian** [comment]
Yes, that happens a lot

http://stackoverflow.com/questions/36067080/aws-lambda-cant-call-cognito-identity-iam-role
