### ISSUE TITLE
How to disable an user after "Password attempts exceeded"?

### ISSUE THREAD

**Issue by lborgav** [aws/amazon-cognito-identity-js#257]
After trying to authenticate several times, it returns "Password attempts exceeded" exception.
I'd like to disable the user when that event happens. Is there any kind of support for this flow?

**Comment by hfougere** [comment]
You should be able to call the admin disable user function. I haven't tried it myself yet though :)

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminDisableUser-property

**Comment by lborgav** [comment]
I found this entry on documentation, but I think it doesn't work, because it disable AS ADMINISTRATOR. I'd like to disable/enable the user, like we have on dashboard

<img width="644" alt="cognito" src="https://cloud.githubusercontent.com/assets/1133835/22226144/2cee19b4-e193-11e6-8954-18ac3cd200a3.png">

**Comment by hfougere** [comment]
enable/disable from the dashboard is the same as doing so using the admin enable/disable api functions as far as I know.  Just initialize AWS with your accessid and secret key on your backend service and you should be able to do whatever want to any user.

**Comment by yishafang** [comment]
Using adminDisableUser or adminEnableUser api performs the same functionality as disable/enable from the dashboard.

**Comment by sutineeangs** [comment]
User will deleted, if disabled it long time ?
