### ISSUE TITLE
use standard/custom attributes to customize email verification

### ISSUE THREAD

**Issue by cfranc10** [aws/amazon-cognito-identity-js#259]
I'd like to be able to chose attributes to customize email verification upon registration. For example, if i want to add the website name in the email that goes out to where I want them to go to finalize registration (shown below). How can I accomplish this?

**Email Verification Body**
Please go to: {website} to finalize your registration. 

Your verification code is: {####}

**Comment by itrestian** [comment]
You could use a lambda function for the CustomMessage_SignUp trigger. 

http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

In the event object, you get all the user attributes and the verification code that you can use to verify the message.
