### ISSUE TITLE
Confusing repo name

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#26]
This repo name makes no mention of User Pools and appears to cover more general functionality.

Needs to be renamed to something like Amazon-cognito-user-pools-js-client-sdk

**Comment by itrestian** [comment]
Hi Steve,

Noted, will discuss it with the team.

Ionut.

**Comment by itrestian** [comment]
We are working on our plan to rollout the service for GA. We will take care of naming issues with other changes.

Ionut.

**Comment by SteveALee** [comment]
"GA"?
