### ISSUE TITLE
The type of  Amazon Software License

### ISSUE THREAD

**Issue by extend1994** [aws/amazon-cognito-identity-js#261]
Hi!
I am a member of cdnjs. 
There is one lib request cdnjs/cdnjs#9725.
To add the lib correctly, could you please tell me that whether Amazon Software License is a kind of open source license or give me some suggestion about it?

Thank you :)

**Comment by hyandell** [comment]
Hi LboAnn,

I'm not sure what you're looking for. 

The Amazon Software License is derived from the Microsoft Limited Public License + Apache License 2.0. It's neither approved by, nor submitted to, the Open Source Initiative.

**Comment by PeterDaveHello** [comment]
@hyandell so would you call it an open source license?

**Comment by PeterDaveHello** [comment]
Hello @hyandell ?

**Comment by hyandell** [comment]
Sorry for missing this.

I wouldn't call it Open Source - I don't believe the Microsoft Limited Public License that this shares terms with has been reviewed by the OSI and neither has this license.

**Comment by tdmalone** [comment]
For others coming across this, just to clarify, the ASL is not open source.

From the [Open Source Definition](https://opensource.org/docs/osd#fields-of-endeavor):
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

From the [Amazon Software License](https://aws.amazon.com/asl/):
> The Work and any derivative works thereof only may be used or intended for use with the web services, computing platforms or applications provided by Amazon.com, Inc. or its affiliates, including Amazon Web Services, Inc.

In general it appears the ASL is quite permissive, but you can't take an ASL licensed product and use it on Google Cloud, for instance. Nor can you in the future, so if you put a lot of effort into building on an ASL licensed product, you might be locking yourself into only using it on AWS.

But, IANAL ;)
