### ISSUE TITLE
Login workflow from server

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#263]
Hi there,
I was wondering if any of you had thoughts as to how the login workflow would work if a NodeJS server was used to make all the requests to the Cognito Identity API instead of the Android, iOS or web frontend application. Thanks.

**Comment by itrestian** [comment]
You can have a look at an angular js example to get a quick idea:

https://github.com/awslabs/aws-cognito-angular2-quickstart

**Comment by yulric** [comment]
Thanks. In that angular app though it deals with only one user where as in a nodejs server I would have to authenticate multiple users at once. Does this mean I need to store the reference to all the CognitoUser objects created?

**Comment by itrestian** [comment]
Sorry but I don't understand the use case. Everything should function in the context of the same request you make to the server. Is it a different type of app that you are targeting?

**Comment by yulric** [comment]
My "system" consists of a NodeJS server which several client application running on iOS, Android and browsers. All requests by the clients are made to my NodeJS server and if the request involves authentication such as signing up a user, verifying a user the NodeJS server uses this library to do so. In the case of the logging in a user, once I login a user using the authenticateUser method and send the 3 tokens that Amazon sends back to me to the right client how do I "recognize" the logged in user when he sends the request to my NodeJS with those 3 tokens? 

Sorry for not being clear enough. Hopefully this makes my use case clear.

**Comment by yulric** [comment]
So I figured out how the authentication workflow goes using this http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html and this https://aws.amazon.com/blogs/mobile/integrating-amazon-cognito-user-pools-with-api-gateway/. The only question I have remaining and I'm not sure if anybody here will be able to answer it but should I ever go back to the amazon cognito server to check an access token or is it safe to just verify the signature?

**Comment by collinforrester** [comment]
So from your login page/sign up page, you make all calls to your NodeJS API first and then broker calls to Cognito? Meaning your end clients iOS/Android never know rally that they're touching Cognito

**Comment by yulric** [comment]
Yes, but after discussing with my colleagues we were thinking of making all our clients handle authentication (login and signup) themselves. The only problem we were having with this approach was sessions. When one of the clients calls a route to our server that requires the user to be authenticated, we were not too sure how to accomplish that since I couldn't find any API method to check with Amazon Cognito if a token was valid or not?

**Comment by collinforrester** [comment]
I guess we never had to answer that because we are using API Gateway with Cognito, and APIG does that verification for us.

We have the Cognito code on the client at the moment but would much rather have that abstracted to the server.

**Comment by yulric** [comment]
That's what we thought, I have not looked into API gateway but would it essentially act like a wall in front of our server (running on elastic beanstalk) that handles making sure a client is authenticated to go through certain routes on our server?

**Comment by collinforrester** [comment]
that's exactly how it behaves for us.  You can set up a single API gateway route if you wish that is a proxy to your EB environment.  It's only role would be to do the authentication for you.

**Comment by yulric** [comment]
Thank you for your help. That's pretty much what I needed to know, closing this issue.
