### ISSUE TITLE
cognitoUser.getSession(callback) should always invoke the callback

### ISSUE THREAD

**Issue by mvila** [aws/amazon-cognito-identity-js#264]
When we call cognitoUser.getSession(callback) and tokens are not present in localStorage (because the user logged out), the callback is never invoked. I think it is a terrible behavior. A function with a callback should always invoke the callback.

**Comment by itrestian** [comment]
Thanks for the suggestion, I will mention this within the team and make a change accordingly.

**Comment by mvila** [comment]
Thanks for your quick reply @itrestian!

**Comment by itrestian** [comment]
See https://github.com/aws/amazon-cognito-identity-js/pull/299
