### ISSUE TITLE
How to find out if the user is already signed in from a previous visit?

### ISSUE THREAD

**Issue by mvila** [aws/amazon-cognito-identity-js#265]
After a successful sign in, the different tokens are cached in localStorage. This is a good thing because as long as the refreshToken is still valid the user doesn't have to sign in each time he is using the app. But how to find out if the user is already signed in from a previous visit? I didn't find a clean way to answer this simple question. Should I check the localStorage myself?

**Comment by itrestian** [comment]
The tokens in local storage are keyed based on client id and username so if you instantiate a CognitoUserPool object and a CognitoUser object with the appropriate information, you can call getSession to retrieve the stored tokens.

**Comment by mvila** [comment]
Thanks for your answer @itrestian, this is exactly what I tried to do but then I ran into issue #264 when the user is logged out. Also, to create a CognitoUser I need to retrieve the username from somewhere (i.e. localStorage). Since this library is already storing it (CognitoIdentityServiceProvider.{clientId}.LastAuthUser), it would be nice to be able to get it through the public API.
