### ISSUE TITLE
Publish aws-cognito-sdk to npm

### ISSUE THREAD

**Issue by ryanwitt** [aws/amazon-cognito-identity-js#266]
It would be helpful for workflow to be able to include `aws-cognito-sdk` as a dependency and not write custom build rules on every project.

Tangentially related to #171.

**Comment by itrestian** [comment]
Yes, that's a good idea. I will mention it within the team to prioritize this change accordingly.

**Comment by iguana** [comment]
+1

**Comment by loixlab** [comment]
Is there any progress on this? I am looking for a way to import just the aws-cognito-sdk from npm. thanks! 👍

**Comment by felzix** [comment]
+1

**Comment by itrestian** [comment]
We have removed the AWS-Cognito SDK dependency. 

Also, you can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo.

https://github.com/aws/aws-amplify
