### ISSUE TITLE
Do you plan to make this package more friendly to use on backend with for ex cookie storage?

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#268]
It's good for client side if you want to store your tokens on localstorage, but I feel a lot of ppl want to use this package also as an API, and use different methods for token storage. It gets very hacky pretty fast.

**Comment by itrestian** [comment]
We are definitely interested in making this package usable in different types of environments/scenarios. As you suggested, not all users want to store tokens in local storage. This has been suggested before, see below:

https://github.com/aws/amazon-cognito-identity-js/issues/87

**Comment by itrestian** [comment]
Closing this, You can pass your own storage to the objects through this pull request:

https://github.com/aws/amazon-cognito-identity-js/pull/363
