### ISSUE TITLE
Simple validation of access token for use in Node

### ISSUE THREAD

**Issue by RobinJayaswal** [aws/amazon-cognito-identity-js#269]
**Desired Use Case:**

I have a Node.js backend and a client-side web app (Polymer), and would like to use Cognito to simplify my token based authentication system.
 
I would like to use this library for user authentication by having them register and authenticate on the client and storing the access token AWS gives me, then for all future requests to the Node.js backend, sending the access token in the header. I was hoping that the backend could check with Cognito whether the access token is associated with a valid session, and get a user id if so. However, I see no such method for checking an access token against Cognito.

Is there any way I can accomplish this?

Here is a general idea of the flow I am envisioning in code:

```javascript
// client
cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            setCookie('access-token', result.getAccessToken().getJWT())
        },
```

```javascript
// client
function fetchData() {
   ajax.request('/server/data',
   headers: {
     token: getCookie('access-token')
   })
}
```

```javascript
// node server
get('/data', function(req, res) {
   AWSCognito.validateAccessToken(req.headers.token).then(function(userId) {
     // if user id exists, this is a valid token. now have user id, can look them up in database 
     // and do stuff
   }
})

**Comment by collinforrester** [comment]
You didn't ask about adding API Gateway integration, but I thought I'd add that if you did add it, it would do exactly what you're describing.

APIG setup as the entry point to your node app, with the authorization settings pointing to your user pool. By the time you get your request in your node code, the identity is resolved and available on the request heqders (or depending on how you tell APIG to forward that info)

**Comment by Epochi** [comment]
I'm trying to do the same thing, AFAIK [this](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-identity-user-pools-using-id-and-access-tokens-in-web-api) is describing what you need to do to verify authenticity of the token on the server and it can be done without calling aws api twice

I'm just not completely sure if this is specifically talking about cognito user pool or cognito federated identity pool

**Comment by rachitdhall** [comment]
I answered your question on [stackoverflow](http://stackoverflow.com/questions/41969355/aws-cognito-for-standard-token-based-authentication).

But it is essentially what others have suggested. You can validate the id token on your backend to verify the identity of the token. If you use [API Gateway integration](http://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-integrate-with-cognito.html) you get this out of the box.

Closing this issue as it is not an issue with JS SDK. Please feel free to post such questions on [Amazon Cognito Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173).
