### ISSUE TITLE
Need to document the possible error returns

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#27]

**Comment by itrestian** [comment]
Noted, will discuss with the team.

Ionut.

**Comment by itrestian** [comment]
Hi Steve,

Actually some documentation about the errors can be found here (for the different operations):
http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html

However, not all operations are exposed through the low level SDK,

Ionut.

**Comment by SteveALee** [comment]
Thanks. However we only get strings, not any sort of error ID. Anyway I resolved for my use but felt some docs would help others.

**Comment by itrestian** [comment]
Hi Steve,

We will work on getting the error codes mapped into a common document.

Ionut.
