### ISSUE TITLE
How to remember auth & auto refresh token?

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#271]
I have built a website that uses AWS Cognito with the Userpool functionality.

If I leave the page, the login is forgotten, and after one hour the token expires.

I'd like the login to be remembered when the user closes their browser and comes back.

I'd also like the auth token to auto refresh instead of just giving errors after one hour.

How can I do this?

**Comment by sbussard** [comment]
Save the json web token to local storage. Create a fallback for your users who are using safari in private browsing mode (where there is no access to local storage). Do not use client side cookies, it's complicated to make them secure.

**Comment by itrestian** [comment]
Yes, as @sbussard mentioned, this library already saves tokens to local storage and Use case 16 shows how to retrieve the user from local storage. When the window object is not defined, this library falls back to in memory storage.

**Comment by crowdwave** [comment]
@itrestian how about auto refreshing the token, how can I do that?  Currently the token expires after one hour.  It would be good for it to auto refresh instead of just giving errors. thanks

**Comment by itrestian** [comment]
Answered your question on stackoverflow:

http://stackoverflow.com/questions/42002953/how-to-remember-autorefresh-login-token-when-using-amazon-web-services-cognito/42010337#42010337

**Comment by crowdwave** [comment]
OK so I'm not getting how this should work.

To keep the session valid for more then one hour, I have a timer set up which calls my getSession function, which as I understand it, should ensure that the sesson is valid.

But later after more than an hour when I try to use the session I get an error 400 saying that the token is not valid (I think, I'll have to check the exact error)

What am I doing wrong?  How can I keep the session valid? thanks!

```
// every X seconds we refresh the amazon Cognito connection token
let refreshSession = (err, session) => {
  if (err) {
    console.log('error getting session: ', err)
  } else {
    console.log('session validity: ' + session.isValid())
  }
}

let intervalID = window.setInterval(() => {application.user.getSession(refreshSession)}, 10000);

```


```
  getSession = (callback) => {
    // Use case 16. Retrieving the current user from local storage.

    if (!this.cognitoUser) {return callback(new Error('cognito user is not initialized'))}

      this.cognitoUser.getSession((err, session) => {
        if (err) {
          return callback(err)
        } else {
          return callback(null, session)
        }
      })
  }
```

**Comment by thiagomcampos** [comment]
+1

Exactly the same here.

I have an Angular 1.x based webapp that uses cognito-identity-js and if I call Use Case 16 code after one hour, my session object is null, so I get the same error (even if I did login today - my refreshToken is new).

I am not sure, but I guess this didn't use to happen until few weeks ago.

**Comment by sbussard** [comment]
After one hour all of your access tokens have expired. You'll need to use your refresh token. That's covered in use case 17 using calling a special function `AWS.config.credentials.refresh`. Your refresh token is valid for 30 days by default.

----

"The ID token expires one hour after the user authenticates. You should not process the ID token in your client or web API after it has expired."

"The access token expires one hour after the user authenticates. It should not be processed after it has expired."

"By default, the refresh token expires 30 days after the user authenticates. When you create an app for your user pool, you can set the app’s Refresh token expiration (days) to any value between 1 and 3650."

http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by onassar** [comment]
Just stumbled into this. I'm using the `needsRefresh` method to determine in my application code whether to make a request to the `refresh` method. However I have two questions (to anyone):

1. Is it possible to lower the time from one hour, so that I can properly test this? Having to wait one hour to see if my application code is running properly is kind of annoying ;-)

2. Do I have to do anything other than call the `refresh` method? I assume that will automatically update the token? I noticed that the only arguments sent to the callback that I pass into the `refresh` method is an `err` object. So I assume all the token reference switching is done automatically on my behalf?

Thanks!

**Comment by chasebleyl** [comment]
@onassar what did you end up finding through your testing? I am looking into resolving similar issues and your proposed implementation sounded promising. Did you determine how to lower the token time from one hour?

**Comment by onassar** [comment]
@chasebleyl Unfortunately I don't think it's possible at the moment.
I haven't yet dealt with the test/underlying issue, but when I have I'll post what I found back in here :)

**Comment by rms80** [comment]
If you do a global sign out, the refresh tokens will be invalidated (for testing).
