### ISSUE TITLE
Missing definitions for some CognitoUser functions

### ISSUE THREAD

**Issue by Dunos** [aws/amazon-cognito-identity-js#273]
Some functions available for CognitoUser are missing in the typings definition file ("index.d.ts"), at least a couple of them, "completeNewPasswordChallenge" and "sendMFACode", both required in the use case 23.

**Comment by itrestian** [comment]
Thanks for mentioning! I see there is a pull request for this already!

https://github.com/aws/amazon-cognito-identity-js/pull/272

**Comment by paulsson** [comment]
I noticed there are a couple other definitions missing.
signOut()
globalSignOut(callback)
https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L1303

**Comment by itrestian** [comment]
Pulled in pull request. Closing.
