### ISSUE TITLE
Cognito JWT Token not working with API Gateway

### ISSUE THREAD

**Issue by georgeismike** [aws/amazon-cognito-identity-js#274]
I have followed the README to get a user to signup, confirm, signin and get a token.  When I pass the token into the API Gateway either in my app or directly on the API GW Console, I get a 401 unauthorized. 

AWS Support was able to reproduce my issue following the README as well. They are reaching out to their internal teams.  Any guidance available here while I wait for info from the support team? 

I think the token is bad in some way. I put the token into: https://jwt.io/ to validate it.  It says the invalid signature.  The payload looks fine as far as I can tell.

**Comment by georgeismike** [comment]
Support figured it out. 

I was using `result.getAccessToken().getJwtToken()` as my token istead of `result.getIdToken().getJwtToken()` .

**Comment by Zim95** [comment]
Mine does not work even when i use result.getIdToken().getjwtToken(). I got the id token and it seems to work for one api but not for another api gateway. Can anybody help
