### ISSUE TITLE
Need to pass tokens (id, access and refresh) to new CognitoUser instance (server side)

### ISSUE THREAD

**Issue by codepreneur** [aws/amazon-cognito-identity-js#279]
So when I :

```
      let cognitoUser = new CognitoUser({
        Username: email,
        Pool: userPool
      })

      cognitoUser.updateAttributes([
        new CognitoUserAttribute({
          Name: 'profile',
          Value: 'admin'
        })
      ], (err, res) => {
        if (err) return reject(err)

        let response = {
          status: res
        }

        return resolve(response)
      })

```

this fails with 
```
User is not authenticated
```

Now, I cant do `.getSession()` here because I am doing this from server side (from aws lambda function), therefore I need to be able to pass those tokens (which I get from client side localStorage, which I set there once user logins) into `new CognitoUser` instance.

How can I do that ?

@itrestian @simonbuchan

**Comment by hfougere** [comment]
AFAIK you need to recreate the user session with the tokens you got back after a successful login. They get stored in local storage. Technically you should only have to do this once on the server side, then you can save those tokens in the server side session per user. I added this method.  I post the tokens along with the username and pass the data to this function.

function getUserSession(userCredentials) {

    const idToken = new AmazonCognitoIdentity.CognitoIdToken({
        IdToken: userCredentials.tokens.idToken.jwtToken,
    });
    const accessToken = new AmazonCognitoIdentity.CognitoAccessToken({
        AccessToken: userCredentials.tokens.accessToken.jwtToken,
    });
    const refreshToken = new AmazonCognitoIdentity.CognitoRefreshToken({
        RefreshToken: userCredentials.tokens.refreshToken.token,
    });

    let tokenData = {
        IdToken: idToken,
        RefreshToken: refreshToken,
        AccessToken: accessToken
    };

    let session = new AmazonCognitoIdentity.CognitoUserSession(tokenData);

    let userData = {
        Username: userCredentials.username,
        Pool: userPool
    };

    var cognitoUser = new AmazonCognitoIdentity.CognitoUser(userData);
    cognitoUser.signInUserSession = session;

    if (!session.isValid()) {
        return null;
    }

    return cognitoUser;
};

@itrestian please let me know if you think there is a better solution. Thanks.

**Comment by codepreneur** [comment]
@hfougere I solved my problem by doing it like so:

```
    return new Promise((resolve, reject) => {

      let cognitoUser = new CognitoUser({
        Username: email,
        Pool: userPool
      })

      cognitoUser.authenticateUser(new AuthenticationDetails({
        Username: email,
        Password: password
      }), {
        onSuccess: (result) => {
          return cognitoUser.updateAttributes([
            new CognitoUserAttribute({
              Name: 'profile',
              Value: 'admin'
            })
          ], (err, res) => {
            if (err) return reject(err)

            let response = {
              status: res
            }

            return resolve(response)
          })
        },
        onFailure: (err) => {
          return reject(err)
        }
      })

```

and it works! So far, I found only changing attributes, deleting a user or changing password requires authenticated user (in any other case it does not) so only in these cases I have to do these operations inside `onSuccess` of `authenticateUser`

**Comment by codepreneur** [comment]
This works as well:

```
    return new Promise((resolve, reject) => {

      const idToken = new CognitoIdToken({
        IdToken: clientIdToken
      })

      const accessToken = new CognitoAccessToken({
        AccessToken: clientAccessToken
      })

      const refreshToken = new CognitoRefreshToken({
        RefreshToken: clientRefreshToken
      })

      let tokens = {
        IdToken: idToken,
        RefreshToken: refreshToken,
        AccessToken: accessToken
      }

      let session = new CognitoUserSession(tokens)

      let cognitoUser = new CognitoUser({
        Username: email,
        Pool: userPool
      })

      cognitoUser.signInUserSession = session

      if (!session.isValid()) {
        let sessionErr = new Error('Invalid Session!')
        return reject(sessionErr)
      }

      cognitoUser.updateAttributes([
        new CognitoUserAttribute({
          Name: 'profile',
          Value: 'readonly'
        })
      ], (err, res) => {
        if (err) return reject(err)

        let response = {
          status: res
        }

        return resolve(response)
      })

    })

```

So its really just a matter of preference, whether you want to require user for password (kind of like github does) if you want to delete account, changes attributes or change password.

**Comment by itrestian** [comment]
You should be able to recreate the session from tokens the way you are describing. What is the use case you are targeting?
