### ISSUE TITLE
bundle size of Webpack method

### ISSUE THREAD

**Issue by psiho** [aws/amazon-cognito-identity-js#280]
I'm not sure if I'm doing something wriong but Webpack method increases my bundle for about 600KB. Sum of all 5 files used in `<SCRIPT>` method is about 350KB. I have moved many other modules from `<SCRIPT>` to Webpack and none of them increased my bundle size more than sum of their files included via `<SCRIPT>`.

It is a considerable size difference which for me makes Webpack method unusable so for now I'm using script-loader and simply including minimized versions. I'd love to do it properly though.

**Comment by itrestian** [comment]
Basically this is the way you build only the necessary clients for the AWS SDK

http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html

node dist-tools/browser-builder.js 

and specify the services you want to include.

**Comment by itrestian** [comment]
Note also that we have a couple of pull requests that we are in the process of integrating to remove some of the dependencies.

**Comment by psiho** [comment]
Thank you. That builder tool is very useful. I'm sorry I haven't started with that and built my own SDK. Maybe documentation on Cognito Javascript should promote this option too. I focused only on Cognito help and tutorials and completely bypassed main AWS SDK and option to build customized SDK.

**Comment by itrestian** [comment]
No worries. Totally understandable. Glad to be able to help! We do have a dependency on the AWS SDK to make the service requests. Did it help with your bundle size?
