### ISSUE TITLE
I do a signOut(), but the username remains the same.....

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#283]
In the following code I do a sign out, but a call to get the cognito username still returns the username.

I'm having real trouble understanding this.

How can I sign out, and what method can I call, or what property can I inspect, to determine that the user is actually signed out?

And why does user data remain after calling signOut()?

```
this.props.application.user.cognitoUser.signOut()
console.log('this.props.application.user.cognitoUser.username ', this.props.application.user.cognitoUser.username)

```

My user interface displays the username when signed in, and I'd like it to display no username after the user has signed out, but the way this library works makes it hard to work out how to clear away the username on signout.  I there something I am I not understanding?

thanks

**Comment by itrestian** [comment]
SignOut clears the tokens stored in local storage such that if you would use the same CognitoUser object you wouldn't be able to preform any of the calls that require authentication. You would need to authenticate again after.

**Comment by crowdwave** [comment]
Thanks ionut. What is the correct way for my application to determine if the user is signed out?  I need to hide or show the username and indicate to the user that they are signed in or signed out.

thanks

**Comment by itrestian** [comment]
You could check if the signInUserSession is null at that point since it is being made null in the signOut call.

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L1292
