### ISSUE TITLE
I'm puzzled - the cognitoUser session seems to be disappearing..

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#287]
The cognito user seems to be retained in localstorage across page changes, and earlier today it was retaining the cognito user session too.

Now, it appears that the session data is somehow being lost after a page change.

Can anyone suggest what might cause this?

**Comment by itrestian** [comment]
The tokens are stored in local storage and that is not available across different domains, only available on the same domain.

**Comment by itrestian** [comment]
It should be available across different page loads.
