### ISSUE TITLE
Unclear how to resume a session

### ISSUE THREAD

**Issue by seanjb** [aws/amazon-cognito-identity-js#29]
Hi There,
Struggling to find much documentation about this new service. Perhaps someome can help. So after authenticating a user I have a cognitoUser object on the scope with their JWT tokens. I can also see this info is stored in the Local Storage.

If I loose the user object (say the user closes the tab or reloads their page) how do I recreate the authenticated object without making the user sign in again, as I can see the JWT tokens still exist in local storage so they are not lost.

**Comment by lusentis** [comment]
I've written a demo just to play around, you may want to check this file:
https://github.com/plasticpanda/cognito-idp-demo/blob/master/lib/idp.js
The "restoreAuthenticatedUsermethod" method does what you say (restores a
user object from local cached token). I can also correctly handle expiring
sts credentials etc...

**Comment by seanjb** [comment]
Awesome thanks! I will check that out. Would be great to get an example like this referenced in the docs. Good on ya

**Comment by itrestian** [comment]
Hi Sean,

Does example 15 in the readme help with that?

Ionut.
