### ISSUE TITLE
CognitoUser.getAttributeVerificationCode callback execution

### ISSUE THREAD

**Issue by stmarseglia** [aws/amazon-cognito-identity-js#293]
According to Cognito documentation, the method CognitoUser.getAttributeVerificationCode should be called by passing in a callback object containing the "onSuccess" function, but looking at the source code it seems like this function is never invoked:

```javascript
getAttributeVerificationCode(attributeName, callback) {
if (this.signInUserSession == null || !this.signInUserSession.isValid()) {
  return callback.onFailure(new Error('User is not authenticated'));
}

this.client.makeUnauthenticatedRequest('getUserAttributeVerificationCode', {
  AttributeName: attributeName,
  AccessToken: this.signInUserSession.getAccessToken().getJwtToken(),
}, (err, data) => {
  if (err) {
	return callback.onFailure(err);
  }
  return callback.inputVerificationCode(data);
});
return undefined;
}
```

**Comment by itrestian** [comment]
The onSuccess is called when you call verifyAttribute. Basically, you call getAttributeVerificationCode, you get a verification code, inputVerificationCode is called and you call verifyAttribute with the code. After that the onSuccess is called.
