### ISSUE TITLE
Pre-sign up lambda autoConfirmUser

### ISSUE THREAD

**Issue by robertbrower-technologies** [aws/amazon-cognito-identity-js#297]
I am experiencing the same problem as in https://github.com/aws/amazon-cognito-identity-js/issues/161. But it was closed.

I set event.response.autoConfirmUser = false. The response.autoConfirmUser in the logged event is false. My user still get registered. I tried what sarah-pixvana suggested, ie, just not set event.response.autoConfirmUser in case of preconfirmation failure, but that doesn't work. If you set response.failAuthentication to true, you can prevent the user registration process from continuing, but the user gets a no so user friendly error in the Register UI, ie, Unexpected Lambda Output or something along those lines. I need a real solution.

Please reopen.

Thank you.

**Comment by mreddyg** [comment]
If you want to stop a user from registering, the Pre-signup Lambda must return an error. Setting  event.response.autoConfirmUser = false will simply set the user's state to not-confirmed and will allow the user registration to continue.<br>
For example, adding this code in your pre-signup lambda, where it decides to stop a user from registering, will stop the registration and return an exception to the client.<br>
```
    var errorMessage = 'This text will appear in the exception message on the client';
    var error = new Error(errorMessage);
    context.done(error, event);
```
