### ISSUE TITLE
getSession() doesn't connect User Pool to Identity Pool

### ISSUE THREAD

**Issue by PrismaticPolygon** [aws/amazon-cognito-identity-js#298]
According to the documentation (use case 17), calling `getSession()` and then updating `AWS.config.credentials` appropriately should integrate a user pool with an identity pool. This is not the case. While I can see my identityID in LocalStorage, a corresponding entry does not appear on the AWS console. To actually connect the two, I run:
```
let cognitoIdentity = new AWS.CognitoIdentity();
cognitoIdentity.getId({IdentityPoolId: this.IDENTITY_POOL_ID, Logins: logins}, (error, result) => {
//Do stuff here
});
```
where logins is as described in the documentation: 
`logins['cognito-idp.' + this.REGION + '.amazonaws.com/' + this.USER_POOL_ID] = ID_TOKEN`;

However, calling this generates a _new_ IdentityId, leaving me with an incorrect one in the cache controlled by amazon-cognito-identity-js. So my question is this: are the two pools not connected until the credentials are actually used for something? Should I send some DynamoDB request or somesuch? If this is the case, can some utility 'ping' method be provided for this purpose?

**Comment by itrestian** [comment]
This SDK doesn't manage the identity id. It is managed by the main AWS SDK. And you are correct, updating the logins map, needs to be followed by a call to refresh or get to actually retrieve the credentials.
