### ISSUE TITLE
Use case 4 example returns error

### ISSUE THREAD

**Issue by m-schrepel** [aws/amazon-cognito-identity-js#3]
In the minified code, I get `amazon-cognito.js:3541 Uncaught TypeError: c.update is not a function`

When I dig into it and look at C it is a `new sjcl.misc.hmac(prk, sjcl.hash.sha256)` and it does have an update method, but it is on the prototype of a function inside that object.

I'm pretty sure this is the source for where this is going wrong.
[source](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/AuthenticationHelper.js#L169-L178)

**Comment by itrestian** [comment]
Hi Matthew,

From what I see sjcl.misc.hmac does have an update method, however it was missing at some point. Any idea if the library you are using is missing the method?

https://github.com/bitwiseshiftleft/sjcl/commits/master/core/hmac.js

Ionut.

**Comment by m-schrepel** [comment]
@itrestian 
I downloaded the library yesterday from the repo you linked to, so I should be using the same version as you are since the last commit was months ago.

When I dig into the minified source I see that sjcl.misc.hmac has an M constructor and in that constructor's prototype I see an update method. 
[screenshot of C](http://s31.postimg.org/cw3qgkjgb/Screen_Shot_2016_04_22_at_9_09_56_AM.png)

**Comment by m-schrepel** [comment]
@itrestian 
Ok, I redownloaded everything, made sure it was in the right order, and now... this error happens. It is different, but still can't get through the authenticateUser method.

`Uncaught TypeError: Cannot read property 'toBits' of undefined`

```
var authenticationData = {
      Username : '**********',
      Password : '**********',
    };

    var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);

    var poolData = {
      UserPoolId : 'UserPoolId Stuff',
      ClientId : 'clientIdStuff'
    };

    var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);

    var userData = {
        Username : 'username',
        Pool : userPool
    };

    var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('access token + ' + result.getAccessToken().getJwtToken());
        },

        onFailure: function(err) {
            alert(err);
        },

    });
```

**Comment by itrestian** [comment]
Hi Matthew,

In your case, I think the error happens because you haven't included the bytes codec in sjcl. By default, sjcl doesn't come with the bytes codec so you need to configure and make it with that particular option (this is mentioned in the README.md file).

Ionut.

**Comment by m-schrepel** [comment]
@itrestian 
Thank you so much. That solved the issue. For anyone looking at this in the future:

### 1. Clone the SJCL Repo

### 2. in the root run `./configure --with-codecBytes`

### 3. `make`

### 4. `make sjcl.js tidy`

### 5. replace your old library with this newly compiled library

### 6. Log in!

**Comment by EmmanuelTsouris** [comment]
@itrestian this looks like the issue I'm running into also. I'll run through the steps above.
