### ISSUE TITLE
Cannot get Authentication to work

### ISSUE THREAD

**Issue by SteveALee** [aws/amazon-cognito-identity-js#30]
My code is basically your examples from the README. and I can create a user but the authentication step always returns `Incorrect username or password`. I'm convinced the user name and pass word are identical in each step ('fred' and 'password')

Any help you can offer would be greatly appreciate as I'm going mad. My code is [here](https://github.com/OpenDirective/brian/blob/master/src/js/drivers/providers/AWS/authAWSCognitoUserPool.js)

If I try to authenticate before creating the user I get an error that the user/password can't be found. SO the basic access is working.

I can't find a way to list the user pool settings the AWS so here's the pool details from the web site

```
    Pool Id us-east-1_A2HeABQfl
    Pool ARN arn:aws:cognito-idp:us-east-1:063024541135:userpool/us-east-1_A2HeABQfl
    Number of users 1
    Required attributes none
    Alias attributes none
    Custom attributes Choose custom attributes... None
    Minimum password length 6
    Password policy no requirements
    MFA Enable MFA...
    Verifications none
    Apps Brian
    Triggers Add triggers... None
```

My Identity Pool region is in Ireland and I notice contains no identities, I assume that happens later? I've certainly seen no code to create them after creating the pool user.

A wild stab in the dark is it is perhaps something to do with the fact I have disabled all Verifications? This is a requirement as the users will be elderly people in a care home settings and will not have email or SMS.

**Comment by lusentis** [comment]
In my experiments, I can login only with users who are verified. You can manually verify user from the console or via api; I suppose you can setup an hook and automatically verify via Lambda upon sign up. 

Simone

**Comment by itrestian** [comment]
Hi Steve,

In the case you mention where your users have no email or SMS, you need to write a lambda hook that will auto confirm them. You cannot authenticate the users because they are unconfirmed as of yet. The error is just a general error trying to prevent an information leak.

Ionut.

**Comment by SteveALee** [comment]
@lusentis @itrestian yes, If I manually confirm them the the login works.

I did wonder if the error was deliberately obscure, Not much help when you are developing though. I feel like I'm missing documentation on the important details.

I was planning to leave Lambda for the next iteration, especially as this was all supposed to be released 2 weeks ago :( Are there any good examples of what I need to do? Looks like I have another learning curve to get up quickly. From the little I know I think I used node and the JS api? I assume it's not possible form the browser.

Thanks again.

**Comment by SteveALee** [comment]
I see there are triggers for the user pool but none of then are right for this purpose. Though at a pinh 'pre signup' might just work. I'll give it a go

**Comment by SteveALee** [comment]
Looks like the answer I want is provided in the docs - https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html?icmpid=docs_cognito_console

**Comment by SteveALee** [comment]
What are the json blocks provided after each example lambda function, There's nowhere in the web UI to put them, and naturally I get syntax errors if put in after the function in the code editor

Do we need to put them someplace? are is used somewhere like the CLI to define the function config and not needed if setup via the pools triggers feature

Interestingly they seem to include the validation data we can add in the test edit box. They also seem incomplete as have .... in them. That makes me think they are just examples of something not required to setup the function

**Comment by itrestian** [comment]
Hi Steve,

Basically the json after each example lambda function is input data that can be used when executing the lambda function. As you said, you don't need them to setup the function in the first place.

Ionut.
