### ISSUE TITLE
cognitoUser.authenticateUser doesn't work after HTML5 canvas loaded, only before

### ISSUE THREAD

**Issue by jdilkes** [aws/amazon-cognito-identity-js#300]
cognito authentication works before I load up the canvas on this page:
http://lacunapress.s3-website-eu-west-1.amazonaws.com/

but once the canvas has been loaded, the authentication won't work until I refresh the window again. I have narrowed the problem down to the **cognitoUser.authenticateUser** command.

Any ideas why this issue is happening?

Thanks.

**Comment by itrestian** [comment]
What is the error you are getting? As long as the libraries are loaded in the correct order and the user pool and user objects are populated, don't see what could go wrong.

**Comment by jdilkes** [comment]
The libraries are being loaded like this:

    <script src="./js/jsbn.js"></script>
    <script src="./js/jsbn2.js"></script>
    
    <script src="./js/sjcl.js"></script>
    
    <script src="./js/aws-cognito-sdk.min.js"></script>
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.9.0.min.js"></script>
    
    <script src="./js/amazon-cognito-identity.min.js"></script>

The login process works unless the canvas has been loaded first.

**Comment by itrestian** [comment]
What exactly is the exception you are getting?

**Comment by jdilkes** [comment]
It is not throwing an error that I have found.

In browser console it shows "TypeError: t is not a function" at the point this happens

**Comment by jdilkes** [comment]
from sjcl.js

**Comment by jdilkes** [comment]
But the same function works unless the canvas has been loaded. Here are more details from the browser console:

sjcl.cipher.aes.prototype.encrypt http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/sjcl.js:4:55
	z http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/sjcl.js:48:467
	sjcl.prng.prototype.randomWords http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/sjcl.js:40:197
	h</<.value http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/amazon-cognito-identity.min.js:17:3249
	e http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/amazon-cognito-identity.min.js:17:2898
	E</<.value http://lacunapress.s3-website-eu-west-1.amazonaws.com/js/amazon-cognito-identity.min.js:17:10653
	authenticateUser https://code.jquery.com/jquery-1.11.0.min.js%20line%202%20%3E%20eval:503:5
	onclick http://lacunapress.s3-website-eu-west-1.amazonaws.com/:1:1

**Comment by itrestian** [comment]
Maybe try to pull the latest version of the library. That doesn't use SJCL anymore (the dependency has been removed).

**Comment by jdilkes** [comment]
Thanks, it is working now.
