### ISSUE TITLE
Non-minified export

### ISSUE THREAD

**Issue by mitranim** [aws/amazon-cognito-identity-js#303]
Currently, the default export is minified, complicating development. Users importing your library from NPM are likely to have a build system with its own minifier. You should at least provide a non-minified version, and ideally make it default.

**Comment by jogold** [comment]
https://github.com/aws/amazon-cognito-identity-js/pull/294

**Comment by itrestian** [comment]
Merged in the pull request. Closing this in favor of 

https://github.com/aws/amazon-cognito-identity-js/issues/354
