### ISSUE TITLE
API Documentation? Promise?

### ISSUE THREAD

**Issue by paolavness** [aws/amazon-cognito-identity-js#305]
Hi there,
Where can I find API documentation for this?
Does this API follow [promises?]
Could not find this anywhere in the READ.ME, unless I missed it. Would be great to have it somewhere accessibly easy to find.
Thank you!

**Comment by mreddyg** [comment]
You can find the developer documentation for JS SDK [here](http://docs.aws.amazon.com/cognito/latest/developerguide/setting-up-the-javascript-sdk.html).  The JS SDK API does not follow promises.

Also, here is the reference for the Cognito APIs (ForgotPassword for example):

http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html

**Comment by paolavness** [comment]
Hi there, thanks for the reply!
The link you gave is more like a help file. I'm looking for proper docs on each function, method, returns, types, etc.
If Promises are not used, what is?
Thanks again.

**Comment by matikucharski** [comment]
> If Promises are not used, what is?

Just callbacks

**Comment by paolavness** [comment]
Hi, you've closed this but no response on thorough documentation of the **amazon-cognito-identity-js.** I am specifically looking for something like the AWS SDK documentation: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/_index.html

Does it not exist? If not, I'd like to make a request for this.

Thank you.

**Comment by itrestian** [comment]
I will mention this request internally (providing SDK-style documentation).
