### ISSUE TITLE
User invite

### ISSUE THREAD

**Issue by diogocravo** [aws/amazon-cognito-identity-js#308]
Is there any API where I can authenticate as a user and invite another user to join the system? Something like AdminCreateUser, but for any user, not using developer credentials?

**Comment by itrestian** [comment]
This is not possible at this point without using developer credentials since sign up which doesn't require developer credentials requires a password. I will mention this as a feature request within the team.

**Comment by sehmaschine** [comment]
Same issue here. I could use a temporary password with sign up, if I'm able to also set `FORCE_CHANGE_PASSWORD`. Is that possible?
