### ISSUE TITLE
ENOTFOUND

### ISSUE THREAD

**Issue by esteban-uo** [aws/amazon-cognito-identity-js#309]
Hi dear team,

Somehow whenever the package makes a request I get:

```js
{
"message": {
"message": "Inaccessible host: `cognito-idp.eu-central-1.amazonaws.com'. This service may not be available in the `eu-central-1' region.",
"code": "UnknownEndpoint",
"region": "eu-central-1",
"hostname": "cognito-idp.eu-central-1.amazonaws.com",
"retryable": true,
"originalError": {
"message": "getaddrinfo ENOTFOUND cognito-idp.eu-central-1.amazonaws.com cognito-idp.eu-central-1.amazonaws.com:443",
"code": "NetworkingError",
"errno": "ENOTFOUND",
"syscall": "getaddrinfo",
"hostname": "cognito-idp.eu-central-1.amazonaws.com",
"host": "cognito-idp.eu-central-1.amazonaws.com",
"port": 443,
"region": "eu-central-1",
"retryable": true,
"time": "2017-02-23T19:49:31.681Z"
},
"time": "2017-02-23T19:49:31.682Z"
},
"answer": null
}
```

For example with `CognitoUser::authenticateUser`

Any idea what could be wrong? looks like the hostname would be down... thanks!

**Comment by behrooziAWS** [comment]
Can you hit: https://cognito-idp.eu-central-1.amazonaws.com/sping from your host?

**Comment by esteban-uo** [comment]
Actually now, I can... I thought it might be underlying connection issues so I used different networks and so and wasn't working... then I just did what a good technician has to do, reboot the computer and worked... 😭 so sorry, closing issue.
