### ISSUE TITLE
Dependency aws-sdk/clients/cognitoidentityserviceprovider

### ISSUE THREAD

**Issue by jellevlassenbroeck** [aws/amazon-cognito-identity-js#314]
I have two projects to test authentication only with Cognito (Visual Studio 2015), no signup, no federated identities, just using user pools. I would prefer to only use the 'dist' versions of amazon-cognito-identity-js and aws-sdk (if required).

In an initial test project, using Javascript, I could get everything running by including the separate javascript files from the 'dist' folder here (and the cryptographic files required on top of that).

When integrating everything in our actual Typescript project, I get an error when running the code that aws-sdk/clients/cognitoidentityserviceprovider can not be found by require. I don't see this dependency listed on the homepage here. Also, I can't just include it, since it introduces other dependencies (I assume from Node.js). 

Am I correct that the distribution of this library is somehow broken, and I need to use the complete Javascript SDK and package things myself? Also, any ideas on why I only get the problem when using Typescript?

**Comment by orgreeno** [comment]
I'm not using Typescript, but have you tried a single build specific to your project using the builder tool?
https://sdk.amazonaws.com/builder/js/

**Comment by jellevlassenbroeck** [comment]
Thanks, I'll give that a try. For now I wrapped all Cognito functionality in functions in Javascript and added typing (.d.ts) for these wrapper functions, that does solve the problem. So it does seem to be related to the use of Typescript. I'll leave this open for a bit longer should anyone else have input on the issue.

**Comment by itrestian** [comment]
The main aws sdk has added typescript support. Just wondering if this was solved by that release?
