### ISSUE TITLE
API Gateway and Cognito User Pool Authorizer

### ISSUE THREAD

**Issue by xelita** [aws/amazon-cognito-identity-js#317]
Hello Guys. 

First, thanks for the job you achieved in that library.

I just defined a Cognito User Pool Authorizer to secure all calls to my API Gateway endpoints but I'm not able to test it using the Identity token and to be honest I'm a little bit lost with the SRP protocol.

Indeed, I do not know what to put in the Identity Token input to test my API (see attachment). 

In a node program I was able to authenticate a test user to Cognito using the authenticateUser API but I do not know what to do with the AuthResult as it contains accessToken, refreshToken and idToken information.

Thank you in advance for your help. 

<img width="1022" alt="capture d ecran 2017-03-05 a 15 58 25" src="https://cloud.githubusercontent.com/assets/1111273/23588365/f4f2d33e-01bc-11e7-8abc-aa17aec4fb03.png">

**Comment by jbailey2010** [comment]
Hi,

So you have signed in successfully and are just trying to figure out what to use to test your API? The idToken in the AuthResult is the identity token you were looking for to use.

**Comment by xelita** [comment]
Hello @jbailey2010: 
You are right. I just want to test the token I obtain in the AuthResult of my nodeJS authentication code.
To achieve this, I copy the value set for the jwtToken attribute (from AuthResult) and paste it in the test field.

This is what my token looks like:
`
  idToken:
   e {
     jwtToken: 'eyJraWQiOiJrdzVkTkNuc1FcL3N1Yk9pRU5XTHVJdzY1MWpzQkxxOWZIVmhCVkJTeTZzND0iLCJhbGciOi
JSUzI1NiJ9.eyJzdWIiOiJhNjE4NWYwOS1kNzUyLTRiNTMtYTA4Ni0yNjNlYmYyYmZlZmEiLCJhdWQiOiI3ZGk0OWMwM2NyczB
mdTQyNGZpN3ZiNzhoNSIsImNvZ25pdG86Z3JvdXBzIjpbInJlYWRlciJdLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInRva2VuX
3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNDg4ODc1NDEwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmF
tYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9XNURvMUc5aUoiLCJjb2duaXRvOnVzZXJuYW1lIjoiYmVuamFtaW4uc2VtcGVyZUBve
C5pbyIsImV4cCI6MTQ4ODg3OTAxMCwiaWF0IjoxNDg4ODc1NDEwLCJlbWFpbCI6ImJlbmphbWluLnNlbXBlcmVAb3guaW8ifQ.
P_-OTT_H2SlLN6QLrMVgyhLDhKbYjhnyDWXfQz8vZRvSidr_odch7Yj9kkHd36JjtRT2nHiUCoyBjudN8qSpIG0tSSq_oKUmlU
iQhuv9ZnSNc78BmuHNCMPc-YBUTlIFABrGItdt7Zx6evDXVsdiF78xiX5EjWno0lFTI-JjRK0NCFRWMoDH5CJgkz-WtE0I74Pc
NMYQ8Y1T0EAdRi8ucCT3p1Iyo9eSwNBqgX53cg51-biWO9gZUKGoSijAB-qvUQxIfCIxvv4C9xaIsKqhM2lC3phIFtU5BQlVUN
EW8WayAfSS4aWqN5iIva9N_A12PPGAcB2YRs-vUsR9hrPefA' }
`

So I copy the following value:
`
eyJraWQiOiJrdzVkTkNuc1FcL3N1Yk9pRU5XTHVJdzY1MWpzQkxxOWZIVmhCVkJTeTZzND0iLCJhbGciOi
JSUzI1NiJ9.eyJzdWIiOiJhNjE4NWYwOS1kNzUyLTRiNTMtYTA4Ni0yNjNlYmYyYmZlZmEiLCJhdWQiOiI3ZGk0OWMwM2NyczB
mdTQyNGZpN3ZiNzhoNSIsImNvZ25pdG86Z3JvdXBzIjpbInJlYWRlciJdLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInRva2VuX
3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNDg4ODc1NDEwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmF
tYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9XNURvMUc5aUoiLCJjb2duaXRvOnVzZXJuYW1lIjoiYmVuamFtaW4uc2VtcGVyZUBve
C5pbyIsImV4cCI6MTQ4ODg3OTAxMCwiaWF0IjoxNDg4ODc1NDEwLCJlbWFpbCI6ImJlbmphbWluLnNlbXBlcmVAb3guaW8ifQ.
P_-OTT_H2SlLN6QLrMVgyhLDhKbYjhnyDWXfQz8vZRvSidr_odch7Yj9kkHd36JjtRT2nHiUCoyBjudN8qSpIG0tSSq_oKUmlU
iQhuv9ZnSNc78BmuHNCMPc-YBUTlIFABrGItdt7Zx6evDXVsdiF78xiX5EjWno0lFTI-JjRK0NCFRWMoDH5CJgkz-WtE0I74Pc
NMYQ8Y1T0EAdRi8ucCT3p1Iyo9eSwNBqgX53cg51-biWO9gZUKGoSijAB-qvUQxIfCIxvv4C9xaIsKqhM2lC3phIFtU5BQlVUN
EW8WayAfSS4aWqN5iIva9N_A12PPGAcB2YRs-vUsR9hrPefA
`

Thank you for your help.

**Comment by xelita** [comment]
I noticed that my generated JWT identity token had some special formatting characters in it that were due to my IDE. When fixed, the identity token was correctly recognized. My bad!
Thank you again for your help

**Comment by jbailey2010** [comment]
Great, happy to hear it's resolved!

**Comment by lehtiton** [comment]
Hi @xelita, I have exactly the same issue. Could you describe a bit more of how did you copy the identity token that you made successful test with? I used the aws cognito js sdk sample code and made it successfully to print the idToken (like you above), but could not figure out how to copy paste it from the browser (chrome developer tools console login or network tab response box) to aws api gateway test authorizer.

**Comment by xelita** [comment]
Hi @lehtiton: The issue was resolved just by generating a file containing the token with NodeJS. The generated file has "wrap text automatically" option disabled.
Hope it can help!
