### ISSUE TITLE
Is it possible to invoke a Lambda function with a cognito userpool identity?

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#318]
I want to invoke a Lambda function using the Javascript API.

I want it to be invoked with the cognito userpool credentials of the user who is authenticated on the browser.

The objective is that the Lambda function will have the same level of access to S3 as the user from the cognito userpool.

How can I do this?

thanks

**Comment by kushwahavinay** [comment]
This was answered here: http://stackoverflow.com/questions/42619395/is-it-possible-to-invoke-a-lambda-function-with-a-cognito-userpool-identity/42620898#42620898
Pointing to link to have a single thread.
