### ISSUE TITLE
Multi tenant and Cognito user pool

### ISSUE THREAD

**Issue by outmarch** [aws/amazon-cognito-identity-js#319]
I am planning to use Cognito user pool, federated identities with  APIG  and lambda. 
In my case I am planning to use this for multi-tenant SaaS application and planning to use different Cognito user pool per tenant.  USER_POOL_ID, CLIENT_ID, IDENTITY_POOL_ID constants are used in cognito SDK to make calls like authenticate users. 

My question is, in my case as I will have different USER_POOL_IDs per tenant how do I handle this in client app? dont want to update client app as we add new tenants. If I make a API service wrapper for cognito then I need to send password over wire. What is the best practice to handle this  use case?

**Comment by itrestian** [comment]
The client abstraction refers to an app so we recommend one client id per application. However, it seems that the groups feature in User Pools might fulfil your use case.

https://aws.amazon.com/blogs/aws/new-amazon-cognito-groups-and-fine-grained-role-based-access-control-2/

**Comment by itrestian** [comment]
Hope this answers it. Closing this, feel free to reopen if necessary.

**Comment by outmarch** [comment]
@itrestian  looks like you can create only 25 groups in a user pool also I would like to have different password policies for different tenants so groups and one user pool might not be good idea of multi tenant solution. 
What do you suggest then? how other customers have implemented similar use case ? what is the best practice for Cognito user pool and multi-tenancy ..

**Comment by itrestian** [comment]
You can create a limited number of user pools as well. Although the limit you mention is a soft limit that can be increased depending on the use case.

In general we use the user pool/client abstraction to separate different apps and groups to separate users of said apps. I can mention the password policies requirement within the team as a feature request.

**Comment by outmarch** [comment]
@itrestian  
I was going to through below article and it kind of suggests that to use different user pool for different  tenant so that you have more flexibility on password policies triggers etc. 

https://aws.amazon.com/blogs/apn/managing-saas-users-with-amazon-cognito/

so i am now confused on how to configure cogito pool for multiple tenants :(

**Comment by itrestian** [comment]
You can definitely go that route, however the heavy lifting is on the app side for managing the different user pools for different tenants. The blog post I believe claims that the benefits come from a centralized user management (In Amazon Cognito, each user pool represents a grouping of users that are owned by that pool. This ability to have many user pools under a single AWS account provides SaaS developers with the option of having separate user management experiences for each tenant.)

As I mentioned, our SDKs are meant to work with the client/app abstraction. Groups is a newer feature that targets your use case and works within this abstraction.

**Comment by outmarch** [comment]
@itrestian  thanks for the help .. password policies at user group level is it on your roadmap or currently actively working on it? based on timeline we might go with single user pool or multiple user pools ..

**Comment by tanzeelrana** [comment]
Hi @itrestian  

Any updates on supporting password polices at user group level ? 

Cheers

**Comment by BenjaminWatts** [comment]
Any idea how to create groups of users for each household or business that signs up for an app! So that different users within that entity can share a subscription and data? As I understand there is a pretty finite limit on the groups (200).
