### ISSUE TITLE
Problem with JavaScripts

### ISSUE THREAD

**Issue by suibinz** [aws/amazon-cognito-identity-js#321]
I tried to wrap the js in a simple html, but nothing happened - no error loading the script, but page showed nothing. When trying to looked into the scripts themselves, the format is a long string. Is there a mistake in those scripts?

my html:
<!doctype html>
<html lang=en>
<head>
 	<script src="/Users/suibin/Projects/aws/myAwsCognito/amazon-cognito-identity-js/dist/aws-cognito-sdk.min.js"></script>
	<script src="/Users/suibin/Projects/aws/myAwsCognito/amazon-cognito-identity-js/dist/amazon-cognito-identity.min.js"></script>
	<title>ResultrSignUp</title>
</head>

</html>

**Comment by itrestian** [comment]
Not sure I understand the question. Yes you would have to include the files but you would have to write JavaScript code such as in the use cases in the Readme to access the functionality.

**Comment by suibinz** [comment]
I mean, if I can understand the javascript more I can write the html page (more than just embedded) the script tag. But the /dist files are in such a "long-string" format that I can't really (or hard) to read into it.

Are those .js meant to be like that?

**Comment by itrestian** [comment]
Yes.

**Comment by suibinz** [comment]
Ahh, understand now.
