### ISSUE TITLE
Disabling email verification on updating user email using adminUpdateUserAttributes

### ISSUE THREAD

**Issue by iflp** [aws/amazon-cognito-identity-js#322]
Hey all, I have an edge case where if an admin updates the `email` user attribute (which is also an alias) using`adminUpdateUserAttributes` , the user's status will be CONFIRMED, email is changed to the new email, but email_verified is set to false.

If the user is not logged in at that point, he or she will be unable to login to verify the new email. Is there a way to set email_verified to true or override the verification?

I am aware of `event.response.autoVerifyEmail = true` but that only works in the pre-sign up trigger. Wouldn't it make more sense conceptually to allow it in the custom message trigger so we can have that option for the different trigger sources `CustomMessage_SignUp` and `CustomMessage_VerifyUserAttribute`?

**Comment by hithisisneel** [comment]
In this case, when you call adminUpdateUserAttributes to set the new email, I guess you should also be able to set the email_verified = true. That doesn't work?

**Comment by prem911** [comment]
email_verified and phone_verified can be set using the admin API only
during user creation once. The update user API will not let you do that.

**Comment by iflp** [comment]
@hithisisneel That works, thanks! I failed to consider the possibility that `email_verified` is an attribute.

**Comment by caldwecr** [comment]
I can confirm that this is the correct answer. You are (now) able to specify the email_verified attribute in the adminUpdateUserAttributes call.

I would also point out that this results in post-confirmation lambda from not being executed, so if you have downstream logic from there, you'll need to trigger it manually.
