### ISSUE TITLE
When would forgotPassword / onSuccess be called?

### ISSUE THREAD

**Issue by cgodkin** [aws/amazon-cognito-identity-js#324]
Sorry if this is obvious or has been answered elsewhere, but I couldn't find it.

The CognitoUser forgotPassword() function has an onSuccess callback but I can't imagine when it would be used.  I understand inputVerificationCode or onFailure would be called of course, but under what circumstances would onSuccess be called?

The underlying function (documented [here](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html)) doesn't seem to allow for it as far as I can tell either.

Thanks a lot!

**Comment by disciple-dev** [comment]
Not all applications will need data back, but they still might need to know the request was successful; this is where `onSuccess` is handy; if it has been invoked, the request was a success.

If you want more information, as in `Hey, we sent a verification by ${type} to ${recipient}`, that information would only be available through `inputVerificationCode`, I think.

**Comment by cgodkin** [comment]
Okay, I see.  Looking again I see that if you leave off inputVerificationCode then you'll get onSuccess.  But you'll never get onSuccess if you have inputVerificationCode (and it's a function).

Thanks very much.

**Comment by disciple-dev** [comment]
No worries.

The documentation seems to be inconsistent with forgotPassword, as I noted in #323.
