### ISSUE TITLE
Client side - attaching token to the request. 

### ISSUE THREAD

**Issue by BigglesATlarge** [aws/amazon-cognito-identity-js#326]
Hi there, 

I have created the authentication on the client side with AWS Cognito User Pool and Cognito Federation. Upon log in I get the 3 tokens in localStorage plus LastAuthUser. I know that I can use the token to attach to the request header when POST/GET using Ajax, so the NodeJS at the backend can verify the request and respond with the appropriate content, i.e. using Passport. 

But if the user just types in the URL to my app in the browser, or refreshes the page while being logging in, the request will go out and I will have no way to attach the token to the request. In that case Node will reply with the content for the non-authenticated user even though the user is logged in. 

Am I missing something obvious here? Can I add token to such a request?

**Comment by gitjeff05** [comment]
You need some sort of  pre-hook in your route handler that essentially does:

```
// gets current user from local storage
let cognitoUser = userPool.getCurrentUser();

// get current session from storage or by getting a new refresh token from the server
cognitoUser.getSession((err, session) => { 
    if (!session) {
        throw(err); // have your route handler toss user back to login route
    }
    // now you'll have your session here
});
```

I don't know what framework you're using if any but most should have this capability. You can't send your other request until you have the session.

**Comment by BigglesATlarge** [comment]
I am not using any framework at the moment, although considering using Vue.js in the near future. 

Correct me if I am wrong, just trying to get my head around this. Is the fact of having a session === valid tokens? It would have to be attached to window.onload event on every page then? Also, in that case I wouldn't validate the token on the client side, so I would have to send it back to the server, right? 

Thanks

**Comment by itrestian** [comment]
Yes, that is correct. having valid tokens means having a session. You can validate the token on the client side as well, they're basically jwt tokens that have an expiration attribute.

**Comment by BigglesATlarge** [comment]
Ok, thanks Ionut. You mean I would have to follow steps 1-7 for Using ID Tokens and Access Tokens in your Web APIs in here: http://amzn.to/2lWvHy0

**Comment by BigglesATlarge** [comment]
Btw, is JSON Web Token (JWT) Set located at https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json  publicly available?

**Comment by prem911** [comment]
Yes these are.
Btw, this brings up a question. In my client javascript, we have to use the
region and UserPoolId to make the API calls. Is it a security issue if the
userPoolId is known to all? ( meaning anyone who can look into the
javascript? )

**Comment by itrestian** [comment]
jwks are public keys so they are publicly available. user pool id or client id are not secret either. only the client secret is a secret but it should be used in a secure backend or with platforms that can manage secrets, not in javascript.
