### ISSUE TITLE
Token validation through middleware

### ISSUE THREAD

**Issue by mailtobash** [aws/amazon-cognito-identity-js#330]
Hello guys,
I have an app where I have a flow like Browser -> Middleware (express) -> Backend
In my middleware I am migrating user from another user store into Cognito userpool.

So I need to find a way such that I can issue login token to browser and then validate the incoming token on each request to my middleware.
Is there an SDK provided Javascript method I can call to validate the incoming token?

Thanks!

**Comment by itrestian** [comment]
You can pretty much do what is mentioned here:

https://forums.aws.amazon.com/message.jspa?messageID=772768#772768

**Comment by mailtobash** [comment]
Thank you @itrestian ,
I did as you mentioned, the link [ here](https://aws.amazon.com/blogs/mobile/integrating-amazon-cognito-user-pools-with-api-gateway/) does exactly what I was looking for - I could easily port it to express.

**Comment by arturojain** [comment]
@mailtobash did you create the middleware and published it somewhere?

**Comment by mailtobash** [comment]
Hey @arturojain ,
Sorry was busy in a few other things.
Here is a [gist](https://gist.github.com/mailtobash/768c31e0aa0a956c3b10899e1b94a07a) for the way I implemented it.
