### ISSUE TITLE
'undefined' is not a constructor (evaluating 'new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authData)) on Safari

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#331]
Hi,
We followed the steps provided in below URL(Usecase 4),

https://github.com/aws/amazon-cognito-identity-js

Everything works fine in Chrome, but not in Safari. It throws "undefined is not a constructor."

Bower.json entries,
    "aws-sdk-js": "~2.28.0",
    "amazon-cognito-identity-js":"~1.16.0",
    "jsbn":"~1.3.0"

Regards

**Comment by itrestian** [comment]
You don't need to include jsbn with version 1.16 anymore. What particular object ends up as undefined?
