### ISSUE TITLE
Can I get "sub" id in JS SDK?

### ISSUE THREAD

**Issue by Biggles-at-large21** [aws/amazon-cognito-identity-js#332]
Hello, 

is it possile to get {cognito-identity.amazonaws.com:sub} of Cognito auth user from the browser using SDK? 
I want to use it within access policy for accessing the files within the bucket (multiple users store files in the same bucket). 

Initially I wanted to use the "username" as a policy variable, but it doesnt seem to be possible. Second try is to use sub_id, but I am not sure if Cognito ID from here  http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#getId-property  is the same as here http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_examples.html#iam-policy-example-cognito 

Thanks 
Michael

**Comment by mcleary** [comment]
Yes you can.
Check the function [CognitoUser.getUserAttributes()](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L728)

**Comment by itrestian** [comment]
The sub should also be available in the id token. It is a JWT token that can be decoded to get to the attributes. 
An example of how to do that is retrieving the exp here

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoIdToken.js#L41
