### ISSUE TITLE
BigInterger causing the browser tab freeze a while

### ISSUE THREAD

**Issue by twxia** [aws/amazon-cognito-identity-js#333]
Hi there ~

I use `Use case 4` in my `signin` function and used in the React component.
When `cognitoUser.authenticateUser` is called, the CPU gets to 100% and the tab freeze (you can see below link 500ms to 4000ms).

https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=https://www.dropbox.com/s/sphwoju68voo0n7/Profile-20170319T232833.json?dl=0

I just noticed that the bigInterger.js cause the problem, but don't know how to solve it.

My enviroment: 
Ubuntu 16.04
Chrome v57.0.2987.98 (64 bit)

**Comment by itrestian** [comment]
Can you try version 1.15?

**Comment by itrestian** [comment]
Of this library.

**Comment by twxia** [comment]
@itrestian Thanks for the quick reply.  :smile: 
Use v1.15 works like a charm, It seems same as the issue: https://github.com/aws/amazon-cognito-identity-js/issues/315

**Comment by itrestian** [comment]
Yes, closing this as a duplicate.
