### ISSUE TITLE
Importing existing users to Cognito

### ISSUE THREAD

**Issue by bhaminisurya** [aws/amazon-cognito-identity-js#334]
I have my existing users  stored in RDS and i want them to be moved to cognito. When i import users to console, i see that users have to reset password , how do i skip that and import my existing users to cognito without resetting password.

Thanks in advance.

**Comment by itrestian** [comment]
When you use the user import feature, they will require a password reset. There is no current way to go around that at this point.

**Comment by bhaminisurya** [comment]
Thank you for your response. Now after importing users, unless I click reset password manually they are not receiving it. Can you plz let me know if there is any automated way as I can't manually reset thousands of user's passwords. Do we have any inbuilt ApIs.

**Comment by itrestian** [comment]
Basically when the users login into the system after they have imported, they get a reset required exception which you can code around so that you call reset password for the given user.

**Comment by bhaminisurya** [comment]
Thanks much.

**Comment by byjoh** [comment]
@itrestian would it not be possible to use the CognitoUserPool.signUp method to import users with their existing passwords and use a PreSignup lambda to autoconfirm them?
