### ISSUE TITLE
Update username

### ISSUE THREAD

**Issue by sehmaschine** [aws/amazon-cognito-identity-js#337]
I'm probably missing something, but I'm currently not able to let an authenticated user update her username (which equals email in my case). I'm able to update email though (which is the only required field, no alias).

I've done quite a bit of research on this topic but I'm not able to find questions (or answers or code examples). So I assume there's something wrong with my assumption about being able to update a username. That said, why shouldn't it be possible?

**Comment by prem911** [comment]
AFAIK, username is set once and cannot be modified later.
We can change the email, phone number, etc

**Comment by jeffski** [comment]
Can you use the 'preferred username' attribute and set this as an alias?

**Comment by sehmaschine** [comment]
@jeffski Thanks, that should solve it. Just for reference, the behavior is describe here: http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-usernames
