### ISSUE TITLE
how to verify if the authenticated user is disabled or not?

### ISSUE THREAD

**Issue by natanielkdias** [aws/amazon-cognito-identity-js#339]
Hi,

Can I verify if the authenticate user is disabled?

**Comment by anilreddykatta** [comment]
@natanielkd Do you mean user is able to log in even when he is `disabled`?

**Comment by natanielkdias** [comment]
Hi,
@anilreddykatta, not exactly, I want to know if I'm able to know the user status (disabled or enabled) when it is logged. Can I?

**Comment by chetanme** [comment]
If the user is logged in, you can assume the user it is Enabled. Disabled users will never be allowed to log in in the first place.

**Comment by natanielkdias** [comment]
Oh, okay @chetanme, thank you!
