### ISSUE TITLE
react native authentication performance issues

### ISSUE THREAD

**Issue by jmparsons** [aws/amazon-cognito-identity-js#340]
I've manually imported and connected the src files here to my project changing the sdk to point to the new `react-native` branch of aws-sdk-js https://github.com/aws/aws-sdk-js/tree/react-native.

I have everything working, login, verification codes, registration. It runs great in my simulator, but once I run it on my device the app goes to using 100% CPU usage and has 10-20 second lag responses for authentication.

I've read through the issues #209 #69  and it seems to be correlated with the BigInteger library or not using the correct WebView - in this case I'm not using a webview, just a react native view. Are there any possible workarounds besides going with a WebView?

**Comment by timCF** [comment]
have the same issue on ios, but on android it works more strange
1) if remote js debug is on - it works fast and nice, I can sign in
2) if remote js debug is off - it freezes for 30-40 sec and after that shows auth error message ( wrong credentials )

**Comment by itrestian** [comment]
Thank you for the contribution! Most probably this will greatly help other developers.

**Comment by jmparsons** [comment]
@itrestian Yep no prob! I can finally close this issue out. I tried to keep the code as close to the source here, so it could be updated easily in the future. 

@timCF I'll have android in shortly. I'm working on a temp computer and have to re-download studio to test on. Here's a link to the project https://github.com/AirLabsTeam/react-native-aws-cognito-js.

**Comment by timCF** [comment]
@jmparsons great! Thx U!
