### ISSUE TITLE
authenticating users based on username

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#342]
i have created a user pool with preferred_username as only Required attributes , but i am also passing email id so that i could reset user password later , but when i try to register two users with same email address but with different preferred_username i am  getting an error that user already exists , any way that i authenticate uniqueness based only on username instead of email id and should have an option to reset password.

Thanks

**Comment by anilreddykatta** [comment]
can you provide masked out screen shot of you configurations? and also provide an example?

**Comment by itrestian** [comment]
Is the email used as an alias?

**Comment by abhishekpalavancha** [comment]
Yes the problem is solved i was using email as alias now i just use username as required and no email in required or alias it works for me
