### ISSUE TITLE
doc change to use case 17 to make things more clear

### ISSUE THREAD

**Issue by davidholiday** [aws/amazon-cognito-identity-js#344]
I was having a similar issue as the person who created issue #162 - the fix posted there helped a lot. It would've saved me a lot of time had the answer posted there been in the documentation. I know I'm not the first person to pull out certain variables into a config file and reference them that way.

**Comment by itrestian** [comment]
I believe we already had a pull request that updated the documentation in the issue you mentioned. What would make the documentation clearer?

**Comment by davidholiday** [comment]
in the README, for use case 17, I think you need to state explicitly what the respondent to #162 wrote -- that you can't put a variable inside the Logins block because it won't get resolved.

**Comment by itrestian** [comment]
Feel free to submit a pull request to address this.

**Comment by itrestian** [comment]
Closing this. Thanks!
