### ISSUE TITLE
Cognito change email scenarios

### ISSUE THREAD

**Issue by mailtobash** [aws/amazon-cognito-identity-js#345]
Hello guys,
I have posted this in the AWS forum [here](https://forums.aws.amazon.com/thread.jspa?threadID=252038) , but no response yet. I am able to reproduce this using the javascript sdk as well. Hence my post here.

I am experiencing some unexpected behaviour when trying to use Cognito user pools.

Here is my scenario:
An existing user pool exists that was configured to use email as an alias.

1. Create a user in the user pool with email a@b.com
2. Update the user attribute with email as b@b.com
3. Try performing retrieveUser using b@b.com -> Get the user not found error
4. Try performing retrieveUser using a@b.com -> User is returned with email as b@b.com
5. Try to add a new user with email a@b.com -> get an error saying user already exists.

Is this expected?
Let me know if anyone has experienced this before or how to get around this
The API used is AdminUpdateUserAttributes.

**Comment by itrestian** [comment]
I assume you're also confirming the emails after you're doing the above operations?

Can you try this again with newly created users? We pushed a fix last week that should address this.

**Comment by mailtobash** [comment]
Hey @itrestian ,
We tested this and its fixed now.
Thanks!
