### ISSUE TITLE
Signature verification. 

### ISSUE THREAD

**Issue by michielboekhoff** [aws/amazon-cognito-identity-js#347]
Hi there,

After reading the source code, it seems like the RS256 signature is __not__ being verified on the client-side. Is there any way to verify a user's token after logging in, preferably without a network request?

Thanks.

**Comment by itrestian** [comment]
Yes, we don't in our SDKs. Here is some example on how to do that:

https://forums.aws.amazon.com/thread.jspa?threadID=250900&tstart=0
