### ISSUE TITLE
cognitoUser.getUserAttributes error: User is not authenticated

### ISSUE THREAD

**Issue by lusentis** [aws/amazon-cognito-identity-js#35]
Hi,
I've completed the authentication flow and I can successfully login, get the tokens, set AWS credentials via Cognito Identity etc...
All the methods in this library works correctly, for example i can change a password, but `getUserAttributes` always returns an error: `User is not authenticated`, the code is:

```
const cognitoUser = userPool.getCurrentUser();
cognitoUser.getUsername(); // 'simone'
cognitoUser.changePassword('asdASD123!', 'newPassword000$$$', function(err, result) {
  // ok!
});
cognitoUser.deleteAttributes(['custom:xxx'], function(err, result) {
  // ok!
});
cognitoUser.getUserAttributes((err, result) => {
  // error: User is not authenticated
});
```

I've tried to wrap the call in a setTimeout etc... but no luck.

This is the full code I use for authenticating etc...: https://github.com/plasticpanda/cognito-idp-demo/blob/master/lib/idp.js

Thank you,
Simone

**Comment by itrestian** [comment]
Hi Simone,

Not sure what the problem might be but some ways to debug might be:
- what are the attributes you set for the user in the first place? Make sure you set some attributes. Any case the error might be confusing if there are no attributes.
- can you verify if the session is valid? Before you make the call, you can actually retrieve the session and see if the object is null or you can check if the access token is valid. The access token is a jwt token. Basically in the CognitoUser object, there is a check that does just those things and throws an error if the conditions are not met.

Ionut.

**Comment by lusentis** [comment]
Thank you, I'm closing this since I can't reproduce anymore...
Sorry

**Comment by khubilla** [comment]
Having the same issue. What's your resolution for this?

**Comment by stvhanna** [comment]
@lusentis @khubilla I'm having the same issue as well. The session token is valid but keeps getting `Error: User is not authenticated` on `cognitoUser.getUserAttributes()`. Any advice on how to resolve this would be greatly appreciated. :)

**Comment by mcrider** [comment]
@stvhanna @khubilla  you need to call getSession on the user before you can get their attributes.  [This rackspace blog post](http://blog.rackspace.com/part-2-building-serverless-architecture-aws) was immensively helpful for me.

**Comment by balint42** [comment]
This absolutely needs to be better documented..
(e.g. added to http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html)
