### ISSUE TITLE
Phone verification

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#350]
When a user's phone_number attribute is updated does Cognito automatically send a confirmation code to their phone in order to verify it?

Thanks
Yulric

**Comment by itrestian** [comment]
Yes.

**Comment by yulric** [comment]
Hmm, that does not seem to be happening for me.
I know that I Cognito is sending SMS messages because when I sign up a new user with my phone number it sends me a code.
But when I signup up a user and then update the phone_number attribute it does not send anything.

Are there any options that need to be set in Cognito for this to work?

**Comment by yulric** [comment]
Nvm, it looks like it's working (In the verifications tab you have to check the Phone Number checkbox). I thought it wasn't working because if you update the phone number to the same value it does not send a verification code. Is there a way to resend a phone verification code?

**Comment by itrestian** [comment]
You can call update attributes again and that will resend the code.

**Comment by yulric** [comment]
Calling updateAttributes again does not resend the code for some reason, my code looks like this.

```
    user.updateAttributes([
        {
            Name: 'phone_number',
            Value: '+15140143257'
        },
    ], (err, result) => {
        console.log(err);
        console.log(data);
    });
```
It only seems to send a code when the phone_number attribute is different from the one in Cognito.

**Comment by itrestian** [comment]
In that case you could call getAttributeVerificationCode to get a new code (use case 6).

**Comment by itrestian** [comment]
Closing. Feel free to reopen if there are more issues.

**Comment by yulric** [comment]
That worked. Thanks a lot.
