### ISSUE TITLE
How detect if user is authenticated, using Federated Identities

### ISSUE THREAD

**Issue by fopnet** [aws/amazon-cognito-identity-js#353]
==== When authentication is done by the method below: 

let cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData); cognitoUser.authenticateUser( ... );

==== I get to know if the user is authenticated like this way below, even that I refresh my web page. This works fine.

 let cognitoUser = this.cognitoUtil.getCurrentUser();

        if (cognitoUser != null) {
            cognitoUser.getSession(function (err, session) {
                if (err) {
                    // console.log("UserLoginService: Couldn't get the session: " + err, err.stack);
                    callback.isLoggedIn(err, false);
                }
                else {
                    // console.log("UserLoginService: Session is " + session.isValid());
                    callback.isLoggedIn(err, session.isValid());
                }
            });
        } else {
            // console.log("UserLoginService: can't retrieve the current user");
            callback.isLoggedIn("User not authenticated", false);
        }

=== So when authentication is performed through federated identities, the code below returns 'Successfully logged' 

AWS.config.credentials.refresh((error) => {
            if (error) {
                console.error(error);
            } else {
                console.log('Successfully logged!');
            }
        });

=== but this code below returns null !
new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(CognitoUtil._POOL_DATA).getCurrentUser() 

1) Question: How can i detect if the cognito sdk has a authenticated user by federated identities method, even that i refresh my web page ?

**Comment by itrestian** [comment]
Not really sure what the question is. There are 2 SDKs at play here, the User Pools SDK that interacts with the Cognito User Pools service. That saves the last authenticated user and the session in local storage when you authenticate such that when you refresh the page, you can retrieve it.

The refresh part belongs to Cognito Federated Identities that federates different identity providers into AWS and gives them AWS credentials. It has no connection to getCurrentUser or the session provided by User Pools.

**Comment by fopnet** [comment]
Hi itrestian, thanks for your answer,  I understand they are two different things. But would you like to know how to retrieve the credentials of federal entities after a page refresh ?

================= recover my credentials after refresh? 

There are a short way ?

================= login() =>

FB.login(function (response) {

  // Check if the user logged in successfully.
  if (response.authResponse) {

    console.log('You are now logged in.');

    // Add the Facebook access token to the Cognito credentials login map.
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'IDENTITY_POOL_ID',
      Logins: {
        'graph.facebook.com': response.authResponse.accessToken
      }
    });

    // Obtain AWS credentials
    AWS.config.credentials.get(function(){
        // Access AWS resources here.
    });

  } else {
    console.log('There was a problem logging you in.');
  }

});

==================== logout() => 
AWS.config.credentials.clearCachedId()

**Comment by itrestian** [comment]
I would assume you would have to get the access token from local storage, populate the logins map and call refresh or get to retrieve credentials.
