### ISSUE TITLE
Unconfirm user

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#355]
Hi there,
We have a use case where we need a user who has changed their email address to be unconfirmed. Is that possible in cognito?

Thanks,
Yulric

**Comment by itrestian** [comment]
Only if you call adminDisableUser through the main aws sdk. You would need AWS credentials to do that since it is an authenticated API.

https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.min.json#L150

**Comment by yulric** [comment]
So once I disable a user I can set his status to UNCONFIRMED?

**Comment by itrestian** [comment]
Sorry for the misunderstanding but what are you trying to achieve? Restrict the ability of the user to login? That would be achieved by enabling, disabling the user.

When the email is updated, email verified is changed to false. You can then write a lambda trigger that restricts the user's ability to login by checking the email verified user attribute.

**Comment by yulric** [comment]
Yeah that's what I want to do, prevent a user from logging in if their email is unverified. So would that be a pre-authentication or post-authentication trigger?

**Comment by itrestian** [comment]
Pre authentication:

Amazon Cognito invokes this trigger when a user attempts to authenticate (sign in), allowing you to perform custom validation to accept or deny the authentication request.

**Comment by yulric** [comment]
Thanks a lot. I couldn't really find a lot of documentation on how to fail a user authentication though, do you have a link for that? Thanks a lot for your help btw

**Comment by itrestian** [comment]
You should throw a UnauthorizedException from the trigger. It will get translated to a not authorized exception by the service.

**Comment by yulric** [comment]
That worked thanks a lot. The lambda code looks like this,
````
exports.handler = (event, context, callback) => {
    //Check if email is verified
    if(event.request.userAttributes['email_verified'] === false) {
        //Send back error if not
        return context.done({name: 'EmailNotVerifiedError'}, event);   
    }
    
    //All good
    return context.done(null, event);
};
````

**Comment by JustinBis** [comment]
The actual process for preventing a login in a pre-authentication trigger really needs to be somewhere in the cognito docs. I spent far too long searching for this answer.
