### ISSUE TITLE
SRP_A server validation. Security issue?

### ISSUE THREAD

**Issue by SVPA-CharlieSantos** [aws/amazon-cognito-identity-js#356]
I'm using `CognitoIdentityServiceProvider` to authenticate users using username and password. This works fine and I'm able to get a jwtToken.

I noticed in the request, the client SDK is sending a SRP_A parameter which looks something like below
```
{
  "AuthFlow": "USER_SRP_AUTH",
  "ClientId": "my_client_id",
  "AuthParameters": {
    "USERNAME": "my_user_name",
    "SRP_A": "28f2e0044eefbd9f0ab91cf3e19cdfd18a5e30f71368e9cf86d0976c261ef33c60a73d4ca10ea5ba04c47311cd02b0ac9454381791475e32224cfaaa1e06ef0f48a5a064e194dde376845add327c20f57832f77cb6dc2f858a418a89c80b8f7adb1a950308418b295dd6ebd9196a5131c2377859545de04e28b37d7d3ae5e3352d1b5af9d1ff540d5380e798c3318689eeec29177649b3ff7f9dfd328eab29558d323a592225861ff9c167d29eb6e95226b7eb6de14e381ca1a40fb2c592839271502dcf29c0d1fb0b9f209579fca15d865ca97d1bedaf7534642d1e1b56fe2a965cf663329fbec3aaa4b42c5b6e7c71ac8ad1d24f472cd6a888046b0774134d700ce95a6f8b1669df52050cc8e8f1e57d618d8bc9cda376acae534111d19e32cdef0ed068b55741f7c831bdcfa042a45e95a43ffabe46b4f471379e42e3c15578451664c9c85437371558d7be21936e41eed9eb3a2f2a0cbdf46ee336f0e205a271f193557c15a2496cf99e2de7509928dd80ffd12b1a9e37eb41f6178d125a"
  },
  "ClientMetadata": {}
}
```
When I changed the SRP_A value and replay the request, most of the time I'm getting `InvalidParameterException` which is good. But the request still succeeds on certain values, like the value below
```
{
  "AuthFlow": "USER_SRP_AUTH",
  "ClientId": "my_client_id",
  "AuthParameters": {
    "USERNAME": "my_user_name",
    "SRP_A": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "ClientMetadata": {}
}
```
Using the value above, we expect that the request would fail, but it did not. This was reported by our security testing team, where the server is not properly validating request parameters. We would like to understand, what is the role of SRP_A parameter and what possible security risk this may cause?

**Comment by itrestian** [comment]
The A value is a public value as per the SRP algorithm

http://srp.stanford.edu/design.html

You can see that the following safeguards need to be implemented 

    The user will abort if he receives B == 0 (mod N) or u == 0.
    The host will abort if it detects that A == 0 (mod N).
    The user must show his proof of K first. If the server detects that the user's proof is incorrect, it must abort without showing its own proof of K.

**Comment by SVPA-CharlieSantos** [comment]
Thanks @itrestian .
