### ISSUE TITLE
Forgot Password Email

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#360]
Hi there,

Is there a way to go through the forgot password workflow through an email? i.e. when a user wants to reset their password we send them an email with a link that already has the code they need in it so they don't have to type it in?

Thanks,
Yulric

**Comment by chetanme** [comment]
This is possible. You can follow these steps to do this.

- Configure a Custom Message lambda trigger for your user pool
- Cognito before sending any message (email/SMS) will invoke this trigger
- From this trigger, return a link to your app/website. This trigger source gets the username and user pool information which can be embedded in the URL.
  - This link must have a place holder for the one time code value, {####}, which Cognito will replace with the real code.
- You can optionally add text or HTML in this message too.
- Cognito will replace {####} with the 6 digit code and send the message to destination (email/phone) depending on the flow.

**Comment by yulric** [comment]
Thank you for your reply. Is there a way to know what this message is for? i.e. is there a way to know this message is for a forgot password request?

**Comment by chetanme** [comment]
As mentioned in our [documentation](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html), all Lamda triggers are invoked with a specific trigger source value.

For customer message trigger and forgot password flow, the trigger source value you should see in your event source is _CustomMessage_ForgotPassword_.

**Comment by kaykaul** [comment]
@chetanme Is it possible to only have custom messages for ForgotPasword but use default message for others?

**Comment by yulric** [comment]
I think you can check why this CustomMessage Lambda trigger was called using the triggerSource variable (the different values are available here http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-pools-lambda-trigger-syntax-custom-message).

So for a ForgotPassword custom message call you would modify the fields and then call 
````
context.done(null, event)
````

and for everything else you would just call the above code without modifying the event object

**Comment by chetanme** [comment]
The approach to use trigger source value in the event source is correct. You can customize messages for all the different flows which invoke CustomMessage lambda trigger using this.

**Comment by kp-dhvani** [comment]
Is there any way to send a link with user's username and the code by email to the user to initiate the change password flow?
