### ISSUE TITLE
UserImportJob CSV File

### ISSUE THREAD

**Issue by iyz1891** [aws/amazon-cognito-identity-js#362]
Howdy,

I'm setting up a feature to allow an authorized user to bulk import users into a pool. The createUserImportJob operation works fine (shows up in console import job list), the problem is I can't seem to find anywhere in the documentation to actually upload/attach the CSV file with the request (or attach after it's created). None of the userImportJob methods seem to have a spot for it. Not sure If I overlooked something but any help is appreciated.

Thanks.

**Comment by itrestian** [comment]
Seems this was answered in another thread:

https://github.com/aws/aws-sdk-js/issues/1470#issuecomment-295971648
