### ISSUE TITLE
web page break down when using authenticateUser

### ISSUE THREAD

**Issue by MengchenZu** [aws/amazon-cognito-identity-js#364]
Hi all,

When I use authenticateUser to authenticate a confirmed user, the web page broke down. I use Chrome to test the code. What should I do to debug? Thanks

There is the core code:

···
handleSubmit(e) {
    e.preventDefault();
    const username = this.state.username.trim();
    const password = this.state.password.trim();

    var authenticationData = {
        Username : username,
        Password : password,
    };
    var authenticationDetails = new AuthenticationDetails(authenticationData);

    var userData = {
        Username : username,
        Pool : userPool
    };
    var cognitoUser = new CognitoUser(userData);

    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            console.log('access token + ' + result.getAccessToken().getJwtToken());
        },

        onFailure: function(err) {
            console.log(err);
            alert(err);
        },
    });
  }
···

**Comment by itrestian** [comment]
If you are using react, see issue https://github.com/aws/amazon-cognito-identity-js/issues/315

**Comment by MengchenZu** [comment]
Thanks, that really helps
