### ISSUE TITLE
InvalidParameterException: Missing required parameter Session

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#365]
Hi guys ,

when i call  cognitoUser.completeNewPasswordChallenge() , out of the newPasswordRequired call back it's return an error with this message : Missing required parameter Session 

even i sent the needed params like so :
cognitoUser.completeNewPasswordChallenge(this.newPassword, this.userAttributes, this.cognitoObj);

please advice ,
Thanks in advance .

**Comment by itrestian** [comment]
What is cognitoObj? and what does this refer to in your context?

**Comment by HDaghash** [comment]
cognitoObj is "this" in the cognito callback function

**Comment by magicfa** [comment]
I face the same problem. Any news on that?

**Comment by HDaghash** [comment]
for me the solution to keep the logic inside the callback function it's seems it's work as a session , so after the callback is done the guys treat  the session as invalid .

**Comment by saswatkumarsahoo** [comment]
I am also facing the same issue. While calling the "completeNewPasswordChallenge" without newPasswordRequired callback it is throwing the error: Missing required parameter Session. Anyone knows the resolution ? 

cognitoUser.completeNewPasswordChallenge(password, null, {
            onSuccess: function(result) {
                console.log(result)
               
            },
           
            onFailure: function(error) {
                console.error(error.message)
            }
        });

**Comment by saswatkumarsahoo** [comment]
I am also facing the same issue. While calling the "completeNewPasswordChallenge" without newPasswordRequired callback it is throwing the error: Missing required parameter Session. Anyone knows the resolution ?

```
cognitoUser.completeNewPasswordChallenge(password, null, {
onSuccess: function(result) {
console.log(result)
},
onFailure: function(error) {
console.error(error.message)
}
});
```

**Comment by itrestian** [comment]
That assumes cognitoUser.authenticateUser has been called first to retrieve a session that needs to be passed to the service.

**Comment by MarcelloDiSimone** [comment]
In case someone else is running in this issue, it happens due to `cognitoUser` being stateful for some reasons, which means if you're in a class context, store your `cognitoUser` with `this` in a member variable or wrap the `completeNewPasswordChallenge` call in a `newPasswordRequired` callback:

```typescript
// login.service.ts
class LoginClass {
  //...
  completeNewPasswordChallenge(password: string, requiredAttributes: any = [], cb: any) {
    this.cognitoUser.completeNewPasswordChallenge(password, requiredAttributes, {
        onSuccess: () => cb.onSuccess(),
        onFailure: err => cb.onFailure(err)
      });
  }
  authenticate(username: string, password: string, cb: any) {
    // on the initial authentication attempt, store cognitoUser in a member variable
    this.cognitoUser = this.getCognitoUser(username);
    const authenticationDetails = this.getAuthenticationDetails(username, password);
    this.cognitoUser.authenticateUser(authenticationDetails, {
      newPasswordRequired: (userAttributes, requiredAttributes) => {
        // ConfirmController calls completeNewPasswordChallenge and hand over requiredAttributes
        // Angular router... 
        this.router.navigate(['/confirm'], {
          skipLocationChange: true,
          queryParams: {requiredAttributes}
        });
      },
      onSuccess: () => cb.onSuccess(),
      onFailure: err => cb.onFailure(err)
    });
  }
}
```
if this isn't possible in your code, you're left with redundant code in your `completeNewPasswordChallenge` method, calling `authenticate` a second time and complete the password challenge in that `newPasswordRequired` callback. 

Hope this helps
