### ISSUE TITLE
Changing a users e-mail address

### ISSUE THREAD

**Issue by spoit** [aws/amazon-cognito-identity-js#369]
If a user pool is configured to use e-mail addresses as alias (so the user can login with his e-mail address), and the logged-in user changes his e-mail address (through UpdateAttributes), he gets an conformation e-mail on the new e-mail address with a confirmation code.

We're finding the verifyAttribute() function to confirm the changing of said e-mail address, but this seems to presume the user is logged in.

If that's not the case (eg the user logged out or he is on a different device) then the user cannot log in with the old e-mail address (that's gone) nor the new e-mail address (which is email_verified:false).

Is there a way to confirm the changing of an e-mail address without the user authenticating?

**Comment by kushwahavinay** [comment]
Currently this case is not supported by user pool. Alias feature is more useful when user has multiple usernames. Currently, using only email alias might cause this situation. 
One workaround could be, on attribute update use lambda trigger (CustomMessage_VerifyUserAttribute) to send a customized link to user which points to your app, this link can contain the unique id which you used for the username. When user clicks this link, you can auto-populate the username behind the scene.

We have heard this problem from other customers as well and it is in our backlog to handle such cases for single user alias. We will consider it in our future releases.

**Comment by spoit** [comment]
Ok thx
