### ISSUE TITLE
When logging in, jsbn.js is throwing Object doesn't support property or method 'fromRadix'

### ISSUE THREAD

**Issue by EmmanuelTsouris** [aws/amazon-cognito-identity-js#37]
I've implemented the registration, confirmation, and login samples. Unfortunately after successfully registering and confirming a user in the pool, I'm unable to get the login sample working. 

Am I missing something?

I receive this in the console: Object doesn't support property or method 'fromRadix

```
SCRIPT438: Object doesn't support property or method 'fromRadix'
File: jsbn.js, Line: 137, Column: 10
```

jsbn.js line 137:

```
else { this.fromRadix(s,b); return; }
```

**Comment by itrestian** [comment]
Hi Emmanuel,

I think the problem is that you have included only one of the libraries that make up the javascript big integer library:

Check:
http://www-cs-students.stanford.edu/~tjw/jsbn/

You should include both as shown below:

```
<script src="/path/to/jsbn.js"></script>
<script src="/path/to/jsbn2.js"></script>
```

Let us know if this fixes it:

Ionut.

**Comment by EmmanuelTsouris** [comment]
@itrestian that fixed it! That was an oversight on my part. Thank you... 

Now I'm getting another error from _aws-cognito-sdk.min.js_ :(

```
Uncaught TypeError: c.update is not a function
```

I see that it's resolved in this other thread. https://github.com/aws/amazon-cognito-identity-js/issues/3

I saw it in the readme, but somehow it didn't click.

**Comment by itrestian** [comment]
Hi Emmanuel,

So is the issue resolved?

Ionut.

**Comment by EmmanuelTsouris** [comment]
yes, thank you!
