### ISSUE TITLE
catch 401 for any requisites

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#370]
i'm trying to catch the non authenticated responses from angular 2 interceptor by extend Http class

but Cognito requisites are not showing inside angular . 

is there a built in function to intercept response / requests 

so i can handle the 401 errors etc .. 

please advice 
Thanks in advance .

**Comment by itrestian** [comment]
Not sure what you mean but you should be able to handle the errors we return in the following manner:

https://github.com/aws/amazon-cognito-identity-js/issues/192

**Comment by HDaghash** [comment]
Thanks for the response !
simply what i need to redirect the user to another page if he dose not have a vlid token

**Comment by HDaghash** [comment]
Thank you @itrestian  solved my issue , but it seems you return 400 on not valid token instead of 401

**Comment by itrestian** [comment]
Yes, Cognito User Pools returns 400 when the access token is not valid. The code should have more info on the cause.
