### ISSUE TITLE
NotAuthorizedException when i'm trying to reset password !

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#373]
Hello guys 

i got "NotAuthorizedException" when i'm trying to reset password for a disabled user 

the error stack is :
User is disabled

the error.code is :
NotAuthorizedException

i think this is a valid bug .

Thank you !

**Comment by kushwahavinay** [comment]
This is an expected behavior. Disabling a user is an admin functionality and user will not be able to override this by resetting password.

**Comment by HDaghash** [comment]
@kushwahavinay  
Thanks for the response but you didn't got the point !
what i meant here i was trying to reset password to user using admin token , so i'm admin and i have access , but the user that i need to reset password for him is disabled so the API return NotAuthorizedException which is not valid 

any way i handle this from the client side , so i prevent the admin to reset password for disabled user 

Thank you !

**Comment by behrooziAWS** [comment]
You need to use admin-enable-user before admin-reset-user-password.
