### ISSUE TITLE
checking if the token is still valid 

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#375]
Hello guys 

is there a function to check the validity of token , so i send a token and the function return if the token is valid or not 

i'm not able to find it here : http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#initiateAuth-property

please advice !

**Comment by itrestian** [comment]
you should be able to have access to signInUserSession from the CognitoUser object and do getAccessToken and getExpiration on that.
