### ISSUE TITLE
resetPassword function fired 4 requests for the one call

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#376]
why this happening guys 

it's fired 4 requests when i'm calling

 cognitoidentityserviceprovider.adminResetUserPassword ...

please advice !

**Comment by alihalabyah** [comment]
As @HDaghash mentioned there are 4 calls being initiated after each others as per the screenshot

https://www.dropbox.com/s/ybkxs9nuie3y7oj/Screenshot%202017-05-07%2017.05.21.png?dl=0

Moreover, this number of calls brings in another issue which is the `LimitExceededException` 
`Attempt limit exceeded, please try after some time.`

**Comment by itrestian** [comment]
Note that that is an authenticated API so you would need appropriate AWS credentials in order to call that.
