### ISSUE TITLE
ClearCacheId() on logout?

### ISSUE THREAD

**Issue by dreams-and-thoughts** [aws/amazon-cognito-identity-js#378]
I find it is necessary to call **AWS.config.credentials.clearCacheId()** on logout, otherwise the next login (of a different user) will still try and use the previous users credentials, resulting in the following error:

> Logins don't match. Please include at least one valid login for this identity or identity pool.

This only happens on the first attempt at login, subsequent attempts will use the new ID.

This issue on aws-sdk also describes the problem:
https://github.com/aws/aws-sdk-js/issues/609

I can't find any documentation or examples with the suggested 'LoginHint' property. Is there some other way around this issue?

**Comment by vangorra** [comment]
Interesting, I'm experiencing the same issue but AWS.config.credentials is null.

**Comment by jbailey2010** [comment]
Apologies for the issues. I believe this can be a necessary step, we recommend on logging out to include this call in the logic. Otherwise, as you stated, it ends up with some metadata (e.g. credentials) for the previous user's login.
