### ISSUE TITLE
Use case 16 not working except in the login scope 

### ISSUE THREAD

**Issue by HDaghash** [aws/amazon-cognito-identity-js#379]
Hello guys , 

i'm trying to validate token by using Use case 16 

 ```
var poolData = {
        UserPoolId : '...', // Your user pool id here
        ClientId : '...' // Your client id here
    };
    var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
    var cognitoUser = userPool.getCurrentUser();
//cognitoUser returned as null
    if (cognitoUser != null) {
        cognitoUser.getSession(function(err, session) {
            if (err) {
                alert(err);
                return;
            }
            console.log('session validity: ' + session.isValid());

            // NOTE: getSession must be called to authenticate user before calling getUserAttributes
            cognitoUser.getUserAttributes(function(err, attributes) {
                if (err) {
                    // Handle error
                } else {
                    // Do something with attributes
                }
            });

 

        });
    }
```

session.isValid() ...

but i'm using single sign on application so i do the login on different sub domain and i transfer the tokens using the cookies 

the question is how i can do use case 16 with different scope  due to now when i'm doing the Use case 16 the cognitoUser returned with null value 

i think what i need here is to do this cognitoUser.authenticateUser() ... but is this is doable with the token instead of the username and password due to after you login the sing sign on will redirect you to another app  

please advice what is missing here so i can solve this .

many thanks for the support .

**Comment by itrestian** [comment]
If you have valid tokens, you should be able to construct the tokens objects and construct a session object using the appropriate constructors. 

After that, you can set

     cognitoUser.signInUserSession = yourConstructedSession
