### ISSUE TITLE
Cognito User AWS forget password step error

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#381]
have an error for the forget-password step.

I have seen how to do on the exemple given in the AWS github.

This is how I do : 

```
AuthService.forgetPassword = function(username) {
            var userData = {
                Username : username,
                Pool : userPool
            };
            cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
            cognitoUser =
                cognitoUser.forgotPassword({
                   onSuccess: function (result) {
                       console.log('call result: ' + result);
                   },
                   onFailure: function(err) {
                        alert(err);
                   },
                   inputVerificationCode() {
                     var verificationCode = prompt('Please input verification code ' ,'');
                     var newPassword = prompt('Enter new password ' ,'');               
               cognitoUser.confirmPassword(verificationCode, newPassword, this);
                    }
               });
            };
```
I can not figure out why its not working .

I always have this error : 

> Error:
> callListeners
>     emit 
>     emitEvent 
>     a 
>     [52]</d.prototype.runTo 
>     [52]</d.prototype.runTo/< 
>     a/<
>     emitEvent/< 
>     callListeners 
>     emit 
>     emitEvent
>     a 
>     [52]</d.prototype.runTo 
>     [52]</d.prototype.runTo/< 
>     a/< 
>     emitEvent/< 
>     callListeners f
>     emit 
>     emitEvent 
>     a 
>     [52]</d.prototype.runTo 
>     [52]</d.prototype.runTo/< 
>     a/< 
>     emitEvent/< 
>     callListeners 
>     emit 
>     emitEvent 
>     a 
>     [52]</d.prototype.runTo 
>     [52]</d.prototype.runTo/< 
>     a/< 
>     emitEvent/< 
>     callListeners 
>     f 
>     c/<
>     finishRequest 
>     handleRequest/<

Note that the verificationCode and the newPassword getted are well setted.
Does anyone know how to do ?

**Comment by jbailey2010** [comment]
Can you re-paste the error? I can't tell what's going on in what's there.
