### ISSUE TITLE
Password strength bugs

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#386]
I'm making an user management with the Amazon Webservice Cognito on AngularJS.

I have several bugs but I can not tricks for this one.

When a new user try to registering to my platform, if its password do not the password policies set in the user pool, he first have an error message for invalid password (that's normal) but after choosing a correct password he goes to have this error message :

> UsernameExistsException: User already exists

and while this exception the user is corectly added to the user pool...

How can I fixe it ?

**Comment by jbailey2010** [comment]
Answered on S/O: http://stackoverflow.com/questions/43940488/cognito-password-strength-bugs
