### ISSUE TITLE
AuthenticationDetails undefined is not an object (evaluating 'crypto.pbkdf2Sync.toString')

### ISSUE THREAD

**Issue by doovers** [aws/amazon-cognito-identity-js#387]
Adding the following:

    const authenticationData = {
      Username: 'username',
      Password: 'password',
    };
    const authenticationDetails = new AuthenticationDetails(authenticationData);

Results in the following error:

> index.js:3 TypeError: undefined is not an object (evaluating 'crypto.pbkdf2Sync.toString')

**Comment by itrestian** [comment]
That is really weird. AuthenticationDetails doesn't call anything from crypto. It just sets some internal fields. Are you sure you're not getting a similar object from somewhere else?

**Comment by doovers** [comment]
I've tried that exact code in an empty app.component constructor and the error is definitely only showing up when I uncomment the call to create a new `AuthenticationDetails` object. I'll create a clean ng-cli project and see can I replicate the behavior.

**Comment by doovers** [comment]
Strange, I'm not having the same behavior in a clean project. I wonder why that particular code is causing an issue in my main project?

**Comment by itrestian** [comment]
Just wondering if you figured this out. AuthenticationDetails in our codebase is just a constructor that sets internal fields. It doesn't use crypto in any way.

**Comment by doovers** [comment]
I had a look again today to see why this was happening but I can't figure it out. In any case, while it is hardly a workable solution for a big project, creating a new project and copy pasting everything in solved the problem so I'll close the issue.

**Comment by cbartondock** [comment]
Also having this issue.. sane solution would be appreciated!
