### ISSUE TITLE
Programmatic error codes

### ISSUE THREAD

**Issue by bgourlie** [aws/amazon-cognito-identity-js#388]
Consider a scenario where a customer is creating a registration form using the Cognito SDK. If there are server-side validation errors, this is how the response looks:

    {
      "__type":"InvalidParameterException",
      "message":"4 validation errors detected: Value at 'password' failed to satisfy constraint: Member must have length greater than or equal to 6; Value at 'password' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\S]+; Value at 'username' failed to satisfy constraint: Member must have length greater than or equal to 1; Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\p{L}\\p{M}\\p{S}\\p{N}\\p{P}]+"
    }

The problem with this response is that it's difficult to provide good user feedback because it involves parsing the response to determine which fields need to be fixed. **The response should return validations in a format that is easier to work with programmatically.**

**Comment by jbailey2010** [comment]
Noted as a request for a future update!

**Comment by bgourlie** [comment]
Is there anywhere I can track this issue?

**Comment by cdo1828** [comment]
Yes, this.  Please change.

**Comment by lfabricio** [comment]
Please... change...

**Comment by mordka** [comment]
@jbailey2010 Hey Jeff, where is this request noted and how can we track your work on it? Why is this issue closed?
