### ISSUE TITLE
Amazon Cognito “A client attempted to write unauthorized attribute”

### ISSUE THREAD

**Issue by crowdwave** [aws/amazon-cognito-identity-js#397]
Hello,

I have asked a question on StackOverflow for Cognito / JavaScript thanks.

http://stackoverflow.com/questions/44013901/amazon-cognito-a-client-attempted-to-write-unauthorized-attribute

Edit - I self answered this on SO - the problem is that the permissions for those attributes were not set in the app for the user pool.  The custom attributes documentation should be making this requirement clear where is talks about custom attributes.

**Comment by jbailey2010** [comment]
Appreciate the update, making our lives easier. I'll note the docs update request.

**Comment by crowdwave** [comment]
It would make alot of sense for the console UI "add custom attributes" to have some sort of reminder that attributes can only be used once permissions have been set, along with a link to the relavent settings.
