### ISSUE TITLE
Trying to log in unconfirmed user gives UserNotFoundException

### ISSUE THREAD

**Issue by karin-toth** [aws/amazon-cognito-identity-js#398]
Our user pool requires email and phone verification. Signing up with new user, but not verifying phone number or email. User is then stated as unconfirmed in cognito. Trying login with `cognitoUser.authenticateUser` returns `UserNotFoundException`.  Expected `UserNotConfirmedException`. 

Verifying phone number but leaving email unconfirmed gives same result.  
Confirming email lets me log in without errors.

Using cognito 1.17.0.
I might be wrong, can someone confirm this?

**Comment by itrestian** [comment]
Are you using aliases to login? Aliases won't kick in until they are actually confirmed.

**Comment by karin-toth** [comment]
Yes, we use aliases to log in. Then that is the problem, thank you!
