### ISSUE TITLE
Question: Authenticating a user after confirmation?

### ISSUE THREAD

**Issue by nenadlukic** [aws/amazon-cognito-identity-js#399]
I'm unable to understand or find resources related to automatically authenticating a user after they confirm their account without storing their plaintext password and performing the login procedure or forcing them to login in manually. Can somebody point me in the right direction?

**Comment by prem911** [comment]
![image](https://cloud.githubusercontent.com/assets/7778147/26189120/8a79ad32-3bc0-11e7-8578-8dca542635ca.png)
This is the normal flow of signup, confirm and signin.

Typically, after a user confirms, we should ask him/her to signin. We should not be signin him on behalf of the application.

**Comment by nenadlukic** [comment]
Hmm, I don't see why it would be bad practice to automatically sign in the user that just signed up for the app and confirmed their identity by providing the confirmation code. Having to input login info again seems like an extra step that can sometimes be necessary, but in most use cases probably shouldn't be. But alas, ok, thank you for the clarification.

**Comment by bennypowers** [comment]
It's possible to have the user enter their password on the confirmation screen. Here's how we do it in a Polymer SPA with our newly-released `<shameless-plug>`[PolymerAWS/aws-cognito](http://github.com/PolymerAWS/polymeraws)`</shameless-plug>` element:

```js
// <my-app> container element

// `confirm-new-user` fired by confirm page
_handleConfirmNewUser: function(e) {
  let cognito = this.$.auth.$.cognito; // aws-cognito element
  cognito.verify(e.detail.email, e.detail.code);
},

// `confirm-success` fired by aws-cognito
_handleConfirmSuccess: function(e) {
  this.set('route.path', '/'); // go home
  let cognito = this.$.auth.$.cognito; // aws-cognito element
  let confirm = this.$.confirm; // confirm page

  this.async(cognito.login(confirm.email, confirm.password));
  this.$.confirm.reset();
},
```

**Comment by nenadlukic** [comment]
Yes that seems like a good way that seems to improve the UX, but I would still expect for it to be supported out of the box without hacky solutions.

**Comment by kvnwolf** [comment]
So this wouldn't be supported out of the box like never?
