### ISSUE TITLE
Error: resendConfirmationCode result is not defined

### ISSUE THREAD

**Issue by rchall-gladly** [aws/amazon-cognito-identity-js#400]
Error:
request.js:31 Uncaught Error: result is not defined
at Response.eval (CognitoUser.js:837)
at Request.eval (request.js:360)
at Request.callListeners (sequential_executor.j

Source:

``` 
  /**
   * This is used by a user to resend a confirmation code
   * @param {nodeCallback<string>} callback Called on success or error.
   * @returns {void}
   */
CognitoUser.prototype.resendConfirmationCode = function resendConfirmationCode(callback) {
    this.client.makeUnauthenticatedRequest('resendConfirmationCode', {
      ClientId: this.pool.getClientId(),
      Username: this.username
    }, function (err) {
      if (err, result) {
        return callback(err, null);
      }
      return callback(null, result);
    });
  };
```

See how the if statement in the callback it's using an undefined result.

This isn't breaking the main functionality but an error is being displayed on the console.

**Comment by itrestian** [comment]
Should be working now. Can you give it a try?

**Comment by rchall-gladly** [comment]
It's working, thanks a lot @itrestian 
Closing
