### ISSUE TITLE
1.17 : awsSdk.CognitoIdentityServiceProvider.CognitoUserPool is not a constructor

### ISSUE THREAD

**Issue by PatrickDuncan** [aws/amazon-cognito-identity-js#401]
My cloned repo works fine with v1.16, but v.1.17 gave this error:

`awsSdk.CognitoIdentityServiceProvider.CognitoUserPool is not a constructor`

from this function:

`export function getUserPool(username) {
  let poolData = {
    UserPoolId: appConfig.UserPoolId,
    ClientId: appConfig.ClientId,
  };
  return new CognitoIdentityServiceProvider.CognitoUserPool(poolData);
}`

while using case 4

I can just force the library to use 1.16 of course, just giving you guys a heads up!

**Comment by tarepan** [comment]
Me too, same error occur with v1.17, not with  1.16.
And also with v1.18, it do not work.

**Comment by forforf** [comment]
May also be related to #392

**Comment by patotoma** [comment]
Hello @PatrickDuncan, try importing `CognitoUserPool` like this:
```
import { CognitoUserPool } from 'amazon-cognito-identity-js';
```
I guess it's no longer attached to `CognitoIdentityServiceProvider` object. The same goes for `AuthenticationDetails`, `CognitoUser` and other cognito modules...

**Comment by itrestian** [comment]
Not really sure awsSdk.CognitoIdentityServiceProvider.CognitoUserPool is mentioned in the documentation but AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool should still work with script/browser usage.
