### ISSUE TITLE
Cognito WebService from Amazon crashing on Apache server

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#402]
Everything is running smoothly on local but everything crash when I use it on a Wamp server and I can not figure out why.

I'm doing as of now my registration directly on my controller like this :

```
AWSCognito.config.region = 'eu-west-1';
    var cognitoUser;
    var poolData = {
      UserPoolId: 'eu-west-1_XXXXXXXX',
      ClientId: '4dkagd3xxxxxxxxxxxxxx'
    };
    AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({
      IdentityPoolId: 'eu-west-1:xxxxxx-xxxx-xxx-xxxxx-xxxxxxxxxx',
    });
    var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData)

    userPool.signUp($scope.username, $scope.password, attributeList, null, function(err, result) {
      if (err) {
        alert(err);
        return;
      } else {
        alert('successfully registered');
        routeService.goToView('/users-confirmation');
      }
    });
```

The mysterious thing is that I never get any of the two alerts (error or success) and I'm directly redirected to my main page...

Does anyone know why and how can I fixe it ?

**Comment by jbailey2010** [comment]
So you're receiving no message? Can you give a request id and a timestamp?

**Comment by ghost** [comment]
Thank you @jbailey2010 , can you please tell me how to find a request id an timestamp ?

**Comment by ghost** [comment]
I have something very strange, when I use break point to try to debug it's work... Do there is a way to temporize it ?

**Comment by itrestian** [comment]
Are you trying to use this in a WordPress context?

**Comment by itrestian** [comment]
Closing as no response.
