### ISSUE TITLE
Keeping User Authenticated

### ISSUE THREAD

**Issue by PatrickDuncan** [aws/amazon-cognito-identity-js#403]
How exactly does one keep a user authenticated?

I'm using Case 16/17 to check if the user is still authenticated and refresh the credentials when necessary. `AWS.config.credentials.expireTime` updates accordingly, i.e. it shows exactly one hour from when I did `AWS.config.credentials.refresh()` and `AWS.config.credentials.needsRefresh()` return _false_.

The problem is that an hour from the first time that I set `AWS.config.credentials` it becomes undefined which means I can't call `AWS.config.credentials.refresh/get`! 

>   if (AWS.config.credentials) {
    AWS.config.credentials.get(error => {
      if (error) {
        AWS.config.credentials.refresh(error => {
          if (error) {
            console.error(error);
            signOut();
            return;
          }
        });
      }
    });
  }
  else {
    signOut();
    return;
  }

I read somewhere that you have to redo the login request (Case 4) to keep the user signed in, but saving the password in a cookie or something seems like a horrible practice.

Any advice would be well appreciated, thanks.

**Comment by itrestian** [comment]
You should get the current user from local storage as in use case 16. That retrieves a valid session using a refresh token that can be used to get new credentials.
