### ISSUE TITLE
Performance of authenticateUser

### ISSUE THREAD

**Issue by dsandmark** [aws/amazon-cognito-identity-js#404]
Hi,

I'm writing a React app and use AWS Cognito to authenticate users. The `cognitoUser.authenticateUser` call works but takes 15-20 seconds on 4Ghz iMac. While `authenticateUser` is running, my Login screen grinds to a freeze.

I ran Chrome's profiler and I believe `BigInteger.js` may be the culprit. Is there any improvements I can do to not have my UI freeze while `cognitoUser.authentication` is performed?

The same issue occurs for `amazon-cognito-identity-js` of version `1.15.0` through `1.18.0`.

I'm using
```
"amazon-cognito-identity-js": "1.18.0",
"amazon-cognito-js": "1.1.0",
```

`signInUser` is called when a user clicks `Login`.
```javascript
import {
  CognitoUser,
  AuthenticationDetails,
  CognitoIdentityCredentials,
} from 'amazon-cognito-identity-js'

export function signInUser({ email, password }) {
  return new Promise((resolve, reject) => {
    const authenticationDetails = new AuthenticationDetails({
      Username: email,
      Password: password
    })

    const cognitoUser = new CognitoUser({
      Username: email,
      Pool: userPool,
    })

    authenticateUser(cognitoUser, authenticationDetails)
      .then(() => buildUserObject(cognitoUser))
      .then((userProfileObject) => {
        resolve(userProfileObject)
      })
      .catch((err) => {
        reject(err)
      })
  })
}

function authenticateUser(cognitoUser, authenticationDetails) {
  return new Promise((resolve, reject) => {
    cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: function(result) {
        localStorage.setItem('user_token', result.accessToken.jwtToken)

        const loginsObj = {
          [USERPOOL_ID]: result.getIdToken().getJwtToken()
        }

        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
          IdentityPoolId: IDENTITY_POOL_ID,
          Logins: loginsObj,
        })

        AWS.config.credentials.refresh(() => {})

        resolve()
      },
      onFailure: function(err) {
        console.log(err)
        reject(err)
      },
      newPasswordRequired: function(userAttributes, requiredAttributes) {
        // the api doesn't accept this field back
        delete userAttributes.email_verified;

        // Get these details and call
        cognitoUser.completeNewPasswordChallenge('***', userAttributes, this)
      }
    })
  })
}
```

When I run profiler:
<img width="537" alt="profile of login 2017-05-21 09 14 39" src="https://cloud.githubusercontent.com/assets/2494389/26282303/fe3727d4-3e06-11e7-8fac-3c0ba2685a16.png">

Appreciate any help. And thanks for an otherwise great library.

**Comment by dsandmark** [comment]
Update:

These 15-20 seconds that `cognitoUser.authenticateUser` takes disappears when I host my website on an AWS S3 bucket. It works great there, still grinds UI to a halt when running locally.

**Comment by pizzarob** [comment]
This method nearly crashes the browser when using IE Edge. I've created an issue for that. #419

**Comment by itrestian** [comment]
Is the new version (1.19.0) of any help? Seems the montReduce function that is part of modPow is the culprit in your photo

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/BigInteger.js#L640
