### ISSUE TITLE
How to refresh IdToken using refreshToken Value after session Expire?

### ISSUE THREAD

**Issue by tbiinfotech** [aws/amazon-cognito-identity-js#405]
Is it possible we can force expire before one hour and get new IdToken using refresh token 
OR
How to get new IdToken after auto expire time using refreshToken value in this amazon-cognito-identity-js module?

I am getting 
`TypeError: refreshToken.getToken is not a function` as error.

I am using this code as follows:

```
cognitoUser.refreshSession(refreshToken, (err, session) => {
                          if (err) {//throw err;
                            console.log('In the err'+err);
                          }
                          else{
                            console.log('session '+session);
                          }
                    }); 
```

I am passing refreshToken correct value in the function. Can any one please help me out there?

**Comment by jbailey2010** [comment]
Looking on StackOverflow: https://stackoverflow.com/questions/44107689/how-to-refresh-idtoken-using-refreshtoken-value-after-session-of-idtoken-expire

**Comment by tbiinfotech** [comment]
Yes I have discussed same issue with the colleague. Can not I ask there now ?

**Comment by tbiinfotech** [comment]
If I replace the code line in refreshToken() function in CognitoUser.js file.

`authParameters.REFRESH_TOKEN = refreshToken.getToken(); `

the above line with the 

`authParameters.REFRESH_TOKEN = this.signInUserSession.getRefreshToken().getToken();`

then it starts working.
