### ISSUE TITLE
Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by akashbiz** [aws/amazon-cognito-identity-js#407]
Hi, I am using this SDK in Angular2 project. Whenever I try to login to cognito it gives me this error `Invalid login token. Issuer doesn't match providerName.` If I refresh the page it doesn't show the error. I am facing this issue while login only, not sure if it is related to some tokens in storage of previous login even after using `this.cognitoUtil.getCurrentUser().signOut()`.

**Comment by itrestian** [comment]
Have you configured the user pool to be a provider for your identity pool?

**Comment by akashbiz** [comment]
Yes, I did configured and I found that It was issue with making Logins object. Somehow it was not in appropriate format. Now, Issue has been resolved. Thanks for your feedback.
