### ISSUE TITLE
Refreshed Tokens are not cached locally

### ISSUE THREAD

**Issue by anthonymclaughlin** [aws/amazon-cognito-identity-js#41]
After the initially issued id/access tokens have expired (1 hour) calls to cognitoUser.getSession() will retrieve new tokens from the endpoint.

These tokens aren't cached in localstorage so any subsequent calls to getSession() always results in a call to the endpoint and new id/access tokens being issued.

**Comment by mreddyg** [comment]
Hi,

Thank you for reporting this issue. This bug will be fixed in the next version of the SDK.

**Comment by geertbrit** [comment]
Hi, Any ballpark date on nect release relating to above?

**Comment by mreddyg** [comment]
This fix should be available in the next version of AWS Android SDK. The next version will be available within a couple of weeks.

**Comment by itrestian** [comment]
This was solved at GA. Refreshed tokens are now cached.
