### ISSUE TITLE
Wrong definition type for CognitoRefreshToken constructor (string instead {string=})

### ISSUE THREAD

**Issue by Dunos** [aws/amazon-cognito-identity-js#412]
If I try to do something like this `const RefreshToken = new CognitoRefreshToken(refreshToken);` to later use the `cognitoUser.refreshSession` method, the POST called made is missing the REFRESH_TOKEN parameter. I looked inside the JS library and there the constructor is expecting a variable defined like _{RefreshToken: string}_, so that's why it misss the parameter in the post (or that's what I think!).

The definition looks like this right now:

```
export class CognitoRefreshToken {
      constructor(refreshToken: string);

      public getToken(): string;
      public getExpiration(): number;
}
```
And the real code function looks like this:
```
export default class CognitoRefreshToken {
  /**
   * Constructs a new CognitoRefreshToken object
   * @param {string=} RefreshToken The JWT refresh token.
   */
  constructor({ RefreshToken } = {}) {
    // Assign object
    this.token = RefreshToken || '';
  }

  /**
   * @returns {string} the record's token.
   */
  getToken() {
    return this.token;
  }
}
```

Maybe related with [#130](https://github.com/aws/amazon-cognito-identity-js/issues/130).

**Comment by itrestian** [comment]
Feel free to update the definition by sending a pull request.

**Comment by itrestian** [comment]
Updated https://github.com/aws/amazon-cognito-identity-js/pull/487
