### ISSUE TITLE
Signout without localstorage

### ISSUE THREAD

**Issue by bdschr** [aws/amazon-cognito-identity-js#413]
Hello,

I am setting this SDK up with the serverless framework. Deploying it on AWS Lambda along with the Amazon API service. My question is, how can I signout users when I am not using localstorage.

Regards,
bdschr

**Comment by itrestian** [comment]
If local storage is not available on the platform, the SDK reverts to using in memory storage. That should clear the tokens.

**Comment by bdschr** [comment]
Nevermind, I just set the keys manual on the cognitoUser object. However when signing out either by either manual setting the keys or the SDK way from the browser localstorage. I still am having the following issue as well when trying to logout and revoke the token:

https://github.com/aws/amazon-cognito-identity-js/issues/21

**Comment by itrestian** [comment]
You should be calling globalSignOut in order to revoke the tokens. That revokes the access tokens issued. However they can still be used with services other than user pools.
