### ISSUE TITLE
Cognito User Pool Authorizer availability for ap-south-1

### ISSUE THREAD

**Issue by prem911** [aws/amazon-cognito-identity-js#415]
Starting last month, we saw the introduction of API Gateway and Cognito in Mumbai ( ap-south-1 )

However, if we go to configure Cognito User Pool Authorizer, there is a limited set of regions and this doesnot have Mumbai.

Looked at the service availability table and it doesnot have a mention.
Can the AWS team tell why this feature is specifically kept out?

![image](https://cloud.githubusercontent.com/assets/7778147/26540010/ed509268-446c-11e7-8460-0e7dc2389556.png)
![image](https://cloud.githubusercontent.com/assets/7778147/26540068/35d162f6-446d-11e7-940b-3a512825299a.png)

**Comment by behrooziAWS** [comment]
Thanks for bringing this to our attention, I'll notify api-gateway to add it to their dropdown and add a step to our region buildouts make sure this isn't missed in the future.

**Comment by prem911** [comment]
@behrooziAWS Any ETA that can be shared?

**Comment by prem911** [comment]
ap-south-1 is available. Closing this.
