### ISSUE TITLE
Confuse about using CognitoUserPool.getCurrentUser()

### ISSUE THREAD

**Issue by JonathanFu** [aws/amazon-cognito-identity-js#417]
I use this module for **node back-end** application, so it will use **MemoryStorage** instead of **window.localStorage**.  

**CognitoUserPool.getCurrentUser()**
From the document ```Use case 16. Retrieving the current user from local storage.```.
Above ```local storage``` may not be true, since back-end will use **MemoryStorage**.
Also according to the function definition below. ```getCurrentUser()``` actually returns the last authenticated user of this application. Which means logged in User A calls this function may returns User B data (if User B is the last authenticated user). 
It would be better to make the **use case** more clearly if my understanding is correct.

CognitoUserPool.js
```Javascript
  CognitoUserPool.prototype.getCurrentUser = function getCurrentUser() {
    var lastUserKey = 'CognitoIdentityServiceProvider.' + this.clientId + '.LastAuthUser';

    var lastAuthUser = this.storage.getItem(lastUserKey);
    if (lastAuthUser) {
      var cognitoUser = {
        Username: lastAuthUser,
        Pool: this,
        Storage: this.storage
      };

      return new _CognitoUser2.default(cognitoUser);
    }

    return null;
  };
```
CognitoUser.js, override lastUserKey with current username.
```Javascript
  CognitoUser.prototype.cacheTokens = function cacheTokens() {
    var keyPrefix = 'CognitoIdentityServiceProvider.' + this.pool.getClientId();
    var idTokenKey = keyPrefix + '.' + this.username + '.idToken';
    var accessTokenKey = keyPrefix + '.' + this.username + '.accessToken';
    var refreshTokenKey = keyPrefix + '.' + this.username + '.refreshToken';
    var lastUserKey = keyPrefix + '.LastAuthUser';

    this.storage.setItem(idTokenKey, this.signInUserSession.getIdToken().getJwtToken());
    this.storage.setItem(accessTokenKey, this.signInUserSession.getAccessToken().getJwtToken());
    this.storage.setItem(refreshTokenKey, this.signInUserSession.getRefreshToken().getToken());
    this.storage.setItem(lastUserKey, this.username);
  };
```

**Comment by itrestian** [comment]
Do you mean adding the info that if this is used in a node application, the current user is retrieved from memory storage and not local storage?
