### ISSUE TITLE
cognitoidentityserviceprovider.adminAddUserToGroup is not a function

### ISSUE THREAD

**Issue by chandan5477** [aws/amazon-cognito-identity-js#421]
please tell me how i can use the group functions in node js lambda

**Comment by chandan5477** [comment]
here my code 👍
 var cognitoidentityserviceprovider = new AWSCognito.CognitoIdentityServiceProvider({apiVersion: '2016-04-18'});
                      cognitoidentityserviceprovider.adminAddUserToGroup(params, function(err, data) {
                        if (err) console.log(err, err.stack); // an error occurred
                        else     console.log(data);           // successful response
                  });

**Comment by itrestian** [comment]
Answer is similar to the answer below (replace listUsers with adminAddUserToGroup)

https://stackoverflow.com/questions/43773553/cognito-listusers-function-in-angular-2/43789952#43789952

**Comment by chandan5477** [comment]
same error is coming can u explain me with an example

**Comment by aqibos** [comment]
Try:

```javascript
const Aws = require('aws-sdk')

const cognitoIdentityService = new Aws.CognitoIdentityServiceProvider()

cognitoIdentityService.adminAddUserToGroup(params, function(err, data) {
  // ...
})
```

**Comment by chandan5477** [comment]
can you tell me how do i call lambda function from  my functions

**Comment by itrestian** [comment]
This question is more appropriate for the lambda forums. You would get a better response there.
