### ISSUE TITLE
How to get IdentityPoolId ?

### ISSUE THREAD

**Issue by tbiinfotech** [aws/amazon-cognito-identity-js#423]
I am working on update IdToken by using refresh token and following case 17. Here is my code as follows:

```
AWS.config.credentials  = new AWS.CognitoIdentityCredentials({
                                    IdentityPoolId:IdentityPoolId
                                    Logins: {
                                        
                                        'cognito-idp.us-xxxx-X.amazonaws.com/us-west-2_XXXXXX': result.getIdToken().getJwtToken()
                                    }
                                });
```

Can anyone please let me know how and from where I can get IdentityPoolId ?
Is this possible to get this by programming in this module ?

**Comment by behrooziAWS** [comment]
You need to create an identity pool in Cognito Federated Identity and use that identity pool id:
http://docs.aws.amazon.com/cognito/latest/developerguide/getting-started-with-identity-pools.html#create-identity-pool
