### ISSUE TITLE
Backslash not listed as allowed special character

### ISSUE THREAD

**Issue by clintfoster** [aws/amazon-cognito-identity-js#424]
The [password policy section](http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html) in the developer guide says the following special characters are allowed:

```^ $ * . [ ] { } ( ) ? - " ! @ # % & / , > < ' : ; | _ ~ ```

The backslash (`\`) is not included in the list, even though it seems to work. Is this an omission or is there a reason it cannot be used?

**Comment by behrooziAWS** [comment]
Thanks for reporting, \ is allowed and we will update the docs.

**Comment by clintfoster** [comment]
Closing since the developer guide page cited above has been updated.
