### ISSUE TITLE
TypeError: Cannot read property 'CognitoUserPool' of undefined

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [aws/amazon-cognito-identity-js#426]
Hello,

I am trying to use cognito and register a user. I have set up my pool and app and I got the poolId and client id. have the following code:

    ` var AWS = require('aws-sdk'); // Tried 'aws-sdk/dist/aws-sdk' too
      var AWSCognito = require('amazon-cognito-identity-js'); // Tried var cognito = ... too
      var CognitoUserPool = AWSCognito.CognitoUserPool;
      exports.handler  = function(event, context, callback) {
      registerUset();
      callback(null, "some success message");
     }
    var registerUset= function(){

    var poolData = {
        UserPoolId : 'xxxxxxxxxxxx', // Your user pool id here
        ClientId : 'xxxxxxx' // Your client id here
    };  console.log("YEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS");
    var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
    var attributeList = [];
    var dataEmail = {
        Name : 'email',
        Value : 'xxxxxxxx@brunswicknews.com'
    };
    var dataPhoneNumber = {
        Name : 'phone_number',
        Value : '55555555'
    };
    var attributeEmail = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataEmail);
    var attributePhoneNumber = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataPhoneNumber);

    attributeList.push(attributeEmail);
    attributeList.push(attributePhoneNumber);

    userPool.signUp('username', 'password', attributeList, null, function(err, result){
        if (err) {
            alert(err);
            return;
        }
        cognitoUser = result.user;
        console.log('user name is ' + cognitoUser.getUsername());
        console.log(cognitoUser);
    });
}`

when I upload and run the above code in lambda test console, I get the following error:

> START RequestId: 40f2d39f-4b97-11e7-a9c0-ef84b50cec07 Version: $LATEST
2017-06-07T15:37:50.315Z	40f2d39f-4b97-11e7-a9c0-ef84b50cec07	YEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
2017-06-07T15:37:50.414Z	40f2d39f-4b97-11e7-a9c0-ef84b50cec07	TypeError: Cannot read property 'CognitoUserPool' of undefined
    at registerUset (/var/task/index.js:24:65)
    at exports.handler (/var/task/index.js:8:5)
END RequestId: 40f2d39f-4b97-11e7-a9c0-ef84b50cec07
REPORT RequestId: 40f2d39f-4b97-11e7-a9c0-ef84b50cec07	Duration: 3621.75 ms	Billed Duration: 3700 ms 	Memory Size: 128 MB	Max Memory Used: 31 MB	
RequestId: 40f2d39f-4b97-11e7-a9c0-ef84b50cec07 Process exited before completing request

As far as I see, I am not missing anything and also I followed the following [link:](https://github.com/aws/amazon-cognito-identity-js)

for installation and packages so I used 

> > npm install --save amazon-cognito-identity-js

and also I installed aws-sdk. Not sure why I am getting the above error. Can anyone help?

**Comment by itrestian** [comment]
It seems you answered your own question

https://stackoverflow.com/questions/44417507/typeerror-cannot-read-property-cognitouserpool-of-undefined/44464292#44464292
