### ISSUE TITLE
Resend Forgot Password MFA

### ISSUE THREAD

**Issue by bradennapier** [aws/amazon-cognito-identity-js#427]
You have resend MFA for registration but its completely missing for the forgot password field which seems to expire within a minute or so... makes it confusing in that situation to make them completely start over the process if they don't receive the code.

**Comment by chetanme** [comment]
For ForgotPassword, you can call ForgotPassword API again as a resend action of your app. It basically just initiates the flow to send the code again.

A user doesn't need to go back to the forgot password screen.
