### ISSUE TITLE
MFA with Email instead of Phone?

### ISSUE THREAD

**Issue by bradennapier** [aws/amazon-cognito-identity-js#428]
So I would think that if you have both email and phone available that you could at least choose how to verify in some way.  In my case if the user does not have their phone on them and/or can't access it I would want them to be able to authorize using their email instead...

**Comment by behrooziAWS** [comment]
There are two things you could be describing:

1. On sign up, if you provide both phone and email, and require verification on both, the verification code will only be sent to the phone.  Email verification is a subsequent step.

2. If you have MFA turned on, the MFA code will only be sent to the phone.

Are you describing 1 or 2 or both?  Only 1 code is sent and it always goes to the phone first, without the ability to choose.  So clarifying would help us understand which feature you are requesting.
