### ISSUE TITLE
change user status

### ISSUE THREAD

**Issue by chandan5477** [aws/amazon-cognito-identity-js#432]
how will user status change from unconfirmed to force_change_password ?

**Comment by chetanme** [comment]
This is not possible. A user can only be put into FORCE_CHANGE_PASSWORD if he is created using the AdminCreateUser API.

An administrator using the AdminResetUserPassword API can put the user into RESET_REQUIRED mode if required.

**Comment by chandan5477** [comment]
can u explain me with an example of AdminCreateUser....how can i achieve that ?

**Comment by okarlsson** [comment]
@chandan5477 

Here is an example:

        var cognitoidentityserviceprovider = new AWS.CognitoIdentityServiceProvider({ apiVersion: '2017-05-30' });

        var params: any = {};
        params["Username"] = email.toLowerCase();
        params["UserPoolId"] = environment.userPoolId;

        cognitoidentityserviceprovider.adminCreateUser(params, function (err: any, data: any) {
            if (err) {
                callback.callbackRegisterComplete(err);
            }
            else {
                callback.callbackRegisterComplete(null);
            }
        });

Dont forget to give yourself the correct permissions in your IAM role.

**Comment by chandan5477** [comment]
still my status is same...

**Comment by itrestian** [comment]
Which part is not clear? If you admin create a new user he is not in FORCE_CHANGE_PASSWORD status?
