### ISSUE TITLE
forgotPassword onSuccess doesn´t return response data

### ISSUE THREAD

**Issue by oennen** [aws/amazon-cognito-identity-js#433]
As mentioned in [#323](https://github.com/aws/amazon-cognito-identity-js/issues/323) forgotPassword in src/CognitoUser.js doesn´t returns the response data of the API call. It would be very helpful to receive the response via onSuccess to be able to access the CodeDeliveryDetails object.
We would like to know, if a verification code was sent via SMS or MAIL. Without the response data you don´t know which DeliveryMode has been used.

**Comment by vlekakis** [comment]
Hello,

Yes good point, we have updated the forgotPassword to surface the CodeDeliveryDetails on success.
