### ISSUE TITLE
CognitoRefreshToken does not have getExpiration method

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#435]
The getExpiration method is missing in the CognitoRefreshToken class but the typescript definition file says that it should have the method (https://github.com/aws/amazon-cognito-identity-js/blob/master/index.d.ts#L154)

**Comment by vlekakis** [comment]
Hello,

You are correct, we will update the ts file soon.

**Comment by yulric** [comment]
Is there sample code to get the expiration for the refresh token?

**Comment by itrestian** [comment]
Don't think it's available in the payload. Hence why it wasn't there.
