### ISSUE TITLE
email_verified attribute is a string

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#436]
This is more an issue with AWS Cognito itself as opposed to this library,

When the account is initially created the email_verified field is a boolean
When the account email is changed the email_verified is change to false but it's a string

This was all tested using a PreAuthentication trigger

Is it possible to make it so that it's always a boolean?

**Comment by itrestian** [comment]
I think it's a particularity of our service that attributes are treated as Strings for validation purposes. See my answer on the question below:

https://stackoverflow.com/questions/43378871/aws-cognito-custom-attributes-not-created/43402930#43402930
