### ISSUE TITLE
space character in password

### ISSUE THREAD

**Issue by davidkelley** [aws/amazon-cognito-identity-js#439]
We're having trouble creating users with space characters in their password. Is this a bug or expected functionality? We seem to be getting `InvalidParameterException`?

**Comment by vlekakis** [comment]
Hello,

I'm sorry you're having this problem.  However, Cognito does not support space characters in the password. The password policy of Cognito is described in the userPool settings here: http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html

We will consider this request for future releases.

**Comment by ffxsam** [comment]
What's the reasoning behind disallowing spaces? Passphrases should be allowed.

**Comment by kbrown** [comment]
Is Amazon still invested in Cognito or are they just ceding this space to others?

**Comment by davidkelley** [comment]
Hi, could you please let me know if this is a planned feature change? It
would be useful to allow pass phrases.

**Comment by jjnypr** [comment]
This is a comical shortcoming unworthy of Amazon

**Comment by wshaver** [comment]
Hi, 2018 here, and we still can't 
![image](https://user-images.githubusercontent.com/786554/34898925-7c0bc572-f7aa-11e7-8290-895f47329728.png)

**Comment by retwedt** [comment]
+1
