### ISSUE TITLE
Question: Why no server side?

### ISSUE THREAD

**Issue by mikedizon** [aws/amazon-cognito-identity-js#44]
Hi, just wondering why this wasn't included in the mainline aws-sdk. Is this how you plan on supporting User Pools going forward?

**Comment by luckybroman5** [comment]
Hi @mikedizon,

I have an open source hack for you. It is far from perfect, but will get the ball rolling. Any PR's are appreciated :)

https://github.com/luckybroman5/amazon-cognito-identity-js/tree/node

**Comment by behrooziAWS** [comment]
User Pools is in beta, it will not be part of mainline until we exit beta as api are expected to change.

**Comment by shortjared** [comment]
@luckybroman5 Thank you for that implementation, after bashing my head against the wall for a few hours it plugged in and worked flawlessly.

**Comment by wmarsey** [comment]
@behrooziAWS Any time scale for this?

**Comment by behrooziAWS** [comment]
Due to dependencies, we have chosen to keep the user pools SDK separate.  There is no timeline for integration at this point.

**Comment by VictorioBerra** [comment]
Can this be used server side? Should it be? I want to add login to my site, but im not sure how to integrate this into an ExpressJS session.

**Comment by behrooziAWS** [comment]
Victorio, take a look at Admin Authentication Flow on [this page](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-authentication-flow.html).  I'm not familiar with ExpressJS so I don't know if it will work for sure, but the page describes the process of calling AdminInitiateAuth from your backend to obtain tokens.

**Comment by VictorioBerra** [comment]
@behrooziAWS I think thats exactly what I need. I also stumbled upon a similar answer here https://github.com/aws/amazon-cognito-identity-js/issues/101 basically I can do ADMIN_NO_SRP_AUTH and fire adminInitiateAuth from my back-end to make things super easy.
