### ISSUE TITLE
Support searching by address

### ISSUE THREAD

**Issue by clintfoster** [aws/amazon-cognito-identity-js#442]
Per the documentation for the [listUsers](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html) API, it's possible to search by attributes such as `email` and `phone`, but not `address`. For applications that involve delivery, service or installation at an address it would be very useful to support searching by the `address` attribute. Are there any plans to support this?

If the index is difficult to retroactively implement it seems reasonable to say that this would only work for newly-added addresses.

We plan to work around this issue by putting the street address in the `name` attribute. We can still use `given_name` and `family_name` for the actual name. But is there (or will there be) some kind of special meaning attached to `name`, or is it intended for generic cases such as this?

**Comment by vlekakis** [comment]
Hello,

We understand that this is a limitation and we will consider this feature it for future releases.
What you are describing is a possible work around. However, we are not encouraging it.

**Comment by clintfoster** [comment]
Thanks for the reply. It would be interesting to know how much demand there might be for this. If you think about it, most applications that need your address likely also require the ability to use it to look up your information, e.g. a utility, landscaper, pool service, delivery service, etc.
