### ISSUE TITLE
How to verify that memorized credentials are still actually valid?

### ISSUE THREAD

**Issue by ffxsam** [aws/amazon-cognito-identity-js#444]
I noticed that if I deleted a user in Cognito, they still have access to the web app because `getSession` returns a positive result. So this part of the README is not quite accurate when it says "getSession must be called to authenticate user" because it's not really authenticating anyone.

```js
        cognitoUser.getSession(function(err, session) {
            if (err) {
                alert(err);
                return;
            }
            console.log('session validity: ' + session.isValid());

            // NOTE: getSession must be called to authenticate user before calling getUserAttributes
```

What's the correct way to make sure that the current session's info is still valid? I assume one just has to use the stored username and check if the user still exists in the user pool.

**Comment by itrestian** [comment]
You are correct in the sense that getSession retrieves the stored tokens and checks the validity of the access token. If that is valid, it will use it so you are basically authenticated. If it is not, it uses the refresh token. If the call succeeds, you basically have new tokens which means you are authenticated. If it doesn't succeed tokens are cleared so you would have to authenticate again.

**Comment by ffxsam** [comment]
But as I mentioned, if the user is deleted, `getSession` has no idea about it. What's the recommended way to check if a user still exists? Maybe `cognitoUser.getUserAttributes` and check for failure?

**Comment by kpesanka** [comment]
@ffxsam - I'm facing the same issue. You can't necessarily trust that the stored token is valid, even if you use the isValid() method for the user session (which simply identifies whether the token should have expired given the current time). I think you're going down the right path with making an authenticated call to get user attributes - it's what I think I'll end up implementing.

On the other hand, if you're authenticating with Cognito in order to get temporary IAM credentials (via federation), I'd imagine that if those IAM credentials expire when the token does? If so, an additional check would be to respond to auth failure with your other calls (which use the IAM credentials) with a re-authentication request by the user.

**Comment by dpantke** [comment]
I think that the right answer here is to always regenerate AWS credentials when doing a refresh. If you build a new CongnitoIdentityCredentials object and call get() on it, this should force a WS call to AWS to actually get the credentials. If there was some metadata change about the user on the Cognito side of the equation (like the user no longer exists), this get() operation should fail and we can act accordingly. This may be useful to people generally, and not just when using AWS resources using Cognito Credentials. Perhaps even so useful that AWS credential handling should be added directly in this library, as opposed to requiring clients to deal with it.

Now, this mechanism would protect you from changes that occur during the STS credentials validity period (by default 1 hour). If you need a higher resolution than this, you could probably simply set the STS credentials time to something low enough for your purposes.

**Comment by itrestian** [comment]
Yes, basically the validity of the tokens (except for the refresh token) is given by the expiration field inside the token. You would have to use the token and get a unauthorized exception to know that the token doesn't work anymore. That's the mechanism we use for refreshing the session in case the access token is not valid https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L900

A better integration between the main AWS SDK and the Cognito SDK for Javascript is also on the roadmap to have a better managing of credentials.

**Comment by ffxsam** [comment]
Just an update: I verify account validity by calling `cognitoUser.getUserAttributes` right after authentication. This works perfectly.
