### ISSUE TITLE
Missing required key 'IdentityId' in params

### ISSUE THREAD

**Issue by akashbiz** [aws/amazon-cognito-identity-js#445]
Hello, I am using cognito for authentication of user and after authentication I am trying to access Cognito Datasets but I am facing this issue: "Missing required key 'IdentityId' in params". Below is my code for authenticating user and then accessing datasets, please let me know how I can solve this issue.

Authenticating User: 
`authenticate(username: string, password: string, callback: CognitoCallback) {
	AWS.config.region = AWSCognito.config.region = <REGION>;
	AWS.config.credentials = AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
		IdentityPoolId: <IDENTIY_POOL_ID>
	});
	AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'})

	let authenticationData = {
		Username: username,
		Password: password,
	};
	let authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);

	let userData = {
		Username: username,
		Pool: this.cognitoUtil.getUserPool()
	};

	let cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
	cognitoUser.authenticateUser(authenticationDetails, {
		onSuccess: function (result) {
		  let loginsCognitoKey = 'cognito-idp.' + <REGION> + '.amazonaws.com/' + <USER_POOL-ID>;
		  let loginsIdpData = {};
		  loginsIdpData[loginsCognitoKey] = result.getIdToken().getJwtToken();
		  AWS.config.credentials = new AWS.CognitoIdentityCredentials({
			  IdentityPoolId: <IDENTIY_POOL_ID>,
			  Logins: loginsIdpData
		  });
		  callback.cognitoCallback(null, result);
		},
		onFailure: function (err) {
			callback.cognitoCallback(err.message, null);
		},
	});`

Accessing Datasets after Authentication Success:
`getAllDatasets(callback: Callback) {
  if (callback == null) {
	  throw("CognitoUtil: callback in getAllDatasets is null...returning");
  } else {
	let params = {
	  IdentityId: AWS.config.credentials.params.IdentityId,
	  IdentityPoolId: <IDENTITY_POOL-ID>
	};
	this.cognitosync.listDatasets(params, function(err, data) {
	  if(err) {
		console.log('error fetching datasets', err);
	  }
	  else {
		callback.callbackWithParam(data);
	  }
	});
  }
}`

Thanks in advance.

**Comment by akashbiz** [comment]
Any update on this?

**Comment by dpantke** [comment]
I ran into this a while back while working on an example Cognito Angular project. If you use Pools for authentication and populate the CognitoIdentityCredentials object yourself (which is what we all do), the individual identityID for that user is not available until you either:

1. Call the get() method on the credentials object to actually get the real credentials (and the identityID at the same time). See http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html (the get method is part of the base Credentials class)

2. Call any other AWS API that needs to use credentials but doesn't require the identityID as a param (in which case get() is called for you by the AWS SDK).

**Comment by itrestian** [comment]
Yes, you should call any of those APIs as showcased in Use Case 17 in this repo.

**Comment by akashbiz** [comment]
This is reoccurring now, I had used getPromise() method earlier to solve the problem but after setting up this library using NPM I am facing an issue: **Property 'getPromise' does not exist on type 'Credentials | CredentialsOptions'.  Property 'getPromise' does not exist on type 'CredentialsOptions'.**

I wanted to get all datasets from cognito sync so below is code I am trying 

` let promise = AWS.config.credentials.getPromise();
                promise.then(() => {
                console.log(AWS.config.credentials);
                    let identityID = AWS.config.credentials.identityId;
                    let params = {
                        IdentityId: identityID,
                        IdentityPoolId: Environment.IDENTITY_POOL_ID
                    };
                    this.cognitosync.listDatasets( params, ( error, data ) => {
                        if ( error ) {
                            console.error( error );
                            reject( error );
                        }
                        else {
                            resolve( data );
                        }
                    } );
                } ).catch( error => {
                    console.error( error );
                } ); `
