### ISSUE TITLE
User.signOut() is not clearing storage / cached?

### ISSUE THREAD

**Issue by bradennapier** [aws/amazon-cognito-identity-js#448]
When I logout one user then login another user I am getting the error discussed here:

https://github.com/aws/amazon-cognito-identity-js/issues/68

I have gone through and i do not have unauthenticated active.  All works fine on a refresh but fails when just logging out then logging back in with another account.  

After a significant time trying to figure out the properties causing this I noticed that the previous user is still cached within storage after signing out.  This is then used instead of the new identity when you attempt to refresh the credentials. 

This occurs even when replacing AWS.config.credentials with a `new CognitoIdentityCredentials` on the second login... 

The (undocumented, per usual) fix to this was to manually call `AWS.config.credentials.clearCachedId()` before refreshing the credentials.

Perhaps adding something and/or fixing this issue so that it properly replaces this information when calling User.signOut() so you can allow the user to switch the authenticated user?

**Initial Solution**

Initial Solution was to clear right before refreshing credential (this uses redux-saga)...

```js
export function* setupAWSCredentials(session, poolID, mfa, observer) {
  
  const token = session.getIdToken().getJwtToken()

  const identity = yield select(
    state => state.config.identity.params
  )

  if ( token && identity && identity.IdentityPoolId ) {
    
    if ( AWS.config.credentials && AWS.config.credentials.clearCachedId ) {
      AWS.config.credentials.clearCachedId()
    }
    
    AWS.config.credentials = new CognitoIdentityCredentials({
      ...identity,
      Logins: {
        [`cognito-idp.${AWS_REGION}.amazonaws.com/${poolID}`]: token
      }
    })

    AWS.config.credentials.refreshPromise()
      .then(() => handleUserDataSync(observer))
      .then(userIdentityID => {
        observer.publish('user_session', session, userIdentityID)
      })
      .catch(error => {
        console.error('Failed to Establish AWS User Session: ', error.message)
      })

  }
}
```

**Proper Solution?**

Probably the better solution is to clear the cache during signOut which also fixes this bug.

```js
// aws.js
export function clearAWSCache() {
  AWS.config.credentials.clearCachedId()
}
```

```js
// cognito.js
export function* userLogout(observer) {
  yield call(getPool)
  yield call(getUser)

  if ( User ) {
    // If we have a User then we will sign them out
    User.signOut()
    // We need to clear the AWSCache or we can not re-login with a different user
    clearAWSCache()
    if ( typeof observer.publish === 'function' ) {
      observer.publish('signout')
    }
  }
  // remove locally cached
  User = undefined
  PoolData = undefined
  PoolID = undefined
}
```

**Comment by itrestian** [comment]
Thank you for bringing this up. A better integration between the main AWS SDK and the Cognito SDK for Javascript is on the roadmap. Just to be clear, you mean mention in the documentation that if you integrate User Pools with Cognito Identity, one would need to clear the credentials as well so that we use credentials obtained by the newly authenticated user?
