### ISSUE TITLE
Automatic login for a user in the background

### ISSUE THREAD

**Issue by tbachosz** [aws/amazon-cognito-identity-js#449]
Hello,

I looked through the examples and other issues and I still do not understand - how do I keep my user signed in? I am making an Android App in Java and I am trying to have the behavior like with majority of apps (example: Instagram). I want to keep user signed in all the time, unless he or she logs out. How to achieve this? All I see is I can refresh the credentials, to keep session going on, hence check the session once the user logs in. But how to referesh them if they do not exist after an hour. Say user has turned off his or her phone, and turns it on again to log in. How can I do it without saving user and password to Shared Preferences, which seems too dangerous to me? Is the only possibility scheduling a job in the background that refereshes credentials every 59 minutes?

Thank you for help!

**Comment by itrestian** [comment]
Here's a sample app for Android that showcases that functionality.

https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo

**Comment by tbachosz** [comment]
I will look this up during the weekend and see how it works

**Comment by chapeljuice** [comment]
I have the same question except for React Native. Are there any examples that people know of?

**Comment by tbachosz** [comment]
I looked into the application and did not find any solution to the problem. It seems like a basic activity for logging in and remembering the details, but I cannot find the system to refresh the user's session. Could you point to the exact place in the code which does it?

**Comment by tbachosz** [comment]
Does remembering the device is connected to this problem?

**Comment by itrestian** [comment]
The session management should be abstracted by the SDK by using the refresh token internally. Any APIs you call in Android will first try to see if the access token is valid and use the refresh token to get a new valid access token if it is not. Otherwise you would get an exception to re authenticate the user.
