### ISSUE TITLE
not a constructor

### ISSUE THREAD

**Issue by AlexMcConnell** [aws/amazon-cognito-identity-js#45]
I did my best to follow the directions. Not sure if I succeeded or not, but I'm getting these errors:

TypeError: AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool is not a constructor
TypeError: AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails is not a constructor

**Comment by itrestian** [comment]
Hi Alex,

How are you instantiating the 2 objects? Are you using new and passing the json data objects that they expect? Are any of the other classes causing problems?

Ionut.

**Comment by AlexMcConnell** [comment]
As far as I can tell, I've done it the same as the README:

```
AWS.config.region = 'us-east-1'; // Region
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'xxx' // your identity pool id here
});

AWSCognito.config.region = 'us-east-1';
AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({
    IdentityPoolId: 'xxx' // your identity pool id here
});

// Need to provide placeholder keys unless unauthorised user access is enabled for user pool
AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'})

function login(user) {
  var authenticationData = {
      Username : user.username,
      Password : user.password,
  };
  var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
  var poolData = { 
      UserPoolId : 'xxx',
      ClientId : 'xxx'
  };
  var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
  var userData = {
      Username : user.username,
      Pool : userPool
  };
  var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
  cognitoUser.authenticateUser(authenticationDetails, {
      onSuccess: function (result) {
          console.log('access token + ' + result.getAccessToken().getJwtToken());
      },

      onFailure: function(err) {
          alert(err);
      },
  });
};
```

**Comment by itrestian** [comment]
Hi Alex,

So I think the problem is that you have an error in that the line 

AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({

should be 

AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({

Note that you don't actually need all that part if you don't require AWS credentials. So this can be replaced

AWS.config.region = 'us-east-1'; // Region
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'xxx' // your identity pool id here
});

AWSCognito.config.region = 'us-east-1';
AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({
    IdentityPoolId: 'xxx' // your identity pool id here
});

// Need to provide placeholder keys unless unauthorised user access is enabled for user pool
AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'})

with only:

AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'})

if all you need to do is work with User Pools.

Ionut.

**Comment by AlexMcConnell** [comment]
This did not fix the problem.

I would have actually been pretty surprised if it had, since the problem is with code that runs after that stuff.

**Comment by itrestian** [comment]
Hi Alex,

I will try to reproduce. What are the libraries you are including and in what order?

Ionut.

**Comment by JeffMangan** [comment]
I was getting this same error and realized my ref path to one of the js files was incorrect.  I fixed that and the error went away.  Double check all your refs to the js files and try again.  I think it was this one but not 100% sure. 
moment.js

**Comment by itrestian** [comment]
Does this solve it for you as well, Alex?

Ionut.

**Comment by AlexMcConnell** [comment]
No, all my references are correct, although the npm package for jsbn doesn't have jsbn.js and jsbn2.js and just has index.js, so there could be something there. My scripts:

```
<script src="node_modules/angular/angular.js"></script>
<script src="node_modules/angular-ui-router/release/angular-ui-router.min.js"></script>

<script src="app.module.js"></script>

<script src="node_modules/jsbn/index.js"></script>
<script src="node_modules/sjcl/sjcl.js"></script>
<script src="node_modules/moment/min/moment.min.js"></script>
<script src="vendor/aws-cognito-sdk.min.js"></script>
<script src="vendor/amazon-cognito-identity.min.js"></script>
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.3.15.min.js"></script>
```

**Comment by guylhermetabosa** [comment]
I faced this problem a little time ago, the problem was related to the file `jsbn2.js`, that i was forgetting to put in my applicattion. As you said, the issue could be related with those files (`jsbn2.js` and `jsbn.js`).

**Comment by AlexMcConnell** [comment]
It's not really a matter of forgetting. It's simply not in the npm package. Perhaps I need to download and install it directly like it's 2005 or something.

**Comment by itrestian** [comment]
Is this working now? I have tried a similar setup as well within node and it seems to be working for me.

**Comment by sabirali007** [comment]
I have same problem 
Uncaught TypeError: AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool is not a constructor

my js files
<script src="js/aws-cognito-sdk.min.js"></script>
    <script src="js/amazon-cognito-identity.min.js"></script>
    <script src="js/aws-sdk-2.6.10.js"></script>

**Comment by dorarep** [comment]
I had same problem when I used vue.js + nuxt.js.
I've solved this problem this way.

```
const {AuthenticationDetails} = require('amazon-cognito-identity-js')
...
const authenticationDetails = new AuthenticationDetails({
```
