### ISSUE TITLE
Can github account be used as identity provider for my app?

### ISSUE THREAD

**Issue by syang** [aws/amazon-cognito-identity-js#450]
I understand that google, Facebook and twitter are integrated as identity providers in Cognito Federated Identities. If I want to build my webapp so that my users can sign-up with her github account, I.e, I want to have github as ine of the IDP, is that possible? And how?

**Comment by prem911** [comment]
On similar lines, do we have any working example of using LinkedIn?

**Comment by syang** [comment]
@itrestian could you please take a quick look at this question?

**Comment by ankitnaugariya** [comment]
Amazon Cognito does not support (Git and LinkedIn as IDP) at the current time. We have heard this request from other customers and will consider it in future updates to the service.
