### ISSUE TITLE
Understanding UserPools App Integration beta

### ISSUE THREAD

**Issue by prem911** [aws/amazon-cognito-identity-js#451]
Went through the documentation
http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-federation-beta-release-overview.html
It says that Fedration to a SAML is optional. So, without SAML how does the app integration work?
Is the app integration an OAuth Provider for the userpool?
If yes, how do we do the OAuth "dance" to get the tokens?

**Comment by rachitdhall** [comment]
Hi,

Yes SAML is optional and App Integration does enable you to be an OAuth Provider (each user pool can be an OAuth provider). To do the OAuth "dance" just follow the OAuth spec for any flow. I will try and provide an example for code grant flow:

1. Start with the authorize endpoint
<user_pool_domain>/authorize?redirect_uri=<redirect_uri_as_configured _in_console>&response_type=code&client_id=<client_id_for_which_this_flow_isEnabled>

There are more parameters which are outlined in the link in your question. This would authenticate the user (with their preferred mode, for your use case with username password) and redirect with an authorization code to the redirect URL provided.

2. After this you can use the [token endpoint](http://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) with the code provided to get the tokens.
