### ISSUE TITLE
How to access the UserSub

### ISSUE THREAD

**Issue by gchokeen** [aws/amazon-cognito-identity-js#453]
Hi,

I am using cognition in angular 4 using javascript SDK. I am using UserSub as primary key in my graph database to create a unique node. I don't know how to access the UserSub once user logged in. I want to use this UserSub all over the application. Is there any easy way to access the UserSub.

I can access the identityId as below. but how can use the sub.

`AWS.config.credentials.identityId `

**Comment by itrestian** [comment]
It should be in the id token or it should be available when you retrieve user attributes.

**Comment by gchokeen** [comment]
Thanks, I took from idToken
