### ISSUE TITLE
IdentityServer3 as Federated Identity for AWS Cognito

### ISSUE THREAD

**Issue by lucasklaassen** [aws/amazon-cognito-identity-js#454]
# Question

Hey guys, just wondering if anyone has used AWS Cognito with IdentityServer3 as an OpenID Federated Identity for a user pool? I'm currently working on a Cognito project that may have to integrate with IdentityServer3 and was just wondering if anyone out there has gone through this successfully.

**Comment by rachitdhall** [comment]
I have answered your question on [StackOverflow](https://stackoverflow.com/questions/44703925/identityserver3-as-idp-for-aws-cognito). Closing this issue as duplicated as well as not related to JS SDK. Please use [Amazon Cognito forum](https://forums.aws.amazon.com/forum.jspa?forumID=173) or Stackoverflow for general Cognito questions.
