### ISSUE TITLE
How to use User inputted username and password through html form in signup process?

### ISSUE THREAD

**Issue by darspatel** [aws/amazon-cognito-identity-js#455]
Hi,
I was wondering how to use variable username and password which is submitted by user in HTML form. I am passing username and password into javascript function defined in<script> tag. Below is my code:
	
	<script language="javascript">		
	function signUpFunction(newEmail, newNumber, newUserid, newPassword)
	{		
		var CognitoUserPool = AmazonCognitoIdentity.CognitoUserPool;
	
		var poolData = {
			UserPoolId : File_UserPoolId, 
			ClientId : File_UserPoolClientId 
		};
		var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
		
		var userData = {
			Username : newUserid,
			Pool : userPool
		};
		
		var attributeList = [];
	
		var dataEmail = {
			Name : 'email',
			Value : newEmail
		};
		var attributeEmail = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataEmail);
		attributeList.push(attributeEmail);
		
		var dataPhoneNumber = {
			Name : 'phone_number',
			Value : newNumber
		};
		var attributePhoneNumber = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute(dataPhoneNumber);		
		attributeList.push(attributePhoneNumber);
		
		var userid = newUserid;
		var pass = newPassword;
		
		userPool.signUp(userid, pass, attributeList, null, function(err, result){
			if (err) {
				console.log(err);
				return;
			}
			cognitoUser = result.user;
			console.log('user name is ' + cognitoUser.getUsername());
		});
	}
</script>`

**Comment by itrestian** [comment]
Why can't you fetch the username and password from the corresponding HTML elements?
