### ISSUE TITLE
How to use Cognito by importing just AWS SDK for JavaScript?

### ISSUE THREAD

**Issue by dotchev** [aws/amazon-cognito-identity-js#458]
The readme says:

> Note that the Amazon Cognito AWS SDK for JavaScript is just a slimmed down version of the AWS Javascript SDK namespaced as AWSCognito instead of AWS.

Then in the usage example:
```js
    // Under the original name:
    var CognitoUserPool = AWSCognito.CognitoIndentityServiceProvider.CognitoUserPool;
```

But there is no `CognitoUserPool` class in [AWS SDK for JavaScript](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/).

So how can one use Cognito by importing just AWS SDK for JavaScript?

**Comment by itrestian** [comment]
That means that you can use amazon-cognito-identity.min.js + aws-cognito-sdk.min.js

https://github.com/aws/amazon-cognito-identity-js/tree/master/dist

aws-cognito-sdk is built from the aws-sdk just by using the cognito part of it by doing:
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html

Or you can use the main aws-sdk instead of the aws-cognito-sdk.

**Comment by dotchev** [comment]
Where can I find the documentation of `CognitoUserPool` and its methods?
I could not find it in AWS SDK API reference.
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/index.html

**Comment by itrestian** [comment]
In the Cognito documentation. As I mentioned, this SDK is not part of the main AWS Javascript SDK.

http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html

**Comment by dotchev** [comment]
Those examples are fine, but where can I find API reference documentation with description of each parameter, return value, etc.?
e.g. for this function call
```js
userPool.signUp('username', 'password', attributeList, null, function(err, result){
```

**Comment by itrestian** [comment]
The parameters are the ones mentioned in the documentation for each API call with the only just that the Javascript SDK doesn't allow passing a client secret. This SDK is just a wrapper around the main AWS SDK that provides a Secure Remote Password protocol implementation, similar to our Android and iOS SDKs.

http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html
