### ISSUE TITLE
Is it possible to make Amazon Cognito to send SMS messages by other sms provider

### ISSUE THREAD

**Issue by ijustyce** [aws/amazon-cognito-identity-js#459]
I am a Chinese developer , and I used Amazon Cognito in my app, but Amazon SNS is not a good choice for Chinese user.

I want to use Amazon Cognito but send sms by Chinese sms provider (such as aliyun). How can I do this? Is it possible now ?

**Comment by rachitdhall** [comment]
Can you please let us know what are the pain points of using Amazon SNS for Chinese user?

Amazon Cognito does not support (SMS provider other than Amazon SNS) at the current time. We have heard this request from other customers and will consider it in future updates to the service.

**Comment by ijustyce** [comment]
Amazon SMS price is too expensive（6-7 times） for China, almost $0.04543 , but if we use China sms provider it less than $0.007. @rachitdhall

**Comment by sabri916** [comment]
This might be an old issue, but I'd like to add my voice as well. Regulations in my country (Oman) are iffy when it comes to SMS from abroad. Most of my clients insist on using local SMS providers.
