### ISSUE TITLE
How would I use this having id_token after successful SAML 2.0 IP auth?

### ISSUE THREAD

**Issue by Nogbit** [aws/amazon-cognito-identity-js#461]
`cognitoUser` is always null.  When stepping through the SDK code it's because it's looking at `window.localStorage` and finds nothing there.  Though there are no examples in the readme or advice even on the best practice of taking the id_token from the query string of a logged in user and using that with this SDK (if even that is the solution).  I can authenticate fine and have the id_token in the URL, it's the resulting static page (code below) that I want to use this SDK on.

Do I need to do some work manually as outlined at http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html in order to use http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html with this repo?

```JavaScript
<script src="....aws-cognito-sdk.js"></script>
<script src="....amazon-cognito-identity.js"></script>
<script src="....aws-sdk.min.js"></script>


var clientId   = 'MY CLIENT ID';
var poolData = {
    UserPoolId : 'MY POOL ID',
    ClientId : clientId
};
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
var cognitoUser = userPool.getCurrentUser();

if (cognitoUser != null) {
  console.log('cognitoUser is', cognitoUser);
  cognitoUser.getSession(function(err, result) {
    if (result) {
      console.log('You are now logged in.');

      // Add the User's Id Token to the Cognito credentials login map.
      AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId: 'MY POOL ID',
        Logins: {
          'cognito-idp.uw-west-2.amazonaws.com/MY POOL ID': result.getIdToken().getJwtToken()
        }
      });
    }
  });
} else {
  console.error('cognitoUser is null');
}

```

**Comment by Nogbit** [comment]
Hmm, I think maybe this repo has not been updated to work with the new beta SAML 2.0 IP auth.  But, it does look like I can possibly prime the storage using [the same expected schema](https://github.com/aws/amazon-cognito-identity-js/blob/3e960090751b4d03f4acae568d2fe9c7cac21110/src/CognitoUser.js#L835-L849).  That will still require some work though to validate the signature and grab the username.  Is there an ETA on when this will work more seamlessly with SAML 2.0 IP?

**Comment by itrestian** [comment]
I think you want to have a look at: https://github.com/aws/amazon-cognito-auth-js

**Comment by Nogbit** [comment]
Fantastic, thanks!
