### ISSUE TITLE
Prop Action is undefined when used after successful authentication 

### ISSUE THREAD

**Issue by fdm20** [aws/amazon-cognito-identity-js#462]
Hi All,

I'm trying to use  this.props.actions.createNewUserIdAsync(this) with the function that runs after successful authentication however the get the error that the "action" is undefined.

createNewUserIdAsync pulls information from a database so it can be displayed.

Can anyone help? I'm still new to cognate and react.

thanks!

class SignUpForm extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
    };
      
      
    
      
  }

    
    
  handleEmailChange(e) {
    this.setState({email: e.target.value});
  }

  handlePasswordChange(e) {
    this.setState({password: e.target.value});
  }

  handleSubmit(e) {
    //  this.handleClick 
     
    e.preventDefault();
    const email = this.state.email.trim();
    const password = this.state.password.trim();
    const attributeList = [
      new CognitoUserAttribute({
        Name: 'email',
        Value: email,
      })
    ];  

      
      
        var authenticationData = {
        Username : this.state.email,
        Password : this.state.password,
    };
      
       
    var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
      var userData = {
        Username : this.state.email,
        Pool : userPool
    };
      
      
                      

        var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
    this.props.actions.createNewUserIdAsync(this);  (Action is Undefined)!!!!!

 console.log('access token + ' + result.getAccessToken().getJwtToken());
            /*Use the idToken for Logins Map when Federating User Pools with Cognito Identity or when passing through an Authorization Header to an API Gateway Authorizer*/
            console.log('idToken + ' + result.idToken.jwtToken);
             cognitoUser.getUserAttributes(function(err, result) {
        if (err) {
            alert(err);
            return;
        }
        for (i = 0; i < result.length; i++) {
            console.log('attribute ' + result[i].getName() + ' has value ' + result[i].getValue());
        }
    });
            
    if (cognitoUser != null) {
        cognitoUser.getSession(function(err, session) {
            if (err) {
               alert(err);
                return;
            }
            console.log('session validity: ' + session.isValid());

         console.log('user name is ' + cognitoUser.getUsername());

            // Instantiate aws sdk service objects now that the credentials have been updated.
            // example: var s3 = new AWS.S3();

        });         
            
    }
           
             AWS.config.credentials = new AWS.CognitoIdentityCredentials({
                 region: 'us-west-2',
    IdentityPoolId: APP_CONSTANT.IDENTITY_POOL_ID,
    Logins: {
        'cognito-idp.us-west-2.amazonaws.com/us-west-2_': 
 result.getIdToken().getJwtToken()
    }
});
 

            AWS.config.credentials.get(function(err) {
              if (err) console.log(err);
              else console.log("Cred",AWS.config.credentials);
            });
            
            var db =  new AWS.DynamoDB({region: 'us-west-2'});
            db.listTables(function(err, data) {
                if (err) console.log(err, err.stack);
                else console.log(data.TableNames);
            });
            /////////////////
            

            /////////////////
            
            
            
        
        
        
        
        
        
        
        
        },

        onFailure: function(err) {
            alert(err);
        },

    });
      
      this.props.actions.createNewUserId(cognitoUser.getUsername())
      
  }

  render() {
    return (
      <form onSubmit={this.handleSubmit.bind(this)}>
        <input type="text"
               value={this.state.email}
               placeholder="Email"
               onChange={this.handleEmailChange.bind(this)}/>
        <input type="password"
               value={this.state.password}
               placeholder="Password"
               onChange={this.handlePasswordChange.bind(this)}/>
        <input type="submit"/>
      </form>
    );
  }
}

**Comment by itrestian** [comment]
This seems more of a react than a cognito question. Leaving open for the community to see.

**Comment by itrestian** [comment]
You can have a look at AWS Amplify which exposes a higher order auth component based on react for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo.

https://github.com/aws/aws-amplify
