### ISSUE TITLE
A little help on Server side auth

### ISSUE THREAD

**Issue by iq-dot** [aws/amazon-cognito-identity-js#463]
Hi Guys,

I just needed a little help on a server side based auth.

I need to manage fully all the authentication on the back-end, including login and retrieval of user on every request. The client will only receive the access token after logging in.

I am clear on the part about logging in, what I am unsure of and could not find on the documentation is **how to retrieve the User again using the 'access token'** (or rather how to have a cognitoUser object authenticated using just a token) and also **refreshing the token** on every request.

If you could nudge me in the right direction for those two I would greatly appreciate the help.

I am also using the standard auth flow, is there a way to use the AdminAuth flow?

**Comment by itrestian** [comment]
You would need to use the main aws sdk to work with the AdminAuth flow.

https://github.com/aws/aws-sdk-js

This SDK covers mostly the client side browser operations.

**Comment by iq-dot** [comment]
Ok cheers, thanks
