### ISSUE TITLE
Don't send forgot password code through sms

### ISSUE THREAD

**Issue by yulric** [aws/amazon-cognito-identity-js#464]
Hi,

In my aws cognito console. in the verifications tab I set it it up so that all verification codes are sent only through email. But when a user has a verified email and phone number and a forgot password request is sent, the verification code is always sent through an SMS. Any idea how to prevent this?

Thanks

**Comment by itrestian** [comment]
Not possible at this point but we can take this as a feature request. When phone number is also confirmed, SMS is always preferred.

**Comment by yulric** [comment]
Ok, it would be great if this was a feature. In the meantime, is it possible to also send an email along with the SMS message?

**Comment by itrestian** [comment]
Yes, I marked that as a feature request.
