### ISSUE TITLE
Big Number Library over Big Integer

### ISSUE THREAD

**Issue by kadeatfox** [aws/amazon-cognito-identity-js#47]
Hello,

I'm sure you guys will be coming up with a node implementation for this. (and probably with a lot less crypto graphic functions because it will be server side)

Please consider using Big Number of Big Integer. Big Integer has terrible performance in node 👎

**Comment by itrestian** [comment]
Hi kadeatfox,

Thanks for the suggestion. Indeed, different big integer libraries can have a huge performance impact on SRP math.

Ionut.

**Comment by itrestian** [comment]
After checking big number, it seems that it doesn't have the an implementation of the modPow function. It shouldn't be that hard to implement it since it. Big Integer has an implementation of it and jsbn also has an implementation of it.

https://www.npmjs.com/package/jsbn
