### ISSUE TITLE
Using window.sessionStorage and rememberThisDevice

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#472]
Right now, I am using window.sessionStorage to store the cognitoUser and retrieve the userPool. This achieves the desired behavior of not remembering a user and always automatically logging them in on fresh sessions.

However, this does not allow me to rememberThisDevice because each session creates a new and different device key.

So I guess this is a two part issue and question:
1. Is using window.sessionStorage the best way (only way?) to achieve my desired affect of only remembering a logged in user per session?

2. Is there a way to store the deviceKey in local storage, and using that, assuming #1 is correct and I continue to use sessionStorage to store my cognitoUser?

**Comment by itrestian** [comment]
What exactly is the use case you are targeting? Do you want the user to stay logged in only in the current tab and not across browser restarts?

**Comment by ghost** [comment]
Yes, that is exactly the use case I am looking for.
