### ISSUE TITLE
Different CognitoUserPool methods between Webpack and using Script tags - I can't getCurrentUser with Webpack

### ISSUE THREAD

**Issue by villagebike** [aws/amazon-cognito-identity-js#474]
Hello,
I am trying to follow the latest guide which allows CognitoIdentity to be used with Webpack.
However, I can no longer use getCurrentUser() to return the authentication details once I refresh the page after a successful login. Using webpack to import Cognito I get the following UserPool Object

```
 {
  "userPoolId": "us-west-2_DKJaaaaa",
  "clientId": "1arl8pglu5aaaaaaaaaaaaa",
  "client": {
    "config": {
      "credentials": {
        "expired": false,
        "expireTime": null,
        "accessKeyId": "anything"
      },
      "credentialProvider": null,
      "region": "us-west-2",
      "logger": null,
      "apiVersions": {},
      "apiVersion": "2016-04-19",
      "endpoint": "cognito-idp.us-west-2.amazonaws.com",
      "httpOptions": {
        "timeout": 3600000
      },
      "maxRedirects": 10,
      "paramValidation": true,
      "sslEnabled": true,
      "s3ForcePathStyle": false,
      "s3BucketEndpoint": false,
      "s3DisableBodySigning": true,
      "computeChecksums": true,
      "convertResponseTypes": true,
      "correctClockSkew": false,
      "customUserAgent": null,
      "dynamoDbCrc32": true,
      "systemClockOffset": 0,
      "signatureVersion": "v4",
      "signatureCache": true,
      "retryDelayOptions": {},
      "useAccelerateEndpoint": false
    },
    "isGlobalEndpoint": false,
    "endpoint": {
      "protocol": "https:",
      "host": "cognito-idp.us-west-2.amazonaws.com",
      "port": 443,
      "hostname": "cognito-idp.us-west-2.amazonaws.com",
      "pathname": "/",
      "path": "/",
      "href": "https://cognito-idp.us-west-2.amazonaws.com/"
    },
    "_clientId": 1
  },
  "storage": {}
}
```

When I import using <script> tags I get this UserPool object : 
```
{
  "userPoolId": "us-west-2_DKJaaaaa",
  "clientId": "1arl8pglu5aaaaaaaaaaaaa",
  "paranoia": 0,
  "client": {
    "config": {
      "credentials": {
        "expired": false,
        "expireTime": null,
        "accessKeyId": "anything"
      },
      "credentialProvider": null,
      "region": "us-west-2",
      "logger": null,
      "apiVersions": {},
      "apiVersion": "2016-04-19",
      "endpoint": "cognito-idp.us-west-2.amazonaws.com",
      "httpOptions": {
        "timeout": 120000
      },
      "maxRedirects": 10,
      "paramValidation": true,
      "sslEnabled": true,
      "s3ForcePathStyle": false,
      "s3BucketEndpoint": false,
      "s3DisableBodySigning": true,
      "computeChecksums": true,
      "convertResponseTypes": true,
      "correctClockSkew": false,
      "customUserAgent": null,
      "dynamoDbCrc32": true,
      "systemClockOffset": 0,
      "signatureVersion": "v4",
      "signatureCache": true,
      "retryDelayOptions": {
        "base": 100
      },
      "useAccelerateEndpoint": false
    },
    "isGlobalEndpoint": false,
    "endpoint": {
      "protocol": "https:",
      "host": "cognito-idp.us-west-2.amazonaws.com",
      "port": 443,
      "hostname": "cognito-idp.us-west-2.amazonaws.com",
      "pathname": "/",
      "path": "/",
      "href": "https://cognito-idp.us-west-2.amazonaws.com/"
    },
    "_clientId": 1
  }
}
```

Note that there seems to be a "storage" parameter in the webpack imported object that doesn't exist in the script tag version. 

Anyway, when I use the script tag, I can successfully use userPool.getCurrentUser() to get the information for the logged in user. When I use Webpack 2 I am return 'null'.

Can anybody help me?

**Comment by villagebike** [comment]
This is what I am doing when using Webpack 2: 

```
import AWS from 'aws-sdk';
import {
    CognitoUserPool,
    CognitoUserAttribute,
    CognitoUser,
    AuthenticationDetails
} from 'amazon-cognito-identity-js';

import appConfig from "./credentials";

var userPool;
var cognitoUser;

var credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: appConfig.IdentityPoolId,
    Region: 'us-west-2',
});

AWS.config.region = appConfig.region;
AWS.config.credentials = credentials;
AWS.config.httpOptions = {
    timeout: 3600000
};

AWS.config.update({
    accessKeyId: 'anything',
    secretAccessKey: 'anything'
});


var poolData = {
    UserPoolId: appConfig.UserPoolId,
    ClientId: appConfig.ClientId
};
var userPool = new CognitoUserPool(poolData);
var cognitoUser = userPool.getCurrentUser() // returns null
```


This is what I am doing when I have imported Cognito using script tags 

```
var creds = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: identityPoolId
});
AWS.config.region = region; 
AWS.config.credentials = creds;
AWS.config.httpOptions = {
    timeout: 3600000
}
// Cognito User Pool Id
AWSCognito.config.region = region;
AWSCognito.config.credentials = creds;
AWSCognito.config.update({
    accessKeyId: 'anything',
    secretAccessKey: 'anything'
});
var poolData = {
    UserPoolId: userPoolId,
    ClientId: clientId
};
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
//returns user
```

**Comment by itrestian** [comment]
Storage shouldn't depend on the particular bundler, it depends on the environment the code is running in (defaults to local storage, if that is not available, stores stuff in memory). You can also pass a particular storage method to the user pool constructor, maybe give that a shot? The two objects look like the objects coming from the SDK so your setup seems to be working.

**Comment by villagebike** [comment]
Thanks. 
I know the login is getting stored correctly because I can login successfully using the Webpack bundled method and then retrieve that very session ( using userPool.getCurrentUser()) on the page built using script tags.
What I can't do is authenticate using the Webpack environment and then also retrieve that session on the Webpack page after I refresh the page.

So I know that I am storing the credentials correctly using the Webpack based authentication process, I just can't work out how to retrieve the correct CognitoUser again in my Webpack environment.

I'll try and explicitly set the UserPool to use local storage but as I can retrieve the session using my page with script tag loaders I don't think it can be that...

**Comment by itrestian** [comment]
local storage is based on current page as well, are you sure you're on the same page when you're retrieving the user?

**Comment by villagebike** [comment]
I authenticate successfully and can access other aws resources using the session... Until I press refresh on the browser and then null is returned when I try and load the userpool.getcurrentuser method.

I am authenticating and trying to retrieve the session on the same page. 

Why would my userpool object have a 'storage'  key with no value when using the webpack es6 imported but this key is not present at all on my non-webpack page?

**Comment by itrestian** [comment]
That is strange indeed. Maybe try passing the particular storage in the constructors to make sure it is the same.

**Comment by villagebike** [comment]
Hey Itrestian.
Thanks for your help with this issue. It turns out a module I was importing in my Webpack project was wiping the local storage on page load. Not looked into it too much - I just removed the module and it all seems to work now. Sorry for wasting your time.
