### ISSUE TITLE
Request to port Custom Challenge Response from mainline AWS SDK

### ISSUE THREAD

**Issue by mahbub02** [aws/amazon-cognito-identity-js#475]
Hello,

We want to create a custom authentication workflow so that users can reset their password. We can't use the current provided `forgotPassword` function since it emails the user a token, but in our environment, the user does not have access to the internet (user first needs to login to gain access to the internet) at the time that they want to reset their password. We want to be able to bypass this and instead let the user authenticate using their security question and answer.

But when we use this SDK, [this line in `CognitoUser.js`](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L158) is hard-coded to require the user's password (SRP_A). 

We contacted the AWS SDK before, and [they provided a way for us to create a custom workflow](https://aws.amazon.com/blogs/mobile/customizing-your-user-pool-authentication-flow/), however these changes have not been ported into this SDK.

Would you be able to port this feature or provide a way for us to supply a callback to create a custom authentication workflow to bypass the SRP_A?

**Comment by itrestian** [comment]
How do you plan to change the password since the change password API requires knowledge of the previous password (Use case 11)?

**Comment by gdw2** [comment]
@itrestian , I'm with @mahbub02 .  Ignore the nuance about the forgotten password.  I think our issue is already discussed here: https://github.com/aws/amazon-cognito-identity-js/issues/228, so I will continue the conversation over there.

**Comment by itrestian** [comment]
Got it.

**Comment by itrestian** [comment]
We just added the call to initiate auth to the SDK in the dist folder. You should be fine for your use case by calling initiateAuth and this would call customChallenge for the user to provide input and you can call cognitoUser.sendCustomChallengeAnswer(challengeAnswer, this) to subsequently reply to the challenge. If something doesn't work, let me know.

https://github.com/aws/amazon-cognito-identity-js/commit/56a13d8065b34f7f57b44ee7ec2fedc3b4818e54#diff-26892805fc0b4c2b37c713f88295be13R126
