### ISSUE TITLE
Cognito Forgot password for Admin authentication in .net core 

### ISSUE THREAD

**Issue by kallam9** [aws/amazon-cognito-identity-js#476]
I am performing  admin authentication of the user and need to perform the Forgot password with Cognito.
However I am not providing an option for Multifactor authentication (where in cognito sends the confirmation code either to email or password, I am using my own notification service to do that) , So I just need the cognito to accept the reset the password as an admin. and set the new password to username. Is there any way it can be done ?

**Comment by itrestian** [comment]
Functionality for the admin to set a password for a user is in the backlog. However, I cannot comment on the availability date.
