### ISSUE TITLE
userPool.getCurrentUser() returns null in React Native

### ISSUE THREAD

**Issue by jiahaochua** [aws/amazon-cognito-identity-js#478]
I am using this library to provide cognito user pool authentication for my react native app. However, the access/id tokens are expiring after one hour, and I am unable to refresh them as the userPool.getCurrentUser() function returns null, and thus I cannot get the session to force a refresh.

My code is based on the example provided in this guide https://shellmonger.com/2017/05/15/authenticating-react-native-to-aws-cognito-user-pools/
which is essentially the same as your use case 4 and use case 16

This function works if I call it immediately after authenticateUser during Login. However, if I try to call the function again anytime after, getCurrentUser just returns null. Is this an issue with my code or is there a known issue with react native?

**Comment by itrestian** [comment]
What library are you using for react native? React native doesn't have local storage available to store the tokens so adaptations need to be made to support async storage. There are a couple of versions available out there.

**Comment by jiahaochua** [comment]
Thanks for the response.
I have simply been using this library and the aws javascript sdk, with the imports adjusted to reference the react native version. If it is just a storage issue, would I be looking for a library like this?
 https://www.npmjs.com/package/react-native-aws-cognito-js
Alternatively, could I just rework the StorageHelper class to use AsyncStorage instead?

**Comment by itrestian** [comment]
I believe the library you mentioned does that.

**Comment by jiahaochua** [comment]
Ok thanks for the help
