### ISSUE TITLE
Password attempts exceeded needs its own error code

### ISSUE THREAD

**Issue by jstradli** [aws/amazon-cognito-identity-js#479]
When a user has exceeded their password attempts the error code is set to "NotAuthorizedException".  However this is the same error code you get when they simply enter the wrong credentials the only difference is the message property has a different value.

Wrong password:   message === **"Incorrect username or password"**
too many attempts: message === **"Password attempts exceeded"**

It is fairly easy to reproduce, just execute cognitoUser.authenticateUser() maybe 10 times or so in succession with the incorrect password.  Then execute it again with the correct password and you will see it return the "NotAuthorizedException" with the message field set to "Password attempts exceeded"

It is unwise to program off of the message field as this can possibly change over time.  To correctly handle this I believe amazon-cognito-identity-js should provide a new error code for this situation such as "PasswordAttemptsExceeded" for example.

**Comment by itrestian** [comment]
Thank you for bringing this up. I will mention this desired behaviour within the team.
