### ISSUE TITLE
Breaking Password Reset Function in to 2 Parts

### ISSUE THREAD

**Issue by Arunaliyanaarachchi** [aws/amazon-cognito-identity-js#481]
Hi ,
In Use Case 12 we have Complete Password reset Process and it Works Great.

` cognitoUser.forgotPassword({
        onSuccess: function (data) {
            // successfully initiated reset password request
	    console.log('CodeDeliveryData from forgotPassword: ' + data);
        },
        onFailure: function(err) {
            alert(err);
        },
        //Optional automatic callback
        inputVerificationCode: function(data) {
            console.log('Code sent to: ' + data);
            var verificationCode = prompt('Please input verification code ' ,'');
            var newPassword = prompt('Enter new password ' ,'');
            cognitoUser.confirmPassword(verificationCode, newPassword, this);
        }
    });`

But How i can put this Optional Automatic callback i to a different button..? that means reset the password in one button and once we receive the code we type it in another textbox (not a prompt) and using another button submit the code. tried so many ways nothing is working (but reseting and send the confimation code part is working) here i listed the one way i tried to do it,but still it gives me errors

`function Submitpasswordreset()
	{
		Providedemail = localStorage.getItem("Useremail");
		var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
		var userData = {
		        Username : Providedemail,
		        Pool : userPool
						};
		
		var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
		
		cognitoUser.confirmPassword(document.getElementById("confimationcode").value,document.getElementById("newpassword").value, function(err, result){
	        if (err) {
	            alert(err);
	            return;
	        }
	        console.log('Success: ' + result);
	        
	    });
	        
	    
	}
	`

**Comment by itrestian** [comment]
Think it should already work as you mentioned it. You basically can call forgotPassword without an inputVerificationCode function and call confirmPassword in a separate piece of code.

**Comment by Arunaliyanaarachchi** [comment]
Thanks for your reply .i tried but it didn't work.it gives me below error

`aws-cognito-sdk.min.js:21 Uncaught Error: n.onFailure is not a function
 at constructor.<anonymous> (amazon-cognito-identity.min.js:32)
 at constructor.<anonymous> (aws-cognito-sdk.min.js:21)
 at constructor.callListeners (aws-cognito-sdk.min.js:21)
 at constructor.emit (aws-cognito-sdk.min.js:21)
 at constructor.emitEvent (aws-cognito-sdk.min.js:21)
 at constructor.a (aws-cognito-sdk.min.js:21)
 at d.runTo (aws-cognito-sdk.min.js:22)
 at aws-cognito-sdk.min.js:22
 at constructor.<anonymous> (aws-cognito-sdk.min.js:21)
 at constructor.<anonymous> (aws-cognito-sdk.min.js:21)`


can you help me to solve this...?

**Comment by Arunaliyanaarachchi** [comment]
Use this One and it works

`
	function Submitpasswordreset()
	{
		Providedemail = localStorage.getItem("Useremail");
		var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
		var userData = {
		        Username : Providedemail,
		        Pool : userPool
						};
		
		var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
		
			cognitoUser.confirmPassword(document.getElementById("confimationcode").value,document.getElementById("newpassword").value, {
			onSuccess: function (Data) {
	  
				    console.log('Success: ' + Data);
		    
		    	       				   },
			onFailure: function (err)  
			{

		   			 console.log('Error: ' + err);
		     }
	       
	        
	    });
	        
	    
	}
	

	`

Thanks for Help..!
