### ISSUE TITLE
Using ES6 imports, everything global under AWS namespace

### ISSUE THREAD

**Issue by gitjeff05** [aws/amazon-cognito-identity-js#483]
Using create-react-app (**babel + webpack**) and following instructions [using npm and webpack](https://github.com/aws/amazon-cognito-identity-js#using-npm-and-webpack). After I ``npm install`` and import a module with: ``import { CognitoUserPool, CognitoUserAttribute, CognitoUser } from 'amazon-cognito-identity-js';``, I don't get the named methods like I would expect. I get the entire cognito identity API under the window global: **AWS**

### AWS
- CognitoIdentity
- CognitoIdentityCredentials
- CognitoIdentityServiceProvider
- Config
_...more_

Also when I use ``import { CognitoIdentityServiceProvider } from 'aws-sdk';`` I get what appears to be the entire aws-sdk API under the same global AWS namespace.

Furthermore, when I attempt to use: 

``new AWS.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);`` 

there is an error thrown: 

```AWS.CognitoIdentityServiceProvider.AuthenticationDetails is not a constructor``` 

Setting a breakpoint and checking the scope for ``AWS.CognitoIdentityServiceProvider`` I see:

```
function () {
  if (klass !== Object) {
    return klass.apply(this, arguments);
  }
}
```

What am I doing wrong?

**Comment by Vizards** [comment]
It's a little different when you use "import" method in example code, you need to import something before you use it.

For example, if you want to use these example code:

```
var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
```

You should write code like these in your app:

```
import { CognitoUser, AuthenticationDetails } from 'amazon-cognito-identity-js';

const cognitoUser = new CognitoUser(userData);
const authenticationDetails = new AuthenticationDetails(authenticationData);
```

Other functions are similar. 
I hope it can help you.
