### ISSUE TITLE
Documentation For "SerializationException"

### ISSUE THREAD

**Issue by lauraannwilliams** [aws/amazon-cognito-identity-js#485]
I suggest the Cognito docs be updated to include when SerializationException is returned. It's not on the list for any of the Cognito endpoints I'm using. 

I triggered this exception by submitting a boolean instead of a string for an AttributeType.Value and it was unexpected.

A good global place to note this might be with the attribute type documentation:
http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AttributeType.html or the Common Errors section http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/CommonErrors.html

**Comment by ankitnaugariya** [comment]
Thanks for your input. 
To identify best way to update the documents, can you please share the exception stacktrace.

**Comment by lauraannwilliams** [comment]
This error is actually from the API, not this library. Apologies for posting in the wrong place.
