### ISSUE TITLE
Difficulty handling Cognito exceptions, can't find additional doc

### ISSUE THREAD

**Issue by guilsa** [aws/amazon-cognito-identity-js#488]
Does AWS publicize the source code for Cognito? Some of the errors I know of I've discovered from experience. For example, why is `NotAuthorizedException` not listed on the Common Errors [1] page? 

[1]. http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/CommonErrors.html

**Comment by itrestian** [comment]
Not entirely sure, I think some of the API calls don't throw that particular exception. I can definitely mention this within the team. In general for this package, here is the model file in the main aws sdk that the APIs respect (including exceptions).

https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.normal.json

**Comment by guilsa** [comment]
thanks @itrestian. Will reopen if needed.
