### ISSUE TITLE
ClearCachedId is undefined after AWS.config.credentials.get

### ISSUE THREAD

**Issue by michaelyfan** [aws/amazon-cognito-identity-js#491]
(forgive the buggy markdown styling of code...my code is whatever's in between the backticks)

Hello,

I call clearCachedId() upon every signout, as in:

`
  signOut(callback) {
    AWS.config.credentials.clearCachedId();
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: IDENTITY_POOL_ID
    });

    this.state.activeUser.host.signOut();
    this.setState({
      activeUser: null
    }, callback);
  }
`

To prevent the "Logins don't match" error if signing in again with another account. This normally works fine, unless I make a call to get credentials (for later use with DynamoDB) before logging out. This is the method that contains the call to AWS.config.credentials.get:

`
  callDynamo(callback) {

    AWS.config.credentials.get(function() {
      AWS.config.update({
        accessKeyId: AWS.config.credentials.accessKeyId,
        secretAccessKey: AWS.config.credentials.secretAccessKey,
        sessionToken: AWS.config.credentials.sessionToken
      })
    
    });
    
    //react and dynamodb stuff...
  
    AWS.config.credentials.refresh((error) => {
      if (error) {
        console.error(error);
      }    
    });   

  }
`

If I try to sign out after calling this method, I get the error:
"Uncaught TypeError: _awsSdk2.default.config.credentials.clearCachedId is not a function"

Attempting to sign in again afterwards will result in the "Logins don't match" error.

Testing has revealed that clearCacheId is defined before calling AWS.config.update, but undefined after. Why is this? And what is a good way to work around this problem?

**Comment by itrestian** [comment]
That actually makes it really hard to understand the code. Could you post it in a better formatted way? Or a link to some website that would display it better?

**Comment by musso** [comment]
After user login, console log ```CognitoUser``` will show many other previous users including token, uid, email even they were sign-out ,as shown in picture below. May I know how to clear them? I tried to use ```AWS.config.credentials.ClearCachedId()``` but ```ClearCachedId()``` doesn't exist under ```AWS.config.credentials```. Many thanks!

![screen-shot-2018-02-09-at-6 31 39-pm](https://user-images.githubusercontent.com/2177290/36023654-1f06276c-0dc8-11e8-8768-ce23d16a435d.png)
