### ISSUE TITLE
cognito iss claim

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#492]
So we need to verify accessToken of a users, for that first we need to verify iss claim according to docs : http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html (step 3)

but the problem is that we have multiple user pools(in same region) so we cannot mention all iss claim url, so do we have any way to extract iss claim so that i can verify signature.

Thank you.

**Comment by vlekakis** [comment]
You have users that belong to multiple userPools? that's what you mean? The iss is userPool specific.

As the documentation [here](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-identity-user-pools-structure-of-access-tokens) says: 

> iss : The issuer. It has the following format: https://cognito-idp.{region}.amazonaws.com/{userPoolId}. For example, if you created a user pool in the us-east-1 region and its ID is u123456, the ID token
