### ISSUE TITLE
Error in Use case 23

### ISSUE THREAD

**Issue by ryan-ds17** [aws/amazon-cognito-identity-js#493]
in use case 23 I wrote the same function as is but an error occurs => authDetails.getValidationData is not a function.

**Comment by itrestian** [comment]
I don't think authDetails.getValidationData is in the example.

**Comment by ryan-ds17** [comment]
I have attached a file with the method I used and the error I got in 
[function.txt](https://github.com/aws/amazon-cognito-identity-js/files/1192689/function.txt)

comments.

**Comment by itrestian** [comment]
It's probably related to this that somehow you are getting an AuthenticationDetails object from some different package. 

https://github.com/aws/amazon-cognito-identity-js/issues/387

**Comment by ryan-ds17** [comment]
I created the whole project again and I got the output. The error was due to another package
https://github.com/kndt84/amazon-cognito-identity-js
