### ISSUE TITLE
userPool.getCurrentUser() === null

### ISSUE THREAD

**Issue by ljovanovic** [aws/amazon-cognito-identity-js#494]
Hello,

I have quick question on an aspect of some of the examples, specifically use cases 16 & 17.  The bulk of the logic is contained within an if statement that checks to see if ```userPool.getCurrentUser() != null```

My question is what a null value would indicate.  We've seen this happen a few times within our application - sometimes in cases where there is a valid session in local storage so I'm curious as to why getCurrentUser() could return null, so that I can better handle it within our application.

Thanks in advance for any insights.

**Comment by itrestian** [comment]
The behaviour should be pretty deterministic. The last successfully authenticated user is saved against the client id in local storage and retrieved when getCurrentUser is called. Tokens and last auth user are deleted upon sign out.

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUserPool.js#L112
