### ISSUE TITLE
How to handle system clock skew with Cognito?

### ISSUE THREAD

**Issue by mevatron** [aws/amazon-cognito-identity-js#495]
We've run into an issue where some clients have their system clock ahead by more that 3600 seconds and the `CognitoUserSession.isValid` is returning false:

```
isValid() {
    const now = Math.floor(new Date() / 1000);

    return now < this.accessToken.getExpiration() && now < this.idToken.getExpiration();
  }
```
Obviously, this is causing authenticated actions to fail.

I have seen references on `aws-sdk` to correct clock skew issues by setting `AWS.config.correctClockSkew` to true. However, setting this field does not seem to change the expiration time in either of the tokens checked by `CognitoUserSession.isValid`.

What is the best way to handle clock skew with Cognito?

Thanks for your time!

**Comment by itrestian** [comment]
I would guess if there is such a large time skew for your clients it would be best you create a branch without this check.
