### ISSUE TITLE
Refresh access token issue

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#496]
So i am writing server side code , once a user is successfully signed up i am giving back access token so that from next request this access token is used to authenticate user ,so the problem is when token gets expired i'm not sending refresh token to the user , so my doubt is if i can use single refresh token from one user and use that refresh token to refresh access tokens for all users in that user pool, this might not be safe but this is suitable for our use case.

**Comment by itrestian** [comment]
I understand the use case but I think such behavior would deviate from the OAuth standard.

**Comment by abhishekpalavancha** [comment]
okay thanks for information.
