### ISSUE TITLE
Refresh Token Expiration

### ISSUE THREAD

**Issue by bhaminisurya** [aws/amazon-cognito-identity-js#497]
So I’m trying to update expired access token using AdminInitiateAuthRequest by sending refresh token and as per documentation(http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html) refresh token expires after 30 days. So does it mean I need to update refresh token too? When I tried to get a new refresh token from AdminInitiateAuthRequest.getAuthenticationResult().getRefreshToken, I am getting a null response. 

So my question is does refresh token expires after user is successfully signed up? 
If expires then how to get a new refresh token?

**Comment by itrestian** [comment]
You get a new refresh token after every successful authentication. That would be valid for as long as you have configured it in the user pool (default is indeed 30 days). When you use the refresh token, you don't get a new one but you can use the old one for as long as it is valid after which you would need to authenticate to get a new one.

**Comment by bhaminisurya** [comment]
Just to confirm, we are using ADMIN_NO_SRP_AUTH while signing in a user to avoid a step of sending temporary code to user. Will we get a new refresh token even in this case if we use AdminInitiateAuthRequest?

**Comment by itrestian** [comment]
Yes, for ADMIN_NO_SRP_AUTH  you get a new refresh token after you complete the authentication.

**Comment by bhaminisurya** [comment]
Thanks much.
