### ISSUE TITLE
Question : User Pool region different from Identity pool region

### ISSUE THREAD

**Issue by lauterry** [aws/amazon-cognito-identity-js#50]
Hello, this is a general question

I work in France so the region of all my aws service including Cognito Federated Identity is **eu-west-1**.

I want to use Cognito User Pool which is only available in **us-east-1** region.

I intend to user the Cognito User Pool as a provider for the Cognito Identity Pool.

I wonder if it is possible since there are on different region ?

Best regards

**Comment by chetanme** [comment]
It is possible technically. Although, you will face some high latencies when making cross region calls.

User Pools is currently in public beta and that is why the region availability is limited. We will be expanding the service to other region with our GA release. Hope this helps.

**Comment by lauterry** [comment]
thx @chetanme 

Can't wait to see User Pool available in Europe

**Comment by lauterry** [comment]
hi @chetanme 

I follow the snippet from [here](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html) to implement user pool in javascript, trying to have a user pool in a different region than identity pool.

```
AWS.config.update({
            region: "eu-west-1",
            credentials: new AWS.CognitoIdentityCredentials({
                IdentityPoolId: "eu-west-1:xxxxxxxx"
            })
        });

        AWSCognito.config.region = "eu-west-1";
        AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: "eu-west-1:xxxxxxxx"
        });

        var poolData = {
            UserPoolId: 'us-east-1xxxxxxx',   // <---- user pool in us-east-1 region
            ClientId: 'xxxxxxxxxxxxxx'
        };

        var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
```

It seems to not working since I got from https://cognito-identity.eu-west-1.amazonaws.com/ : 

```
x-amzn-ErrorMessage:Access to Identity 'eu-west-1:5732b0c2-ddd6-4408-8f9d-5ab5b91f9fd0' is forbidden.
x-amzn-ErrorType:NotAuthorizedException:
```

Are you sure it is technically possible to do so as you said ? Or Am I doing something wrong ?

**Comment by chetanme** [comment]
On what action are you getting this exception?

It looks like you need to write more code for this integration to work. [This guide](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html) tells you how to integrated Cognito User pools in any region with Cognito Federated identity.

If you have already done this, can you post the code which adds User Pool tokens in the logins map?

**Comment by lauterry** [comment]
I'm getting this exception on `signUp` action.

I don't think you need Logins Map pour the `signUp` action, right ?

**Comment by lauterry** [comment]
One question : Do you have to enable Unauthenticated identities to be able to signUp with CognitoUser Pool ?

**Comment by chetanme** [comment]
No. You do not need unauthenticated identities for user pools. You also don't need logins map in signUp.

The exception "Access to Identity" is thrown from the federated identity service while `signUp` is an action on user pool service. They are completely different which means `signUp' throwing this exception is not possible. There is definitely some disconnect here.

Can you post your full code here?
