### ISSUE TITLE
Manage stale unconfirmed users

### ISSUE THREAD

**Issue by manubhat90** [aws/amazon-cognito-identity-js#502]
If there is a user that has a verified email and someone tries to create another account with a different username but the same email, it results in an unconfirmed account (assuming forceAliasCreation is turned off). Is there way to delete the unconfirmed account in this situation so that the second username is not taken up?

Additionally, is there a recommended way to clean up all the unconfirmed users in a pool?

**Comment by kushwahavinay** [comment]
Currently there is no in-built feature in Cognito to support this. But one options is to call list-users with filter for unconfirmed user and delete the accounts which were created before a certain period. This can be done on periodic basis.
