### ISSUE TITLE
forgot password verification code 

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#504]
So im verifying users with both phone number and email but when user forget password they are receiving verification code only through SMS not through email is this how it supposed to work ,when a user registers only with email without phone number then they get verification code through email.

**Comment by itrestian** [comment]
When both phone number and email are verified, phone number is preferred to send the code.

**Comment by abhishekpalavancha** [comment]
any way we can send verification code for both?

**Comment by itrestian** [comment]
We have that as a feature request on our side.

**Comment by abhishekpalavancha** [comment]
ok thanks for information
