### ISSUE TITLE
Account lock out functionality

### ISSUE THREAD

**Issue by ryutamaki** [aws/amazon-cognito-identity-js#506]
Hi, I'm trying to figure out account lock out condition.

I have node api which implements this module and trying to sign in with WRONG password several times.
The error message I got is this. This error message comes to me since I tried to login 7 times
```json
{
	"message": "Incorrect username or password.",
	"code": "NotAuthorizedException",
	"time": "2017-08-21T23:44:36.514Z",
	"requestId": "xxxxxxxx-86ca-11e7-9f35-ad28739d7d6e",
	"statusCode": 400,
	"retryable": false,
	"retryDelay": 93.13158028780859
}
```

After 8, I got this instead
```json
{
	"message": "Password attempts exceeded",
	"code": "NotAuthorizedException",
	"time": "2017-08-21T23:45:29.847Z",
	"requestId": "xxxxxxxx-86ca-11e7-aba2-8b7a474ba219",
	"statusCode": 400,
	"retryable": false,
	"retryDelay": 98.6736681421833
}
```

It looks like, the account I tried to sign in is locked out and can not sign in next time even if I enter CORRECT password.
However, I can normally sign in and get tokens from server.

My questions are
1. Is there the functionality to lock out from brute force attacks like I was trying?
2. If you have that, what is the condition to lock out?

thanks

**Comment by vlekakis** [comment]
1. Yes

2. Cognito has a built in backoff mechanism which after certain unsuccessful attempts, prevents the user to authenticate for x period of time. This x grows exponentially with each failed attempt. This kind of back off is also valid for operations which involve code verfications (ForgotPassword, ConfirmSignUp, VerifyAttribute).

**Comment by ryutamaki** [comment]
Thanks for your reply!

If you can, could you give me some of sample times?
When I tried for 20 or 30times, the preventing time to auth is likely to 10 to 30 seconds.
How many attempts do I need for making preventing time over minutes or over hours?

**Comment by vlekakis** [comment]
Hi, 

Unfortunately, it is company policy not to disclose this information publicly. I think though you should never expect the locking to go on for hours.

**Comment by ryutamaki** [comment]
I'm grad to hear that!
Thanks a lot for your response!

I close this issue, thanks again
