### ISSUE TITLE
 Cannot read property 'fromBits' of undefined 

### ISSUE THREAD

**Issue by JeffMangan** [aws/amazon-cognito-identity-js#51]
I keep getting this err on the following file: amazon-cognito-identity.min.js
amazon-cognito-identity.min.js:19 Uncaught TypeError: Cannot read property 'fromBits' of undefined 

step (use case) 1 and 2 work fine for me on the following link, but not step 4.
Doing step 4 here: https://github.com/aws/amazon-cognito-identity-js/
I have copied and pasted all the proper values into the fake variables u see below. Not sure what's happening. The user is in the pool and currently User Status    Enabled / Confirmed

var authenticationData = {
Username : 'username',
Password : 'password',
};
var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
var poolData = { 
UserPoolId : 'us-east-1_TcoKGbf7n',
ClientId : '4pe2usejqcdmhi0a25jp4b5sh3'
};
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
var userData = {
Username : 'username',
Pool : userPool
};
var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
cognitoUser.authenticateUser(authenticationDetails, {
onSuccess: function (result) {
console.log('access token + ' + result.getAccessToken().getJwtToken());
},

onFailure: function(err) {
alert(err);
},

});

**Comment by itrestian** [comment]
Hi Jeff, when using the Stanford Crypto Library note that by default the Stanford JavaScript Crypto Library doesn't include the bytes codec that the SDK uses so it must be included with the --with-codecBytes option when configuring the Stanford JavaScript Crypto Library (see sjlc README/INSTALL). It is known to build on Linux and requires a Java runtime.

Ionut.

**Comment by JeffMangan** [comment]
wow, i'm a windows guy (unfortunately) so I'll have to make some sense out of this.  Is there a pimplier way to get this working, using some other library or?   This is all just javascript running in my browser Otherwise ill read that readme later when i have time.

**Comment by itrestian** [comment]
Someone linked a version that has all the codecs. See below:

https://github.com/aws/amazon-cognito-identity-js/issues/9

Ionut.

**Comment by JeffMangan** [comment]
Awesome ill try it out shortly.

**Comment by JeffMangan** [comment]
Excellent, it's working now. Thank you so much.
