### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#518]
I think there is an error in the README.md.  In the initial paragraph, this is stated:

> The Amazon Cognito Identity SDK for JavaScript depends on: The CognitoIdentityServiceProvider service from the AWS SDK for JavaScript

However, a few lines below, it says the following:

> Optionally, to use other AWS services, include a build of the AWS SDK for JavaScript.

If it depends on it, I don't think it should be optional.

**Comment by yuntuowang** [comment]
You are not exactly correct. 
"The Amazon Cognito Identity SDK for JavaScript depends on: The CognitoIdentityServiceProvider service from the AWS SDK for JavaScript" means this JS SDK has a require for CognitoIdentityServiceProvider, which is the client for our service. The SDK has a require only on this client. 

"Optionally, to use other AWS services, include a build of the AWS SDK for JavaScript." This means if you want to use other AWS services such S3, DynamoDB and so on, you can include a build of the AWS SDK for JavaScript.
