### ISSUE TITLE
AWS Cognito Missing required key 'DeviceKey' in params

### ISSUE THREAD

**Issue by ghost** [aws/amazon-cognito-identity-js#519]
I'm doing my user management using the so useful Amazon web service name Cognito.

I would remember my users devices on login but when I'm calling the

` cognitoUser.setDeviceStatusRemembered()`

I have this error message :

> Missing required key 'DeviceKey' in params

This is how I have implement it:

```
  AuthService.login($scope.username.toLowerCase(), $scope.password)
           .then(function(res) {
              if ($scope.rememberMe == true)
                AuthService.setRememberedDevice($scope.username);
            })
```
My login function is well working for a long time.

I have read on this question :https://github.com/aws/amazon-cognito-identity-js/issues/456

...that a call to the getCachedDeviceKeyAndPassword() could solve this problem but I can not figure out where to find an implementation of this method or how to use it.

I think @itrestian could have the right answer :)

**Comment by gwander** [comment]
I already answered your question on stackoverflow: https://stackoverflow.com/questions/46041065/aws-cognito-missing-required-key-devicekey-in-params

**Comment by ghost** [comment]
thanks for your answer @yutingguo  , I'm doing both. I run in in my firefox browser in dev and in an Apache server in production and in both cases I have the same error message "Missing required key 'DeviceKey' in params". Do you know how to fixe it ?

**Comment by gwander** [comment]
It seems you are running in some sort of server side framework in which case you need to first make sure that the location where the device key is saved is available across different parts of your application

**Comment by ghost** [comment]
We deliver an Angular front with the AWS SKD.
The device key mus be on local storage no ?

Could you please show me by an exemple how I should do @yutingguo ?
I have tried everything since few weeks without success. How could I use the device key if I'm able to get it ?

**Comment by itrestian** [comment]
If you have access to the device key then you can set it as cognitoUser.deviceKey = yourDeviceKey. All getCachedDeviceKeyAndPassword does is get that value from local storage. You can check if the value is there.

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L991

**Comment by ghost** [comment]
Thanks for your answer @itrestian, I have succeed with your answer to patch my bug.
One more and last question, as of now, do my users, if their devices are remembered, are going to be directly authenticated to my application or do I have to call a special method to do it ? @yutingguo

**Comment by itrestian** [comment]
The use case for devices is in device remembering sort of keeping track of the devices your users actually use. Another use case is in allowing your users to bypass MFA if they are on a remembered device. They will always have to authenticate with a username or password.

**Comment by ghost** [comment]
There is no way to let the user decide to keep a session open by choosing a "remember me" button on login @itrestian ?

**Comment by itrestian** [comment]
That's the use case for using the refresh token.
