### ISSUE TITLE
Errors in Cognito's implementation of OpenID Connect's Implicit Grant spec (relating to the refresh token)

### ISSUE THREAD

**Issue by atkallie** [aws/amazon-cognito-identity-js#523]
A few weeks ago I successfully implemented a complete registration/login flow with Cognito while experimenting with the service to see if it would be a viable User Authentication solution for my future projects. I was initially concerned once I realized that the [signout function doesn't revoke the access token](https://github.com/aws/amazon-cognito-identity-js/issues/21#issuecomment-327117539). Since then, I've also realized that there is a security flaw in Cognito's implementation of the Implicit Grant spec in that (1) it issues a refresh token and (2) the refresh token that is issued is stored in the client-side JavaScript of the application (it can be viewed in local storage). As for (1), [The OAuth 2.0 spec explicitly states that no refresh token should be issued by the authorization server in the Implicit Grant flow](https://tools.ietf.org/html/rfc6749#page-35). In the case of (2), even if we were using the Authorization Code Grant, [a refresh token should never be exposed to the client-side JavaScript](https://stackoverflow.com/questions/18280827/using-oauth2-in-html5-web-app). What this means is that if someone is able to get their hands on a refresh token, then they can use it to continually generate new access tokens so long as Cognito's `globalSignOut()` method is never invoked. And considering the [first issue mentioned](https://github.com/aws/amazon-cognito-identity-js/issues/21#issuecomment-327117539), I'm not even sure if this would revoke the token. 

Please let me know if there is anything being done to address this or if I am mistaken.

**Comment by itrestian** [comment]
1) Refresh tokens are not issued in the implicit flow, only in the code grant flow.

2) The storage object is configurable based on your app requirements (can be passed in a constructor to the CognitoUserPool and CognitoUser objects):
https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUser.js#L79

**Comment by atkallie** [comment]
Well, considering that I never implemented any server side code or generated a client secret, I'm pretty sure that I am using the implicit flow and I am getting back a refresh token in the browser--along with the access token and the id token--so I am fairly certain that a refresh token is, indeed, being issued in the implicit flow. I can provide you with images of the flow if that helps.

Thanks for the quick response, btw.

**Comment by itrestian** [comment]
No worries, just trying to get to the bottom of the issue. Images of the flow would be helpful!

**Comment by atkallie** [comment]
I set up my client application with my user pool in the Cognito dashboard as follows (note that no client secret is being generated):

<img width="895" alt="screen shot 2017-09-17 at 10 07 05 am" src="https://user-images.githubusercontent.com/25447331/30521633-8e0e8fe6-9b90-11e7-955b-e121b1b9da92.png">

From that screenshot alone it is already apparent that a refresh token is being generated. Anyway, I then log in the user as follows:

<img width="842" alt="screen shot 2017-09-17 at 10 27 03 am" src="https://user-images.githubusercontent.com/25447331/30521776-d43d5f5e-9b92-11e7-9b4f-c25bc010dd3b.png">
<img width="830" alt="screen shot 2017-09-17 at 10 17 59 am" src="https://user-images.githubusercontent.com/25447331/30521688-c8864ba4-9b91-11e7-8563-7e9387167815.png">

...and upon a successful login, the user is then redirected to their dashboard. On that page I find that Cognito has saved the following in local storage:

<img width="506" alt="screen shot 2017-09-17 at 10 21 54 am" src="https://user-images.githubusercontent.com/25447331/30521729-4f27895c-9b92-11e7-80e2-6d93feb4820e.png">

Please let me know if I am mistaken somehow.

**Comment by itrestian** [comment]
You're not using the hosted UI hence the implicit flow in that case. The hosted UI implements the implicit flow.

You're basically just authenticating with User Pools in which case the settings you have configured in your user pool apply.

**Comment by atkallie** [comment]
Oh, I hadn't realized that using a Hosted UI was necessary for the flow to work properly. I guess I'll look into that, then. Thanks for all your help, Ionut.
