### ISSUE TITLE
It shouldn't be possible to create 2 user with the same email but different upper and lower case letters

### ISSUE THREAD

**Issue by Skaronator** [aws/amazon-cognito-identity-js#524]
As the title already reveals. It should not be possible to create multiple accounts if you use different upper and lower case letters but the same email.

Reproduce:
1. Create user with email Test@Test.com
2. Create user with email test@test.com
3. Check Userpool, both user are created

UsernameExistsException doesn't fire at all and it create both user in my Userpool.

Workaround would be to lowercase all emails on registration but don't really want to do that.

**Comment by mdravida19** [comment]
Hello, thanks for the feedback.
We are considering this change and it is on the roadmap but we cannot comment to when it will be available.

**Comment by Skaronator** [comment]
The email on login is also case sensitive. So if you register your account with xX360NoScOpE@GmAil.com then you must always login with xX360NoScOpE@GmAil.com and if you try xX360NoScOpE@Gm**a**il.com you'll get a error.

**Comment by itrestian** [comment]
Yes, we will add a +1 to the internal feature request on your behalf.

**Comment by lengkhang** [comment]
Same goes to forgot password. I have the email address set as an alias. When the user hit forgot-password, they will get "UserNotFoundException" when the email address's casing does not match with what they registered.

**Comment by Skaronator** [comment]
Sooo it's fixed?

**Comment by yuntuowang** [comment]
@Skaronator We have marked this as a feature request and we will prioritize this case fix. However, we cannot estimate the delivery time at this point.
