### ISSUE TITLE
Question: Do you consider the data transfer functionality from us-east-1 in the future?

### ISSUE THREAD

**Issue by ryutamaki** [aws/amazon-cognito-identity-js#53]
This user pool is awesome and I really eager to use it.

I'm living in Japan and our customers are almost Japanese.
I'm thinking about latency from Japan to us-east-1 and if I could I wanna bring EXISTING user data from `us-east-1` to `ap-northeast-1` in the future.

Please let me know if you think about it or not?

thanks

**Comment by itrestian** [comment]
We do plan to launch in ap-northeast-1, it is in the backlog. Currently we don't have a migration feature of this kind but thank you for bringing the use case up, we will include it in the backlog.

**Comment by ryutamaki** [comment]
Thank you for letting me know and I'm pleasure to here that!
