### ISSUE TITLE
How to verify same email multiple time with unique username

### ISSUE THREAD

**Issue by mowaiskalam** [aws/amazon-cognito-identity-js#530]
I am using Amazon Cognito Identity in my project, everything is working perfectly from registration, login, confirmation etc, but I have requirement of registration by using a unique username. But a user can use a previous email address. When I implement that, I come to know that same email can't be verified multiple times.

But I have a requirement in my application, how can I implement that?

Anyone help would be appreciated. Thanks!

**Comment by itrestian** [comment]
This is not possible at this point, once an email gets verified for one user, it transitions to not verified for the previous user. I will mention this feature request within the team.
