### ISSUE TITLE
Old temporary AWS creds remain valid when user is assigned to new group 

### ISSUE THREAD

**Issue by clintfoster** [aws/amazon-cognito-identity-js#531]
We have a default role defined on our **Identity Pool** for all "ordinary" authenticated users who are not in any particular group. In our **User Pool** we also have a role defined for each group, e.g. the `Admin` group has a role that allows Admin users to invoke Lambdas whose names begin with `admin`. 

If we go into the User Pool console and add a user to the Admin group, they are unable to invoke `admin` functions until they sign out and sign back in. Presumably this is because their temporary AWS credentials are still the ones issued for the old role. 

Ideally when a change is made that could affect the user's effective role, any existing temporary AWS credentials should be automatically invalidated, especially considering the intent might be to _reduce_ their permissions. Possibly this would be difficult to implement, so nearly as good would be if there is a checkbox when adding or removing a user from a group that would allow invalidating any temporary AWS credentials associated with that user. Perhaps it would only be displayed if the group to which the user is being added or removed has an attached role.

**Comment by rachitdhall** [comment]
At this point, if the group membership changes, you have to either re-authenticate the user or refresh the tokens which should be then exchanged with Federated Identities for new AWS Credentials.

**Comment by clintfoster** [comment]
OK, it's clear we need to either re-authenticate the user or refresh the tokens. But how does the app know to do this? The next time it invokes an "admin" Lambda it will fail with a permissions error (if the user was just added to the Admin group) or succeed (if it was just removed). If there were a Cognito console option to invalidate the temporary credentials when changing the user's role, the app would instead get an authentication error. Then it can sign the user back in, after which the operation will succeed if it should and fail if it shouldn't (rather than the other way around).

If this isn't possible, is there a way to look up the session in the identity pool and manually invalidate it?
