### ISSUE TITLE
AWS admin-create-user doesn't seem to work properly

### ISSUE THREAD

**Issue by aaLeXdIn** [aws/amazon-cognito-identity-js#532]
Hi,

I am trying to create a user in Cognito with admin-create-user using the below command:

aws cognito-idp admin-create-user --user-pool-id <value> --user-attributes Name=username,Value=X,Name=email_verified,Value=true,Name=email,Value=Y, --region eu-west-1
 
And I receive the below response showing that the user was created but the email_verified attribute was not registered. 
{
    "User": {
        "UserStatus": "FORCE_CHANGE_PASSWORD",
        "Username": "X",
        "Attributes": [
            {
                "Value": "XXX",
                "Name": "sub"
            },
            {
                "Value": "Y",
                "Name": "email"
            }
        ],
        "Enabled": true,
        "UserCreateDate": 1505847719.992,
        "UserLastModifiedDate": 1505847719.992

How can email_verified attribute be set to true using the above command (I know it can also be set with admin-update-user-attributes)?

Also - when trying to reset the password with admin-reset-user-password or forgot-password it says that User password cannot be reset in the current state. The current state being "FORCE_CHANGE_PASSWORD".

How can the password be reset in this state?
Also - is there any option to reset the password without using the verification code sent by email or phone?

Thanks,

**Comment by itrestian** [comment]
Basically when you login the first time with the temporary password, you will get a challenge (a callback if you use this repo) to set a new password. This is use case 23 in this repo.

**Comment by aaLeXdIn** [comment]
Thanks for your response. Unfortunately it doesn't help much as I have to reset the password for other users with aws cli. 

Can you provide a solution to reset the password for other users who are in "FORCE_CHANGE_PASSWORD" and without having to provide the verification code that the user receives by email/phone?

Thanks.

**Comment by itrestian** [comment]
You can use the AWS CLI to change the users password, however it's a multi step process and you do need the temporary password that was set for the user:

Step 1, is to get a session token for the desired user:
aws cognito-idp admin-initiate-auth --user-pool-id %USER POOL ID% --client-id %APP CLIENT ID% --auth-flow ADMIN_NO_SRP_AUTH --auth-parameters USERNAME=%USERS USERNAME%,PASSWORD=%USERS CURRENT PASSWORD%

this will respond with the challenge "NEW_PASSWORD_REQUIRED", other challenge parameters and the users session key. Then, you can run the second command to issue the challenge response:
aws cognito-idp admin-respond-to-auth-challenge --user-pool-id %USER POOL ID% --Client-id %CLIENT ID% --challenge-name NEW_PASSWORD_REQUIRED --challenge-responses NEW_PASSWORD=%DESIRED PASSWORD%,USERNAME=%USERS USERNAME% --session %SESSION KEY FROM PREVIOUS COMMAND with ""%
