### ISSUE TITLE
Typescript React-Native 'couldn't to find preset es2015'

### ISSUE THREAD

**Issue by AlexThomas90210** [aws/amazon-cognito-identity-js#533]
I am getting an error which I have not been able to solve for a while now, hoping somebody has any information to point me in the right direction, I am getting this error when I try to import this library. Any input would be greatly appreciated!

<img width="363" alt="screen shot 2017-09-20 at 10 32 21" src="https://user-images.githubusercontent.com/17221873/30637012-0cc1b09c-9def-11e7-8e77-84af47d3e3b7.png">

**Code I am using**
<img width="318" alt="screen shot 2017-09-20 at 10 39 50" src="https://user-images.githubusercontent.com/17221873/30637393-187d43d2-9df0-11e7-9030-d3cd2f349cd3.png">

**My tsconfig.json**
<img width="443" alt="screen shot 2017-09-20 at 10 38 58" src="https://user-images.githubusercontent.com/17221873/30637462-47dd88b2-9df0-11e7-9f43-95291be37f57.png">

**My package.json**
<img width="648" alt="screen shot 2017-09-20 at 10 39 26" src="https://user-images.githubusercontent.com/17221873/30637428-34eaef88-9df0-11e7-82cf-8962381f806b.png">

**Comment by AlexThomas90210** [comment]
Solved: 
I was having an issue with caching inside react native, even when I was installing the es2015 babel preset the app would not recognize it... solved by running
`npm install -D babel-preset-es2015`
`npm start -- --reset-cache`

of course, I solve it 10 minutes after posting this issue...

**Comment by itrestian** [comment]
Glad you got it worked out.
