### ISSUE TITLE
Custom email for user verification

### ISSUE THREAD

**Issue by GDavisSS** [aws/amazon-cognito-identity-js#540]
The company I work for has some files with all the information, links, and images they want in an email when sending verification emails to users who are signing up or changing their email address in our Cognito user pool.  There is a main file with code to import all this information to create the final email that is sent.

Before moving to AWS the process was using php code and I am trying to send the same email php did, but now from AWS hopefully using the same files to create the email.  I am fairly new to AWS, but I don't see anything in their documentation about loading a file for message customization.  Is it possible to do this through the user pool message customization section in AWS?

My company contracted another company to setup our API skeleton with basic lambda code and chalice for deploying the API.  Currently the registration lambda code just does boto3.client.sign_up which automatically sends an email based on settings in the user pool message customization.  My company doesn't want to have to go through the hassle of requesting to be moved out of AWS "sandbox" messaging.

The only other possible solution I could think of is loading the existing email file through the python lambda code and send it through our own server.  Then, after the user verifies the email on our end, call another lambda function and find a way to add the user to the user pool without sending the automatic AWS verification email the function above sends and immediately mark the user as confirmed and enabled with a verified email.

Maybe this could be done with lambda triggers?  I don't really understand those either.  I am the point man for AWS because no one at my company has any experience with it.  I appreciate any help.

**Comment by vlekakis** [comment]
Yes, what you are describing can happen through the lambda triggers. Basically you can customize the signUp/signIn flow by associating lambda functions. 

Please take a look in the options Cognito provides to customize the authentication flow. 
http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

Take a look in the customMessage first.
