### ISSUE TITLE
Unable to confirm MFA Code

### ISSUE THREAD

**Issue by RameshRM** [aws/amazon-cognito-identity-js#542]
Hi , I cannot authenticate and confirm `MFA Code`.  I have MFA flow from login and i try to confirm the code

``cognitoUser.sendMFACode(code, callback)``

I always get exception InvalidParameterException: Missing required parameter Session , Btw, this is used in context of a Lambda not in client side Javascript

Any pointers on this is appreciated

**Comment by itrestian** [comment]
The session would be internal. If you had called authenticateUser on the same cognitoUser object first, it would have a session associated that will be used in this call.

**Comment by RameshRM** [comment]
I see, on a completely disjointed setup, assuming `api gateway` is authentincating the `mfa` how do you expect to pass the session object and maintain the session ?

**Comment by itrestian** [comment]
I don't really understand the use case to be fair. MFA happens in the context of authenticating in the user pool, why would you pass the session to API Gateway?

**Comment by prakashbisht20** [comment]
Hi itrestian,

   I am getting the same issue  Error: Missing required parameter Session while 

 let userData = {
            Username: "psb.bisht20@gmail.com",
            Pool: this.cognitoUtil.getUserPool()
        };

        console.log("UserLoginService: Params set...Authenticating the user");
        
        let cognitoUser = new CognitoUser(userData);

        cognitoUser.sendMFACode(confirmationCode, {
            onSuccess: function (result) {
                console.log('mfa code ', result);
                //callback.cognitoCallback(null, null);
            },
            onFailure: function (err) {
                console.log('mfa error ', err);
                //callback.cognitoCallback(err.message, null);
            }
        });

Please can anyone help me on this?

**Comment by itrestian** [comment]
As I've explained above, the sendMFACode only works in the process of authentication. So you would need to call authenticateUser first to receive a session internally after which you would be able to call sendMFACode.

**Comment by prakashbisht20** [comment]
Hi itrestian,

Thanks for your response. I got it.

Can we use email for MFA on cognito?
Like we are able to do the things on Phone part.

Please confirm me if this is possible.

**Comment by RameshRM** [comment]
@psbbisht you can use both, u can set MFA as an optional and Cognito Users can optin to MFA , with Email being a primary verification mechanism. Cognito docs is a good starting point 

http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html

**Comment by prakashbisht20** [comment]
Yes, but I am not able to enable or disabled the email from my angular code.
Do you have any idea about that? its only accepting the phone number for enabling MFA.

**Comment by RameshRM** [comment]
@psbbisht I think, this is done at the `Cognito Pool Settings` rather at the user level from the `CognitoUser`

**Comment by prakashbisht20** [comment]
I need that part on cognito user part like we are doing the things with phone number.

**Comment by kartou** [comment]
Hi,

> As I've explained above, the sendMFACode only works in the process of authentication. So you would need to call authenticateUser first to receive a session internally after which you would be able to call sendMFACode.

But how would I support that the MFA SMS would contain a link with the code? Since clicking the link will open a new tab in the browser, the closure of the authenticateUser would be gone? I would then re initiate authenticateUser, but that will just send me a new code, and the loop continues?

I'm struggling with this. There must be a way to establish a valid cognito user object to confirmMFA on, without sending a new code right?
