### ISSUE TITLE
How to define scope ?

### ISSUE THREAD

**Issue by martinduris** [aws/amazon-cognito-identity-js#543]
Hi guys,
i am using following code:

```
this.cognitoUser.authenticateUser(authenticationDetails, {
      newPasswordRequired: function (userAttributes, requiredAttributes) {
        console.log('User needs to set password.');
      },
      onSuccess: function (result: CognitoUserSession) {
        console.log(result.getIdToken());
     ...
```

But accessToken (when i decode id) in **scope always contains only 'aws.cognito.signin.user.admin'**. How can i request scope which would contain (in accessToken) also for example '**Allowed Custom Scopes**' (which i have defined in resource server and add add them on 'App client settings' in cognito console) 

Thanks

**Comment by behrooziAWS** [comment]
You can only specify custom scopes if you use the OAuth client:

https://github.com/aws/amazon-cognito-auth-js
