### ISSUE TITLE
Login With Amazon: Token is not from a supported provider of this identity pool.

### ISSUE THREAD

**Issue by Nosajool** [aws/amazon-cognito-identity-js#544]
Following the steps for [External Identity Providers](http://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) for Amazon Cognito Federated Identities, I've been able to successfully login with Facebook and Google but am having trouble with Amazon.

I am using the [react-social-login](https://github.com/deepakaggarwal7/react-social-login) library to retrieve access tokens.

```js
// Login.js
        <SocialButton
          provider="amazon"
          appId='amzn1.application-oa2-client.dc021a6e1ec*************3d65ea3c'
          onLoginSuccess={(resp) => {
            this.props.loginUserProvider(resp.provider, resp.profile, resp.token.accessToken);
          }}
          onLoginFailure={(resp) => { console.log(resp); }}
        >
```

```js
// authActions.js
export const loginUserProvider = (provider, profile, token) => (
  (dispatch) => {
    dispatch({ type: 'LOGIN_USER' });
    Cognito.loginProvider(provider, token)
      .then(awsCredentials => loginUserSuccess(dispatch, profile, awsCredentials))
      .catch((error) => {
        console.log(error);
        loginUserFail(dispatch);
      });
  }
);
```

Once I have the `accessToken`, I try to make a call to `AWS.config.credentials.get` and see the following error:

```
credentials get error: NotAuthorizedException: Token is not from a supported provider of this identity pool.
```

```js
// cognitoService.js
export const loginProvider = (provider, token) => (
  new Promise((resolve, reject) => {
    let providerKey = '';
    switch (provider) {
      case 'facebook':
        providerKey = 'graph.facebook.com';
        break;
      case 'google':
        providerKey = 'accounts.google.com';
        break;
      case 'amazon':
        providerKey = 'www.amazon.com';
        break;
      default:
        break;
    }

    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: AWSConfiguration.identityPoolId,
      Logins: {
        [providerKey]: token,
      },
    });

    debugger;

    AWS.config.credentials.get((error) => {
      if (error) {
        console.error(`credentials get error: ${error}`);
        reject(error);
      }
      resolve(AWS.config.credentials);
    });
  })
```

At the `debugger` line, my CognitoCredentials look like:
<img width="1108" alt="screen shot 2017-10-04 at 3 23 44 pm" src="https://user-images.githubusercontent.com/3674579/31202668-548ca768-a918-11e7-82b5-f78b1bdaa491.png">

Note that the access token is over 500 characters long.

My authentication provider is configured:

<img width="1007" alt="screen shot 2017-10-04 at 3 27 02 pm" src="https://user-images.githubusercontent.com/3674579/31202716-9900d9c8-a918-11e7-91b6-6cceb3a632f1.png">

I've tried using client ids from both the

1. The [Amazon Developer Portal](https://developer.amazon.com/login-with-amazon)
2. And [Seller Central](https://login.amazon.com/)

What might I be doing wrong?

**Comment by chetanme** [comment]
I suspect the issue is the `provider` name you are using. Can you replace `amazon` with `www.amazon.com` in the provider name property?

There is an example for this in our docs [here](http://docs.aws.amazon.com/cognito/latest/developerguide/amazon.html#set-up-amazon-1.javascript).
