### ISSUE TITLE
Forgot password code LimitExceededException

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/amazon-cognito-identity-js#548]
Not really an issue but i'm unable to find proper information in documentation.

so when a user requests for forgot password PIN more than 5 times we are getting LimitExceededException fair enough but need some information : 

1. How long user needs to wait to request new PIN if they hit 5 times limit.
2. if user requests 3 requests now and without verifying let say after 1 day if they request another time how many more attempts do they have 2 or 5.

Thanks.

**Comment by itrestian** [comment]
Please see following post. We do have those protection mechanisms mentioned, however we do not share externally the exact limits involved.

https://stackoverflow.com/questions/37732970/how-aws-cognito-user-pool-defends-against-bruteforce-attacks
