### ISSUE TITLE
Code Samples missing AWS Credential updates on Login/Session Persistence

### ISSUE THREAD

**Issue by hofan41** [aws/amazon-cognito-identity-js#55]
The code samples, while being extremely helpful, were not complete enough for me to use and required a few hours wading through documentation/source code to figure out how to get everything working. 

Some of the personal frustrations I went through included
1. Not knowing how/when to update the AWS credentials. I assumed incorrectly that this library automatically updated them, which, one could argue, should be done here.
2. Not knowing I needed to re-instantiate the AWS service objects after credentials were updated. 
3. Not knowing how to format the `Logins` parameter key for the `CognitoIdentityCredentials`. 

For these reasons, I think we could save a lot of this repeated frustration by modifying code samples 4 and 15 with the necessary AWS glue to make it all work. Submitting PR.

**Comment by et304383** [comment]
I would suggest to the AWS team that this be expanded further.  The documentation and examples are all incomplete and don't give a full working end to end piece of code for performing authentication against Cognito user pools.  

http://stackoverflow.com/questions/37259824/user-pools-for-amazon-cognito-credentialserror-missing-credentials-in-config

This is an example of someone having to debug to figure it out themselves that you have to set credentials against both the AWS and AWSCognito objects.

**Comment by chetanme** [comment]
Hello, thank you for pointing this out. We are working on getting the documentation up to date and complete for a better developer experience.

**Comment by mikedizon** [comment]
@hofan41 how were you able to update the credentials? this has been driving me crazy!

**Comment by hofan41** [comment]
@mikedizon take a look at the PR #56 for the additional code you need to inject the Cognito credentials into AWS SDK. 

Now my next hurdle is figuring out how to get these credentials loaded into my API Gateway client!

**Comment by MarkMercAWS** [comment]
If you are using AWS Credentials with API Gateway, you load them into the API Gateway client like this:

`var client = apigClientFactory.newClient({ 
    accessKey: ACCESS_KEY, 
    secretKey: SECRET_KEY, 
    sessionToken: SESSION_TOKEN });`

**Comment by MarkMercAWS** [comment]
If you want to integrate Cognito User Pool users directly with API Gateway (without getting AWS Credentials), this blog post will be a good guide - https://mobile.awsblog.com/post/Tx3JK25U7Z9EUIU/Integrating-Amazon-Cognito-User-Pools-with-API-Gateway

**Comment by hengbenkeji** [comment]
The developers of the AWS Cognito Identity should stop saying thanks to struggling developers!
You guys need to get the job done!
You get paid for your job!
