### ISSUE TITLE
getAttributes isn't getting all attributes

### ISSUE THREAD

**Issue by jgrigd** [aws/amazon-cognito-identity-js#550]
I'm using getAttributes, but it's not pulling all the attributes. I set several attributes on signup, but one is set by a lambda function upon validation. I confirmed the attribute exists in the console UI, but it isn't retrieved by getAttributes, only those set upon initial signup are. I made sure to clear my browser cache and tired from multiple browsers, so it does not appear to be a client side caching issue.

**Comment by chetanme** [comment]
Can you make sure the app client id you are using to call getAttributes has permissions to read the attribute you are not getting?

Relevant docs: http://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html

**Comment by jgrigd** [comment]
That was it! I added the property after creating the pool and app client so it was unchecked. Thanks
