### ISSUE TITLE
confirm sign up  username regex

### ISSUE THREAD

**Issue by mercurynomercy** [aws/amazon-cognito-identity-js#551]
right now i have signup a user with username like test+test@test.com.

It return me a code. when I try to call the confirmRegistration. it return the error 
**1 validation error detected: Value at 'username' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{S}\p{N}\p{P}]+**
which the username is able to signup with that weird username

`

return new Promise(function(resolve, reject) {
     

    let userData = {
      Username: username,
      Pool: userPool
    };

    let cognitoUser = new CognitoUser(userData);
    cognitoUser.confirmRegistration(code, false, function (err, result) {
      if (err) {
        reject(err)
      }
      resolve()
    });
  })

`

**Comment by ryanbelt** [comment]
is there anyway i can change the regex for the validation?

**Comment by mercurynomercy** [comment]
found the problem, sorry for the post
