### ISSUE TITLE
A working example for case 4 with S3?

### ISSUE THREAD

**Issue by lielran** [aws/amazon-cognito-identity-js#552]
I configure authorized user for s3-admin in the IAM, still when I tried to do `
         s3.listBuckets({},()=> ???)` 
`
I'm getting this errors:
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
:3000/#/login:1 
```
```
Failed to load https://s3.amazonaws.com/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.```

**Comment by itrestian** [comment]
This issue is not related to this library. See issue below:

https://stackoverflow.com/questions/35588699/response-to-preflight-request-doesnt-pass-access-control-check
