### ISSUE TITLE
Plus Sign (+) not a Special Character

### ISSUE THREAD

**Issue by paolavness** [aws/amazon-cognito-identity-js#556]
Hi there,
I've noticed the `+` is not a special character and am wondering what the reason for this is and whether it can be added as one. A small number of users appear to use `+` as their default "special character" across their passwords. We've had complaints from them about not being able to use it in our app

Thank you,
Paola

**Comment by itrestian** [comment]
Closing as a duplicate of: https://github.com/aws/amazon-cognito-identity-js/issues/527
