### ISSUE TITLE
Use relative paths in es module specifiers

### ISSUE THREAD

**Issue by bennypowers** [aws/amazon-cognito-identity-js#563]
On line 20 of CognitoUserPool.js, 

```js
import CognitoIdentityServiceProvider from 'aws-sdk/clients/cognitoidentityserviceprovider';
```

breaks the browser, since `'aws-sdk/clients/cognitoidentityserviceprovider';` is not a valid specifier.

I would suggest changing that line to 

```js
import CognitoIdentityServiceProvider from '../../aws-sdk/clients/cognitoidentityserviceprovider';
```

So that users who aren't looking to add a build step don't have to.

I realize that this will also require the aws-sdk lib to release an es modules version. See https://github.com/aws/aws-sdk-js/issues/1766

**Comment by itrestian** [comment]
It seems this is dependent on the issue you mentioned. Also, we are considering removing the AWS SDK dependency https://github.com/aws/amazon-cognito-identity-js/pull/473

**Comment by itrestian** [comment]
You can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo. We have also removed the AWS SDK dependency.

https://github.com/aws/aws-amplify
