### ISSUE TITLE
Get current user and logout with Federated Identity Pool

### ISSUE THREAD

**Issue by dbeja** [aws/amazon-cognito-identity-js#564]
I know how to get the current user and logout from an user pool, but how do I do that on a federated identity pool and the user logged in with another provider like Facebook or Google+?

Thanks

**Comment by mqasem92** [comment]
+1

**Comment by mqasem92** [comment]
Could you please share your code how you add Facebook and Google login ?!

**Comment by dbeja** [comment]
For Facebook I have something like this:

```
window.FB.login(function(response) {
  if(response.authResponse) {
    // login on Cognito with FB token
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'identityPoolId',
      Logins: {
        'graph.facebook.com': response.authResponse.accessToken
      }
    });

    AWS.config.credentials.refresh((error) => {
      if(error) {
        console.log(error);
      } else {
        console.log('Logged in...');
      }
    });
  } else {
    console.log('FB auth error');
  }
}, {scope: 'email'});

```

**Comment by itrestian** [comment]
The Javascript SDK for federated identities caches the identity that was most recently used. There is no real way to logout since the vended credentials are valid for up to 1 hour.

**Comment by AashishKJha** [comment]
@dbeja have u got solution ?? how to get current_user and jwt_token from 
let params = this.getFacebookCognitoParametersForIdConsolidation(accessToken);

        AWS.config.credentials = new AWS.CognitoIdentityCredentials(params);
        AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials(params);

        console.log("Getting the credentials class");
        AWS.config.credentials.get((err) => {
            if (err) {
                alert("Error: " + err);
                return;
            }
            alert("Cognito Identity Id: " + AWSCognito.config.credentials);
        });

getFacebookCognitoParametersForIdConsolidation(accessToken: string): {} {
        console.log("enter getFacebookCognitoParametersForIdConsolidation()");
        AWS.config.region = _REGION;
        let urlfb = 'graph.facebook.com'
        console.log("ur: " + urlfb);
        let logins: Array<string> = [];
        logins[urlfb] = accessToken;
        alert("Access Token" + accessToken);

        let params = {
            IdentityPoolId: _IDENTITY_POOL_ID, /* required */
            Logins: logins
        };
        return params;
    }

please help??
