### ISSUE TITLE
Add User To Group After Signup

### ISSUE THREAD

**Issue by jessekendrick** [aws/amazon-cognito-identity-js#565]
After signing up a new user (userPool.signUp), I would like to add that user to an existing Cognito Group (for role-based permission purposes).  Is this possible?

**Comment by itrestian** [comment]
Yes, it is possible but it is an admin operation so you would have to call it from your backend by using the main AWS SDK for Javascript.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminAddUserToGroup-property
