### ISSUE TITLE
Confirm User from the Service portal.

### ISSUE THREAD

**Issue by chinmayjain18** [aws/amazon-cognito-identity-js#566]
Hello,

I have a user email ID and I tried to confirm the user from the service portal page by clicking the CONFIRM USER button.

This changed the status of the user to CONFIRMED, however the user was not able to use any of the functionality in the app. On investigation I found out the user was getting **No registered/verified email or phone_number (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException)** error message. On further investigation I found out that the email_verified field for the user was still false. 

I have two queries regarding this behavior:

1. Is there any way to update the email_verified field to true after confirming the user directly from the portal?
2. If the user was confirm by the admin in the portal, why is the email_verified field still marked as false?

Thanks in advance!

**Comment by itrestian** [comment]
On the first screen, when you create the  user, you can check the Mark email as verified? Another way would be to create a lambda trigger that confirms the user and verifies the email upon registration.

**Comment by chinmayjain18** [comment]
I should clarify the scenario more. The user was created by using the app, using the CreateUser action. And then I tried to confirm the user by using the Confirm User button on the service portal (Users and Groups) page. After confirming the user, the status did get updated to CONFIRMED but the email_verified was still false and consequently the user was not able to use the app.

**Comment by itrestian** [comment]
Yes, they are separate things (confirmed users and attributes that are verified such as email and phone_number). As an alternative, you can use the CLI to call adminUpdateUserAttributes and send email_verified as true.
