### ISSUE TITLE
user pool Storage property contains entire local storage

### ISSUE THREAD

**Issue by richbrill** [aws/amazon-cognito-identity-js#569]
Not sure if this is intended behaviour but when I create a new user pool using `userPool = new CognitoUserPool(poolData);` the storage property of the userPool object contains my entire localStorage and not just the Cognito specific keys.

If I add a random key value item to localstorage and access the userPool I can see that random key value pair in the storage property.

Is this intended Cognito behaviour?

It feels a little nefarious...

**Comment by itrestian** [comment]
not sure exactly what you mean. local storage is usually restricted to the domain you are running your app from. They're anyway available on the window object.

**Comment by richbrill** [comment]
Yep, understood, I think my concern was more about whether the Storage property is a reference to localStorage or a copy of it?

It could be an issue if localStorage contains a lot of stuff if it was a copy, that's all

**Comment by itrestian** [comment]
It is configurable so you can pass your own storage object.

https://github.com/aws/amazon-cognito-identity-js/blob/master/src/CognitoUserPool.js#L51

**Comment by richbrill** [comment]
OK, thanks @itrestian
