### ISSUE TITLE
Example code for authentication does not work - ValidationData not sent

### ISSUE THREAD

**Issue by et304383** [aws/amazon-cognito-identity-js#57]
I am running the code in scenario 4 to try to login against Cognito using user pools and an identity pool backed by the user pool.

When I debug the flow and look at the post request to Cognito, the validation data is blank (empty array).

From Firebug, looking at the JSON payload:

```
"ValidationData":[]
```

Code snippet:

```
<html>
<body>

<script src="file:///home/etucker/cognito/jsbn.js"></script>
<script src="file:///home/etucker/cognito/jsbn2.js"></script>
<script src="file:///home/etucker/cognito/sjcl.js"></script>
<script src="file:///home/etucker/cognito/moment.min.js"></script>
<script src="file:///home/etucker/cognito/aws-cognito-sdk.min.js"></script>
<script src="file:///home/etucker/cognito/amazon-cognito-identity.min.js"></script>
<script src="file:///home/etucker/cognito/aws-sdk.min.js"></script>

<script>
AWS.config.region = 'us-east-1';
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:<SNIP>'
});

AWSCognito.config.region = 'us-east-1';
AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
  IdentityPoolId: 'us-east-1:<SNIP>'
});

// Need to provide placeholder keys unless unauthorised user access is enabled for user pool
AWSCognito.config.update({accessKeyId: 'anything', secretAccessKey: 'anything'})

var poolData = {
  UserPoolId : 'us-east-1_<SNIP>',
  ClientId : '<SNIP>'
};

var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);

var userData = {
  Username : '<SNIP>',
  Pool : userPool
};

var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

var authenticationData = {
  Username : '<SNIP>',
  Password : '<SNIP>',
};

var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
cognitoUser.authenticateUser(authenticationDetails, {
  onSuccess: function (result) {
      console.log('access token = ' + result.getAccessToken().getJwtToken());
  },

  onFailure: function(err) {
      alert(err);
  },
});
</script>
</body>
</html>
```

**Comment by itrestian** [comment]
You are not setting ValidationData in the authenticationData JSON. That is why the ValidationData is empty.

var authenticationData = {
  Username : '<SNIP>',
  Password : '<SNIP>',
};

**Comment by et304383** [comment]
Huh?  That is not how the example is listed.

**Comment by itrestian** [comment]
ValidationData is an optional parameter. That example doesn't pass the ValidationData to the service. Thanks for bringing it up, we will update the example to pass ValidationData as well.

**Comment by et304383** [comment]
I'm sorry, can you please elaborate?  I really need a working example to login to Cognito user pools.

**Comment by itrestian** [comment]
Your above code should work as well. ValidationData is not required, it is an optional parameter.

ValidationData
    The validation data in the request to register a user.
    Type: array of AttributeType objects
    Required: No 

However, if you want to pass validation data you can just pass an array of name value pairs in the authentication details as below:

var validationData1 = {
    Name : '...',
    Value : '...'
};
var validationData2 = {
    Name : '...',
    Value : '...'
};
var validationData3 = {
    Name : '...',
    Value : '...'
};

var validationData = [];
validationData.push(validationData1);
validationData.push(validationData2);
validationData.push(validationData3);

var authenticationData = {
  Username : '<SNIP>',
  Password : '<SNIP>',
  ValidationData : validationData
};

**Comment by et304383** [comment]
Ok well my code does not work. There is no password in the request. Unless it's sent as part of the other fields. The username is sent but I don't see the password in the payload.

**Comment by itrestian** [comment]
Your password is never sent over the wire. We use the SRP protocol to send a password verifier. The password verifier is computed using the password you entered.

**Comment by et304383** [comment]
Ok well in that case, what do you suggest I look at to explain getting back a null response from cognito?

**Comment by itrestian** [comment]
authenticateUser makes 2 calls to our service that you should be able to see with Firebug, a call to getAuthenticationDetails to pass the client challenge and get the server challenge and a call to authenticate to pass the password verifier after which you get tokens or an exception.

**Comment by et304383** [comment]
Looking at firebug it's the first post request to cognito idp that's returning null.

**Comment by itrestian** [comment]
Does the request return a 200?

**Comment by et304383** [comment]
Request returns a 200 but shortly after the following error is thrown:

```
POST https://cognito-idp.us-east-1.amazonaws.com/  200 OK  174ms      aws-cog....min.js (line 2168)

Error: 
h = d.util.error(h || new Error, j)

file:///home/etucker/cognito/aws-cognito-sdk.min.js
Line 3569
```

Sorry for the awful formatting.  

Edit: I pretty printed the JS trying to debug.  It's no longer one line.  Hence Line 3569.

Here's some context:

```
            callListeners: function(a, b, c, e) {
                function f(e) {
                    return e && (h = d.util.error(h || new Error, e), g._haltHandlersOnError) ? c.call(g, h) : void g.callListeners(a, b, c, h)
                }
                for (var g = this, h = e || null; a.length > 0;) {
                    var i = a.shift();
                    if (i._isAsync) return void i.apply(g, b.concat([f]));
                    try {
                        i.apply(g, b)
                    } catch (j) {
                        h = d.util.error(h || new Error, j)
                    }
                    if (h && g._haltHandlersOnError) return void c.call(g, h)
                }
                c.call(g, h)
            },
```

**Comment by itrestian** [comment]
That is probably a dependency problem. The cognito endpoint is returning either 200 or exceptions and in Firebug, I get null for the Response as well.

It could be that you didn't compile sjcl with the --with-codecBytes option. Can you check in sjcl if you have it?

Please note, that by default the Stanford JavaScript Crypto Library doesn't include the bytes codec that the SDK uses so it must be included with the --with-codecBytes option when configuring the Stanford JavaScript Crypto Library (see sjlc README/INSTALL). It is known to build on Linux and requires a Java runtime.

**Comment by et304383** [comment]
Ahh.  I simply visited the various pages and copied the JS files as is.  So either I'm not very bright or the setup instructions need a bit more explaining.  :)

Edit: for sjcl I simply downloaded and included this file.  Are you saying that's not sufficient?

https://github.com/bitwiseshiftleft/sjcl/blob/master/sjcl.js

**Comment by et304383** [comment]
That was it.  I'm now getting a token.  Thanks for your help and sorry for being a dohead who didn't follow the instructions.  :)

**Comment by soacs** [comment]
Eric - I have been stuck with this problem for a while as well. So what is your resolution create a f sjcl.codec.bytes file or download and recompile? What the hell why am I even using this? Isn't AWS SDK suppose to encapsulate all this stuff so I do not have to worry about it?

**Comment by itrestian** [comment]
I have removed the dependency on the bytes codec in the current version. Can you check if you can authenticate now?
