### ISSUE TITLE
Pre Token Generation trigger details

### ISSUE THREAD

**Issue by pisaacs** [aws/amazon-cognito-identity-js#571]
First, I am not sure if this is the correct forum or not but thought to start here (since AWS Cognito team members support this project as well). 

In Cognito, I just noticed a 'Pre Token Generation' trigger - good stuff! 

However, maybe this is still "rolling out"? Can't seem to find any doc on this trigger or API references.  

Lastly, will it support setting token expiration time (since it's a claim field)?  

http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html

http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

**Comment by itrestian** [comment]
The documents are in the process of getting updated for that change.

**Comment by vlekakis** [comment]
Hello, 

Docs are out:
http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html


Currently, we don't allow override of the expiration time. As a work around (if at least you want tokens for less than an hour) you can invalidate the token manually, and then get new tokens.
We will consider this feature in the future, if it gets some traction.

**Comment by pisaacs** [comment]
Thanks - appreciate the update.

**Comment by jogold** [comment]
@vlekakis: what do you mean by invalidate the token manually? how can this be achieved?

**Comment by vlekakis** [comment]
Sorry, I meant not accept the token. So we know that the token is good for 1 hour. But an application needs only  tokens with expiration time of 10 minutes. Before you issue a request with this token you can check if the token is 10 minutes old. And choose not to accept it.

**Comment by dkuchler** [comment]
@vlekakis Does anyone know what the value is to configure the pre token generation lambda on a user pool resource? I don't see it in the documentation here:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html

**Comment by itrestian** [comment]
it is not in available in cloudformation yet but you can definitely configure it using the CLI if you take a look at the Cognito documentation.
