### ISSUE TITLE
Access token not saved to Session Storage after authenticated using Facebook identity provider

### ISSUE THREAD

**Issue by vedtam** [aws/amazon-cognito-identity-js#572]
Hi,

With User Pools and Facebook as identity provider set up I can authorize and authenticate users with the built Cognito UI, the access token appears in the URL but `userPool.getCurrentUser()` returns `null`. Checked the storage manually, its empty.

Took the acces token from the URL, decoded it, i guess this is ok:

```
{
  "sub":"072579dd-0646-441d-b1df-xxx-xxx",
  "token_use":"access",
  "scope":"openid profile email",
  "iss":"https://cognito-idp.eu-west-1.amazonaws.com/xxx",
  "exp":1509476704,
  "iat":1509473104,
  "version":2,
  "jti":"a4d1de4b-2b04-4083-ac6d-xxx",
  "client_id":"3atditmln68cjsschnexxxxx",
  "username":"Facebook_10157221555xxxxx"
}
```

Than why is Session Storage empty?

Scripts I use:

```
    <!-- AWS -->
    <script src="https://sdk.amazonaws.com/js/aws-sdk-2.130.0.min.js"></script>
    <script src="js/amazon-cognito.min.js"></script>
    <script src="js/aws-cognito-sdk.min.js"></script>
    <script src="js/amazon-cognito-identity.min.js"></script>
```

Thanks!

**Comment by itrestian** [comment]
How are you authenticating with the hosted UI? Are you using the auth js sdk?

https://github.com/aws/amazon-cognito-auth-js/

**Comment by vedtam** [comment]
You saved my day!! I was missing that library 😄  Thanks!
