### ISSUE TITLE
Is it possible to have the hosted sign-in UI translated in other languages?

### ISSUE THREAD

**Issue by vedtam** [aws/amazon-cognito-identity-js#573]
Hi,

I am wondering if there is a way to have the sign-in UI in a different language then english.

Thanks!

**Comment by itrestian** [comment]
This is not available at this point but very much on our roadmap. I can't comment on a date for the availability though.

**Comment by vedtam** [comment]
I would gladly offer my help with translations for Hungarian and Romanian languages.
