### ISSUE TITLE
README.md webpack.config.js path: dist is wrong

### ISSUE THREAD

**Issue by entrpn** [aws/amazon-cognito-identity-js#576]
I couldn't get it to work until I changed it to:

path: __dirname + '/dist',

Also for those new to web development would it make sense to explain that the src folder and entry.js needs to be created?

Thanks!

**Comment by yuntuowang** [comment]
Glad it works! Yes you need to create src folder and entry.js. If you feel something else needs to be clearer, feel free to send a pull request.
