### ISSUE TITLE
cognitoUser.getUserAttributes gives an empty error object

### ISSUE THREAD

**Issue by hsyyid** [aws/amazon-cognito-identity-js#579]
My code:

```javascript
cognitoUser.getUserAttributes(function(err, res) {
        if (err) {
            window.Raven.captureMessage("Error [getUserAttributes]: " + JSON.stringify(err));
            cognitoUser.signOut();
            return;
        }

        var attributes = {};

        for (let i = 0; i < res.length; i++) {
            if (res[i].getName() !== "sub") {
                attributes[res[i].getName()] = res[i].getValue();
            }
        }

        store.dispatch({type: 'user/attributes', attributes: attributes});
    });
```

Somehow the callback has an error, but it is empty. What does that mean?
ie. `err = {}`

Also `res = null`

**Comment by itrestian** [comment]
Can you try that in Chrome with developer tools enabled? You can have a look at the actual error returned by the service.

**Comment by hsyyid** [comment]
@itrestian 

Could this come from using an outdated AWS SDK? 

I am on version 2.39.0, latest is 2.146.0

**Comment by itrestian** [comment]
Yes, there might be an extra missing exception that was added to the SDK later I would think.
