### ISSUE TITLE
react native starter/example project

### ISSUE THREAD

**Issue by 0zguner** [aws/amazon-cognito-identity-js#583]
Thanks for your great effort ! I've been looking for a react native (crna) example, I believe https://github.com/awslabs/aws-mobile-react-native-starter this is pretty old and not using this library. Any progress on starter project  or any example ?

**Comment by itrestian** [comment]
Thank you for your feedback. We are constantly working on adding new features aimed at improving developer experience.

**Comment by minbi** [comment]
@mzgnr The sample app that you linked should be compatible with this library. You will need to change the dependency to point to this library and change an import, but the APIs are compatible.
