### ISSUE TITLE
JSON value '0' error while using authenticateUser with react-native app

### ISSUE THREAD

**Issue by dahudson88** [aws/amazon-cognito-identity-js#588]
I am trying to follow the example for Use Case 4 but when I attempt to run the code with my authenticationData I get the following Error:
![simulator screen shot - iphone 8 - 2017-11-13 at 16 54 52](https://user-images.githubusercontent.com/31221472/32751311-6763e424-c893-11e7-9394-e61c230d56bb.png)
![simulator screen shot - iphone 8 - 2017-11-13 at 16 55 38](https://user-images.githubusercontent.com/31221472/32751328-7cbf9250-c893-11e7-80df-af46c60db6fa.png)

I do not believe that it is the format of the authenticationData because when I input the incorrect information it does note that the username or password is invalid.

See Code Below:
loginUser()
    {

      var authenticationData = {
        Username : this.state.emailText,
        Password : this.state.passwordText
    };
    var authenticationDetails = new AuthenticationDetails(authenticationData);

    var userData = {
        Username : this.state.emailText,
        Pool : userPool
    };
    var cognitoUser = new CognitoUser(userData);
    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: function (result) {
            // console.log('access token + ' + result.getAccessToken().getJwtToken());

            // //POTENTIAL: Region needs to be set if not already set previously elsewhere.
            // AWS.config.region = MATAppRegion;
        
            // AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            //     IdentityPoolId : MATAppIdentityPool, // your identity pool id here
            //     Logins : {
            //         // Change the key below according to the specific region your user pool is in.
            //         idpURL: result.getIdToken().getJwtToken()
            //     }
            // });
             onSignIn().then(() => navigate("SignedIn"));
            // // Instantiate aws sdk service objects now that the credentials have been updated.
            // // example: var s3 = new AWS.S3();

        },

        onFailure: function(err) {
            alert(err);
        },

    });
   
   
    }

**Any ideas what could be causing this issue?**

**Comment by itrestian** [comment]
Can you check with the new version?
