### ISSUE TITLE
About google redirect URLs

### ISSUE THREAD

**Issue by edongashi** [aws/amazon-cognito-identity-js#591]
We are trying to integrate google sign in for our app which is using cognito. In the [docs](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social.html) I followed all steps:

> Developers must also add their Amazon Cognito User Pool domain URL https://your-user-pool-domain/oauth2/idpresponse in the Google app's Authorized redirect URIs (in the Credentials section). This ensures that Google will accept the redirect URL supplied by Amazon Cognito when it authenticates users. For more information, see https://developers.google.com/identity/protocols/OAuth2WebServer.

I am lost in `URL supplied by Amazon Cognito`. What URL should users visit to sign in via google? I can't find anything about this...

**Comment by rachitdhall** [comment]
Here's our [developer guide](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html) which goes over how to setup a user pool domain and identity providers (Google in your case).

Post that URL for your app will look like this example: https://example.auth.us-east-1.amazoncognito.com/login?redirect_uri=<redirect_uri>&response_type=<outh_flow>&client_id=<client_id_value>

**Comment by edongashi** [comment]
Thanks! After some configuration I managed to get it working 👍
