### ISSUE TITLE
Lack of customizability on hosted UI

### ISSUE THREAD

**Issue by kpitzen** [aws/amazon-cognito-identity-js#601]
As a cognito developer,  I would like the following functionality to be available to me on the hosted Cognito Sign In UI:
- Forgot Username
    - If I allow my users to use a User ID rather than an email address, I would like my users to be able to recover their username from cognito from within the sign in page

**Comment by rachitdhall** [comment]
Amazon Cognito does not support Forgot UserName at the current time. We have heard this request from other customers and will consider it in future updates to the service.

**Comment by kpitzen** [comment]
Thank you for your reply. Is there a roadmap or tracker somewhere where we
can see the progress on this?

**Comment by yuntuowang** [comment]
At this point, we cannot estimate the delivery time.
