### ISSUE TITLE
Unable to verify via email link

### ISSUE THREAD

**Issue by GarlandM** [aws/amazon-cognito-identity-js#604]
Hi All,

Up until yesterday, this worked without issue. 

**My signup flow:**

Website signup -> sent verification email -> verify via link

However any time someone signs up now they're still the sent the link correctly, but anytime they click on the link it'll come back with: **An error was encountered with the requested page.** and the error is: **invalid_request**

**Comment by jndev90** [comment]
Same issue here.

**Comment by tobiastornros** [comment]
Same here, link is sent to user but doesn´t work.

**Comment by itrestian** [comment]
What region are your pools in?

**Comment by GarlandM** [comment]
US-East for me.

**Comment by itrestian** [comment]
We are not able to reproduce this issue. Can you email me (trestian@amazon.com) the pool ID and some request information (like a request id and some timing information of when the request was made).

**Comment by jndev90** [comment]
EU-central1, tested with multiple pool ids.

**Comment by GarlandM** [comment]
@itrestian

I've emailed you.

**Comment by itrestian** [comment]
Thanks, we're looking into it.

**Comment by rachitdhall** [comment]
We have been able to reproduce the issue. It happens when you do not have any OAuth Flows/Scopes configured. This is a recent bug and we are working on a fix.

A workaround is to enable any OAuth flow which will allow it to work.

**Comment by rachitdhall** [comment]
The fix has been deployed to all regions, please let us know if you are still having issues. Thanks for your patience.

**Comment by jndev90** [comment]
I can confirm that the issue is resolved.
