### ISSUE TITLE
Cookie Storage not working

### ISSUE THREAD

**Issue by woodpav** [aws/amazon-cognito-identity-js#609]
## Expected Behavior
After authenticating and refreshing the page, `pool.getCurrentUser()` should return the user instead of `null`.

## Actual Behavior
User is successfully authenticated and tokens are retrieved. Storage is set in `CognitoUserPool` and `CognitoUser` on construction but calling `pool.getCurrentUser()` returns null.

## Code ##

    const DOMAIN = ".localhost:5000"

    import { CognitoUserPool, CognitoUser, CookieStorage } from 'amazon-cognito-identity-js';

    var pool = new CognitoUserPool({
      UserPoolId: COGNITO_USER_POOL_ID,
      ClientId: COGNITO_CLIENT_ID,
      Storage: new CookieStorage({ domain: DOMAIN })
    });

    var user = new CognitoUser({
      Username: username,
      Pool: pool,
      Storage: new CookieStorage({ domain: DOMAIN })
    });

    user.authenticateUser(auth, { ... });  // successful

    pool.getCurrentUser();  // returns null after refresh

Maybe worth noting that cookies are blank. (However if I set cookies through `js-cookies` it works as expected.)

    import * as Cookies from 'js-cookie';
    Cookies.get()  // returns {}

**Comment by woodpav** [comment]
`const DOMAIN = "localhost"`

**Comment by ispulkit** [comment]
I'm facing the same error with correct code also.

`const authenticationData = {
        Username: 'pulkit.kumar@xxxxx,
        Password: 'xxxxxxxxx',
    };
    const authenticationDetails = new AuthenticationDetails(authenticationData);
    const poolData = {
        UserPoolId: 'ap-southeast-x_xxxxx',
        ClientId: 'xxxxxxxxx',
        Storage: new CookieStorage({domain: 'localhost', path: '/token'})
    };
    const userPool = new CognitoUserPool(poolData);
    const userData = {
        Username: 'pulkit.kumar@xxxxxxxxx,
        Pool: userPool,
        Storage: new CookieStorage({domain: 'localhost', path: '/token'})
    };
    const cognitoUser = new CognitoUser(userData);
    cognitoUser.authenticateUser(authenticationDetails, {
        onSuccess: (result) => {
            console.log('access token: ' + result.getIdToken().getJwtToken());
            this.access_token = result.getIdToken().getJwtToken();
            AWSCognito.config.region = 'ap-southeast-1';

            AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({
                IdentityPoolId: '...', 
                Logins: {
                    'cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-xxxxxx': result.getIdToken().getJwtToken()
                }
            });
            console.log(this.access_token);
        },

        onFailure: function (err) {
            alert(err);
        },
        newPasswordRequired: function (err) {
          const attributeList = [];
          const dataEmail = {
            Name: 'email',
            Value: 'pulkit.kumar@xxxxxx'
          };
          attributeList.push(new CognitoUserAttribute(dataEmail));
          cognitoUser.completeNewPasswordChallenge('xxxxxxxxxxxxx', null, this);
          console.log(err);
        }

    });
    console.log(userPool.getCurrentUser()); // null
  }`

**Comment by fahrenq** [comment]
If you found this issue while trying to fix this 'bug' and @woodpav's answer not working - try to set `secure` property of CookieStorage to false.

`new CookieStorage({ domain: 'localhost', secure: false })`
