### ISSUE TITLE
Question: Configuring API Gateway SDK using CognitoUser credentials

### ISSUE THREAD

**Issue by hofan41** [aws/amazon-cognito-identity-js#61]
It appears the de-facto way to configure an API Gateway SDK is the following:

```
                var apigClient = apigClientFactory.newClient({
                    accessKey : 'ACCESS_KEY',
                    secretKey : 'SECRET_KEY',
                    sessionToken : 'SESSION_TOKEN'
                });
```

It seems that the CognitoUser.authenticateUser returns a CognitoUserSession consisted of the following:

```
ID Token
Refresh Token
Access Token
```

These tokens appear to be the wrong set of keys that the API Gateway SDK is expecting. Reading further on the documents, it seems I need to make an additional call to `STS.assumeRoleWithWebIdentity` in order to get them. 

Digging through the implementation of the Cognito Identity SDK, I see that the credentials I need are already available internally inside the implementation of CognitoIdentityCredentials.

aws-cognito-sdk.js : 414

```
  loadCredentials: function loadCredentials(data, credentials) {
    if (!data || !credentials) return;
    credentials.expired = false;
    credentials.accessKeyId = data.Credentials.AccessKeyId;
    credentials.secretAccessKey = data.Credentials.SecretKey;
    credentials.sessionToken = data.Credentials.SessionToken;
    credentials.expireTime = data.Credentials.Expiration;
  },
```

Is there some mechanism by which I can readily use these credentials instead of making a redundant call to STS? 

Please advise.

**Comment by MarkMercAWS** [comment]
You can use the tokens from Cognito User pools directly with API Gateway following this blog post:
https://mobile.awsblog.com/post/Tx3JK25U7Z9EUIU/Integrating-Amazon-Cognito-User-Pools-with-API-Gateway

If you want to get AWS Credentials, you need to use Cognito Federated Identities:
http://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-integrating-user-pools-with-identity-pools.html

**Comment by hofan41** [comment]
Both of those solutions seem to be more convoluted than simply calling `STS.assumeRoleWithWebIdentity` to get the AWS Credentials. Is this not a recommended way to do so?

**Comment by MarkMercAWS** [comment]
It really depends on your use case.

(1) If you will need AWS Credentials for using services other than API Gateway and you allow multiple providers, you likely want to use Cognito Federated Identities.

(2) If you are _only_ using API Gateway, and you are doing it from more than just a web app, the Cognito User Pools integration with API Gateway may be the way to go. That way you can customize your authorization to your APIs.

(3) Finally, you can call STS directly as you mentioned. Which will give you credentials with  permissions defined by the role. This will work but does not give you some of the same options listed in (1) or (2). 

It all really depends on your use case and application's needs.

**Comment by hofan41** [comment]
If I use solution 2, and integrate with API Gateway which goes to Lambda, how can I use the resulting principalId to retrieve the Cognito User Name and User Attributes?

**Comment by hofan41** [comment]
Nevermind, found the solution here: https://forums.aws.amazon.com/thread.jspa?threadID=232829&tstart=0

**Comment by hengbenkeji** [comment]
The convoluted reference is here:
https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/

This reference lacks important details, which reflects negative working attitudes of the developers from AWS!

No other explanation!
