### ISSUE TITLE
Issue with latest version (1.27.0)

### ISSUE THREAD

**Issue by hsyyid** [aws/amazon-cognito-identity-js#610]
Got error "Unexpected key 'UserContextData' found in params"

Did not see any stacktrace or other mention of error in console.

I reverted a version and everything works normally once more.

Thanks.

**Comment by itrestian** [comment]
it probably has to do with how you are consuming the main aws sdk. The new shapes for the new service operations are already available in the aws-cognito-sdk library that I updated and will be available in the main aws-sdk as well shortly.

**Comment by hsyyid** [comment]
Ok, thanks

**Comment by thegreatsunra** [comment]
I'm seeing this too. Thanks for the heads up.

**Comment by thegreatsunra** [comment]
Just confirmed that I experience this issue with amazon-cognito-identity-js **1.27.0** and aws-sdk 2.158.0, but _not_ with amazon-cognito-identity-js **1.26.0** and aws-sdk 2.158.0.

**Comment by Skaronator** [comment]
I don't use aws-sdk at all and still got this error.

**Comment by Skaronator** [comment]
Well this package use aws-sdk as dependencies but it should work together, right?

https://github.com/aws/amazon-cognito-identity-js/blob/258b0f049d7ac0c40bed139c988cbaa92514ad5d/package.json#L63

**Comment by itrestian** [comment]
Can you check if the latest version solves this issue?

**Comment by Skaronator** [comment]
Seems to work now, thanks!

Hope you get some automated test soon.. #154

**Comment by itrestian** [comment]
kk, closing. feel free to reopen if it's still an issue.

**Comment by thegreatsunra** [comment]
Confirmed that this issue is resolved for me with amazon-cognito-identity-js **1.28.0** and aws-sdk **2.159.0**. Thanks for the responsiveness!

**Comment by itrestian** [comment]
The new version of the AWS SDK now has support for the new APIs that were covered here in 1.27.0

https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#changelog-for-aws-sdk-for-javascript
