### ISSUE TITLE
Hosted login UI - Typos

### ISSUE THREAD

**Issue by jonasao** [aws/amazon-cognito-identity-js#613]
When enabling the federated identiy providers Facebook and Google, the buttons on the hosted login UI screen contains misspellings: 
* "Continue withGoogle"
* "Continue withFacebook"

There should be a space between "with" and the name of the federated identity provider.

**Comment by itrestian** [comment]
Thank you for the feedback. We plan to clean that up in a future release. Closing this in favor of: https://github.com/aws/amazon-cognito-auth-js/issues/51
