### ISSUE TITLE
Authenticate user using a proxy

### ISSUE THREAD

**Issue by oennen** [aws/amazon-cognito-identity-js#620]
I already searched for documentation about this issue, but haven´t found any hint.

We authenticate users similar to the example code at http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html (topic "Authenticate a User").

Is there a way to do that when the user is behind a proxy? Do you have any example code?

Best regards

**Comment by itrestian** [comment]
I'm not entirely sure what the difference would be. As long as our service endpoints are reachable there shouldn't be a problem. Can you expand your question a little?

**Comment by oennen** [comment]
I was refering to customers whose internet access is through a proxy server, which is quite common in business type environments.
`npm` can be configured accordingly using a proxy via `npm config set proxy` or `npm config set https-proxy`. The popular node module [request](https://github.com/request/request) may be configured using a `proxy` option.

I was wondering, if this node module also offers a way to handle the cognito api calls through a proxy server. Or will it work out-of-the-box?

**Comment by itrestian** [comment]
It should work out of the box as far as I am aware as long as the Amazon Cognito service endpoints are reachable.

http://docs.aws.amazon.com/general/latest/gr/rande.html#cognito_identity_region
