### ISSUE TITLE
CookieStorage.setItem does not set the secure attribute

### ISSUE THREAD

**Issue by numaroth** [aws/amazon-cognito-identity-js#621]
Pretty much what it says in the title. CookieStorage.setItem does not set the secure attribute when calling Cookies.set. 

Since the secure attribute is not passed through and the [default of js-cookie is to set secure to false](https://github.com/js-cookie/js-cookie/blob/a0012f21ba0519fa3c7571cc6f16e15902ec051b/README.md#secure), it seems that no cookie made using CookieStorage will be set as secure.

**Comment by itrestian** [comment]
Great! Thanks for the pull request!
