### ISSUE TITLE
How to react to ChallengeName : "PASSWORD_VERIFIER"

### ISSUE THREAD

**Issue by pizzarob** [aws/amazon-cognito-identity-js#628]
I am using the authenticateUser method and am getting a 400 error with the following field in the response:

`ChallengeName: "PASSWORD_VERIFIER"`

How can I respond to this?

**Comment by itrestian** [comment]
If you are calling authenticateUser this SDK should take care of that considering you are passing the correct user pool id, client id, username, and password. So authenticate user is responding to the PASSWORD_VERIFIER challenge. What exactly is the 400 error you are getting?

**Comment by pizzarob** [comment]
Sorry - my mistake. I wasn't passing all the required information. Closing.
