### ISSUE TITLE
authenticateuser method is not working.

### ISSUE THREAD

**Issue by joe455** [aws/amazon-cognito-identity-js#629]
As part of my usercase I want to auto login the user into the app and show him the profile page.But which is not supported by cognito yet.So to tweak this case, I saved username and password on session storage and calling authenticating using authenticate user method once user confirmed. But for some reason it's not working. Could you somebody please help me.Below is my code.
`Auth(){`
        console.log("auth method");`

        let passkey = sessionStorage.getItem('pass1');
        let uname = sessionStorage.getItem('uname');
        console.log("password",passkey);

        //this.loginservice.authenticate(uname,passkey,null);
        let authenticationData = {
            Username : uname,
            Password : passkey,
        };
        console.log("authentication details",authenticationData);
        let authenticationDetails = new AuthenticationDetails(authenticationData);

        let userData = {
            Username: uname,
            Pool: this.cognitoUtil.getUserPool()
        };
        let cognitoUser = new CognitoUser(userData);
        console.log("cognitoUser",cognitoUser);
        let self = this;
        cognitoUser.authenticateUser(authenticationDetails, {
            onSuccess: (result) => {
                console.log("login sucuess",result);
            },
            newPasswordRequired: () => {

            },
            onFailure : (err) => {
                console.log("Login Failed",err.message);
            },
            mfaRequired: () => {
            }
    });
        sessionStorage.clear();
    }``
It's not showing error also :(

**Comment by itrestian** [comment]
You can try debugging with Chrome Developer Tools. You can see in the Network tab if any calls are made and if there is an error you can get a more descriptive message. Also try using non minified version of packages so that the variable names are kept.

**Comment by joe455** [comment]
localstorage is not clearing on signout method.

**Comment by itrestian** [comment]
I don't really understand. You mean that is the issue?

**Comment by joe455** [comment]
Sorry for confusing @itrestian .

I am able to authenticate but cognitoUser.signout() is not clearing cache/storage.
Is this is a existed issue. ??

**Comment by itrestian** [comment]
I haven't seen this issue brought up before. signOut basically clears all the keys associated with the tokens retrieved from the service, it won't clear any of the data you might have written in your app, just the keys associated with the tokens.

**Comment by joe455** [comment]
Got it!! 
Sorry for bothering @itrestian
