### ISSUE TITLE
.getAuthenticationDetails in CognitoUser is not a function

### ISSUE THREAD

**Issue by roman-yakobnyuk** [aws/amazon-cognito-identity-js#63]
Good morning!

I am trying to run example provided, but I hit a dead end with .getAuthenticationDetails method not being present on AWS-SDK object.

Specifically, when my code reaches authenticateUser() call in the CognitoUser file i get the error `TypeError: this.client.getAuthenticationDetails is not a function`

As I can see, this.client gets created from AWS SDK like that 
`this.client = new AWSCognito.CognitoIdentityServiceProvider({apiVersion: '2016-04-19'});`
However, I cannot see it in the documentation for it here http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html

I noticed that version used is different from documented version by one day, can that cause a problem?

Thank you!

**Comment by itrestian** [comment]
Hi! Those APIs are not exposed in the main aws-sdk. They are only exposed through the aws-cognito-sdk.min.js which is mentioned in the Readme file.

https://raw.githubusercontent.com/aws/amazon-cognito-identity-js/master/dist/aws-cognito-sdk.min.js
