### ISSUE TITLE
Suppress MFA when device is remembered is not working.

### ISSUE THREAD

**Issue by joe455** [aws/amazon-cognito-identity-js#637]
Userpool Settings: Remember device -> always,
suppress MFA:yes

Now, when I am logging in with the same device it's creating separate device key's for every login. As per the userpool settings, It should suppress the MFA. But it'snot happening for some reason. Any workaround for this?

**Comment by itrestian** [comment]
Are you confirming the device? You can look at this blog to understand more about the device remembering feature: https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/
