### ISSUE TITLE
Getting username from IdentityId in lambda with Developer Authenticated identities

### ISSUE THREAD

**Issue by okarlsson** [aws/amazon-cognito-identity-js#643]
Hi!

I'm retrieving a identity id from a developer authentication in my lambda function. Now I want to get the username that the user logged in with when they request a different function with the token that they recieved. I can see a value "Developer identifiers" in the console, is there a way to access that value from the sdk?

![image](https://user-images.githubusercontent.com/6207594/34641726-cdd6fe40-f308-11e7-8e09-828cdc922ce4.png)

**Comment by PedrooBritoo** [comment]
I have the same problem.

**Comment by okarlsson** [comment]
Hey @PedrooBritoo!

I was able to solve this. Have a look at this function in the sdk:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#lookupDeveloperIdentity-property

**Comment by PedrooBritoo** [comment]
Hey @okarlsson!

Thanks for sharing.
