### ISSUE TITLE
adminGetUser timeout on Lambda

### ISSUE THREAD

**Issue by david4City** [aws/amazon-cognito-identity-js#648]
Hi, 

I'm using `amazon-cognito-identity-js` on a Node 6.10 Lambda.
When calling `adminGetUser`, the Lambda function times out.

I tried :
 - rights defined in IAM
 - rights defined in cedentials
 - Increasing Lambda timeout to 20s
 - Tried more memory in Lambda

None of those seem to change anything.

Also calling `adminCreateUser` and `adminDeleteUser` but haven't tested them yet.

PS: Works well on my workstation.

**Comment by itrestian** [comment]
Have you checked out the following post:

https://github.com/aws/amazon-cognito-identity-js/issues/247

"Nevermind, I had my Lambda function setup to use a VPC and needed to add a NAT gateway for it."

**Comment by david4City** [comment]
Ok, that was the fix. 

The process : 

## In aws VPC : 
  - Create an elastic IP
  - Create a NAT Gateway on that IP
  - Create a route with the rule 0.0.0.0/0 => nat network
  - Create a private Subnet
  - Affect the routes

## In aws Lambda
 - Affect the subnets to the Lambda
