### ISSUE TITLE
Missing region in config

### ISSUE THREAD

**Issue by ToddHoff** [aws/amazon-cognito-identity-js#65]
I've downloaded all the libraries and copied the code from use case 1 into a web page, substituting in my settings. When I run it I get:
    Missing region in config

I've included AWS.config.credentials.get(function (err) {
  if (err) console.log(err);
  else console.log(AWS.config.credentials); 
});

and it made no difference. I've searched around and haven't found anything.

Any ideas on how I can make progress?

thanks

**Comment by itrestian** [comment]
Do you have the line below in your config and the aws-cognito-sdk.min.js included?

```
AWSCognito.config.region = 'us-east-1';
```

**Comment by ToddHoff** [comment]
My basic problem is I'm an idiot. I couldn't see the difference between AWS.config.regio and AWSCognito.config
