### ISSUE TITLE
Can't resolve 'amazon-cognito-identity-js'

### ISSUE THREAD

**Issue by M0ssMan** [aws/amazon-cognito-identity-js#650]
Just updated to the new version 1.30.0 and I'm getting the error `Can't resolve 'amazon-cognito-identity-js` I reverted to version 1.29.0 and everything is working properly again.  Is there some incorrect configuration I have that would cause this?

**Comment by Skaronator** [comment]
Yup got the same error.

![image](https://user-images.githubusercontent.com/2886913/34854035-78573772-f737-11e7-8938-841e31bbb5a5.png)

CC @itrestian

**Comment by itrestian** [comment]
I added the missing lib folder to the newest release.
