### ISSUE TITLE
Check password

### ISSUE THREAD

**Issue by ynnr85** [aws/amazon-cognito-identity-js#651]
Hi, How can I check if password field match current user password?
I am implementing a confirmation dialog modal, but its require to enter again logged in user password, and check if is valid. How can get this working? 

Thanks in advance

**Comment by itrestian** [comment]
I'm not entirely sure what you are asking. Are you trying to log the user in?

**Comment by ynnr85** [comment]
No really, I want the user reenter his password to confirm critical actions, such as delete an entire data collection. What I'm doing is calling to authenticate passing this password and in callback doing the delete action. Do you thinks this is the correct way or there is another way to check password? Best regards

**Comment by itrestian** [comment]
Would storing a PIN in an attribute that you can check using getUserAttributes before calling delete satisfy your use case?

**Comment by ynnr85** [comment]
It could be a solution, but that way user should remember password but also should remember PIN. Thanks for your time, you can close the issue.
