### ISSUE TITLE
Strange error in response when trying to use cognito sdk (response encrypted?)

### ISSUE THREAD

**Issue by deni-zen** [aws/amazon-cognito-identity-js#66]
I am trying to implement Cognito via javascript into my web application. I intend to allow login via facebook and google, but for now I'm just trying to set up user registration and login via cognito. I followed the instructions here: http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html#using-amazon-cognito-identity-user-pools-javascript-example-authenticating-user

This is what my signup code looks like:

```
        AWS.config.region = 'us-east-1'; // Region
        AWSCognito.config.region = 'us-east-1';
        AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: 'us-east-xxx' // your identity pool id here
        });

        var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool({
            UserPoolId: 'us-east-xxx',
            ClientId: 'xxx',
            Paranoia: 7
        });
        console.log(userPool, 'userPool')

        var attributeList = [
            new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute({
                Name: 'email',
                Value: email
            }),
            new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute({
                Name: 'preferred_username',
                Value: username
            }),
            new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute({
                Name: 'phone_number',
                Value: phone
            }),
            new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute({
                Name: 'given_name',
                Value: firstname
            }),
            new AWSCognito.CognitoIdentityServiceProvider.CognitoUserAttribute({
                Name: 'family_name',
                Value: lastname
            })
        ];

            userPool.signUp(this.state.signup.username, this.state.signup.password, attributeList, null, function(err, result){
                if (err) {
                    console.error(err);
                    return;
                }
                cognitoUser = result.user;
                console.log('user name is ' + cognitoUser.getUsername());
            });
```

The code actually works fine. The user gets created in my user pool (I can see the user in my Cognito admin console. But when I submit the form that runs this code, I get an error in my javascript console that just says "Error". When I inspect the API response it says "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". Then I inspect the raw response and it's just a long sequence of seemingly random characters. I can't figure out if the response is encrypted or base64 encoded or what... what am I doing wrong?

**Comment by deni-zen** [comment]
I ran the response through a base64 decoder and got valid JSON. But why is this response being base64 encoded. I can't find a WORD about this in ANY documentation ANYWHERE

**Comment by chetanme** [comment]
This seems very strange. Exactly what line in this code is giving you the error? Can you check the raw response from service in one of the development inspector tools like Firebug for the SignUp call and paste it here?

**Comment by ShahnazK** [comment]
i also getting the same error. can some one tell me the solution?
