### ISSUE TITLE
Does a user have to re-authenticate after page refresh?

### ISSUE THREAD

**Issue by dksheffield** [aws/amazon-cognito-identity-js#67]
Once I authenticate a user I can do all of the authenticated examples that you have posted. If I refresh the web page > I can use cognitoUser.getSession() and I can get the session and see that the session is valid, but I'm not able to make authenticated calls again unless I re-authenticate with a username and password.

Is this the expected behavior?

My use case is that when users request a page - i check some user attributes in the user pool and determine if they have access on the front end to view the page. So my problem is after I authenticate then refresh the page for whatever reason i'm not able to check the attributes without the user re-authenticating even though I have a valid session and valid tokens.

Thanks

**Comment by itrestian** [comment]
You shouldn't need to re-authenticate a user using a username and password. Basically the username is stored in local storage and by calling getUser on a CognitoUserPool followed by getSession on the retrieved user, you should be able to get the attributes. This is basically use case 15 in the readme file.

**Comment by dksheffield** [comment]
I see now - my code was getting the cognito user but not getting the session before trying to make authenticated calls. I should be good now. Thanks
