### ISSUE TITLE
AWS Cognito SDK required even if AWS SDK is already imported

### ISSUE THREAD

**Issue by rianwouters** [aws/amazon-cognito-identity-js#671]
"Note that the Amazon Cognito AWS SDK for JavaScript is just a slimmed down version of the AWS Javascript SDK namespaced as AWSCognito instead of AWS. It references only the Amazon Cognito Identity service."

This suggests that if the Javascript SDK is ready included, the AWSCognito SDK is no longer needed.

The proposed approach is:
<script src="/path/to/aws-cognito-sdk.min.js"></script>
<script src="/path/to/amazon-cognito-identity.min.js"></script>

<script src="/path/to/aws-sdk-2.6.10.js"></script>

it would be nice to be able to do
<script src="/path/to/aws-sdk-2.6.10.js"></script>
<script src="/path/to/amazon-cognito-identity.min.js"></script>

however this is not currently possible because amazon-cognito-identity.min.js depends on AWSCognito

I am using the following workaround:

<script src="https://sdk.amazonaws.com/js/aws-sdk-2.74.0.min.js"></script>
<script>AWSCognito=AWS</script>
<script src="/assets/sdk/aws/amazon-cognito-identity.min.js"></script>

However, I'd prefer this being a feature in amazon-cognito-identity,
even if it's not compatible with newer AWS SDK versions

**Comment by itrestian** [comment]
You can have a look at AWS Amplify which exposes a higher order auth component for this SDK. Maybe that can suit your use case. Also note that we will continue developing this library in the AWS Amplify repo. Also we have removed the AWS SDK dependency for this library.

https://github.com/aws/aws-amplify
