### ISSUE TITLE
Performance issue with hybrid mobile apps

### ISSUE THREAD

**Issue by pvadam** [aws/amazon-cognito-identity-js#69]
I am trying to use Cognito UserPools with a mobile app created with Ionic Framework. Everything works fine, except one thing: the performance.

I know there is a slowdown since I am located in Europe and there is a network lag in the communication with the AWS servers in N.Virginia, but I guess it will go away once the service is released and available in at least one of the EU regions.

But! The `cognitoUser.authenticateUser` function call takes ca. 10-20 seconds! The bottleneck is the `modPow` function of the jsbn lib. I have tried [another library](https://github.com/peterolson/BigInteger.js) to replace jsbn with, but it went even worse.

The `modPow` function calls take min. 5 seconds / function call on an iPhone 6.

Do you have any suggestion to improve the performance on mobile devices?

**Comment by cleitonjar** [comment]
@pvadam is true. in my lambda I got 10-20 seconds too. 
I am in Brazil!
I would like to know how to solve it too?
Someone?

**Comment by chetanme** [comment]
Hello, for JavaScript SDK, jsbn was one of the best available options for the SRP related BigInteger math. We have not evaluated the performance in hybrid apps but the browser version of the SDK work much much faster than the numbers you posted.

We have also optimized our other platform specific SDKs like iOS and Android for performance and we would suggest to use those as per requirement. Is it not an option for you?

**Comment by pvadam** [comment]
Thank you for the answer! Let's forget about hybrid apps. Did you test it on mobile browsers also? That is where I have the issue! If you did so, could you please share your benchmark with us?

**Comment by cleitonjar** [comment]
Hello @chetanme.
I made a test in my iPhone with browser and the login was bad performance.
Example: I made a page (html5 and javascript with aws sdk congnito) and added in my S3.

**Comment by vbudilov** [comment]
@pvadam -- I have created a sample web app and the authentication is fast on laptops and phones. Try it out while in Europe and let me know how long it takes (it's pointing to us-east-1) -- http://cognito.budilov.com/

**Comment by pvadam** [comment]
@vbudilov I have never seen the starter project you used, but the solution is lightning fast compared to mine. Thanks for letting us know. I will review the differences in the codebases.

Test devices:
iPhone 6: ~2.5s
Raspberry PI 3: ~5-7s

Closing the issue.

**Comment by vbudilov** [comment]
@pvadam -- glad it helped. I have it checked-in here if you want to play around with it locally: https://github.com/awslabs/aws-cognito-angular2-quickstart

**Comment by pvadam** [comment]
@vbudilov thank you, that is what I am doing now..

**Comment by FLATT-Dev** [comment]
I amd using the SDK in a hybrid app and it's still rather slow. Cognito authenticateUser takes 7-10 seconds on my Galaxy 3.  I see that the issue is closed but  don't see the solution
Thanks
Andy
