### ISSUE TITLE
Use Web Cryptography API

### ISSUE THREAD

**Issue by mseddon** [aws/amazon-cognito-identity-js#70]
Currently jsbn, jsbn2 and sjcl are mandatory dependencies- but for modern browsers supporting the [Web Cryptography API](http://caniuse.com/#feat=cryptography) this dependency is possibly not needed (and, one would expect, the native API would execute faster).  This may also help with the licensing issues.

Any thoughts on this?

**Comment by chetanme** [comment]
Thanks for pointing this out. During authentication we use SRP at the client side which involved big integer calculations. These libraries are required by the SDK for the big integer math and this was one of the best performing libraries we researched.

Although, we will definitely look into this and see if there is a substitute we can use. Thanks again.

**Comment by mseddon** [comment]
I'm pretty sure there's not an SRP implementation, and while the spec defines `BigInteger`, it's an opaque type used for the RSA algorithm, so it probably wouldn't work out of the box without changing the Cognito back end to be more browser-friendly. There is however almost certainly a way it could be leveraged in the long term though, since it does support ECDH, Diffie-Hellman and RSA, so the asymmetric cryptographic requirements are there.

**Comment by chetanme** [comment]
Can you elaborate on specifically what part of this SDK are you pointing? Is this not working for you in some browser version?

**Comment by mseddon** [comment]
I've not had any issues so far with this library (once I figured out how to set it up correctly, but that's expected of a beta).  That second comment was really to say that I don't know how the SRP algorithm maps onto the set of algorithms implemented in [WebCrypto API](https://www.w3.org/TR/WebCryptoAPI/), as I'm not a cryptographer, so I am unsure if the WebCrypto API would provide you a drop in replacement for what is needed in SRP.  I see you use modExp directly in your code. So perhaps leveraging the WebCrypto API on the current protocol is not feasible (but maybe I am wrong).

**Comment by chetanme** [comment]
SRP as authentication protocol was a cautious choice by security experts here at AWS. I will bring this up in our discussions and see if WebCrypto is a potential parallel solution instead of just SRP. Thank you for bringing this up.

**Comment by cleitonjar** [comment]
@chetanme A curiosity, when you decided to use the browser (SRP), did not transfer responsibility to third parties? Example: Version Mismatch in different browsers, problems that can arise with each browser specifically and etc. I think the ideal would not depend on implementations of browsers, there are always problems. I'm not a cryptographer. I don't understand about this.

**Comment by itrestian** [comment]
This SDK depends on the AWS SDK so the browsers supported are mostly the browsers that support the AWS SDK (mostly modern browsers).

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-intro.html
