### ISSUE TITLE
Request: Separate out the AWS Cognito SDK so it can be imported as a module

### ISSUE THREAD

**Issue by fluffywaffles** [aws/amazon-cognito-identity-js#72]
It's pretty hard right now to use the AWS Cognito SDK with a typical module bundler like Webpack or SystemJS. It would be much appreciated if the AWS Cognito SDK could be hosted on its own repo so that it can be imported as a separate module.

Thanks!

**Comment by fluffywaffles** [comment]
Actually, that's not enough. The fact that the aws-cognito-identity.min.js file assumes that AWSCognito is available as a global breaks any effort at bundling or modular design whatsoever. Please at the very least restructure the code to use `require`s so that we can use the cognito identity sdk in modular code.

**Comment by mreddyg** [comment]
Thank you for bringing your concerns to our attention. We will consider these as possible feature requests.

**Comment by juanqui** [comment]
See issue https://github.com/aws/amazon-cognito-identity-js/issues/48 for an example using the imports and exports loaders in WebPack to work around modularity issues in the meantime. Not a long term solution, but it might help in the meantime.

**Comment by fluffywaffles** [comment]
@juanqui I am actually using JSPM. The configuration for getting it to work is a bit different from webpack, but thanks!

**Comment by joestump** [comment]
It's somewhat, ah shall we say, "old school" at this point to release JavaScript the way this library has been released. So include me in the calls to properly release this package in a manner that both a `min.js` can be released from compiled source _and_ we can `npm install` this thing.

**Comment by itrestian** [comment]
Pull request solves this

https://github.com/aws/amazon-cognito-identity-js/pull/108
