### ISSUE TITLE
Error: "a.inputVerificationCode is not a function"

### ISSUE THREAD

**Issue by sarah-pixvana** [aws/amazon-cognito-identity-js#73]
On my reset password page, I am passing an email to the cognito api for a forgotten password. The confirmation code is being sent to my email, however the sdk is returning an error which is breaking my app. I followed the examples, except broke out the input verification code step into a seperate function because I wanted to run that on a seperate page in my app. I also am returning a promise so that my app will know if the call passed/failed. Am I getting this error because I broke the forgotPassword step and inputerVerification step into 2 parts? 

Error:

`Uncaught TypeError: a.inputVerificationCode is not a function` aws-cognito-sdk.js?ebb6:3541 

Below is my code for forgotPassword: 

```
export function forgotPassword(email){
    AWS.config.region = 'us-east-1';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId:'us-east-1:0bf0ab2c-c013-4617-be40-e587d29a1c49'
    });

    AWSCognito.config.region = 'us-east-1';
    AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:0bf0ab2c-c013-4617-be40-e587d29a1c49' // your identity pool id here
    });

    let userData = {
        Username : email,
        Pool : userPool
    };

    let cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

    return new Promise(function(resolve,reject){
        cognitoUser.forgotPassword({
        onSuccess: function (result) {
            console.log('call result: ' + result);
            resolve(result)
        },
        onFailure: function(err) {
            reject(err)
            return err;
        }
    });
    })
}
```

Below is my code for inputResetVerification

```
export function inputResetVerification(email,code,newPassword){
    AWS.config.region = 'us-east-1';
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
        IdentityPoolId:'us-east-1:0bf0ab2c-c013-4617-be40-e587d29a1c49'
    });

    AWSCognito.config.region = 'us-east-1';
    AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: 'us-east-1:0bf0ab2c-c013-4617-be40-e587d29a1c49' // your identity pool id here
    });
    let userData = {
        Username : email,
        Pool : userPool
    };

    let cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);

        return new Promise(function(resolve,reject){
        cognitoUser.confirmPassword(code,newPassword,{
        onSuccess: function (result) {
            console.log('call result: ' + result);
            resolve(result)
            return response;
        },
        onFailure: function(err) {
            console.log('there was an error: ',err)
            reject(err)
            return err;
        }
    });
    })

}
```

**Comment by sarah-pixvana** [comment]
Ok so after digging a little deeper I understand that I am correct, as the forgotPassword function returns the data from the function inputVerificationCode(data) instead of an OnSuccess(). This is why I am getting an error. Below is the code I am referencing from CognitoUser.js (lines 525-536)

```
    CognitoUser.prototype.forgotPassword = function forgotPassword(callback) {
        this.client.forgotPassword ({
            ClientId : this.pool.getClientId(),
            Username : this.username
        }, function (err, data) {
            if (err) {
                return callback.onFailure(err);
            } else {
                return callback.inputVerificationCode(data);
            }
        });
    };
```

This seems odd to me. When a user has forgotten a password for a web app, it is not guaranteed that they will immediately check their email for the code and input it right away.  My suggestion is that this is broken into two seperate steps. Step 1) email submitted into the forgotPassword function. Step 2) new password and confirmation code is submitted into confirmPassword function. 

I think that this would be a very simple change. Just have the forgotPassword function return callback.onSuccess() instead of callback.inputVerificationCode(data) and leave it up to the developer to structure how they want to receive the confirmation code.

**Comment by adewaguru** [comment]
I'm experiencing the exact same issue here. Is there at least any workaround for this?

**Comment by sarah-pixvana** [comment]
@adewaguru  you must call the inputVerificationCode method, but you don't actually have to do anything. You can just call a no-op.

**Comment by itrestian** [comment]
I have added a check. If you provided the inputVerificationCode method, it will call it. If not, you can call confirmPassword after.
