### ISSUE TITLE
Best practice: Should all calls to AWS resources be wrapped by `getSession`?

### ISSUE THREAD

**Issue by geertbrit** [aws/amazon-cognito-identity-js#74]
Through some code checking it seems that `getSession` does automatic refresh of tokens, etc. Moreover, tokens are cached so hitting getSession often doesn't matter that much from a performance standpoint. 

Therefore, would it be considered best practice to wrap each and every signed call to an aws-resource by a `getSession`-call?

**Comment by itrestian** [comment]
If you don't preserve the same CognitoUser object that contains the tokens, you need to make calls to getUser on the CognitoUserPool and getSession on the CognitoUser to get the tokens that will allow you to perform authenticated operations.
