### ISSUE TITLE
Login, Logout, Login and then I get the error "d.CognitoIdentity is not a constructor"

### ISSUE THREAD

**Issue by JimBarrows** [aws/amazon-cognito-identity-js#75]
The first login, and logout work just fine.  The next time I login I get the error.  I'm sure I'm doing something wrong, but I'm not sure what.  Any help would be appreciated.

**I login with:**

.service('authenticateUser', function ($rootScope, cognitoUser, authenticationDetails, awsconfig) {
            return function (username, password) {
                return new Promise(function (resolve, reject) {
                    var ad              = authenticationDetails(username, password);
                    $rootScope.username = username;
                    var cu              = cognitoUser(username);
                    cu.authenticateUser(ad, {
                        onSuccess: function (result) {
                            AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials({
                                IdentityPoolId: awsconfig.cognito.identityPoolId
                                , Logins: awsconfig.cognito.amazonLoginNameValuePair(result.getIdToken().getJwtToken())
                            });
                            resolve(result);
                        }
                        , onFailure: function (err) {
                            reject(err);
                        }
                    })
                });
            }

**I logout with:**
getCurrentUsername
                        .then(function (username) {
                            cognitoUser(username).signOut();
                            $location.path("main");
                            $rootScope.$apply();
                        });

**getCurrentUsername:**
.service('getCurrentUsername', function (cognitoUserPool) {
            return new Promise(function (resolve, reject) {
                var user = cognitoUserPool.getCurrentUser();
                if (user) {
                    resolve(user.username);
                } else {
                    reject("No current user");
                }
            });
        })

**cognitoUserPool:**
.factory('cognitoUserPool', function (awsconfig, cognito) {
            return new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool({
                UserPoolId: awsconfig.cognito.userPoolId
                , ClientId: awsconfig.cognito.clientId
            });
        })

**Comment by itrestian** [comment]
The line

AWSCognito.config.credentials = new AWSCognito.CognitoIdentityCredentials

should be

AWSCognito.config.credentials = new AWS.CognitoIdentityCredentials

The CognitoIdentityCredentials is exposed through the main AWS SDK.
