### ISSUE TITLE
`authenticateUser` on Lambda nodejs4.3 with long timeout and wrong username/pw

### ISSUE THREAD

**Issue by dforsber** [aws/amazon-cognito-identity-js#77]
I've been running the SDK on browser, works fine. I switched running on Lambda nodejs4.3 through API Gateway. Register works (also with SMS auth code), but Login just timeouts. The corresponding login code runs locally on my laptop just fine when calling User Pool API directly, but on AWS Lambda the function never returns (timeout up to 90s). I'm testing by calling the Lambda function directly but also through API Gateway integration - the same results.

One way to figure out things a bit more would be to add more tracing into the `amazon-cognito-identity-js` SDK itself, but maybe you guys know the answer already..?
- E.g. does the slow crypto lib issue relate to this (90s timeout should be enough right)? 
- Can it be Lambda function resource problem (I really doubt it)? 
- It should not be a policy issue as the Login should be as "open" as the SignUp (and for me the signup works)?

I'm fairly new to AWS Lambda, but have been using for some time already. Also, it seems there is no CloudWatch logging available for Cognito User Pools. Just can't wait for the NodeJS SDK to come out and solve all the problems 🎅 

_NOTE: When I comment out the `cognitoUser.authenticateUser()` call, then the Lambda function returns fine. So, I assume it is not a problem with the Lambda function itself at this point, but who knows._

**Comment by dforsber** [comment]
Updates:
- When increasing the timeout, I start getting "incorrect username or password" errors when running through Lambda
- When running the code directly with `node` on t2.micro instance (lambda image), **the first try gives "incorrect username or password", but immediate second try succeeds and provides tokens**. However, there is no long waiting time, the authentication response comes in a few seconds.
- Each Login call creates new `Cognito Federated Identity`, which is not intended, but I have currently no idea on how to fix that without providing a fixed `IdentityId`.

**Comment by dforsber** [comment]
#43 had discussion that I missed. Yes, replacing the big-integer solved it.

**Comment by dainbrump** [comment]
I'm trying to do essentially the same thing - using API GW, Lambda and Cognito User pool to authenticate users. I have the user pool setup, the IAM setup for Lambda and endpoints in API GW. I've created my lambda package after doing npm install locally, creating my index.js and zipping the whole thing up.

When I try to authenticate, the function times out even after increasing the timeout to 10 seconds. It's almost as if the callback functions are not being executed. I'm positive I may be missing something, but I'll be darned if I can figure out what I'm missing.

**Comment by ipavlidakis** [comment]
@dainbrump Did you have any luck with that issue? I have the exact same problem. I can see all other threads to be considering the issue closed but maybe it has re-surfaced in the latest update

**Comment by dainbrump** [comment]
@ipavlidakis We switched up to using server-less and followed a tutorial. This doesn't seem to be an issue anymore. I ran into it when I was trying to Lamba with Cognito the hard way. :smile:
