### ISSUE TITLE
Get rid of `moment` dependency ?

### ISSUE THREAD

**Issue by mgoria** [aws/amazon-cognito-identity-js#78]
Hi,

From what I see, moment.js here is used for some basic stuff (see attached screenshot), and imho it can be removed in order to reduce external dependencies (we have already a lot of them jsbn, jsbn2, etc :) ).

Thanks,
Marcel

![screen shot 2016-07-04 at 5 00 43 pm](https://cloud.githubusercontent.com/assets/2959952/16563235/7b6d8176-4209-11e6-9a83-f294051afac7.png)

**Comment by patvyas** [comment]
You are right. We will consider removing the dependency in future releases

**Comment by itrestian** [comment]
This was fixed by the following pull request

https://github.com/aws/amazon-cognito-identity-js/pull/93
