### ISSUE TITLE
Userpool App authentication

### ISSUE THREAD

**Issue by hashitha** [aws/amazon-cognito-identity-js#82]
This is more of a question.

I have users in a user-pool which are able to sign in using that. I now need to give an App access to same resources as a user. E.g. A background process that was added by a user to do work on their data. Is is possible to generate an App password or a key by that user so that App can be logged in indefinitely and keep doing its work?

**Comment by kushwahavinay** [comment]
App can use the access token/refresh token vended to the user. You can configure the validity of refresh token to a long time and the app can keep getting the new access token without having the user log in again.

**Comment by hashitha** [comment]
Thanks, but I don't this refresh token is supported in java or .net sdk. Anyways we have now got this working by using developer authentication instead of user pools.
