### ISSUE TITLE
Reference error: moment is not defined

### ISSUE THREAD

**Issue by sarah-pixvana** [aws/amazon-cognito-identity-js#83]
I am trying to retrieve the current user using the cognitoUser.getSession() function. However, when I call that function, I am getting an uncaught reference error: "moment is not defined" . 

I have the moment library installed and I am requiring it. What is causing this? 

```
export function retrieveCurrentUser(){
  let cognitoUser = userPool.getCurrentUser();
      if (cognitoUser != null) {
        cognitoUser.getSession(function(err, session) {
            if (err) {
                alert(err);
                return;
            }
            console.log('session validity: ' + session.isValid());
        });
    }
  return cognitoUser;
}
```

**Comment by sarah-pixvana** [comment]
I also just realized that I am only getting this error when I refresh my browser after logging in.

**Comment by itrestian** [comment]
We have removed the moment.js dependency with the following pull request

https://github.com/aws/amazon-cognito-identity-js/pull/93
