### ISSUE TITLE
Enable/Disable User

### ISSUE THREAD

**Issue by danielsandrewm** [aws/amazon-cognito-identity-js#84]
Is there a way to enable/disable user accounts via the API? I don't see the "Enabled" attribute that displays in the Cognito console referenced anywhere in the code, or in the available user attributes. I'm currently coding the enable/disable account logic into my app, but would prefer that it were handled via the flag in Cognito.

**Comment by itrestian** [comment]
Currently, you can enable/disable users only from the console as part of administering the user pool.
