### ISSUE TITLE
Authentication with MFA Code

### ISSUE THREAD

**Issue by roman-yakobnyuk** [aws/amazon-cognito-identity-js#85]
Good afternoon,

I am trying to run example following instructions provided in readme, and I had success running it on the user pool without MFA enabled.

However, when I enable mfa and try to run Use Case 4 I get the following error:
`aws-cognito-sdk.min.js:6 Uncaught TypeError: b.mfaRequired is not a function`

I receive the code to my phone, but at what point should I enter it in the example?

Thank you,
Roman

**Comment by itrestian** [comment]
mfaRequired is the callback that is being called from our code and you basically need to implement and call sendMFACode on the cognitoUser object in order to get MFA to work.
