### ISSUE TITLE
Where is the sources of aws-cognito-sdk.min.js

### ISSUE THREAD

**Issue by ribomation** [aws/amazon-cognito-identity-js#89]
Where can I find the readable source code of AWSCognito?

I'm reading the sources of the current library (_amazon-cognito-identity-js_) and noticed that certain methods of `CognitoIdentityServiceProvider`are not part of the regular AWS-SDK-JS library. E.g. `getAuthenticationDetails()` and `authenticate()`.

Browsing through all  [AWS repos](https://github.com/aws) I wasn't able to identify any match.

**Comment by itrestian** [comment]
Only certain low level APIs are exposed through the main AWS SDK. The ones you mentioned are exposed through the following SDK.

https://github.com/aws/amazon-cognito-identity-js/blob/master/dist/aws-cognito-sdk.js

**Comment by vbudilov** [comment]
Hi,

is there a plan to integrate this functionality into the main AWS SDK? 

Thanks!
