### ISSUE TITLE
Empty error returned after authentication attempt

### ISSUE THREAD

**Issue by mmailhos** [aws/amazon-cognito-identity-js#95]
Hello,
I am still trying to figure out if the problem is coming from the SDK or my code (most likely?).

I used this chunk of code found here to authenticate a user and it is returning a blank response.

```
AWSCognito.config.region = 'us-east-1';
var authenticationData = {
    Username : '+1112223333', //some phone number used as an Alias
    Password : 'password123456',
};
var authenticationDetails = new AWSCognito.CognitoIdentityServiceProvider.AuthenticationDetails(authenticationData);
var poolData = {
    UserPoolId : 'us-east-1_P00l1d', // Your user pool id here
    ClientId : 'xxx' // Your client id here
};
var userPool = new AWSCognito.CognitoIdentityServiceProvider.CognitoUserPool(poolData);
var userData = {
    Username : 'myusername',
    Pool : userPool
};
var cognitoUser = new AWSCognito.CognitoIdentityServiceProvider.CognitoUser(userData);
cognitoUser.authenticateUser(authenticationDetails, {
    onSuccess: function (result) {
        console.log('access token + ' + result.getAccessToken().getJwtToken());
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId : 'xxx', // your identity pool id here
            Logins : {
                // Change the key below according to the specific region your user pool is in.
                'cognito-idp.pool_id_number_here_xxx' : result.getIdToken().getJwtToken()
            }
        });
    },

    onFailure: function(err) {
        alert(err)
        console.log("Error " + err);
    },

}); 

```

Some details to reproduce the bug:

For the authenticationData, I used the phone number as username (phone number is set as an alias) and the password. I tried with the username directly as well. The UserPoolId and ClientId are correct as I used the same value for registering and confirming the phone number. In the userData, I set the Username with the proper username (ex: "Billy").

About the Identity Pool, I created an Identity Pool on AWS Console linked to my App and my UserPool and I replaced the values IdentityPoolId and Logins in authenticateUser. I am not completely sure about the value in Logins though. I used cognito-idp.POOLIDNUMBER.

The output from AWS is blank. **I am thinking that I can not even reach the server** and I suspect an issue with the roles or the Identity Pool (the userPool is fine I suppose).
My identity pool is only using AWS Cognito users, not Facebook or other Identity Providers.

**Comment by itrestian** [comment]
Can you see in Firebug if any calls are being made to our endpoint?

**Comment by mmailhos** [comment]
Here is what I see on Firebug without sensitive data. AWS is returning 200 which is a bit strange..
When I check if a user is connected with this piece of code, it returns that the user is not authenticated.

```
    cognitoUser.getUserAttributes(function(err, result) {
        if (err) {
            alert(err);
            return;
        }
        for (i = 0; i < result.length; i++) {
            console.log('attribute ' + result[i].getName() + ' has value ' + result[i].getValue());
        }
    });
```

<img width="1277" alt="screen shot 2016-08-02 at 10 07 06 am" src="https://cloud.githubusercontent.com/assets/5645869/17337775/230f254c-5899-11e6-8374-9fcccae944d8.png">

<img width="427" alt="screen shot 2016-08-02 at 10 07 36 am" src="https://cloud.githubusercontent.com/assets/5645869/17337779/27e32ea6-5899-11e6-8f8d-c9f3aed95976.png">

<img width="1277" alt="screen shot 2016-08-02 at 10 08 14 am" src="https://cloud.githubusercontent.com/assets/5645869/17337783/2cfe81f6-5899-11e6-92fa-adba10358699.png">

**Comment by mmailhos** [comment]
Solved.

Recompiling sjcl `with --with-all` solved the issue. 
I only compiled it with codecBytes in a first place, I guess something was missing. I can figure it out from now.

**Comment by itrestian** [comment]
Actually last night, I removed that dependency. If you pull the latest dist file, you wouldn't need to do that.
